import { deepFreeze } from '../../utils';
import { ArmArmor } from './types';

export const ArmArmors: ArmArmor[] = [
  deepFreeze<ArmArmor>({
    id: 0,
    type: 'arms',
    name: 'Leather Gloves',
    blade: true,
    gunner: true,
    defense: 1,
    fireRes: -1,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 3,
    dragonRes: 2,
    slots: 1,
    rarity: 1,
    skillPoints: [
      { skillId: 35, points: 1 },
      { skillId: 40, points: 1 },
      { skillId: 41, points: 3 },
      { skillId: 69, points: 4 }
    ],
    price: 150,
    maxDefense: 1,
    maxLowRankDefense: 9
  }),
  deepFreeze<ArmArmor>({
    id: 1,
    type: 'arms',
    name: 'Chainmail Gloves',
    blade: true,
    gunner: true,
    defense: 2,
    fireRes: -1,
    waterRes: -1,
    iceRes: 3,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 1,
    skillPoints: [
      { skillId: 23, points: 3 },
      { skillId: 70, points: 2 },
      { skillId: 71, points: 2 },
      { skillId: 72, points: 2 }
    ],
    price: 200,
    maxDefense: 2,
    maxLowRankDefense: 9
  }),
  deepFreeze<ArmArmor>({
    id: 2,
    type: 'arms',
    name: "Hunter's Vambraces",
    blade: true,
    gunner: false,
    defense: 6,
    fireRes: -1,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: -1,
    slots: 1,
    rarity: 1,
    skillPoints: [
      { skillId: 42, points: 5 },
      { skillId: 62, points: -1 },
      { skillId: 68, points: 1 },
      { skillId: 75, points: 2 }
    ],
    price: 500,
    maxDefense: 6,
    maxLowRankDefense: 20
  }),
  deepFreeze<ArmArmor>({
    id: 3,
    type: 'arms',
    name: "Hunter's Guards",
    blade: false,
    gunner: true,
    defense: 3,
    fireRes: -1,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: -1,
    slots: 1,
    rarity: 1,
    skillPoints: [
      { skillId: 42, points: 4 },
      { skillId: 62, points: -2 },
      { skillId: 68, points: 1 },
      { skillId: 75, points: 2 }
    ],
    price: 500,
    maxDefense: 3,
    maxLowRankDefense: 10
  }),
  deepFreeze<ArmArmor>({
    id: 4,
    type: 'arms',
    name: 'Bone Vambraces',
    blade: true,
    gunner: false,
    defense: 8,
    fireRes: 2,
    waterRes: -2,
    iceRes: -1,
    thunderRes: 2,
    dragonRes: 3,
    slots: 1,
    rarity: 1,
    skillPoints: [
      { skillId: 34, points: 4 },
      { skillId: 35, points: 1 },
      { skillId: 54, points: -1 },
      { skillId: 73, points: 2 },
      { skillId: 77, points: 1 }
    ],
    price: 750,
    maxDefense: 8,
    maxLowRankDefense: 22
  }),
  deepFreeze<ArmArmor>({
    id: 5,
    type: 'arms',
    name: 'Bone Guards',
    blade: false,
    gunner: true,
    defense: 4,
    fireRes: 2,
    waterRes: -2,
    iceRes: -1,
    thunderRes: 2,
    dragonRes: 3,
    slots: 1,
    rarity: 1,
    skillPoints: [
      { skillId: 34, points: 4 },
      { skillId: 35, points: 1 },
      { skillId: 54, points: -1 },
      { skillId: 73, points: 2 },
      { skillId: 77, points: 1 }
    ],
    price: 750,
    maxDefense: 4,
    maxLowRankDefense: 11
  }),
  deepFreeze<ArmArmor>({
    id: 6,
    type: 'arms',
    name: 'Alloy Vambraces',
    blade: true,
    gunner: false,
    defense: 8,
    fireRes: 1,
    waterRes: 1,
    iceRes: -1,
    thunderRes: -2,
    dragonRes: -1,
    slots: 1,
    rarity: 1,
    skillPoints: [
      { skillId: 25, points: 2 },
      { skillId: 26, points: 2 },
      { skillId: 76, points: 4 },
      { skillId: 78, points: -1 }
    ],
    price: 1000,
    maxDefense: 8,
    maxLowRankDefense: 22
  }),
  deepFreeze<ArmArmor>({
    id: 7,
    type: 'arms',
    name: 'Alloy Guards',
    blade: false,
    gunner: true,
    defense: 4,
    fireRes: 1,
    waterRes: 1,
    iceRes: -1,
    thunderRes: -2,
    dragonRes: -1,
    slots: 1,
    rarity: 1,
    skillPoints: [
      { skillId: 7, points: 2 },
      { skillId: 25, points: 2 },
      { skillId: 76, points: 3 },
      { skillId: 78, points: -2 }
    ],
    price: 1000,
    maxDefense: 4,
    maxLowRankDefense: 11
  }),
  deepFreeze<ArmArmor>({
    id: 8,
    type: 'arms',
    name: 'Jaggi Vambraces',
    blade: true,
    gunner: false,
    defense: 10,
    fireRes: -3,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: 1,
    slots: 2,
    rarity: 2,
    skillPoints: [
      { skillId: 35, points: 2 },
      { skillId: 55, points: 3 },
      { skillId: 58, points: 1 },
      { skillId: 67, points: -1 }
    ],
    price: 1200,
    maxDefense: 10,
    maxLowRankDefense: 24
  }),
  deepFreeze<ArmArmor>({
    id: 9,
    type: 'arms',
    name: 'Jaggi Guards',
    blade: false,
    gunner: true,
    defense: 5,
    fireRes: -3,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: 1,
    slots: 2,
    rarity: 2,
    skillPoints: [
      { skillId: 35, points: 1 },
      { skillId: 55, points: 2 },
      { skillId: 58, points: 1 },
      { skillId: 67, points: -3 }
    ],
    price: 1200,
    maxDefense: 5,
    maxLowRankDefense: 12
  }),
  deepFreeze<ArmArmor>({
    id: 10,
    type: 'arms',
    name: 'Rhenoplos Vambraces',
    blade: true,
    gunner: false,
    defense: 12,
    fireRes: 2,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: 2,
    slots: 2,
    rarity: 2,
    skillPoints: [
      { skillId: 39, points: 1 },
      { skillId: 46, points: 2 },
      { skillId: 56, points: 3 },
      { skillId: 63, points: -1 }
    ],
    price: 1400,
    maxDefense: 12,
    maxLowRankDefense: 24
  }),
  deepFreeze<ArmArmor>({
    id: 11,
    type: 'arms',
    name: 'Rhenoplos Guards',
    blade: false,
    gunner: true,
    defense: 6,
    fireRes: 2,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: 2,
    slots: 2,
    rarity: 2,
    skillPoints: [
      { skillId: 3, points: 2 },
      { skillId: 31, points: 3 },
      { skillId: 46, points: 1 },
      { skillId: 63, points: -1 }
    ],
    price: 1400,
    maxDefense: 6,
    maxLowRankDefense: 12
  }),
  deepFreeze<ArmArmor>({
    id: 12,
    type: 'arms',
    name: 'Qurupeco Vambraces',
    blade: true,
    gunner: false,
    defense: 12,
    fireRes: 2,
    waterRes: -2,
    iceRes: -3,
    thunderRes: 0,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 35, points: 2 },
      { skillId: 36, points: 3 },
      { skillId: 43, points: 1 },
      { skillId: 44, points: 2 },
      { skillId: 64, points: -1 }
    ],
    price: 1700,
    maxDefense: 12,
    maxLowRankDefense: 24
  }),
  deepFreeze<ArmArmor>({
    id: 13,
    type: 'arms',
    name: 'Qurupeco Guards',
    blade: false,
    gunner: true,
    defense: 6,
    fireRes: 2,
    waterRes: -2,
    iceRes: -3,
    thunderRes: 0,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 35, points: 2 },
      { skillId: 36, points: 1 },
      { skillId: 43, points: 2 },
      { skillId: 44, points: 3 },
      { skillId: 64, points: -1 }
    ],
    price: 1700,
    maxDefense: 6,
    maxLowRankDefense: 12
  }),
  deepFreeze<ArmArmor>({
    id: 14,
    type: 'arms',
    name: 'Ludroth Vambraces',
    blade: true,
    gunner: false,
    defense: 13,
    fireRes: -3,
    waterRes: 2,
    iceRes: 0,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 37, points: 4 },
      { skillId: 49, points: 2 },
      { skillId: 61, points: -1 },
      { skillId: 79, points: 2 }
    ],
    price: 2200,
    maxDefense: 13,
    maxLowRankDefense: 25
  }),
  deepFreeze<ArmArmor>({
    id: 15,
    type: 'arms',
    name: 'Ludroth Guards',
    blade: false,
    gunner: true,
    defense: 7,
    fireRes: -3,
    waterRes: 2,
    iceRes: 0,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 30, points: 3 },
      { skillId: 37, points: 1 },
      { skillId: 49, points: 3 },
      { skillId: 61, points: -2 }
    ],
    price: 2200,
    maxDefense: 7,
    maxLowRankDefense: 13
  }),
  deepFreeze<ArmArmor>({
    id: 16,
    type: 'arms',
    name: 'Steel Vambraces',
    blade: true,
    gunner: false,
    defense: 12,
    fireRes: -1,
    waterRes: 1,
    iceRes: 1,
    thunderRes: -1,
    dragonRes: 0,
    slots: 0,
    rarity: 2,
    skillPoints: [
      { skillId: 26, points: 4 },
      { skillId: 27, points: 3 },
      { skillId: 50, points: -4 }
    ],
    price: 2000,
    maxDefense: 12,
    maxLowRankDefense: 24
  }),
  deepFreeze<ArmArmor>({
    id: 17,
    type: 'arms',
    name: 'Baggi Vambraces',
    blade: true,
    gunner: false,
    defense: 13,
    fireRes: -3,
    waterRes: -1,
    iceRes: 3,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 17, points: 3 },
      { skillId: 18, points: 2 },
      { skillId: 55, points: -1 },
      { skillId: 64, points: 3 }
    ],
    price: 2400,
    maxDefense: 13,
    maxLowRankDefense: 13
  }),
  deepFreeze<ArmArmor>({
    id: 18,
    type: 'arms',
    name: 'Baggi Guards',
    blade: false,
    gunner: true,
    defense: 7,
    fireRes: -2,
    waterRes: -1,
    iceRes: 3,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 6, points: 2 },
      { skillId: 17, points: 4 },
      { skillId: 55, points: -1 },
      { skillId: 64, points: 2 }
    ],
    price: 2400,
    maxDefense: 7,
    maxLowRankDefense: 13
  }),
  deepFreeze<ArmArmor>({
    id: 19,
    type: 'arms',
    name: 'Barroth Vambraces',
    blade: true,
    gunner: false,
    defense: 15,
    fireRes: -4,
    waterRes: 4,
    iceRes: -3,
    thunderRes: 3,
    dragonRes: 0,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 13, points: 1 },
      { skillId: 25, points: -1 },
      { skillId: 35, points: 4 },
      { skillId: 45, points: 3 }
    ],
    price: 3200,
    maxDefense: 15,
    maxLowRankDefense: 27
  }),
  deepFreeze<ArmArmor>({
    id: 20,
    type: 'arms',
    name: 'Barroth Guards',
    blade: false,
    gunner: true,
    defense: 8,
    fireRes: -4,
    waterRes: 4,
    iceRes: -3,
    thunderRes: 3,
    dragonRes: 0,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 13, points: 1 },
      { skillId: 25, points: -1 },
      { skillId: 35, points: 4 },
      { skillId: 45, points: 3 }
    ],
    price: 3200,
    maxDefense: 8,
    maxLowRankDefense: 14
  }),
  deepFreeze<ArmArmor>({
    id: 21,
    type: 'arms',
    name: 'Gobul Vambraces',
    blade: true,
    gunner: false,
    defense: 16,
    fireRes: -2,
    waterRes: 3,
    iceRes: 0,
    thunderRes: -3,
    dragonRes: 2,
    slots: 2,
    rarity: 2,
    skillPoints: [
      { skillId: 24, points: -1 },
      { skillId: 46, points: 2 },
      { skillId: 55, points: 1 },
      { skillId: 62, points: 3 }
    ],
    price: 3600,
    maxDefense: 16,
    maxLowRankDefense: 28
  }),
  deepFreeze<ArmArmor>({
    id: 22,
    type: 'arms',
    name: 'Gobul Guards',
    blade: false,
    gunner: true,
    defense: 8,
    fireRes: -2,
    waterRes: 3,
    iceRes: 0,
    thunderRes: -3,
    dragonRes: 2,
    slots: 2,
    rarity: 2,
    skillPoints: [
      { skillId: 24, points: -1 },
      { skillId: 46, points: 2 },
      { skillId: 55, points: 1 },
      { skillId: 62, points: 3 }
    ],
    price: 3600,
    maxDefense: 8,
    maxLowRankDefense: 14
  }),
  deepFreeze<ArmArmor>({
    id: 23,
    type: 'arms',
    name: "Ranger's Gauntlets",
    blade: true,
    gunner: false,
    defense: 15,
    fireRes: 0,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 0,
    rarity: 3,
    skillPoints: [
      { skillId: 12, points: -4 },
      { skillId: 15, points: 5 },
      { skillId: 38, points: 2 },
      { skillId: 41, points: 1 }
    ],
    price: 10000,
    maxDefense: 15,
    maxLowRankDefense: 27
  }),
  deepFreeze<ArmArmor>({
    id: 24,
    type: 'arms',
    name: "Archer's Gauntlets",
    blade: false,
    gunner: true,
    defense: 8,
    fireRes: 0,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 0,
    rarity: 3,
    skillPoints: [
      { skillId: 12, points: -5 },
      { skillId: 15, points: 4 },
      { skillId: 38, points: 2 },
      { skillId: 41, points: 1 }
    ],
    price: 10000,
    maxDefense: 8,
    maxLowRankDefense: 14
  }),
  deepFreeze<ArmArmor>({
    id: 25,
    type: 'arms',
    name: 'Guild Bard Braces',
    blade: true,
    gunner: false,
    defense: 15,
    fireRes: 0,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 0,
    rarity: 3,
    skillPoints: [
      { skillId: 12, points: 2 },
      { skillId: 42, points: 5 },
      { skillId: 44, points: 3 },
      { skillId: 57, points: -1 }
    ],
    price: 10000,
    maxDefense: 15,
    maxLowRankDefense: 13
  }),
  deepFreeze<ArmArmor>({
    id: 26,
    type: 'arms',
    name: 'Guild Bard Sleeves',
    blade: false,
    gunner: true,
    defense: 8,
    fireRes: 0,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 0,
    rarity: 3,
    skillPoints: [
      { skillId: 12, points: 1 },
      { skillId: 42, points: 4 },
      { skillId: 44, points: 2 },
      { skillId: 57, points: -4 }
    ],
    price: 10000,
    maxDefense: 8,
    maxLowRankDefense: 14
  }),
  deepFreeze<ArmArmor>({
    id: 27,
    type: 'arms',
    name: 'Rathian Vambraces',
    blade: true,
    gunner: false,
    defense: 16,
    fireRes: 3,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 2,
    rarity: 2,
    skillPoints: [
      { skillId: 11, points: 1 },
      { skillId: 23, points: 2 },
      { skillId: 37, points: -1 },
      { skillId: 61, points: 3 }
    ],
    price: 3600,
    maxDefense: 16,
    maxLowRankDefense: 28
  }),
  deepFreeze<ArmArmor>({
    id: 28,
    type: 'arms',
    name: 'Rathian Guards',
    blade: false,
    gunner: true,
    defense: 8,
    fireRes: 3,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 2,
    rarity: 2,
    skillPoints: [
      { skillId: 11, points: 1 },
      { skillId: 23, points: 2 },
      { skillId: 37, points: -3 },
      { skillId: 61, points: 1 }
    ],
    price: 3600,
    maxDefense: 8,
    maxLowRankDefense: 14
  }),
  deepFreeze<ArmArmor>({
    id: 29,
    type: 'arms',
    name: 'Gigginox Vambraces',
    blade: true,
    gunner: false,
    defense: 18,
    fireRes: -4,
    waterRes: 0,
    iceRes: 2,
    thunderRes: 2,
    dragonRes: -1,
    slots: 2,
    rarity: 2,
    skillPoints: [
      { skillId: 9, points: 1 },
      { skillId: 22, points: 1 },
      { skillId: 23, points: -2 },
      { skillId: 49, points: 3 }
    ],
    price: 4100,
    maxDefense: 18,
    maxLowRankDefense: 30
  }),
  deepFreeze<ArmArmor>({
    id: 30,
    type: 'arms',
    name: 'Gigginox Guards',
    blade: false,
    gunner: true,
    defense: 9,
    fireRes: -4,
    waterRes: 0,
    iceRes: 2,
    thunderRes: 2,
    dragonRes: -1,
    slots: 2,
    rarity: 2,
    skillPoints: [
      { skillId: 9, points: 2 },
      { skillId: 22, points: 1 },
      { skillId: 23, points: -2 },
      { skillId: 49, points: 2 }
    ],
    price: 4100,
    maxDefense: 9,
    maxLowRankDefense: 15
  }),
  deepFreeze<ArmArmor>({
    id: 31,
    type: 'arms',
    name: 'Ingot Vambraces',
    blade: true,
    gunner: false,
    defense: 18,
    fireRes: -2,
    waterRes: -1,
    iceRes: 1,
    thunderRes: 3,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 26, points: -1 },
      { skillId: 28, points: 1 },
      { skillId: 39, points: 5 },
      { skillId: 63, points: 2 }
    ],
    price: 5000,
    maxDefense: 18,
    maxLowRankDefense: 28
  }),
  deepFreeze<ArmArmor>({
    id: 32,
    type: 'arms',
    name: 'Ingot Guards',
    blade: false,
    gunner: true,
    defense: 9,
    fireRes: -2,
    waterRes: -1,
    iceRes: 1,
    thunderRes: 3,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 3, points: 5 },
      { skillId: 28, points: 1 },
      { skillId: 29, points: -1 },
      { skillId: 63, points: 2 }
    ],
    price: 5000,
    maxDefense: 9,
    maxLowRankDefense: 14
  }),
  deepFreeze<ArmArmor>({
    id: 33,
    type: 'arms',
    name: 'Lagiacrus Vambraces',
    blade: true,
    gunner: false,
    defense: 20,
    fireRes: -3,
    waterRes: 2,
    iceRes: -1,
    thunderRes: 4,
    dragonRes: -2,
    slots: 2,
    rarity: 3,
    skillPoints: [
      { skillId: 0, points: 3 },
      { skillId: 9, points: -1 },
      { skillId: 10, points: 2 },
      { skillId: 50, points: 2 }
    ],
    price: 5600,
    maxDefense: 20,
    maxLowRankDefense: 30
  }),
  deepFreeze<ArmArmor>({
    id: 34,
    type: 'arms',
    name: 'Lagiacrus Guards',
    blade: false,
    gunner: true,
    defense: 10,
    fireRes: -3,
    waterRes: 2,
    iceRes: -1,
    thunderRes: 4,
    dragonRes: -2,
    slots: 2,
    rarity: 3,
    skillPoints: [
      { skillId: 4, points: 3 },
      { skillId: 9, points: -1 },
      { skillId: 10, points: 2 },
      { skillId: 50, points: 2 }
    ],
    price: 5600,
    maxDefense: 10,
    maxLowRankDefense: 15
  }),
  deepFreeze<ArmArmor>({
    id: 35,
    type: 'arms',
    name: 'Rathalos Vambraces',
    blade: true,
    gunner: false,
    defense: 20,
    fireRes: 3,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 0,
    rarity: 3,
    skillPoints: [
      { skillId: 25, points: 2 },
      { skillId: 35, points: 5 },
      { skillId: 36, points: -1 },
      { skillId: 66, points: 3 }
    ],
    price: 5600,
    maxDefense: 20,
    maxLowRankDefense: 30
  }),
  deepFreeze<ArmArmor>({
    id: 36,
    type: 'arms',
    name: 'Rathalos Guards',
    blade: false,
    gunner: true,
    defense: 10,
    fireRes: 3,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 0,
    rarity: 3,
    skillPoints: [
      { skillId: 25, points: 2 },
      { skillId: 35, points: 5 },
      { skillId: 36, points: -3 },
      { skillId: 66, points: 1 }
    ],
    price: 5600,
    maxDefense: 10,
    maxLowRankDefense: 15
  }),
  deepFreeze<ArmArmor>({
    id: 37,
    type: 'arms',
    name: 'Barioth Vambraces',
    blade: true,
    gunner: false,
    defense: 20,
    fireRes: -4,
    waterRes: 2,
    iceRes: 4,
    thunderRes: -3,
    dragonRes: 0,
    slots: 0,
    rarity: 3,
    skillPoints: [
      { skillId: 13, points: 2 },
      { skillId: 44, points: 5 },
      { skillId: 66, points: -2 },
      { skillId: 67, points: 2 }
    ],
    price: 5600,
    maxDefense: 20,
    maxLowRankDefense: 30
  }),
  deepFreeze<ArmArmor>({
    id: 38,
    type: 'arms',
    name: 'Barioth Guards',
    blade: false,
    gunner: true,
    defense: 10,
    fireRes: -4,
    waterRes: 2,
    iceRes: 4,
    thunderRes: -3,
    dragonRes: 0,
    slots: 0,
    rarity: 3,
    skillPoints: [
      { skillId: 13, points: 3 },
      { skillId: 44, points: 5 },
      { skillId: 66, points: -2 },
      { skillId: 67, points: 1 }
    ],
    price: 5600,
    maxDefense: 10,
    maxLowRankDefense: 15
  }),
  deepFreeze<ArmArmor>({
    id: 39,
    type: 'arms',
    name: 'Diablos Vambraces',
    blade: true,
    gunner: false,
    defense: 22,
    fireRes: 2,
    waterRes: -1,
    iceRes: -3,
    thunderRes: -1,
    dragonRes: -1,
    slots: 0,
    rarity: 3,
    skillPoints: [
      { skillId: 10, points: -3 },
      { skillId: 47, points: 3 },
      { skillId: 48, points: 5 }
    ],
    price: 6300,
    maxDefense: 22,
    maxLowRankDefense: 30
  }),
  deepFreeze<ArmArmor>({
    id: 40,
    type: 'arms',
    name: 'Diablos Guards',
    blade: false,
    gunner: true,
    defense: 11,
    fireRes: 2,
    waterRes: -1,
    iceRes: -3,
    thunderRes: -1,
    dragonRes: -1,
    slots: 0,
    rarity: 3,
    skillPoints: [
      { skillId: 5, points: 3 },
      { skillId: 8, points: 5 },
      { skillId: 10, points: -3 }
    ],
    price: 6300,
    maxDefense: 11,
    maxLowRankDefense: 15
  }),
  deepFreeze<ArmArmor>({
    id: 41,
    type: 'arms',
    name: 'Uragaan Vambraces',
    blade: true,
    gunner: false,
    defense: 22,
    fireRes: 3,
    waterRes: -4,
    iceRes: -1,
    thunderRes: 1,
    dragonRes: 2,
    slots: 1,
    rarity: 3,
    skillPoints: [
      { skillId: 19, points: 1 },
      { skillId: 33, points: 2 },
      { skillId: 36, points: 4 },
      { skillId: 46, points: -2 }
    ],
    price: 6300,
    maxDefense: 22,
    maxLowRankDefense: 30
  }),
  deepFreeze<ArmArmor>({
    id: 42,
    type: 'arms',
    name: 'Uragaan Guards',
    blade: false,
    gunner: true,
    defense: 11,
    fireRes: 3,
    waterRes: -4,
    iceRes: -1,
    thunderRes: 1,
    dragonRes: -2,
    slots: 1,
    rarity: 3,
    skillPoints: [
      { skillId: 3, points: 2 },
      { skillId: 33, points: 2 },
      { skillId: 36, points: 2 },
      { skillId: 46, points: -3 }
    ],
    price: 6300,
    maxDefense: 11,
    maxLowRankDefense: 15
  }),
  deepFreeze<ArmArmor>({
    id: 43,
    type: 'arms',
    name: 'Agnaktor Vambraces',
    blade: true,
    gunner: false,
    defense: 22,
    fireRes: 4,
    waterRes: -4,
    iceRes: -2,
    thunderRes: 1,
    dragonRes: 0,
    slots: 1,
    rarity: 3,
    skillPoints: [
      { skillId: 13, points: -1 },
      { skillId: 27, points: 2 },
      { skillId: 28, points: 3 },
      { skillId: 52, points: 3 }
    ],
    price: 7200,
    maxDefense: 22,
    maxLowRankDefense: 30
  }),
  deepFreeze<ArmArmor>({
    id: 44,
    type: 'arms',
    name: 'Agnaktor Guards',
    blade: false,
    gunner: true,
    defense: 11,
    fireRes: 4,
    waterRes: -4,
    iceRes: -2,
    thunderRes: 1,
    dragonRes: 0,
    slots: 1,
    rarity: 3,
    skillPoints: [
      { skillId: 13, points: -3 },
      { skillId: 28, points: 2 },
      { skillId: 29, points: 2 },
      { skillId: 52, points: 2 }
    ],
    price: 7200,
    maxDefense: 11,
    maxLowRankDefense: 15
  }),
  deepFreeze<ArmArmor>({
    id: 45,
    type: 'arms',
    name: 'Helios Vambraces',
    blade: true,
    gunner: false,
    defense: 24,
    fireRes: 0,
    waterRes: 4,
    iceRes: 3,
    thunderRes: -3,
    dragonRes: -4,
    slots: 1,
    rarity: 3,
    skillPoints: [
      { skillId: 0, points: -3 },
      { skillId: 1, points: 3 },
      { skillId: 11, points: 2 },
      { skillId: 37, points: -1 }
    ],
    price: 11000,
    maxDefense: 24,
    maxLowRankDefense: 32
  }),
  deepFreeze<ArmArmor>({
    id: 46,
    type: 'arms',
    name: 'Helios Guards',
    blade: false,
    gunner: true,
    defense: 12,
    fireRes: 0,
    waterRes: 4,
    iceRes: 3,
    thunderRes: -3,
    dragonRes: -4,
    slots: 1,
    rarity: 3,
    skillPoints: [
      { skillId: 3, points: -3 },
      { skillId: 11, points: 2 },
      { skillId: 14, points: 3 },
      { skillId: 37, points: -1 }
    ],
    price: 11000,
    maxDefense: 12,
    maxLowRankDefense: 16
  }),
  deepFreeze<ArmArmor>({
    id: 47,
    type: 'arms',
    name: 'Yamato Kote',
    blade: true,
    gunner: false,
    defense: 24,
    fireRes: 3,
    waterRes: 0,
    iceRes: -3,
    thunderRes: 0,
    dragonRes: -3,
    slots: 2,
    rarity: 3,
    skillPoints: [
      { skillId: 0, points: 1 },
      { skillId: 18, points: 3 },
      { skillId: 24, points: 1 },
      { skillId: 71, points: -2 }
    ],
    price: 12000,
    maxDefense: 24,
    maxLowRankDefense: 32
  }),
  deepFreeze<ArmArmor>({
    id: 48,
    type: 'arms',
    name: 'Mutsu Kote',
    blade: false,
    gunner: true,
    defense: 12,
    fireRes: 3,
    waterRes: 0,
    iceRes: -3,
    thunderRes: 0,
    dragonRes: -3,
    slots: 2,
    rarity: 3,
    skillPoints: [
      { skillId: 3, points: 1 },
      { skillId: 24, points: 1 },
      { skillId: 32, points: 3 },
      { skillId: 71, points: -2 }
    ],
    price: 12000,
    maxDefense: 12,
    maxLowRankDefense: 16
  }),
  deepFreeze<ArmArmor>({
    id: 49,
    type: 'arms',
    name: 'Leather Vambraces+',
    blade: true,
    gunner: false,
    defense: 26,
    fireRes: -2,
    waterRes: 0,
    iceRes: -2,
    thunderRes: 3,
    dragonRes: 2,
    slots: 2,
    rarity: 4,
    skillPoints: [
      { skillId: 40, points: 2 },
      { skillId: 41, points: 3 },
      { skillId: 69, points: 3 }
    ],
    price: 4600,
    maxDefense: 26
  }),
  deepFreeze<ArmArmor>({
    id: 50,
    type: 'arms',
    name: 'Leather Guards+',
    blade: false,
    gunner: true,
    defense: 15,
    fireRes: -2,
    waterRes: 0,
    iceRes: -2,
    thunderRes: 3,
    dragonRes: 2,
    slots: 2,
    rarity: 4,
    skillPoints: [
      { skillId: 40, points: 4 },
      { skillId: 41, points: 2 },
      { skillId: 69, points: 2 }
    ],
    price: 4600,
    maxDefense: 15
  }),
  deepFreeze<ArmArmor>({
    id: 51,
    type: 'arms',
    name: 'Chainmail Vambraces+',
    blade: true,
    gunner: false,
    defense: 30,
    fireRes: -1,
    waterRes: -2,
    iceRes: 4,
    thunderRes: -1,
    dragonRes: 1,
    slots: 2,
    rarity: 4,
    skillPoints: [
      { skillId: 23, points: 3 },
      { skillId: 71, points: 4 },
      { skillId: 72, points: 1 }
    ],
    price: 5400,
    maxDefense: 30
  }),
  deepFreeze<ArmArmor>({
    id: 52,
    type: 'arms',
    name: 'Chainmail Guards+',
    blade: false,
    gunner: true,
    defense: 18,
    fireRes: -1,
    waterRes: -2,
    iceRes: 4,
    thunderRes: -1,
    dragonRes: 1,
    slots: 2,
    rarity: 4,
    skillPoints: [
      { skillId: 23, points: 5 },
      { skillId: 71, points: 2 },
      { skillId: 72, points: 1 }
    ],
    price: 5400,
    maxDefense: 18
  }),
  deepFreeze<ArmArmor>({
    id: 53,
    type: 'arms',
    name: "Hunter's Vambraces+",
    blade: true,
    gunner: false,
    defense: 30,
    fireRes: 0,
    waterRes: -2,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 2,
    rarity: 4,
    skillPoints: [
      { skillId: 25, points: 2 },
      { skillId: 42, points: 2 },
      { skillId: 44, points: 3 },
      { skillId: 62, points: -1 },
      { skillId: 68, points: 1 }
    ],
    price: 5400,
    maxDefense: 30
  }),
  deepFreeze<ArmArmor>({
    id: 54,
    type: 'arms',
    name: "Hunter's Guards+",
    blade: false,
    gunner: true,
    defense: 18,
    fireRes: 0,
    waterRes: -2,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 2,
    rarity: 4,
    skillPoints: [
      { skillId: 25, points: 2 },
      { skillId: 42, points: 1 },
      { skillId: 44, points: 2 },
      { skillId: 62, points: -1 },
      { skillId: 68, points: 3 }
    ],
    price: 5400,
    maxDefense: 18
  }),
  deepFreeze<ArmArmor>({
    id: 55,
    type: 'arms',
    name: 'Bone Vambraces+',
    blade: true,
    gunner: false,
    defense: 34,
    fireRes: 3,
    waterRes: -2,
    iceRes: -1,
    thunderRes: 2,
    dragonRes: 3,
    slots: 2,
    rarity: 4,
    skillPoints: [
      { skillId: 13, points: 2 },
      { skillId: 34, points: 5 },
      { skillId: 54, points: -1 },
      { skillId: 77, points: 1 }
    ],
    price: 6400,
    maxDefense: 34
  }),
  deepFreeze<ArmArmor>({
    id: 56,
    type: 'arms',
    name: 'Bone Guards+',
    blade: false,
    gunner: true,
    defense: 20,
    fireRes: 3,
    waterRes: -2,
    iceRes: -1,
    thunderRes: 2,
    dragonRes: 3,
    slots: 2,
    rarity: 4,
    skillPoints: [
      { skillId: 13, points: 3 },
      { skillId: 34, points: 4 },
      { skillId: 54, points: -1 },
      { skillId: 77, points: 1 }
    ],
    price: 6400,
    maxDefense: 20
  }),
  deepFreeze<ArmArmor>({
    id: 57,
    type: 'arms',
    name: 'Alloy Vambraces+',
    blade: true,
    gunner: false,
    defense: 34,
    fireRes: 1,
    waterRes: 2,
    iceRes: -1,
    thunderRes: -2,
    dragonRes: -1,
    slots: 2,
    rarity: 4,
    skillPoints: [
      { skillId: 25, points: 4 },
      { skillId: 26, points: 1 },
      { skillId: 76, points: 3 },
      { skillId: 78, points: -1 }
    ],
    price: 7100,
    maxDefense: 34
  }),
  deepFreeze<ArmArmor>({
    id: 58,
    type: 'arms',
    name: 'Alloy Guards+',
    blade: false,
    gunner: true,
    defense: 20,
    fireRes: 1,
    waterRes: 2,
    iceRes: -1,
    thunderRes: -2,
    dragonRes: -1,
    slots: 2,
    rarity: 4,
    skillPoints: [
      { skillId: 7, points: 1 },
      { skillId: 25, points: 4 },
      { skillId: 76, points: 3 },
      { skillId: 78, points: -1 }
    ],
    price: 7100,
    maxDefense: 20
  }),
  deepFreeze<ArmArmor>({
    id: 59,
    type: 'arms',
    name: 'Jaggi Vambraces+',
    blade: true,
    gunner: false,
    defense: 38,
    fireRes: -3,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: 2,
    slots: 1,
    rarity: 5,
    skillPoints: [
      { skillId: 35, points: 3 },
      { skillId: 55, points: 4 },
      { skillId: 58, points: 3 },
      { skillId: 67, points: -1 }
    ],
    price: 8000,
    maxDefense: 38
  }),
  deepFreeze<ArmArmor>({
    id: 60,
    type: 'arms',
    name: 'Jaggi Guards+',
    blade: false,
    gunner: true,
    defense: 22,
    fireRes: -3,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: 2,
    slots: 1,
    rarity: 5,
    skillPoints: [
      { skillId: 35, points: 1 },
      { skillId: 55, points: 5 },
      { skillId: 58, points: 3 },
      { skillId: 67, points: -2 }
    ],
    price: 8000,
    maxDefense: 22
  }),
  deepFreeze<ArmArmor>({
    id: 61,
    type: 'arms',
    name: 'Rhenoplos Vambraces+',
    blade: true,
    gunner: false,
    defense: 38,
    fireRes: 3,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -2,
    dragonRes: 2,
    slots: 2,
    rarity: 5,
    skillPoints: [
      { skillId: 25, points: 1 },
      { skillId: 39, points: 1 },
      { skillId: 46, points: 5 },
      { skillId: 56, points: 1 },
      { skillId: 63, points: -1 }
    ],
    price: 8500,
    maxDefense: 38
  }),
  deepFreeze<ArmArmor>({
    id: 62,
    type: 'arms',
    name: 'Rhenoplos Guards+',
    blade: false,
    gunner: true,
    defense: 22,
    fireRes: 3,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -2,
    dragonRes: 2,
    slots: 2,
    rarity: 5,
    skillPoints: [
      { skillId: 3, points: 2 },
      { skillId: 25, points: 1 },
      { skillId: 31, points: 1 },
      { skillId: 46, points: 3 },
      { skillId: 63, points: -2 }
    ],
    price: 8500,
    maxDefense: 22
  }),
  deepFreeze<ArmArmor>({
    id: 63,
    type: 'arms',
    name: 'Qurupeco Vambraces+',
    blade: true,
    gunner: false,
    defense: 42,
    fireRes: 4,
    waterRes: -3,
    iceRes: -4,
    thunderRes: 0,
    dragonRes: 1,
    slots: 0,
    rarity: 5,
    skillPoints: [
      { skillId: 36, points: 3 },
      { skillId: 38, points: 6 },
      { skillId: 43, points: 3 },
      { skillId: 64, points: -1 }
    ],
    price: 10000,
    maxDefense: 42
  }),
  deepFreeze<ArmArmor>({
    id: 64,
    type: 'arms',
    name: 'Qurupeco Guards+',
    blade: false,
    gunner: true,
    defense: 25,
    fireRes: 4,
    waterRes: -3,
    iceRes: -4,
    thunderRes: 0,
    dragonRes: 1,
    slots: 0,
    rarity: 5,
    skillPoints: [
      { skillId: 36, points: 4 },
      { skillId: 38, points: 6 },
      { skillId: 43, points: 2 },
      { skillId: 64, points: -1 }
    ],
    price: 10000,
    maxDefense: 25
  }),
  deepFreeze<ArmArmor>({
    id: 65,
    type: 'arms',
    name: 'Ludroth Vambraces+',
    blade: true,
    gunner: false,
    defense: 44,
    fireRes: -4,
    waterRes: 4,
    iceRes: 0,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 5,
    skillPoints: [
      { skillId: 25, points: 2 },
      { skillId: 34, points: -1 },
      { skillId: 37, points: 4 },
      { skillId: 49, points: 2 },
      { skillId: 79, points: 2 }
    ],
    price: 11800,
    maxDefense: 44
  }),
  deepFreeze<ArmArmor>({
    id: 66,
    type: 'arms',
    name: 'Ludroth Guards+',
    blade: false,
    gunner: true,
    defense: 26,
    fireRes: -4,
    waterRes: 4,
    iceRes: 0,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 5,
    skillPoints: [
      { skillId: 25, points: 2 },
      { skillId: 30, points: 1 },
      { skillId: 34, points: -1 },
      { skillId: 37, points: 4 },
      { skillId: 49, points: 3 }
    ],
    price: 11800,
    maxDefense: 26
  }),
  deepFreeze<ArmArmor>({
    id: 67,
    type: 'arms',
    name: 'Steel Vambraces+',
    blade: true,
    gunner: false,
    defense: 42,
    fireRes: -1,
    waterRes: 1,
    iceRes: 1,
    thunderRes: -1,
    dragonRes: 0,
    slots: 1,
    rarity: 5,
    skillPoints: [
      { skillId: 26, points: 4 },
      { skillId: 27, points: 5 },
      { skillId: 50, points: -2 }
    ],
    price: 11000,
    maxDefense: 42
  }),
  deepFreeze<ArmArmor>({
    id: 68,
    type: 'arms',
    name: 'Baggi Vambraces+',
    blade: true,
    gunner: false,
    defense: 44,
    fireRes: -4,
    waterRes: -1,
    iceRes: 4,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 5,
    skillPoints: [
      { skillId: 17, points: 2 },
      { skillId: 18, points: 4 },
      { skillId: 55, points: -1 },
      { skillId: 64, points: 4 }
    ],
    price: 12300,
    maxDefense: 44
  }),
  deepFreeze<ArmArmor>({
    id: 69,
    type: 'arms',
    name: 'Baggi Guards+',
    blade: false,
    gunner: true,
    defense: 26,
    fireRes: -4,
    waterRes: -1,
    iceRes: 4,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 5,
    skillPoints: [
      { skillId: 6, points: 3 },
      { skillId: 17, points: 2 },
      { skillId: 55, points: -1 },
      { skillId: 64, points: 5 }
    ],
    price: 12300,
    maxDefense: 26
  }),
  deepFreeze<ArmArmor>({
    id: 70,
    type: 'arms',
    name: 'Barroth Vambraces+',
    blade: true,
    gunner: false,
    defense: 48,
    fireRes: -5,
    waterRes: 5,
    iceRes: -4,
    thunderRes: 4,
    dragonRes: 0,
    slots: 3,
    rarity: 5,
    skillPoints: [
      { skillId: 13, points: 1 },
      { skillId: 25, points: -3 },
      { skillId: 35, points: 1 },
      { skillId: 45, points: 2 }
    ],
    price: 13800,
    maxDefense: 48
  }),
  deepFreeze<ArmArmor>({
    id: 71,
    type: 'arms',
    name: 'Barroth Guards+',
    blade: false,
    gunner: true,
    defense: 28,
    fireRes: -5,
    waterRes: 5,
    iceRes: -4,
    thunderRes: 4,
    dragonRes: 0,
    slots: 3,
    rarity: 5,
    skillPoints: [
      { skillId: 13, points: 1 },
      { skillId: 25, points: -3 },
      { skillId: 35, points: 1 },
      { skillId: 45, points: 2 }
    ],
    price: 13800,
    maxDefense: 28
  }),
  deepFreeze<ArmArmor>({
    id: 72,
    type: 'arms',
    name: 'Gobul Vambraces+',
    blade: true,
    gunner: false,
    defense: 50,
    fireRes: -2,
    waterRes: 4,
    iceRes: 0,
    thunderRes: -4,
    dragonRes: 2,
    slots: 1,
    rarity: 5,
    skillPoints: [
      { skillId: 24, points: -1 },
      { skillId: 25, points: 2 },
      { skillId: 46, points: 4 },
      { skillId: 55, points: 4 }
    ],
    price: 14800,
    maxDefense: 50
  }),
  deepFreeze<ArmArmor>({
    id: 73,
    type: 'arms',
    name: 'Gobul Guards+',
    blade: false,
    gunner: true,
    defense: 30,
    fireRes: -2,
    waterRes: 4,
    iceRes: 0,
    thunderRes: -4,
    dragonRes: 2,
    slots: 1,
    rarity: 5,
    skillPoints: [
      { skillId: 24, points: -1 },
      { skillId: 25, points: 2 },
      { skillId: 46, points: 4 },
      { skillId: 55, points: 4 }
    ],
    price: 14800,
    maxDefense: 30
  }),
  deepFreeze<ArmArmor>({
    id: 74,
    type: 'arms',
    name: 'Guild Bard Braces+',
    blade: true,
    gunner: false,
    defense: 36,
    fireRes: 0,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 1,
    rarity: 6,
    skillPoints: [
      { skillId: 12, points: 3 },
      { skillId: 15, points: 2 },
      { skillId: 17, points: 1 },
      { skillId: 37, points: -5 }
    ],
    price: 25000,
    maxDefense: 36
  }),
  deepFreeze<ArmArmor>({
    id: 75,
    type: 'arms',
    name: 'Guild Bard Sleeves+',
    blade: false,
    gunner: true,
    defense: 22,
    fireRes: 0,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 1,
    rarity: 6,
    skillPoints: [
      { skillId: 12, points: 2 },
      { skillId: 15, points: 2 },
      { skillId: 17, points: 2 },
      { skillId: 37, points: -5 }
    ],
    price: 25000,
    maxDefense: 22
  }),
  deepFreeze<ArmArmor>({
    id: 76,
    type: 'arms',
    name: 'Rathian Vambraces+',
    blade: true,
    gunner: false,
    defense: 50,
    fireRes: 4,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 1,
    rarity: 5,
    skillPoints: [
      { skillId: 11, points: 1 },
      { skillId: 23, points: 4 },
      { skillId: 37, points: -2 },
      { skillId: 61, points: 4 }
    ],
    price: 14800,
    maxDefense: 50
  }),
  deepFreeze<ArmArmor>({
    id: 77,
    type: 'arms',
    name: 'Rathian Guards+',
    blade: false,
    gunner: true,
    defense: 30,
    fireRes: 4,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 1,
    rarity: 5,
    skillPoints: [
      { skillId: 11, points: 2 },
      { skillId: 23, points: 3 },
      { skillId: 37, points: -3 },
      { skillId: 61, points: 3 }
    ],
    price: 14800,
    maxDefense: 30
  }),
  deepFreeze<ArmArmor>({
    id: 78,
    type: 'arms',
    name: 'Gigginox Vambraces+',
    blade: true,
    gunner: false,
    defense: 54,
    fireRes: -4,
    waterRes: -1,
    iceRes: 2,
    thunderRes: 3,
    dragonRes: 0,
    slots: 3,
    rarity: 5,
    skillPoints: [
      { skillId: 9, points: 1 },
      { skillId: 22, points: 1 },
      { skillId: 23, points: -3 },
      { skillId: 49, points: 2 }
    ],
    price: 15800,
    maxDefense: 54
  }),
  deepFreeze<ArmArmor>({
    id: 79,
    type: 'arms',
    name: 'Gigginox Guards+',
    blade: false,
    gunner: true,
    defense: 32,
    fireRes: -4,
    waterRes: -1,
    iceRes: 2,
    thunderRes: 3,
    dragonRes: 0,
    slots: 3,
    rarity: 5,
    skillPoints: [
      { skillId: 9, points: 1 },
      { skillId: 22, points: 2 },
      { skillId: 23, points: -3 },
      { skillId: 49, points: 1 }
    ],
    price: 15800,
    maxDefense: 32
  }),
  deepFreeze<ArmArmor>({
    id: 80,
    type: 'arms',
    name: 'Ingot Vambraces+',
    blade: true,
    gunner: false,
    defense: 54,
    fireRes: -2,
    waterRes: -1,
    iceRes: 1,
    thunderRes: 3,
    dragonRes: 2,
    slots: 3,
    rarity: 5,
    skillPoints: [
      { skillId: 26, points: -3 },
      { skillId: 28, points: 1 },
      { skillId: 39, points: 2 },
      { skillId: 63, points: 1 }
    ],
    price: 17500,
    maxDefense: 54
  }),
  deepFreeze<ArmArmor>({
    id: 81,
    type: 'arms',
    name: 'Ingot Guards+',
    blade: false,
    gunner: true,
    defense: 32,
    fireRes: -2,
    waterRes: -1,
    iceRes: 1,
    thunderRes: 3,
    dragonRes: 2,
    slots: 3,
    rarity: 5,
    skillPoints: [
      { skillId: 3, points: 2 },
      { skillId: 28, points: 1 },
      { skillId: 29, points: -3 },
      { skillId: 63, points: 1 }
    ],
    price: 17500,
    maxDefense: 32
  }),
  deepFreeze<ArmArmor>({
    id: 82,
    type: 'arms',
    name: 'Dober Vambraces',
    blade: true,
    gunner: false,
    defense: 58,
    fireRes: -2,
    waterRes: -2,
    iceRes: 1,
    thunderRes: 1,
    dragonRes: 5,
    slots: 1,
    rarity: 6,
    skillPoints: [
      { skillId: 13, points: 3 },
      { skillId: 45, points: -1 },
      { skillId: 48, points: 2 },
      { skillId: 65, points: 5 }
    ],
    price: 19000,
    maxDefense: 58
  }),
  deepFreeze<ArmArmor>({
    id: 83,
    type: 'arms',
    name: 'Dober Guards',
    blade: false,
    gunner: true,
    defense: 34,
    fireRes: -2,
    waterRes: -2,
    iceRes: 1,
    thunderRes: 1,
    dragonRes: 5,
    slots: 1,
    rarity: 6,
    skillPoints: [
      { skillId: 6, points: 3 },
      { skillId: 30, points: 4 },
      { skillId: 45, points: -1 },
      { skillId: 65, points: 3 }
    ],
    price: 19000,
    maxDefense: 34
  }),
  deepFreeze<ArmArmor>({
    id: 84,
    type: 'arms',
    name: 'Lagiacrus Vambraces+',
    blade: true,
    gunner: false,
    defense: 58,
    fireRes: -4,
    waterRes: 2,
    iceRes: -1,
    thunderRes: 5,
    dragonRes: -2,
    slots: 1,
    rarity: 6,
    skillPoints: [
      { skillId: 9, points: -2 },
      { skillId: 10, points: 2 },
      { skillId: 20, points: 5 },
      { skillId: 50, points: 2 }
    ],
    price: 18000,
    maxDefense: 58
  }),
  deepFreeze<ArmArmor>({
    id: 85,
    type: 'arms',
    name: 'Lagiacrus Guards+',
    blade: false,
    gunner: true,
    defense: 34,
    fireRes: -4,
    waterRes: 2,
    iceRes: -1,
    thunderRes: 5,
    dragonRes: -2,
    slots: 1,
    rarity: 6,
    skillPoints: [
      { skillId: 9, points: -3 },
      { skillId: 10, points: 2 },
      { skillId: 21, points: 2 },
      { skillId: 50, points: 4 }
    ],
    price: 18000,
    maxDefense: 34
  }),
  deepFreeze<ArmArmor>({
    id: 86,
    type: 'arms',
    name: 'Rathalos Vambraces+',
    blade: true,
    gunner: false,
    defense: 58,
    fireRes: 4,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 1,
    rarity: 6,
    skillPoints: [
      { skillId: 2, points: 1 },
      { skillId: 25, points: 3 },
      { skillId: 36, points: -2 },
      { skillId: 66, points: 5 }
    ],
    price: 18000,
    maxDefense: 58
  }),
  deepFreeze<ArmArmor>({
    id: 87,
    type: 'arms',
    name: 'Rathalos Guards+',
    blade: false,
    gunner: true,
    defense: 34,
    fireRes: 4,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 1,
    rarity: 6,
    skillPoints: [
      { skillId: 4, points: 3 },
      { skillId: 25, points: 4 },
      { skillId: 36, points: -1 },
      { skillId: 66, points: 3 }
    ],
    price: 18000,
    maxDefense: 34
  }),
  deepFreeze<ArmArmor>({
    id: 88,
    type: 'arms',
    name: 'Barioth Vambraces+',
    blade: true,
    gunner: false,
    defense: 58,
    fireRes: -4,
    waterRes: 2,
    iceRes: 5,
    thunderRes: -3,
    dragonRes: 0,
    slots: 1,
    rarity: 6,
    skillPoints: [
      { skillId: 16, points: 4 },
      { skillId: 44, points: 4 },
      { skillId: 66, points: -1 },
      { skillId: 67, points: 2 }
    ],
    price: 18000,
    maxDefense: 58
  }),
  deepFreeze<ArmArmor>({
    id: 89,
    type: 'arms',
    name: 'Barioth Guards+',
    blade: false,
    gunner: true,
    defense: 34,
    fireRes: -4,
    waterRes: 2,
    iceRes: 5,
    thunderRes: -3,
    dragonRes: 0,
    slots: 1,
    rarity: 6,
    skillPoints: [
      { skillId: 16, points: 4 },
      { skillId: 44, points: 4 },
      { skillId: 66, points: -2 },
      { skillId: 67, points: 1 }
    ],
    price: 18000,
    maxDefense: 34
  }),
  deepFreeze<ArmArmor>({
    id: 90,
    type: 'arms',
    name: 'Diablos Vambraces+',
    blade: true,
    gunner: false,
    defense: 62,
    fireRes: 3,
    waterRes: -1,
    iceRes: -4,
    thunderRes: -1,
    dragonRes: -1,
    slots: 3,
    rarity: 6,
    skillPoints: [
      { skillId: 10, points: -4 },
      { skillId: 47, points: 1 },
      { skillId: 48, points: 2 }
    ],
    price: 18800,
    maxDefense: 62
  }),
  deepFreeze<ArmArmor>({
    id: 91,
    type: 'arms',
    name: 'Diablos Guards+',
    blade: false,
    gunner: true,
    defense: 37,
    fireRes: 3,
    waterRes: -1,
    iceRes: -4,
    thunderRes: -1,
    dragonRes: -1,
    slots: 3,
    rarity: 6,
    skillPoints: [
      { skillId: 5, points: 1 },
      { skillId: 8, points: 2 },
      { skillId: 10, points: -4 }
    ],
    price: 18800,
    maxDefense: 37
  }),
  deepFreeze<ArmArmor>({
    id: 92,
    type: 'arms',
    name: 'Uragaan Vambraces+',
    blade: true,
    gunner: false,
    defense: 62,
    fireRes: 4,
    waterRes: -4,
    iceRes: -1,
    thunderRes: 1,
    dragonRes: -2,
    slots: 3,
    rarity: 6,
    skillPoints: [
      { skillId: 19, points: 1 },
      { skillId: 33, points: 2 },
      { skillId: 36, points: 2 },
      { skillId: 46, points: -2 }
    ],
    price: 18800,
    maxDefense: 62
  }),
  deepFreeze<ArmArmor>({
    id: 93,
    type: 'arms',
    name: 'Uragaan Guards+',
    blade: false,
    gunner: true,
    defense: 37,
    fireRes: 4,
    waterRes: -4,
    iceRes: -1,
    thunderRes: 1,
    dragonRes: -2,
    slots: 3,
    rarity: 6,
    skillPoints: [
      { skillId: 3, points: 1 },
      { skillId: 33, points: 2 },
      { skillId: 36, points: 1 },
      { skillId: 46, points: -3 }
    ],
    price: 18800,
    maxDefense: 37
  }),
  deepFreeze<ArmArmor>({
    id: 94,
    type: 'arms',
    name: 'Agnaktor Vambraces+',
    blade: true,
    gunner: false,
    defense: 62,
    fireRes: 5,
    waterRes: -4,
    iceRes: -2,
    thunderRes: 1,
    dragonRes: 0,
    slots: 3,
    rarity: 6,
    skillPoints: [
      { skillId: 0, points: 1 },
      { skillId: 13, points: -3 },
      { skillId: 27, points: 2 },
      { skillId: 52, points: 1 }
    ],
    price: 19800,
    maxDefense: 62
  }),
  deepFreeze<ArmArmor>({
    id: 95,
    type: 'arms',
    name: 'Agnaktor Guards+',
    blade: false,
    gunner: true,
    defense: 37,
    fireRes: 5,
    waterRes: -4,
    iceRes: -2,
    thunderRes: 1,
    dragonRes: 0,
    slots: 3,
    rarity: 6,
    skillPoints: [
      { skillId: 4, points: 2 },
      { skillId: 7, points: 1 },
      { skillId: 13, points: -3 },
      { skillId: 52, points: 1 }
    ],
    price: 19800,
    maxDefense: 37
  }),
  deepFreeze<ArmArmor>({
    id: 96,
    type: 'arms',
    name: 'Vangis Vambraces',
    blade: true,
    gunner: false,
    defense: 64,
    fireRes: 0,
    waterRes: 0,
    iceRes: 3,
    thunderRes: -4,
    dragonRes: -4,
    slots: 0,
    rarity: 7,
    skillPoints: [
      { skillId: 1, points: 3 },
      { skillId: 34, points: -1 },
      { skillId: 35, points: 5 },
      { skillId: 42, points: 4 }
    ],
    price: 41500,
    maxDefense: 64
  }),
  deepFreeze<ArmArmor>({
    id: 97,
    type: 'arms',
    name: 'Vangis Guards',
    blade: false,
    gunner: true,
    defense: 38,
    fireRes: 0,
    waterRes: 0,
    iceRes: 3,
    thunderRes: -4,
    dragonRes: -4,
    slots: 0,
    rarity: 7,
    skillPoints: [
      { skillId: 14, points: 2 },
      { skillId: 34, points: -2 },
      { skillId: 35, points: 6 },
      { skillId: 42, points: 3 }
    ],
    price: 41500,
    maxDefense: 38
  }),
  deepFreeze<ArmArmor>({
    id: 98,
    type: 'arms',
    name: 'Damascus Vambraces',
    blade: true,
    gunner: false,
    defense: 62,
    fireRes: -2,
    waterRes: 0,
    iceRes: 2,
    thunderRes: -2,
    dragonRes: 3,
    slots: 0,
    rarity: 6,
    skillPoints: [
      { skillId: 13, points: -2 },
      { skillId: 19, points: 3 },
      { skillId: 23, points: 5 },
      { skillId: 28, points: 3 }
    ],
    price: 32300,
    maxDefense: 62
  }),
  deepFreeze<ArmArmor>({
    id: 99,
    type: 'arms',
    name: 'Damascus Guards',
    blade: false,
    gunner: true,
    defense: 37,
    fireRes: -2,
    waterRes: 0,
    iceRes: 2,
    thunderRes: -2,
    dragonRes: 3,
    slots: 0,
    rarity: 6,
    skillPoints: [
      { skillId: 13, points: -2 },
      { skillId: 23, points: 4 },
      { skillId: 28, points: 2 },
      { skillId: 29, points: 5 }
    ],
    price: 32300,
    maxDefense: 37
  }),
  deepFreeze<ArmArmor>({
    id: 100,
    type: 'arms',
    name: 'Helios Vambraces+',
    blade: true,
    gunner: false,
    defense: 66,
    fireRes: 0,
    waterRes: 5,
    iceRes: 3,
    thunderRes: -3,
    dragonRes: -4,
    slots: 0,
    rarity: 6,
    skillPoints: [
      { skillId: 0, points: -1 },
      { skillId: 1, points: 3 },
      { skillId: 11, points: 5 },
      { skillId: 37, points: -4 }
    ],
    price: 26200,
    maxDefense: 66
  }),
  deepFreeze<ArmArmor>({
    id: 101,
    type: 'arms',
    name: 'Helios Guards+',
    blade: false,
    gunner: true,
    defense: 39,
    fireRes: 0,
    waterRes: 5,
    iceRes: 3,
    thunderRes: -3,
    dragonRes: -4,
    slots: 0,
    rarity: 6,
    skillPoints: [
      { skillId: 3, points: -1 },
      { skillId: 11, points: 5 },
      { skillId: 14, points: 3 },
      { skillId: 37, points: -4 }
    ],
    price: 26200,
    maxDefense: 39
  }),
  deepFreeze<ArmArmor>({
    id: 102,
    type: 'arms',
    name: 'Yamato Kote+',
    blade: true,
    gunner: false,
    defense: 66,
    fireRes: 4,
    waterRes: 0,
    iceRes: -3,
    thunderRes: 0,
    dragonRes: -4,
    slots: 3,
    rarity: 6,
    skillPoints: [
      { skillId: 0, points: 1 },
      { skillId: 18, points: 2 },
      { skillId: 24, points: 1 },
      { skillId: 71, points: -3 }
    ],
    price: 27500,
    maxDefense: 66
  }),
  deepFreeze<ArmArmor>({
    id: 103,
    type: 'arms',
    name: 'Mutsu Kote+',
    blade: false,
    gunner: true,
    defense: 39,
    fireRes: 4,
    waterRes: 0,
    iceRes: -3,
    thunderRes: 0,
    dragonRes: -4,
    slots: 3,
    rarity: 6,
    skillPoints: [
      { skillId: 3, points: 2 },
      { skillId: 24, points: 1 },
      { skillId: 32, points: 1 },
      { skillId: 71, points: -3 }
    ],
    price: 27500,
    maxDefense: 39
  }),
  deepFreeze<ArmArmor>({
    id: 104,
    type: 'arms',
    name: 'Escadora Arms',
    blade: true,
    gunner: false,
    defense: 70,
    fireRes: -1,
    waterRes: -1,
    iceRes: -1,
    thunderRes: 0,
    dragonRes: -5,
    slots: 0,
    rarity: 7,
    skillPoints: [
      { skillId: 16, points: 4 },
      { skillId: 20, points: 5 },
      { skillId: 43, points: -3 },
      { skillId: 81, points: 1 }
    ],
    price: 66666,
    maxDefense: 70
  }),
  deepFreeze<ArmArmor>({
    id: 105,
    type: 'arms',
    name: 'Escadora Arma',
    blade: false,
    gunner: true,
    defense: 42,
    fireRes: -1,
    waterRes: -1,
    iceRes: -1,
    thunderRes: 0,
    dragonRes: -5,
    slots: 1,
    rarity: 7,
    skillPoints: [
      { skillId: 16, points: 4 },
      { skillId: 21, points: 3 },
      { skillId: 43, points: -3 },
      { skillId: 81, points: 1 }
    ],
    price: 66666,
    maxDefense: 42
  }),
  deepFreeze<ArmArmor>({
    id: 106,
    type: 'arms',
    name: 'Chakra Bracelet',
    blade: true,
    gunner: true,
    defense: 18,
    fireRes: 0,
    waterRes: 0,
    iceRes: 10,
    thunderRes: 0,
    dragonRes: -10,
    slots: 3,
    rarity: 7,
    skillPoints: [],
    price: 33333,
    maxDefense: 18
  })
];
