import { deepFreeze } from '../../utils';
import type { ArmArmor } from './types';

export const ArmArmors: ArmArmor[] = [
  deepFreeze<ArmArmor>({
    id: 0,
    type: 'arms',
    name: 'Leather Gloves',
    blade: true,
    gunner: true,
    defense: 1,
    fireRes: -1,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 3,
    dragonRes: 2,
    slots: 1,
    rarity: 1,
    price: 150,
    maxDefense: 1,
    maxLowRankDefense: 9,
    skillPoints: { attack: 1, gathering: 1, spd_gather: 3, whim: 4 }
  }),
  deepFreeze<ArmArmor>({
    id: 1,
    type: 'arms',
    name: 'Chainmail Gloves',
    blade: true,
    gunner: true,
    defense: 2,
    fireRes: -1,
    waterRes: -1,
    iceRes: 3,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 1,
    price: 200,
    maxDefense: 2,
    maxLowRankDefense: 9,
    skillPoints: {
      health: 3,
      fishing: 2,
      combo_rate: 2,
      combo_plus: 2
    }
  }),
  deepFreeze<ArmArmor>({
    id: 2,
    type: 'arms',
    name: "Hunter's Vambraces",
    blade: true,
    gunner: false,
    defense: 6,
    fireRes: -1,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: -1,
    slots: 1,
    rarity: 1,
    price: 500,
    maxDefense: 6,
    maxLowRankDefense: 20,
    skillPoints: { psychic: 5, water_res: -1, map: 1, bbq: 2 }
  }),
  deepFreeze<ArmArmor>({
    id: 3,
    type: 'arms',
    name: "Hunter's Guards",
    blade: false,
    gunner: true,
    defense: 3,
    fireRes: -1,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: -1,
    slots: 1,
    rarity: 1,
    price: 500,
    maxDefense: 3,
    maxLowRankDefense: 10,
    skillPoints: { psychic: 4, water_res: -2, map: 1, bbq: 2 }
  }),
  deepFreeze<ArmArmor>({
    id: 4,
    type: 'arms',
    name: 'Bone Vambraces',
    blade: true,
    gunner: false,
    defense: 8,
    fireRes: 2,
    waterRes: -2,
    iceRes: -1,
    thunderRes: 2,
    dragonRes: 3,
    slots: 1,
    rarity: 1,
    price: 750,
    maxDefense: 8,
    maxLowRankDefense: 22,
    skillPoints: {
      hunger: 4,
      attack: 1,
      sleep: -1,
      lastingpwr: 2,
      perception: 1
    }
  }),
  deepFreeze<ArmArmor>({
    id: 5,
    type: 'arms',
    name: 'Bone Guards',
    blade: false,
    gunner: true,
    defense: 4,
    fireRes: 2,
    waterRes: -2,
    iceRes: -1,
    thunderRes: 2,
    dragonRes: 3,
    slots: 1,
    rarity: 1,
    price: 750,
    maxDefense: 4,
    maxLowRankDefense: 11,
    skillPoints: {
      hunger: 4,
      attack: 1,
      sleep: -1,
      lastingpwr: 2,
      perception: 1
    }
  }),
  deepFreeze<ArmArmor>({
    id: 6,
    type: 'arms',
    name: 'Alloy Vambraces',
    blade: true,
    gunner: false,
    defense: 8,
    fireRes: 1,
    waterRes: 1,
    iceRes: -1,
    thunderRes: -2,
    dragonRes: -1,
    slots: 1,
    rarity: 1,
    price: 1000,
    maxDefense: 8,
    maxLowRankDefense: 22,
    skillPoints: {
      expert: 2,
      sharpener: 2,
      speedsetup: 4,
      oxygen: -1
    }
  }),
  deepFreeze<ArmArmor>({
    id: 7,
    type: 'arms',
    name: 'Alloy Guards',
    blade: false,
    gunner: true,
    defense: 4,
    fireRes: 1,
    waterRes: 1,
    iceRes: -1,
    thunderRes: -2,
    dragonRes: -1,
    slots: 1,
    rarity: 1,
    price: 1000,
    maxDefense: 4,
    maxLowRankDefense: 11,
    skillPoints: {
      'normal_s+': 2,
      expert: 2,
      speedsetup: 3,
      oxygen: -2
    }
  }),
  deepFreeze<ArmArmor>({
    id: 8,
    type: 'arms',
    name: 'Jaggi Vambraces',
    blade: true,
    gunner: false,
    defense: 10,
    fireRes: -3,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: 1,
    slots: 2,
    rarity: 2,
    price: 1200,
    maxDefense: 10,
    maxLowRankDefense: 24,
    skillPoints: { attack: 2, stun: 3, gluttony: 1, cold_res: -1 }
  }),
  deepFreeze<ArmArmor>({
    id: 9,
    type: 'arms',
    name: 'Jaggi Guards',
    blade: false,
    gunner: true,
    defense: 5,
    fireRes: -3,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: 1,
    slots: 2,
    rarity: 2,
    price: 1200,
    maxDefense: 5,
    maxLowRankDefense: 12,
    skillPoints: { attack: 1, stun: 2, gluttony: 1, cold_res: -3 }
  }),
  deepFreeze<ArmArmor>({
    id: 10,
    type: 'arms',
    name: 'Rhenoplos Vambraces',
    blade: true,
    gunner: false,
    defense: 12,
    fireRes: 2,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: 2,
    slots: 2,
    rarity: 2,
    price: 1400,
    maxDefense: 12,
    maxLowRankDefense: 24,
    skillPoints: {
      wind_res: 1,
      eating: 2,
      'mud/snow': 3,
      thunderres: -1
    }
  }),
  deepFreeze<ArmArmor>({
    id: 11,
    type: 'arms',
    name: 'Rhenoplos Guards',
    blade: false,
    gunner: true,
    defense: 6,
    fireRes: 2,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: 2,
    slots: 2,
    rarity: 2,
    price: 1400,
    maxDefense: 6,
    maxLowRankDefense: 12,
    skillPoints: {
      recoil: 2,
      'crag_s+': 3,
      eating: 1,
      thunderres: -1
    }
  }),
  deepFreeze<ArmArmor>({
    id: 12,
    type: 'arms',
    name: 'Qurupeco Vambraces',
    blade: true,
    gunner: false,
    defense: 12,
    fireRes: 2,
    waterRes: -2,
    iceRes: -3,
    thunderRes: 0,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    price: 1700,
    maxDefense: 12,
    maxLowRankDefense: 24,
    skillPoints: {
      attack: 2,
      defense: 3,
      rec_level: 1,
      evasion: 2,
      ice_res: -1
    }
  }),
  deepFreeze<ArmArmor>({
    id: 13,
    type: 'arms',
    name: 'Qurupeco Guards',
    blade: false,
    gunner: true,
    defense: 6,
    fireRes: 2,
    waterRes: -2,
    iceRes: -3,
    thunderRes: 0,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    price: 1700,
    maxDefense: 6,
    maxLowRankDefense: 12,
    skillPoints: {
      attack: 2,
      defense: 1,
      rec_level: 2,
      evasion: 3,
      ice_res: -1
    }
  }),
  deepFreeze<ArmArmor>({
    id: 14,
    type: 'arms',
    name: 'Ludroth Vambraces',
    blade: true,
    gunner: false,
    defense: 13,
    fireRes: -3,
    waterRes: 2,
    iceRes: 0,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    price: 2200,
    maxDefense: 13,
    maxLowRankDefense: 25,
    skillPoints: {
      protection: 4,
      constitutn: 2,
      fire_res: -1,
      currentres: 2
    }
  }),
  deepFreeze<ArmArmor>({
    id: 15,
    type: 'arms',
    name: 'Ludroth Guards',
    blade: false,
    gunner: true,
    defense: 7,
    fireRes: -3,
    waterRes: 2,
    iceRes: 0,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    price: 2200,
    maxDefense: 7,
    maxLowRankDefense: 13,
    skillPoints: {
      'pellet_s+': 3,
      protection: 1,
      constitutn: 3,
      fire_res: -2
    }
  }),
  deepFreeze<ArmArmor>({
    id: 16,
    type: 'arms',
    name: 'Steel Vambraces',
    blade: true,
    gunner: false,
    defense: 12,
    fireRes: -1,
    waterRes: 1,
    iceRes: 1,
    thunderRes: -1,
    dragonRes: 0,
    slots: 0,
    rarity: 2,
    price: 2000,
    maxDefense: 12,
    maxLowRankDefense: 24,
    skillPoints: { sharpener: 4, guard: 3, swimming: -4 }
  }),
  deepFreeze<ArmArmor>({
    id: 17,
    type: 'arms',
    name: 'Baggi Vambraces',
    blade: true,
    gunner: false,
    defense: 13,
    fireRes: -3,
    waterRes: -1,
    iceRes: 3,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    price: 2400,
    maxDefense: 13,
    maxLowRankDefense: 13,
    skillPoints: {
      tranquilzr: 3,
      fastcharge: 2,
      stun: -1,
      ice_res: 3
    }
  }),
  deepFreeze<ArmArmor>({
    id: 18,
    type: 'arms',
    name: 'Baggi Guards',
    blade: false,
    gunner: true,
    defense: 7,
    fireRes: -2,
    waterRes: -1,
    iceRes: 3,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    price: 2400,
    maxDefense: 7,
    maxLowRankDefense: 13,
    skillPoints: {
      pellets_up: 2,
      tranquilzr: 4,
      stun: -1,
      ice_res: 2
    }
  }),
  deepFreeze<ArmArmor>({
    id: 19,
    type: 'arms',
    name: 'Barroth Vambraces',
    blade: true,
    gunner: false,
    defense: 15,
    fireRes: -4,
    waterRes: 4,
    iceRes: -3,
    thunderRes: 3,
    dragonRes: 0,
    slots: 1,
    rarity: 2,
    price: 3200,
    maxDefense: 15,
    maxLowRankDefense: 27,
    skillPoints: { stamina: 1, expert: -1, attack: 4, potential: 3 }
  }),
  deepFreeze<ArmArmor>({
    id: 20,
    type: 'arms',
    name: 'Barroth Guards',
    blade: false,
    gunner: true,
    defense: 8,
    fireRes: -4,
    waterRes: 4,
    iceRes: -3,
    thunderRes: 3,
    dragonRes: 0,
    slots: 1,
    rarity: 2,
    price: 3200,
    maxDefense: 8,
    maxLowRankDefense: 14,
    skillPoints: { stamina: 1, expert: -1, attack: 4, potential: 3 }
  }),
  deepFreeze<ArmArmor>({
    id: 21,
    type: 'arms',
    name: 'Gobul Vambraces',
    blade: true,
    gunner: false,
    defense: 16,
    fireRes: -2,
    waterRes: 3,
    iceRes: 0,
    thunderRes: -3,
    dragonRes: 2,
    slots: 2,
    rarity: 2,
    price: 3600,
    maxDefense: 16,
    maxLowRankDefense: 28,
    skillPoints: { rec_speed: -1, eating: 2, stun: 1, water_res: 3 }
  }),
  deepFreeze<ArmArmor>({
    id: 22,
    type: 'arms',
    name: 'Gobul Guards',
    blade: false,
    gunner: true,
    defense: 8,
    fireRes: -2,
    waterRes: 3,
    iceRes: 0,
    thunderRes: -3,
    dragonRes: 2,
    slots: 2,
    rarity: 2,
    price: 3600,
    maxDefense: 8,
    maxLowRankDefense: 14,
    skillPoints: { rec_speed: -1, eating: 2, stun: 1, water_res: 3 }
  }),
  deepFreeze<ArmArmor>({
    id: 23,
    type: 'arms',
    name: "Ranger's Gauntlets",
    blade: true,
    gunner: false,
    defense: 15,
    fireRes: 0,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 0,
    rarity: 3,
    price: 10000,
    maxDefense: 15,
    maxLowRankDefense: 27,
    skillPoints: {
      fate: -4,
      carving: 5,
      'wide-range': 2,
      spd_gather: 1
    }
  }),
  deepFreeze<ArmArmor>({
    id: 24,
    type: 'arms',
    name: "Archer's Gauntlets",
    blade: false,
    gunner: true,
    defense: 8,
    fireRes: 0,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 0,
    rarity: 3,
    price: 10000,
    maxDefense: 8,
    maxLowRankDefense: 14,
    skillPoints: {
      fate: -5,
      carving: 4,
      'wide-range': 2,
      spd_gather: 1
    }
  }),
  deepFreeze<ArmArmor>({
    id: 25,
    type: 'arms',
    name: 'Guild Bard Braces',
    blade: true,
    gunner: false,
    defense: 15,
    fireRes: 0,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 0,
    rarity: 3,
    price: 10000,
    maxDefense: 15,
    maxLowRankDefense: 13,
    skillPoints: { fate: 2, psychic: 5, evasion: 3, sense: -1 }
  }),
  deepFreeze<ArmArmor>({
    id: 26,
    type: 'arms',
    name: 'Guild Bard Sleeves',
    blade: false,
    gunner: true,
    defense: 8,
    fireRes: 0,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 0,
    rarity: 3,
    price: 10000,
    maxDefense: 8,
    maxLowRankDefense: 14,
    skillPoints: { fate: 1, psychic: 4, evasion: 2, sense: -4 }
  }),
  deepFreeze<ArmArmor>({
    id: 27,
    type: 'arms',
    name: 'Rathian Vambraces',
    blade: true,
    gunner: false,
    defense: 16,
    fireRes: 3,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 2,
    rarity: 2,
    price: 3600,
    maxDefense: 16,
    maxLowRankDefense: 28,
    skillPoints: {
      hearing: 1,
      health: 2,
      protection: -1,
      fire_res: 3
    }
  }),
  deepFreeze<ArmArmor>({
    id: 28,
    type: 'arms',
    name: 'Rathian Guards',
    blade: false,
    gunner: true,
    defense: 8,
    fireRes: 3,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 2,
    rarity: 2,
    price: 3600,
    maxDefense: 8,
    maxLowRankDefense: 14,
    skillPoints: {
      hearing: 1,
      health: 2,
      protection: -3,
      fire_res: 1
    }
  }),
  deepFreeze<ArmArmor>({
    id: 29,
    type: 'arms',
    name: 'Gigginox Vambraces',
    blade: true,
    gunner: false,
    defense: 18,
    fireRes: -4,
    waterRes: 0,
    iceRes: 2,
    thunderRes: 2,
    dragonRes: -1,
    slots: 2,
    rarity: 2,
    price: 4100,
    maxDefense: 18,
    maxLowRankDefense: 30,
    skillPoints: { status: 1, poison: 1, health: -2, constitutn: 3 }
  }),
  deepFreeze<ArmArmor>({
    id: 30,
    type: 'arms',
    name: 'Gigginox Guards',
    blade: false,
    gunner: true,
    defense: 9,
    fireRes: -4,
    waterRes: 0,
    iceRes: 2,
    thunderRes: 2,
    dragonRes: -1,
    slots: 2,
    rarity: 2,
    price: 4100,
    maxDefense: 9,
    maxLowRankDefense: 15,
    skillPoints: { status: 2, poison: 1, health: -2, constitutn: 2 }
  }),
  deepFreeze<ArmArmor>({
    id: 31,
    type: 'arms',
    name: 'Ingot Vambraces',
    blade: true,
    gunner: false,
    defense: 18,
    fireRes: -2,
    waterRes: -1,
    iceRes: 1,
    thunderRes: 3,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    price: 5000,
    maxDefense: 18,
    maxLowRankDefense: 28,
    skillPoints: {
      sharpener: -1,
      guard_up: 1,
      wind_res: 5,
      thunderres: 2
    }
  }),
  deepFreeze<ArmArmor>({
    id: 32,
    type: 'arms',
    name: 'Ingot Guards',
    blade: false,
    gunner: true,
    defense: 9,
    fireRes: -2,
    waterRes: -1,
    iceRes: 1,
    thunderRes: 3,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    price: 5000,
    maxDefense: 9,
    maxLowRankDefense: 14,
    skillPoints: {
      recoil: 5,
      guard_up: 1,
      reload_spd: -1,
      thunderres: 2
    }
  }),
  deepFreeze<ArmArmor>({
    id: 33,
    type: 'arms',
    name: 'Lagiacrus Vambraces',
    blade: true,
    gunner: false,
    defense: 20,
    fireRes: -3,
    waterRes: 2,
    iceRes: -1,
    thunderRes: 4,
    dragonRes: -2,
    slots: 2,
    rarity: 3,
    price: 5600,
    maxDefense: 20,
    maxLowRankDefense: 30,
    skillPoints: {
      sharpness: 3,
      status: -1,
      elemental: 2,
      swimming: 2
    }
  }),
  deepFreeze<ArmArmor>({
    id: 34,
    type: 'arms',
    name: 'Lagiacrus Guards',
    blade: false,
    gunner: true,
    defense: 10,
    fireRes: -3,
    waterRes: 2,
    iceRes: -1,
    thunderRes: 4,
    dragonRes: -2,
    slots: 2,
    rarity: 3,
    price: 5600,
    maxDefense: 10,
    maxLowRankDefense: 15,
    skillPoints: {
      normals_up: 3,
      status: -1,
      elemental: 2,
      swimming: 2
    }
  }),
  deepFreeze<ArmArmor>({
    id: 35,
    type: 'arms',
    name: 'Rathalos Vambraces',
    blade: true,
    gunner: false,
    defense: 20,
    fireRes: 3,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 0,
    rarity: 3,
    price: 5600,
    maxDefense: 20,
    maxLowRankDefense: 30,
    skillPoints: { expert: 2, attack: 5, defense: -1, heat_res: 3 }
  }),
  deepFreeze<ArmArmor>({
    id: 36,
    type: 'arms',
    name: 'Rathalos Guards',
    blade: false,
    gunner: true,
    defense: 10,
    fireRes: 3,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 0,
    rarity: 3,
    price: 5600,
    maxDefense: 10,
    maxLowRankDefense: 15,
    skillPoints: { expert: 2, attack: 5, defense: -3, heat_res: 1 }
  }),
  deepFreeze<ArmArmor>({
    id: 37,
    type: 'arms',
    name: 'Barioth Vambraces',
    blade: true,
    gunner: false,
    defense: 20,
    fireRes: -4,
    waterRes: 2,
    iceRes: 4,
    thunderRes: -3,
    dragonRes: 0,
    slots: 0,
    rarity: 3,
    price: 5600,
    maxDefense: 20,
    maxLowRankDefense: 30,
    skillPoints: {
      stamina: 2,
      evasion: 5,
      heat_res: -2,
      cold_res: 2
    }
  }),
  deepFreeze<ArmArmor>({
    id: 38,
    type: 'arms',
    name: 'Barioth Guards',
    blade: false,
    gunner: true,
    defense: 10,
    fireRes: -4,
    waterRes: 2,
    iceRes: 4,
    thunderRes: -3,
    dragonRes: 0,
    slots: 0,
    rarity: 3,
    price: 5600,
    maxDefense: 10,
    maxLowRankDefense: 15,
    skillPoints: {
      stamina: 3,
      evasion: 5,
      heat_res: -2,
      cold_res: 1
    }
  }),
  deepFreeze<ArmArmor>({
    id: 39,
    type: 'arms',
    name: 'Diablos Vambraces',
    blade: true,
    gunner: false,
    defense: 22,
    fireRes: 2,
    waterRes: -1,
    iceRes: -3,
    thunderRes: -1,
    dragonRes: -1,
    slots: 0,
    rarity: 3,
    price: 6300,
    maxDefense: 22,
    maxLowRankDefense: 30,
    skillPoints: { elemental: -3, tremor_res: 3, crit_draw: 5 }
  }),
  deepFreeze<ArmArmor>({
    id: 40,
    type: 'arms',
    name: 'Diablos Guards',
    blade: false,
    gunner: true,
    defense: 11,
    fireRes: 2,
    waterRes: -1,
    iceRes: -3,
    thunderRes: -1,
    dragonRes: -1,
    slots: 0,
    rarity: 3,
    price: 6300,
    maxDefense: 11,
    maxLowRankDefense: 15,
    skillPoints: { pierces_up: 3, 'pierce_s+': 5, elemental: -3 }
  }),
  deepFreeze<ArmArmor>({
    id: 41,
    type: 'arms',
    name: 'Uragaan Vambraces',
    blade: true,
    gunner: false,
    defense: 22,
    fireRes: 3,
    waterRes: -4,
    iceRes: -1,
    thunderRes: 1,
    dragonRes: 2,
    slots: 1,
    rarity: 3,
    price: 6300,
    maxDefense: 22,
    maxLowRankDefense: 30,
    skillPoints: {
      punishdraw: 1,
      bomb_boost: 2,
      defense: 4,
      eating: -2
    }
  }),
  deepFreeze<ArmArmor>({
    id: 42,
    type: 'arms',
    name: 'Uragaan Guards',
    blade: false,
    gunner: true,
    defense: 11,
    fireRes: 3,
    waterRes: -4,
    iceRes: -1,
    thunderRes: 1,
    dragonRes: -2,
    slots: 1,
    rarity: 3,
    price: 6300,
    maxDefense: 11,
    maxLowRankDefense: 15,
    skillPoints: {
      recoil: 2,
      bomb_boost: 2,
      defense: 2,
      eating: -3
    }
  }),
  deepFreeze<ArmArmor>({
    id: 43,
    type: 'arms',
    name: 'Agnaktor Vambraces',
    blade: true,
    gunner: false,
    defense: 22,
    fireRes: 4,
    waterRes: -4,
    iceRes: -2,
    thunderRes: 1,
    dragonRes: 0,
    slots: 1,
    rarity: 3,
    price: 7200,
    maxDefense: 22,
    maxLowRankDefense: 30,
    skillPoints: {
      stamina: -1,
      guard: 2,
      guard_up: 3,
      flame_aura: 3
    }
  }),
  deepFreeze<ArmArmor>({
    id: 44,
    type: 'arms',
    name: 'Agnaktor Guards',
    blade: false,
    gunner: true,
    defense: 11,
    fireRes: 4,
    waterRes: -4,
    iceRes: -2,
    thunderRes: 1,
    dragonRes: 0,
    slots: 1,
    rarity: 3,
    price: 7200,
    maxDefense: 11,
    maxLowRankDefense: 15,
    skillPoints: {
      stamina: -3,
      guard_up: 2,
      reload_spd: 2,
      flame_aura: 2
    }
  }),
  deepFreeze<ArmArmor>({
    id: 45,
    type: 'arms',
    name: 'Helios Vambraces',
    blade: true,
    gunner: false,
    defense: 24,
    fireRes: 0,
    waterRes: 4,
    iceRes: 3,
    thunderRes: -3,
    dragonRes: -4,
    slots: 1,
    rarity: 3,
    price: 11000,
    maxDefense: 24,
    maxLowRankDefense: 32,
    skillPoints: {
      sharpness: -3,
      handicraft: 3,
      hearing: 2,
      protection: -1
    }
  }),
  deepFreeze<ArmArmor>({
    id: 46,
    type: 'arms',
    name: 'Helios Guards',
    blade: false,
    gunner: true,
    defense: 12,
    fireRes: 0,
    waterRes: 4,
    iceRes: 3,
    thunderRes: -3,
    dragonRes: -4,
    slots: 1,
    rarity: 3,
    price: 11000,
    maxDefense: 12,
    maxLowRankDefense: 16,
    skillPoints: {
      recoil: -3,
      hearing: 2,
      loading: 3,
      protection: -1
    }
  }),
  deepFreeze<ArmArmor>({
    id: 47,
    type: 'arms',
    name: 'Yamato Kote',
    blade: true,
    gunner: false,
    defense: 24,
    fireRes: 3,
    waterRes: 0,
    iceRes: -3,
    thunderRes: 0,
    dragonRes: -3,
    slots: 2,
    rarity: 3,
    price: 12000,
    maxDefense: 24,
    maxLowRankDefense: 32,
    skillPoints: {
      sharpness: 1,
      fastcharge: 3,
      rec_speed: 1,
      combo_rate: -2
    }
  }),
  deepFreeze<ArmArmor>({
    id: 48,
    type: 'arms',
    name: 'Mutsu Kote',
    blade: false,
    gunner: true,
    defense: 12,
    fireRes: 3,
    waterRes: 0,
    iceRes: -3,
    thunderRes: 0,
    dragonRes: -3,
    slots: 2,
    rarity: 3,
    price: 12000,
    maxDefense: 12,
    maxLowRankDefense: 16,
    skillPoints: {
      recoil: 1,
      rec_speed: 1,
      'clust_s+': 3,
      combo_rate: -2
    }
  }),
  deepFreeze<ArmArmor>({
    id: 49,
    type: 'arms',
    name: 'Leather Vambraces+',
    blade: true,
    gunner: false,
    defense: 26,
    fireRes: -2,
    waterRes: 0,
    iceRes: -2,
    thunderRes: 3,
    dragonRes: 2,
    slots: 2,
    rarity: 4,
    price: 4600,
    maxDefense: 26,
    skillPoints: { gathering: 2, spd_gather: 3, whim: 3 }
  }),
  deepFreeze<ArmArmor>({
    id: 50,
    type: 'arms',
    name: 'Leather Guards+',
    blade: false,
    gunner: true,
    defense: 15,
    fireRes: -2,
    waterRes: 0,
    iceRes: -2,
    thunderRes: 3,
    dragonRes: 2,
    slots: 2,
    rarity: 4,
    price: 4600,
    maxDefense: 15,
    skillPoints: { gathering: 4, spd_gather: 2, whim: 2 }
  }),
  deepFreeze<ArmArmor>({
    id: 51,
    type: 'arms',
    name: 'Chainmail Vambraces+',
    blade: true,
    gunner: false,
    defense: 30,
    fireRes: -1,
    waterRes: -2,
    iceRes: 4,
    thunderRes: -1,
    dragonRes: 1,
    slots: 2,
    rarity: 4,
    price: 5400,
    maxDefense: 30,
    skillPoints: { health: 3, combo_rate: 4, combo_plus: 1 }
  }),
  deepFreeze<ArmArmor>({
    id: 52,
    type: 'arms',
    name: 'Chainmail Guards+',
    blade: false,
    gunner: true,
    defense: 18,
    fireRes: -1,
    waterRes: -2,
    iceRes: 4,
    thunderRes: -1,
    dragonRes: 1,
    slots: 2,
    rarity: 4,
    price: 5400,
    maxDefense: 18,
    skillPoints: { health: 5, combo_rate: 2, combo_plus: 1 }
  }),
  deepFreeze<ArmArmor>({
    id: 53,
    type: 'arms',
    name: "Hunter's Vambraces+",
    blade: true,
    gunner: false,
    defense: 30,
    fireRes: 0,
    waterRes: -2,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 2,
    rarity: 4,
    price: 5400,
    maxDefense: 30,
    skillPoints: {
      expert: 2,
      psychic: 2,
      evasion: 3,
      water_res: -1,
      map: 1
    }
  }),
  deepFreeze<ArmArmor>({
    id: 54,
    type: 'arms',
    name: "Hunter's Guards+",
    blade: false,
    gunner: true,
    defense: 18,
    fireRes: 0,
    waterRes: -2,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 2,
    rarity: 4,
    price: 5400,
    maxDefense: 18,
    skillPoints: {
      expert: 2,
      psychic: 1,
      evasion: 2,
      water_res: -1,
      map: 3
    }
  }),
  deepFreeze<ArmArmor>({
    id: 55,
    type: 'arms',
    name: 'Bone Vambraces+',
    blade: true,
    gunner: false,
    defense: 34,
    fireRes: 3,
    waterRes: -2,
    iceRes: -1,
    thunderRes: 2,
    dragonRes: 3,
    slots: 2,
    rarity: 4,
    price: 6400,
    maxDefense: 34,
    skillPoints: { stamina: 2, hunger: 5, sleep: -1, perception: 1 }
  }),
  deepFreeze<ArmArmor>({
    id: 56,
    type: 'arms',
    name: 'Bone Guards+',
    blade: false,
    gunner: true,
    defense: 20,
    fireRes: 3,
    waterRes: -2,
    iceRes: -1,
    thunderRes: 2,
    dragonRes: 3,
    slots: 2,
    rarity: 4,
    price: 6400,
    maxDefense: 20,
    skillPoints: { stamina: 3, hunger: 4, sleep: -1, perception: 1 }
  }),
  deepFreeze<ArmArmor>({
    id: 57,
    type: 'arms',
    name: 'Alloy Vambraces+',
    blade: true,
    gunner: false,
    defense: 34,
    fireRes: 1,
    waterRes: 2,
    iceRes: -1,
    thunderRes: -2,
    dragonRes: -1,
    slots: 2,
    rarity: 4,
    price: 7100,
    maxDefense: 34,
    skillPoints: {
      expert: 4,
      sharpener: 1,
      speedsetup: 3,
      oxygen: -1
    }
  }),
  deepFreeze<ArmArmor>({
    id: 58,
    type: 'arms',
    name: 'Alloy Guards+',
    blade: false,
    gunner: true,
    defense: 20,
    fireRes: 1,
    waterRes: 2,
    iceRes: -1,
    thunderRes: -2,
    dragonRes: -1,
    slots: 2,
    rarity: 4,
    price: 7100,
    maxDefense: 20,
    skillPoints: {
      'normal_s+': 1,
      expert: 4,
      speedsetup: 3,
      oxygen: -1
    }
  }),
  deepFreeze<ArmArmor>({
    id: 59,
    type: 'arms',
    name: 'Jaggi Vambraces+',
    blade: true,
    gunner: false,
    defense: 38,
    fireRes: -3,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: 2,
    slots: 1,
    rarity: 5,
    price: 8000,
    maxDefense: 38,
    skillPoints: { attack: 3, stun: 4, gluttony: 3, cold_res: -1 }
  }),
  deepFreeze<ArmArmor>({
    id: 60,
    type: 'arms',
    name: 'Jaggi Guards+',
    blade: false,
    gunner: true,
    defense: 22,
    fireRes: -3,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: 2,
    slots: 1,
    rarity: 5,
    price: 8000,
    maxDefense: 22,
    skillPoints: { attack: 1, stun: 5, gluttony: 3, cold_res: -2 }
  }),
  deepFreeze<ArmArmor>({
    id: 61,
    type: 'arms',
    name: 'Rhenoplos Vambraces+',
    blade: true,
    gunner: false,
    defense: 38,
    fireRes: 3,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -2,
    dragonRes: 2,
    slots: 2,
    rarity: 5,
    price: 8500,
    maxDefense: 38,
    skillPoints: {
      expert: 1,
      wind_res: 1,
      eating: 5,
      'mud/snow': 1,
      thunderres: -1
    }
  }),
  deepFreeze<ArmArmor>({
    id: 62,
    type: 'arms',
    name: 'Rhenoplos Guards+',
    blade: false,
    gunner: true,
    defense: 22,
    fireRes: 3,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -2,
    dragonRes: 2,
    slots: 2,
    rarity: 5,
    price: 8500,
    maxDefense: 22,
    skillPoints: {
      recoil: 2,
      expert: 1,
      'crag_s+': 1,
      eating: 3,
      thunderres: -2
    }
  }),
  deepFreeze<ArmArmor>({
    id: 63,
    type: 'arms',
    name: 'Qurupeco Vambraces+',
    blade: true,
    gunner: false,
    defense: 42,
    fireRes: 4,
    waterRes: -3,
    iceRes: -4,
    thunderRes: 0,
    dragonRes: 1,
    slots: 0,
    rarity: 5,
    price: 10000,
    maxDefense: 42,
    skillPoints: {
      defense: 3,
      'wide-range': 6,
      rec_level: 3,
      ice_res: -1
    }
  }),
  deepFreeze<ArmArmor>({
    id: 64,
    type: 'arms',
    name: 'Qurupeco Guards+',
    blade: false,
    gunner: true,
    defense: 25,
    fireRes: 4,
    waterRes: -3,
    iceRes: -4,
    thunderRes: 0,
    dragonRes: 1,
    slots: 0,
    rarity: 5,
    price: 10000,
    maxDefense: 25,
    skillPoints: {
      defense: 4,
      'wide-range': 6,
      rec_level: 2,
      ice_res: -1
    }
  }),
  deepFreeze<ArmArmor>({
    id: 65,
    type: 'arms',
    name: 'Ludroth Vambraces+',
    blade: true,
    gunner: false,
    defense: 44,
    fireRes: -4,
    waterRes: 4,
    iceRes: 0,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 5,
    price: 11800,
    maxDefense: 44,
    skillPoints: {
      expert: 2,
      hunger: -1,
      protection: 4,
      constitutn: 2,
      currentres: 2
    }
  }),
  deepFreeze<ArmArmor>({
    id: 66,
    type: 'arms',
    name: 'Ludroth Guards+',
    blade: false,
    gunner: true,
    defense: 26,
    fireRes: -4,
    waterRes: 4,
    iceRes: 0,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 5,
    price: 11800,
    maxDefense: 26,
    skillPoints: {
      expert: 2,
      'pellet_s+': 1,
      hunger: -1,
      protection: 4,
      constitutn: 3
    }
  }),
  deepFreeze<ArmArmor>({
    id: 67,
    type: 'arms',
    name: 'Steel Vambraces+',
    blade: true,
    gunner: false,
    defense: 42,
    fireRes: -1,
    waterRes: 1,
    iceRes: 1,
    thunderRes: -1,
    dragonRes: 0,
    slots: 1,
    rarity: 5,
    price: 11000,
    maxDefense: 42,
    skillPoints: { sharpener: 4, guard: 5, swimming: -2 }
  }),
  deepFreeze<ArmArmor>({
    id: 68,
    type: 'arms',
    name: 'Baggi Vambraces+',
    blade: true,
    gunner: false,
    defense: 44,
    fireRes: -4,
    waterRes: -1,
    iceRes: 4,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 5,
    price: 12300,
    maxDefense: 44,
    skillPoints: {
      tranquilzr: 2,
      fastcharge: 4,
      stun: -1,
      ice_res: 4
    }
  }),
  deepFreeze<ArmArmor>({
    id: 69,
    type: 'arms',
    name: 'Baggi Guards+',
    blade: false,
    gunner: true,
    defense: 26,
    fireRes: -4,
    waterRes: -1,
    iceRes: 4,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 5,
    price: 12300,
    maxDefense: 26,
    skillPoints: {
      pellets_up: 3,
      tranquilzr: 2,
      stun: -1,
      ice_res: 5
    }
  }),
  deepFreeze<ArmArmor>({
    id: 70,
    type: 'arms',
    name: 'Barroth Vambraces+',
    blade: true,
    gunner: false,
    defense: 48,
    fireRes: -5,
    waterRes: 5,
    iceRes: -4,
    thunderRes: 4,
    dragonRes: 0,
    slots: 3,
    rarity: 5,
    price: 13800,
    maxDefense: 48,
    skillPoints: { stamina: 1, expert: -3, attack: 1, potential: 2 }
  }),
  deepFreeze<ArmArmor>({
    id: 71,
    type: 'arms',
    name: 'Barroth Guards+',
    blade: false,
    gunner: true,
    defense: 28,
    fireRes: -5,
    waterRes: 5,
    iceRes: -4,
    thunderRes: 4,
    dragonRes: 0,
    slots: 3,
    rarity: 5,
    price: 13800,
    maxDefense: 28,
    skillPoints: { stamina: 1, expert: -3, attack: 1, potential: 2 }
  }),
  deepFreeze<ArmArmor>({
    id: 72,
    type: 'arms',
    name: 'Gobul Vambraces+',
    blade: true,
    gunner: false,
    defense: 50,
    fireRes: -2,
    waterRes: 4,
    iceRes: 0,
    thunderRes: -4,
    dragonRes: 2,
    slots: 1,
    rarity: 5,
    price: 14800,
    maxDefense: 50,
    skillPoints: { rec_speed: -1, expert: 2, eating: 4, stun: 4 }
  }),
  deepFreeze<ArmArmor>({
    id: 73,
    type: 'arms',
    name: 'Gobul Guards+',
    blade: false,
    gunner: true,
    defense: 30,
    fireRes: -2,
    waterRes: 4,
    iceRes: 0,
    thunderRes: -4,
    dragonRes: 2,
    slots: 1,
    rarity: 5,
    price: 14800,
    maxDefense: 30,
    skillPoints: { rec_speed: -1, expert: 2, eating: 4, stun: 4 }
  }),
  deepFreeze<ArmArmor>({
    id: 74,
    type: 'arms',
    name: 'Guild Bard Braces+',
    blade: true,
    gunner: false,
    defense: 36,
    fireRes: 0,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 1,
    rarity: 6,
    price: 25000,
    maxDefense: 36,
    skillPoints: {
      fate: 3,
      carving: 2,
      tranquilzr: 1,
      protection: -5
    }
  }),
  deepFreeze<ArmArmor>({
    id: 75,
    type: 'arms',
    name: 'Guild Bard Sleeves+',
    blade: false,
    gunner: true,
    defense: 22,
    fireRes: 0,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 1,
    rarity: 6,
    price: 25000,
    maxDefense: 22,
    skillPoints: {
      fate: 2,
      carving: 2,
      tranquilzr: 2,
      protection: -5
    }
  }),
  deepFreeze<ArmArmor>({
    id: 76,
    type: 'arms',
    name: 'Rathian Vambraces+',
    blade: true,
    gunner: false,
    defense: 50,
    fireRes: 4,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 1,
    rarity: 5,
    price: 14800,
    maxDefense: 50,
    skillPoints: {
      hearing: 1,
      health: 4,
      protection: -2,
      fire_res: 4
    }
  }),
  deepFreeze<ArmArmor>({
    id: 77,
    type: 'arms',
    name: 'Rathian Guards+',
    blade: false,
    gunner: true,
    defense: 30,
    fireRes: 4,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 1,
    rarity: 5,
    price: 14800,
    maxDefense: 30,
    skillPoints: {
      hearing: 2,
      health: 3,
      protection: -3,
      fire_res: 3
    }
  }),
  deepFreeze<ArmArmor>({
    id: 78,
    type: 'arms',
    name: 'Gigginox Vambraces+',
    blade: true,
    gunner: false,
    defense: 54,
    fireRes: -4,
    waterRes: -1,
    iceRes: 2,
    thunderRes: 3,
    dragonRes: 0,
    slots: 3,
    rarity: 5,
    price: 15800,
    maxDefense: 54,
    skillPoints: { status: 1, poison: 1, health: -3, constitutn: 2 }
  }),
  deepFreeze<ArmArmor>({
    id: 79,
    type: 'arms',
    name: 'Gigginox Guards+',
    blade: false,
    gunner: true,
    defense: 32,
    fireRes: -4,
    waterRes: -1,
    iceRes: 2,
    thunderRes: 3,
    dragonRes: 0,
    slots: 3,
    rarity: 5,
    price: 15800,
    maxDefense: 32,
    skillPoints: { status: 1, poison: 2, health: -3, constitutn: 1 }
  }),
  deepFreeze<ArmArmor>({
    id: 80,
    type: 'arms',
    name: 'Ingot Vambraces+',
    blade: true,
    gunner: false,
    defense: 54,
    fireRes: -2,
    waterRes: -1,
    iceRes: 1,
    thunderRes: 3,
    dragonRes: 2,
    slots: 3,
    rarity: 5,
    price: 17500,
    maxDefense: 54,
    skillPoints: {
      sharpener: -3,
      guard_up: 1,
      wind_res: 2,
      thunderres: 1
    }
  }),
  deepFreeze<ArmArmor>({
    id: 81,
    type: 'arms',
    name: 'Ingot Guards+',
    blade: false,
    gunner: true,
    defense: 32,
    fireRes: -2,
    waterRes: -1,
    iceRes: 1,
    thunderRes: 3,
    dragonRes: 2,
    slots: 3,
    rarity: 5,
    price: 17500,
    maxDefense: 32,
    skillPoints: {
      recoil: 2,
      guard_up: 1,
      reload_spd: -3,
      thunderres: 1
    }
  }),
  deepFreeze<ArmArmor>({
    id: 82,
    type: 'arms',
    name: 'Dober Vambraces',
    blade: true,
    gunner: false,
    defense: 58,
    fireRes: -2,
    waterRes: -2,
    iceRes: 1,
    thunderRes: 1,
    dragonRes: 5,
    slots: 1,
    rarity: 6,
    price: 19000,
    maxDefense: 58,
    skillPoints: {
      stamina: 3,
      potential: -1,
      crit_draw: 2,
      dragon_res: 5
    }
  }),
  deepFreeze<ArmArmor>({
    id: 83,
    type: 'arms',
    name: 'Dober Guards',
    blade: false,
    gunner: true,
    defense: 34,
    fireRes: -2,
    waterRes: -2,
    iceRes: 1,
    thunderRes: 1,
    dragonRes: 5,
    slots: 1,
    rarity: 6,
    price: 19000,
    maxDefense: 34,
    skillPoints: {
      pellets_up: 3,
      'pellet_s+': 4,
      potential: -1,
      dragon_res: 3
    }
  }),
  deepFreeze<ArmArmor>({
    id: 84,
    type: 'arms',
    name: 'Lagiacrus Vambraces+',
    blade: true,
    gunner: false,
    defense: 58,
    fireRes: -4,
    waterRes: 2,
    iceRes: -1,
    thunderRes: 5,
    dragonRes: -2,
    slots: 1,
    rarity: 6,
    price: 18000,
    maxDefense: 58,
    skillPoints: {
      status: -2,
      elemental: 2,
      freeelemnt: 5,
      swimming: 2
    }
  }),
  deepFreeze<ArmArmor>({
    id: 85,
    type: 'arms',
    name: 'Lagiacrus Guards+',
    blade: false,
    gunner: true,
    defense: 34,
    fireRes: -4,
    waterRes: 2,
    iceRes: -1,
    thunderRes: 5,
    dragonRes: -2,
    slots: 1,
    rarity: 6,
    price: 18000,
    maxDefense: 34,
    skillPoints: {
      status: -3,
      elemental: 2,
      rapid_fire: 2,
      swimming: 4
    }
  }),
  deepFreeze<ArmArmor>({
    id: 86,
    type: 'arms',
    name: 'Rathalos Vambraces+',
    blade: true,
    gunner: false,
    defense: 58,
    fireRes: 4,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 1,
    rarity: 6,
    price: 18000,
    maxDefense: 58,
    skillPoints: { fencing: 1, expert: 3, defense: -2, heat_res: 5 }
  }),
  deepFreeze<ArmArmor>({
    id: 87,
    type: 'arms',
    name: 'Rathalos Guards+',
    blade: false,
    gunner: true,
    defense: 34,
    fireRes: 4,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 1,
    rarity: 6,
    price: 18000,
    maxDefense: 34,
    skillPoints: {
      normals_up: 3,
      expert: 4,
      defense: -1,
      heat_res: 3
    }
  }),
  deepFreeze<ArmArmor>({
    id: 88,
    type: 'arms',
    name: 'Barioth Vambraces+',
    blade: true,
    gunner: false,
    defense: 58,
    fireRes: -4,
    waterRes: 2,
    iceRes: 5,
    thunderRes: -3,
    dragonRes: 0,
    slots: 1,
    rarity: 6,
    price: 18000,
    maxDefense: 58,
    skillPoints: {
      evade_dist: 4,
      evasion: 4,
      heat_res: -1,
      cold_res: 2
    }
  }),
  deepFreeze<ArmArmor>({
    id: 89,
    type: 'arms',
    name: 'Barioth Guards+',
    blade: false,
    gunner: true,
    defense: 34,
    fireRes: -4,
    waterRes: 2,
    iceRes: 5,
    thunderRes: -3,
    dragonRes: 0,
    slots: 1,
    rarity: 6,
    price: 18000,
    maxDefense: 34,
    skillPoints: {
      evade_dist: 4,
      evasion: 4,
      heat_res: -2,
      cold_res: 1
    }
  }),
  deepFreeze<ArmArmor>({
    id: 90,
    type: 'arms',
    name: 'Diablos Vambraces+',
    blade: true,
    gunner: false,
    defense: 62,
    fireRes: 3,
    waterRes: -1,
    iceRes: -4,
    thunderRes: -1,
    dragonRes: -1,
    slots: 3,
    rarity: 6,
    price: 18800,
    maxDefense: 62,
    skillPoints: { elemental: -4, tremor_res: 1, crit_draw: 2 }
  }),
  deepFreeze<ArmArmor>({
    id: 91,
    type: 'arms',
    name: 'Diablos Guards+',
    blade: false,
    gunner: true,
    defense: 37,
    fireRes: 3,
    waterRes: -1,
    iceRes: -4,
    thunderRes: -1,
    dragonRes: -1,
    slots: 3,
    rarity: 6,
    price: 18800,
    maxDefense: 37,
    skillPoints: { pierces_up: 1, 'pierce_s+': 2, elemental: -4 }
  }),
  deepFreeze<ArmArmor>({
    id: 92,
    type: 'arms',
    name: 'Uragaan Vambraces+',
    blade: true,
    gunner: false,
    defense: 62,
    fireRes: 4,
    waterRes: -4,
    iceRes: -1,
    thunderRes: 1,
    dragonRes: -2,
    slots: 3,
    rarity: 6,
    price: 18800,
    maxDefense: 62,
    skillPoints: {
      punishdraw: 1,
      bomb_boost: 2,
      defense: 2,
      eating: -2
    }
  }),
  deepFreeze<ArmArmor>({
    id: 93,
    type: 'arms',
    name: 'Uragaan Guards+',
    blade: false,
    gunner: true,
    defense: 37,
    fireRes: 4,
    waterRes: -4,
    iceRes: -1,
    thunderRes: 1,
    dragonRes: -2,
    slots: 3,
    rarity: 6,
    price: 18800,
    maxDefense: 37,
    skillPoints: {
      recoil: 1,
      bomb_boost: 2,
      defense: 1,
      eating: -3
    }
  }),
  deepFreeze<ArmArmor>({
    id: 94,
    type: 'arms',
    name: 'Agnaktor Vambraces+',
    blade: true,
    gunner: false,
    defense: 62,
    fireRes: 5,
    waterRes: -4,
    iceRes: -2,
    thunderRes: 1,
    dragonRes: 0,
    slots: 3,
    rarity: 6,
    price: 19800,
    maxDefense: 62,
    skillPoints: {
      sharpness: 1,
      stamina: -3,
      guard: 2,
      flame_aura: 1
    }
  }),
  deepFreeze<ArmArmor>({
    id: 95,
    type: 'arms',
    name: 'Agnaktor Guards+',
    blade: false,
    gunner: true,
    defense: 37,
    fireRes: 5,
    waterRes: -4,
    iceRes: -2,
    thunderRes: 1,
    dragonRes: 0,
    slots: 3,
    rarity: 6,
    price: 19800,
    maxDefense: 37,
    skillPoints: {
      normals_up: 2,
      'normal_s+': 1,
      stamina: -3,
      flame_aura: 1
    }
  }),
  deepFreeze<ArmArmor>({
    id: 96,
    type: 'arms',
    name: 'Vangis Vambraces',
    blade: true,
    gunner: false,
    defense: 64,
    fireRes: 0,
    waterRes: 0,
    iceRes: 3,
    thunderRes: -4,
    dragonRes: -4,
    slots: 0,
    rarity: 7,
    price: 41500,
    maxDefense: 64,
    skillPoints: {
      handicraft: 3,
      hunger: -1,
      attack: 5,
      psychic: 4
    }
  }),
  deepFreeze<ArmArmor>({
    id: 97,
    type: 'arms',
    name: 'Vangis Guards',
    blade: false,
    gunner: true,
    defense: 38,
    fireRes: 0,
    waterRes: 0,
    iceRes: 3,
    thunderRes: -4,
    dragonRes: -4,
    slots: 0,
    rarity: 7,
    price: 41500,
    maxDefense: 38,
    skillPoints: { loading: 2, hunger: -2, attack: 6, psychic: 3 }
  }),
  deepFreeze<ArmArmor>({
    id: 98,
    type: 'arms',
    name: 'Damascus Vambraces',
    blade: true,
    gunner: false,
    defense: 62,
    fireRes: -2,
    waterRes: 0,
    iceRes: 2,
    thunderRes: -2,
    dragonRes: 3,
    slots: 0,
    rarity: 6,
    price: 32300,
    maxDefense: 62,
    skillPoints: {
      stamina: -2,
      punishdraw: 3,
      health: 5,
      guard_up: 3
    }
  }),
  deepFreeze<ArmArmor>({
    id: 99,
    type: 'arms',
    name: 'Damascus Guards',
    blade: false,
    gunner: true,
    defense: 37,
    fireRes: -2,
    waterRes: 0,
    iceRes: 2,
    thunderRes: -2,
    dragonRes: 3,
    slots: 0,
    rarity: 6,
    price: 32300,
    maxDefense: 37,
    skillPoints: {
      stamina: -2,
      health: 4,
      guard_up: 2,
      reload_spd: 5
    }
  }),
  deepFreeze<ArmArmor>({
    id: 100,
    type: 'arms',
    name: 'Helios Vambraces+',
    blade: true,
    gunner: false,
    defense: 66,
    fireRes: 0,
    waterRes: 5,
    iceRes: 3,
    thunderRes: -3,
    dragonRes: -4,
    slots: 0,
    rarity: 6,
    price: 26200,
    maxDefense: 66,
    skillPoints: {
      sharpness: -1,
      handicraft: 3,
      hearing: 5,
      protection: -4
    }
  }),
  deepFreeze<ArmArmor>({
    id: 101,
    type: 'arms',
    name: 'Helios Guards+',
    blade: false,
    gunner: true,
    defense: 39,
    fireRes: 0,
    waterRes: 5,
    iceRes: 3,
    thunderRes: -3,
    dragonRes: -4,
    slots: 0,
    rarity: 6,
    price: 26200,
    maxDefense: 39,
    skillPoints: {
      recoil: -1,
      hearing: 5,
      loading: 3,
      protection: -4
    }
  }),
  deepFreeze<ArmArmor>({
    id: 102,
    type: 'arms',
    name: 'Yamato Kote+',
    blade: true,
    gunner: false,
    defense: 66,
    fireRes: 4,
    waterRes: 0,
    iceRes: -3,
    thunderRes: 0,
    dragonRes: -4,
    slots: 3,
    rarity: 6,
    price: 27500,
    maxDefense: 66,
    skillPoints: {
      sharpness: 1,
      fastcharge: 2,
      rec_speed: 1,
      combo_rate: -3
    }
  }),
  deepFreeze<ArmArmor>({
    id: 103,
    type: 'arms',
    name: 'Mutsu Kote+',
    blade: false,
    gunner: true,
    defense: 39,
    fireRes: 4,
    waterRes: 0,
    iceRes: -3,
    thunderRes: 0,
    dragonRes: -4,
    slots: 3,
    rarity: 6,
    price: 27500,
    maxDefense: 39,
    skillPoints: {
      recoil: 2,
      rec_speed: 1,
      'clust_s+': 1,
      combo_rate: -3
    }
  }),
  deepFreeze<ArmArmor>({
    id: 104,
    type: 'arms',
    name: 'Escadora Arms',
    blade: true,
    gunner: false,
    defense: 70,
    fireRes: -1,
    waterRes: -1,
    iceRes: -1,
    thunderRes: 0,
    dragonRes: -5,
    slots: 0,
    rarity: 7,
    price: 66666,
    maxDefense: 70,
    skillPoints: {
      evade_dist: 4,
      freeelemnt: 5,
      rec_level: -3,
      blight_res: 1
    }
  }),
  deepFreeze<ArmArmor>({
    id: 105,
    type: 'arms',
    name: 'Escadora Arma',
    blade: false,
    gunner: true,
    defense: 42,
    fireRes: -1,
    waterRes: -1,
    iceRes: -1,
    thunderRes: 0,
    dragonRes: -5,
    slots: 1,
    rarity: 7,
    price: 66666,
    maxDefense: 42,
    skillPoints: {
      evade_dist: 4,
      rapid_fire: 3,
      rec_level: -3,
      blight_res: 1
    }
  }),
  deepFreeze<ArmArmor>({
    id: 106,
    type: 'arms',
    name: 'Chakra Bracelet',
    blade: true,
    gunner: true,
    defense: 18,
    fireRes: 0,
    waterRes: 0,
    iceRes: 10,
    thunderRes: 0,
    dragonRes: -10,
    slots: 3,
    rarity: 7,
    price: 33333,
    maxDefense: 18,
    skillPoints: {}
  })
];
