import { deepFreeze } from '../../utils';
import { ChestArmor } from './types';

export const ChestArmors: ChestArmor[] = [
  deepFreeze<ChestArmor>({
    id: 0,
    type: 'chest',
    name: 'Leather Vest',
    blade: true,
    gunner: true,
    defense: 1,
    fireRes: -1,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 3,
    dragonRes: 2,
    slots: 1,
    rarity: 1,
    skillPoints: [
      { skillId: 40, points: 2 },
      { skillId: 41, points: 3 },
      { skillId: 69, points: 2 }
    ],
    price: 150,
    maxDefense: 1,
    maxLowRankDefense: 9
  }),
  deepFreeze<ChestArmor>({
    id: 1,
    type: 'chest',
    name: 'Chainmail Vest',
    blade: true,
    gunner: true,
    defense: 2,
    fireRes: -1,
    waterRes: -1,
    iceRes: 3,
    thunderRes: -1,
    dragonRes: 1,
    slots: 0,
    rarity: 1,
    skillPoints: [
      { skillId: 23, points: 3 },
      { skillId: 70, points: 1 },
      { skillId: 71, points: 4 },
      { skillId: 72, points: 1 }
    ],
    price: 200,
    maxDefense: 2,
    maxLowRankDefense: 9
  }),
  deepFreeze<ChestArmor>({
    id: 2,
    type: 'chest',
    name: 'Loc Lac Shawl',
    blade: true,
    gunner: true,
    defense: 4,
    fireRes: 4,
    waterRes: -3,
    iceRes: -4,
    thunderRes: 2,
    dragonRes: 0,
    slots: 0,
    rarity: 1,
    skillPoints: [
      { skillId: 24, points: 2 },
      { skillId: 60, points: 2 },
      { skillId: 66, points: 5 }
    ],
    price: 500,
    maxDefense: 4,
    maxLowRankDefense: 11
  }),
  deepFreeze<ChestArmor>({
    id: 3,
    type: 'chest',
    name: "Hunter's Mail",
    blade: true,
    gunner: false,
    defense: 6,
    fireRes: -1,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: -1,
    slots: 1,
    rarity: 1,
    skillPoints: [
      { skillId: 35, points: 1 },
      { skillId: 42, points: 3 },
      { skillId: 62, points: -1 },
      { skillId: 68, points: 1 },
      { skillId: 75, points: 1 }
    ],
    price: 500,
    maxDefense: 6,
    maxLowRankDefense: 20
  }),
  deepFreeze<ChestArmor>({
    id: 4,
    type: 'chest',
    name: "Hunter's Vest",
    blade: false,
    gunner: true,
    defense: 3,
    fireRes: -1,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: -1,
    slots: 1,
    rarity: 1,
    skillPoints: [
      { skillId: 35, points: 1 },
      { skillId: 42, points: 3 },
      { skillId: 62, points: -1 },
      { skillId: 68, points: 1 },
      { skillId: 75, points: 1 }
    ],
    price: 500,
    maxDefense: 3,
    maxLowRankDefense: 10
  }),
  deepFreeze<ChestArmor>({
    id: 5,
    type: 'chest',
    name: 'Bone Mail',
    blade: true,
    gunner: false,
    defense: 8,
    fireRes: 2,
    waterRes: -2,
    iceRes: -1,
    thunderRes: 2,
    dragonRes: 3,
    slots: 1,
    rarity: 1,
    skillPoints: [
      { skillId: 34, points: 4 },
      { skillId: 54, points: -1 },
      { skillId: 73, points: 1 },
      { skillId: 77, points: 1 }
    ],
    price: 750,
    maxDefense: 8,
    maxLowRankDefense: 22
  }),
  deepFreeze<ChestArmor>({
    id: 6,
    type: 'chest',
    name: 'Bone Vest',
    blade: false,
    gunner: true,
    defense: 4,
    fireRes: 2,
    waterRes: -2,
    iceRes: -1,
    thunderRes: 2,
    dragonRes: 3,
    slots: 1,
    rarity: 1,
    skillPoints: [
      { skillId: 34, points: 3 },
      { skillId: 54, points: -2 },
      { skillId: 73, points: 1 },
      { skillId: 77, points: 1 }
    ],
    price: 750,
    maxDefense: 4,
    maxLowRankDefense: 11
  }),
  deepFreeze<ChestArmor>({
    id: 7,
    type: 'chest',
    name: 'Alloy Mail',
    blade: true,
    gunner: false,
    defense: 8,
    fireRes: 1,
    waterRes: 1,
    iceRes: -1,
    thunderRes: -2,
    dragonRes: -1,
    slots: 1,
    rarity: 1,
    skillPoints: [
      { skillId: 25, points: 3 },
      { skillId: 26, points: 2 },
      { skillId: 76, points: 1 },
      { skillId: 78, points: -1 }
    ],
    price: 1000,
    maxDefense: 8,
    maxLowRankDefense: 22
  }),
  deepFreeze<ChestArmor>({
    id: 8,
    type: 'chest',
    name: 'Alloy Vest',
    blade: false,
    gunner: true,
    defense: 4,
    fireRes: 1,
    waterRes: 1,
    iceRes: -1,
    thunderRes: -2,
    dragonRes: -1,
    slots: 1,
    rarity: 1,
    skillPoints: [
      { skillId: 7, points: 2 },
      { skillId: 25, points: 3 },
      { skillId: 76, points: 1 },
      { skillId: 78, points: -1 }
    ],
    price: 1000,
    maxDefense: 4,
    maxLowRankDefense: 11
  }),
  deepFreeze<ChestArmor>({
    id: 9,
    type: 'chest',
    name: 'Jaggi Mail',
    blade: true,
    gunner: false,
    defense: 10,
    fireRes: -3,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 35, points: 2 },
      { skillId: 55, points: 1 },
      { skillId: 58, points: 1 },
      { skillId: 67, points: -3 }
    ],
    price: 1200,
    maxDefense: 10,
    maxLowRankDefense: 24
  }),
  deepFreeze<ChestArmor>({
    id: 10,
    type: 'chest',
    name: 'Jaggi Vest',
    blade: false,
    gunner: true,
    defense: 5,
    fireRes: -3,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 35, points: 2 },
      { skillId: 55, points: 2 },
      { skillId: 58, points: 1 },
      { skillId: 67, points: -2 }
    ],
    price: 1200,
    maxDefense: 5,
    maxLowRankDefense: 12
  }),
  deepFreeze<ChestArmor>({
    id: 11,
    type: 'chest',
    name: 'Bnahabra Suit',
    blade: true,
    gunner: false,
    defense: 10,
    fireRes: -4,
    waterRes: -1,
    iceRes: -1,
    thunderRes: 2,
    dragonRes: 5,
    slots: 0,
    rarity: 2,
    skillPoints: [
      { skillId: 0, points: 3 },
      { skillId: 9, points: 4 },
      { skillId: 22, points: -2 }
    ],
    price: 1800,
    maxDefense: 10,
    maxLowRankDefense: 24
  }),
  deepFreeze<ChestArmor>({
    id: 12,
    type: 'chest',
    name: 'Bnahabra Vest',
    blade: false,
    gunner: true,
    defense: 5,
    fireRes: -4,
    waterRes: -1,
    iceRes: -1,
    thunderRes: 2,
    dragonRes: 5,
    slots: 0,
    rarity: 2,
    skillPoints: [
      { skillId: 9, points: 4 },
      { skillId: 22, points: -2 },
      { skillId: 29, points: 3 }
    ],
    price: 1800,
    maxDefense: 5,
    maxLowRankDefense: 12
  }),
  deepFreeze<ChestArmor>({
    id: 13,
    type: 'chest',
    name: 'Rhenoplos Mail',
    blade: true,
    gunner: false,
    defense: 12,
    fireRes: 2,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: 2,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 35, points: 1 },
      { skillId: 39, points: 2 },
      { skillId: 46, points: 2 },
      { skillId: 56, points: 1 },
      { skillId: 63, points: -1 }
    ],
    price: 1400,
    maxDefense: 12,
    maxLowRankDefense: 24
  }),
  deepFreeze<ChestArmor>({
    id: 14,
    type: 'chest',
    name: 'Rhenoplos Vest',
    blade: false,
    gunner: true,
    defense: 6,
    fireRes: 2,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: 2,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 3, points: 2 },
      { skillId: 31, points: 1 },
      { skillId: 35, points: 1 },
      { skillId: 46, points: 2 },
      { skillId: 63, points: -1 }
    ],
    price: 1400,
    maxDefense: 6,
    maxLowRankDefense: 12
  }),
  deepFreeze<ChestArmor>({
    id: 15,
    type: 'chest',
    name: 'Qurupeco Mail',
    blade: true,
    gunner: false,
    defense: 12,
    fireRes: 2,
    waterRes: -2,
    iceRes: -3,
    thunderRes: 0,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 36, points: 2 },
      { skillId: 43, points: 2 },
      { skillId: 44, points: 2 },
      { skillId: 64, points: -1 }
    ],
    price: 1700,
    maxDefense: 12,
    maxLowRankDefense: 24
  }),
  deepFreeze<ChestArmor>({
    id: 16,
    type: 'chest',
    name: 'Qurupeco Vest',
    blade: false,
    gunner: true,
    defense: 6,
    fireRes: 2,
    waterRes: -2,
    iceRes: -3,
    thunderRes: 0,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 36, points: 1 },
      { skillId: 43, points: 2 },
      { skillId: 44, points: 2 },
      { skillId: 64, points: -2 }
    ],
    price: 1700,
    maxDefense: 6,
    maxLowRankDefense: 12
  }),
  deepFreeze<ChestArmor>({
    id: 17,
    type: 'chest',
    name: 'Ludroth Mail',
    blade: true,
    gunner: false,
    defense: 13,
    fireRes: -3,
    waterRes: 2,
    iceRes: 0,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 35, points: 2 },
      { skillId: 37, points: 2 },
      { skillId: 49, points: 1 },
      { skillId: 61, points: -1 },
      { skillId: 79, points: 1 }
    ],
    price: 2200,
    maxDefense: 13,
    maxLowRankDefense: 25
  }),
  deepFreeze<ChestArmor>({
    id: 18,
    type: 'chest',
    name: 'Ludroth Vest',
    blade: false,
    gunner: true,
    defense: 7,
    fireRes: -3,
    waterRes: 2,
    iceRes: 0,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 30, points: 1 },
      { skillId: 35, points: 2 },
      { skillId: 37, points: 2 },
      { skillId: 49, points: 1 },
      { skillId: 61, points: -1 }
    ],
    price: 2200,
    maxDefense: 7,
    maxLowRankDefense: 13
  }),
  deepFreeze<ChestArmor>({
    id: 19,
    type: 'chest',
    name: 'Steel Mail',
    blade: true,
    gunner: false,
    defense: 12,
    fireRes: -1,
    waterRes: 1,
    iceRes: 1,
    thunderRes: -1,
    dragonRes: 0,
    slots: 0,
    rarity: 2,
    skillPoints: [
      { skillId: 26, points: 3 },
      { skillId: 27, points: 4 },
      { skillId: 50, points: -3 }
    ],
    price: 2000,
    maxDefense: 12,
    maxLowRankDefense: 24
  }),
  deepFreeze<ChestArmor>({
    id: 20,
    type: 'chest',
    name: 'Baggi Mail',
    blade: true,
    gunner: false,
    defense: 13,
    fireRes: -3,
    waterRes: -1,
    iceRes: 3,
    thunderRes: -1,
    dragonRes: 1,
    slots: 2,
    rarity: 2,
    skillPoints: [
      { skillId: 17, points: 1 },
      { skillId: 18, points: 1 },
      { skillId: 35, points: 1 },
      { skillId: 55, points: -1 },
      { skillId: 64, points: 1 }
    ],
    price: 2400,
    maxDefense: 13,
    maxLowRankDefense: 25
  }),
  deepFreeze<ChestArmor>({
    id: 21,
    type: 'chest',
    name: 'Baggi Vest',
    blade: false,
    gunner: true,
    defense: 7,
    fireRes: -3,
    waterRes: -1,
    iceRes: 3,
    thunderRes: -1,
    dragonRes: 1,
    slots: 2,
    rarity: 2,
    skillPoints: [
      { skillId: 6, points: 1 },
      { skillId: 17, points: 1 },
      { skillId: 35, points: 1 },
      { skillId: 55, points: -1 },
      { skillId: 64, points: 1 }
    ],
    price: 2400,
    maxDefense: 7,
    maxLowRankDefense: 13
  }),
  deepFreeze<ChestArmor>({
    id: 22,
    type: 'chest',
    name: 'Barroth Mail',
    blade: true,
    gunner: false,
    defense: 15,
    fireRes: -4,
    waterRes: 4,
    iceRes: -3,
    thunderRes: 3,
    dragonRes: 0,
    slots: 0,
    rarity: 2,
    skillPoints: [
      { skillId: 13, points: 1 },
      { skillId: 25, points: -3 },
      { skillId: 35, points: 3 },
      { skillId: 45, points: 2 }
    ],
    price: 3200,
    maxDefense: 15,
    maxLowRankDefense: 27
  }),
  deepFreeze<ChestArmor>({
    id: 23,
    type: 'chest',
    name: 'Barroth Vest',
    blade: false,
    gunner: true,
    defense: 8,
    fireRes: -4,
    waterRes: 4,
    iceRes: -3,
    thunderRes: 3,
    dragonRes: 0,
    slots: 0,
    rarity: 2,
    skillPoints: [
      { skillId: 13, points: 1 },
      { skillId: 25, points: -3 },
      { skillId: 35, points: 3 },
      { skillId: 45, points: 2 }
    ],
    price: 3200,
    maxDefense: 8,
    maxLowRankDefense: 14
  }),
  deepFreeze<ChestArmor>({
    id: 24,
    type: 'chest',
    name: 'Gobul Mail',
    blade: true,
    gunner: false,
    defense: 16,
    fireRes: -2,
    waterRes: 3,
    iceRes: 0,
    thunderRes: -3,
    dragonRes: 2,
    slots: 0,
    rarity: 2,
    skillPoints: [
      { skillId: 24, points: -1 },
      { skillId: 35, points: 1 },
      { skillId: 46, points: 2 },
      { skillId: 55, points: 2 },
      { skillId: 62, points: 3 }
    ],
    price: 3600,
    maxDefense: 16,
    maxLowRankDefense: 28
  }),
  deepFreeze<ChestArmor>({
    id: 25,
    type: 'chest',
    name: 'Gobul Vest',
    blade: false,
    gunner: true,
    defense: 8,
    fireRes: -2,
    waterRes: 3,
    iceRes: 0,
    thunderRes: -3,
    dragonRes: 2,
    slots: 0,
    rarity: 2,
    skillPoints: [
      { skillId: 24, points: -2 },
      { skillId: 35, points: 1 },
      { skillId: 46, points: 2 },
      { skillId: 55, points: 1 },
      { skillId: 62, points: 3 }
    ],
    price: 3600,
    maxDefense: 8,
    maxLowRankDefense: 14
  }),
  deepFreeze<ChestArmor>({
    id: 26,
    type: 'chest',
    name: "Ranger's Girdle",
    blade: true,
    gunner: false,
    defense: 15,
    fireRes: 0,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 0,
    rarity: 3,
    skillPoints: [
      { skillId: 12, points: -3 },
      { skillId: 15, points: 1 },
      { skillId: 38, points: 2 },
      { skillId: 41, points: 4 }
    ],
    price: 10000,
    maxDefense: 15,
    maxLowRankDefense: 27
  }),
  deepFreeze<ChestArmor>({
    id: 27,
    type: 'chest',
    name: "Archer's Girdle",
    blade: false,
    gunner: true,
    defense: 8,
    fireRes: 0,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 0,
    rarity: 3,
    skillPoints: [
      { skillId: 12, points: -3 },
      { skillId: 15, points: 1 },
      { skillId: 38, points: 2 },
      { skillId: 41, points: 4 }
    ],
    price: 10000,
    maxDefense: 8,
    maxLowRankDefense: 14
  }),
  deepFreeze<ChestArmor>({
    id: 28,
    type: 'chest',
    name: 'Guild Bard Bolero',
    blade: true,
    gunner: false,
    defense: 15,
    fireRes: 0,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 0,
    rarity: 3,
    skillPoints: [
      { skillId: 12, points: 1 },
      { skillId: 42, points: 2 },
      { skillId: 44, points: 3 },
      { skillId: 57, points: -3 }
    ],
    price: 10000,
    maxDefense: 15,
    maxLowRankDefense: 27
  }),
  deepFreeze<ChestArmor>({
    id: 29,
    type: 'chest',
    name: 'Guild Bard Vest',
    blade: false,
    gunner: true,
    defense: 8,
    fireRes: 0,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 0,
    rarity: 3,
    skillPoints: [
      { skillId: 12, points: 2 },
      { skillId: 42, points: 2 },
      { skillId: 44, points: 3 },
      { skillId: 57, points: -2 }
    ],
    price: 10000,
    maxDefense: 8,
    maxLowRankDefense: 14
  }),
  deepFreeze<ChestArmor>({
    id: 30,
    type: 'chest',
    name: 'Rathian Mail',
    blade: true,
    gunner: false,
    defense: 16,
    fireRes: 3,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 11, points: 1 },
      { skillId: 23, points: 2 },
      { skillId: 37, points: -2 },
      { skillId: 61, points: 2 }
    ],
    price: 3600,
    maxDefense: 16,
    maxLowRankDefense: 28
  }),
  deepFreeze<ChestArmor>({
    id: 31,
    type: 'chest',
    name: 'Rathian Vest',
    blade: false,
    gunner: true,
    defense: 8,
    fireRes: 3,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 11, points: 1 },
      { skillId: 23, points: 2 },
      { skillId: 37, points: -2 },
      { skillId: 61, points: 2 }
    ],
    price: 3600,
    maxDefense: 8,
    maxLowRankDefense: 14
  }),
  deepFreeze<ChestArmor>({
    id: 32,
    type: 'chest',
    name: 'Gigginox Mail',
    blade: true,
    gunner: false,
    defense: 18,
    fireRes: -4,
    waterRes: 0,
    iceRes: 2,
    thunderRes: 2,
    dragonRes: -1,
    slots: 0,
    rarity: 2,
    skillPoints: [
      { skillId: 9, points: 1 },
      { skillId: 22, points: 2 },
      { skillId: 23, points: -2 },
      { skillId: 49, points: 4 }
    ],
    price: 4100,
    maxDefense: 18,
    maxLowRankDefense: 30
  }),
  deepFreeze<ChestArmor>({
    id: 33,
    type: 'chest',
    name: 'Gigginox Vest',
    blade: false,
    gunner: true,
    defense: 9,
    fireRes: -4,
    waterRes: 0,
    iceRes: 2,
    thunderRes: 2,
    dragonRes: -1,
    slots: 0,
    rarity: 2,
    skillPoints: [
      { skillId: 9, points: 1 },
      { skillId: 22, points: 3 },
      { skillId: 23, points: -2 },
      { skillId: 49, points: 3 }
    ],
    price: 4100,
    maxDefense: 9,
    maxLowRankDefense: 15
  }),
  deepFreeze<ChestArmor>({
    id: 34,
    type: 'chest',
    name: 'Ingot Mail',
    blade: true,
    gunner: false,
    defense: 18,
    fireRes: -2,
    waterRes: -1,
    iceRes: 1,
    thunderRes: 3,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 26, points: -2 },
      { skillId: 28, points: 1 },
      { skillId: 39, points: 3 },
      { skillId: 63, points: 1 }
    ],
    price: 5000,
    maxDefense: 18,
    maxLowRankDefense: 28
  }),
  deepFreeze<ChestArmor>({
    id: 35,
    type: 'chest',
    name: 'Ingot Vest',
    blade: false,
    gunner: true,
    defense: 9,
    fireRes: -2,
    waterRes: -1,
    iceRes: 1,
    thunderRes: 3,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 3, points: 3 },
      { skillId: 28, points: 1 },
      { skillId: 29, points: -2 },
      { skillId: 63, points: 1 }
    ],
    price: 5000,
    maxDefense: 9,
    maxLowRankDefense: 14
  }),
  deepFreeze<ChestArmor>({
    id: 36,
    type: 'chest',
    name: 'Lagiacrus Mail',
    blade: true,
    gunner: false,
    defense: 20,
    fireRes: -3,
    waterRes: 2,
    iceRes: -1,
    thunderRes: 4,
    dragonRes: -2,
    slots: 1,
    rarity: 3,
    skillPoints: [
      { skillId: 0, points: 1 },
      { skillId: 9, points: -3 },
      { skillId: 10, points: 3 },
      { skillId: 50, points: 1 }
    ],
    price: 5600,
    maxDefense: 20,
    maxLowRankDefense: 30
  }),
  deepFreeze<ChestArmor>({
    id: 37,
    type: 'chest',
    name: 'Lagiacrus Vest',
    blade: false,
    gunner: true,
    defense: 10,
    fireRes: -3,
    waterRes: 2,
    iceRes: -1,
    thunderRes: 4,
    dragonRes: -2,
    slots: 1,
    rarity: 3,
    skillPoints: [
      { skillId: 4, points: 1 },
      { skillId: 9, points: -3 },
      { skillId: 10, points: 3 },
      { skillId: 50, points: 1 }
    ],
    price: 5600,
    maxDefense: 10,
    maxLowRankDefense: 15
  }),
  deepFreeze<ChestArmor>({
    id: 38,
    type: 'chest',
    name: 'Rathalos Mail',
    blade: true,
    gunner: false,
    defense: 20,
    fireRes: 3,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 1,
    rarity: 3,
    skillPoints: [
      { skillId: 25, points: 1 },
      { skillId: 35, points: 2 },
      { skillId: 36, points: -2 },
      { skillId: 66, points: 2 }
    ],
    price: 5600,
    maxDefense: 20,
    maxLowRankDefense: 30
  }),
  deepFreeze<ChestArmor>({
    id: 39,
    type: 'chest',
    name: 'Rathalos Vest',
    blade: false,
    gunner: true,
    defense: 10,
    fireRes: 3,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 1,
    rarity: 3,
    skillPoints: [
      { skillId: 25, points: 1 },
      { skillId: 35, points: 2 },
      { skillId: 36, points: -2 },
      { skillId: 66, points: 2 }
    ],
    price: 5600,
    maxDefense: 10,
    maxLowRankDefense: 15
  }),
  deepFreeze<ChestArmor>({
    id: 40,
    type: 'chest',
    name: 'Barioth Mail',
    blade: true,
    gunner: false,
    defense: 20,
    fireRes: -4,
    waterRes: 2,
    iceRes: 4,
    thunderRes: -3,
    dragonRes: 0,
    slots: 1,
    rarity: 3,
    skillPoints: [
      { skillId: 13, points: 2 },
      { skillId: 44, points: 2 },
      { skillId: 66, points: -2 },
      { skillId: 67, points: 1 }
    ],
    price: 5600,
    maxDefense: 20,
    maxLowRankDefense: 30
  }),
  deepFreeze<ChestArmor>({
    id: 41,
    type: 'chest',
    name: 'Barioth Vest',
    blade: false,
    gunner: true,
    defense: 10,
    fireRes: -4,
    waterRes: 2,
    iceRes: 4,
    thunderRes: -3,
    dragonRes: 0,
    slots: 1,
    rarity: 3,
    skillPoints: [
      { skillId: 13, points: 2 },
      { skillId: 44, points: 2 },
      { skillId: 66, points: -2 },
      { skillId: 67, points: 1 }
    ],
    price: 5600,
    maxDefense: 10,
    maxLowRankDefense: 15
  }),
  deepFreeze<ChestArmor>({
    id: 42,
    type: 'chest',
    name: 'Diablos Mail',
    blade: true,
    gunner: false,
    defense: 22,
    fireRes: 2,
    waterRes: -1,
    iceRes: -3,
    thunderRes: -1,
    dragonRes: -1,
    slots: 0,
    rarity: 3,
    skillPoints: [
      { skillId: 10, points: -4 },
      { skillId: 47, points: 3 },
      { skillId: 48, points: 3 }
    ],
    price: 6300,
    maxDefense: 22,
    maxLowRankDefense: 30
  }),
  deepFreeze<ChestArmor>({
    id: 43,
    type: 'chest',
    name: 'Diablos Vest',
    blade: false,
    gunner: true,
    defense: 11,
    fireRes: 2,
    waterRes: -1,
    iceRes: -3,
    thunderRes: -1,
    dragonRes: -1,
    slots: 0,
    rarity: 3,
    skillPoints: [
      { skillId: 5, points: 3 },
      { skillId: 8, points: 3 },
      { skillId: 10, points: -4 }
    ],
    price: 6300,
    maxDefense: 11,
    maxLowRankDefense: 15
  }),
  deepFreeze<ChestArmor>({
    id: 44,
    type: 'chest',
    name: 'Uragaan Mail',
    blade: true,
    gunner: false,
    defense: 22,
    fireRes: 3,
    waterRes: -4,
    iceRes: -1,
    thunderRes: 1,
    dragonRes: -2,
    slots: 0,
    rarity: 3,
    skillPoints: [
      { skillId: 19, points: 3 },
      { skillId: 33, points: 2 },
      { skillId: 36, points: 3 },
      { skillId: 46, points: -1 }
    ],
    price: 6300,
    maxDefense: 22,
    maxLowRankDefense: 30
  }),
  deepFreeze<ChestArmor>({
    id: 45,
    type: 'chest',
    name: 'Uragaan Vest',
    blade: false,
    gunner: true,
    defense: 11,
    fireRes: 3,
    waterRes: -4,
    iceRes: -1,
    thunderRes: 1,
    dragonRes: -2,
    slots: 0,
    rarity: 3,
    skillPoints: [
      { skillId: 3, points: 4 },
      { skillId: 33, points: 2 },
      { skillId: 36, points: 2 },
      { skillId: 46, points: -1 }
    ],
    price: 6300,
    maxDefense: 11,
    maxLowRankDefense: 15
  }),
  deepFreeze<ChestArmor>({
    id: 46,
    type: 'chest',
    name: 'Agnaktor Mail',
    blade: true,
    gunner: false,
    defense: 22,
    fireRes: 4,
    waterRes: -4,
    iceRes: -2,
    thunderRes: 1,
    dragonRes: 0,
    slots: 1,
    rarity: 3,
    skillPoints: [
      { skillId: 13, points: -2 },
      { skillId: 27, points: 3 },
      { skillId: 28, points: 1 },
      { skillId: 52, points: 1 }
    ],
    price: 7200,
    maxDefense: 22,
    maxLowRankDefense: 30
  }),
  deepFreeze<ChestArmor>({
    id: 47,
    type: 'chest',
    name: 'Agnaktor Vest',
    blade: false,
    gunner: true,
    defense: 11,
    fireRes: 4,
    waterRes: -4,
    iceRes: -2,
    thunderRes: 1,
    dragonRes: 0,
    slots: 1,
    rarity: 3,
    skillPoints: [
      { skillId: 13, points: -2 },
      { skillId: 28, points: 1 },
      { skillId: 29, points: 3 },
      { skillId: 52, points: 1 }
    ],
    price: 7200,
    maxDefense: 11,
    maxLowRankDefense: 15
  }),
  deepFreeze<ChestArmor>({
    id: 48,
    type: 'chest',
    name: 'Helios Mail',
    blade: true,
    gunner: false,
    defense: 24,
    fireRes: 0,
    waterRes: 4,
    iceRes: 3,
    thunderRes: -3,
    dragonRes: -4,
    slots: 0,
    rarity: 3,
    skillPoints: [
      { skillId: 0, points: -2 },
      { skillId: 1, points: 2 },
      { skillId: 11, points: 2 },
      { skillId: 37, points: -2 }
    ],
    price: 11000,
    maxDefense: 24,
    maxLowRankDefense: 32
  }),
  deepFreeze<ChestArmor>({
    id: 49,
    type: 'chest',
    name: 'Helios Vest',
    blade: false,
    gunner: true,
    defense: 12,
    fireRes: 0,
    waterRes: 4,
    iceRes: 3,
    thunderRes: -3,
    dragonRes: -4,
    slots: 0,
    rarity: 3,
    skillPoints: [
      { skillId: 3, points: -3 },
      { skillId: 11, points: 2 },
      { skillId: 14, points: 2 },
      { skillId: 37, points: -2 }
    ],
    price: 11000,
    maxDefense: 12,
    maxLowRankDefense: 16
  }),
  deepFreeze<ChestArmor>({
    id: 50,
    type: 'chest',
    name: 'Yamato Muneate',
    blade: true,
    gunner: false,
    defense: 24,
    fireRes: 3,
    waterRes: 0,
    iceRes: -3,
    thunderRes: 0,
    dragonRes: -3,
    slots: 1,
    rarity: 3,
    skillPoints: [
      { skillId: 0, points: 1 },
      { skillId: 18, points: 2 },
      { skillId: 24, points: 3 },
      { skillId: 71, points: -1 }
    ],
    price: 12000,
    maxDefense: 24,
    maxLowRankDefense: 32
  }),
  deepFreeze<ChestArmor>({
    id: 51,
    type: 'chest',
    name: 'Mutsu Muneate',
    blade: false,
    gunner: true,
    defense: 12,
    fireRes: 3,
    waterRes: 0,
    iceRes: -3,
    thunderRes: 0,
    dragonRes: -3,
    slots: 1,
    rarity: 3,
    skillPoints: [
      { skillId: 3, points: 1 },
      { skillId: 24, points: 3 },
      { skillId: 32, points: 1 },
      { skillId: 71, points: -2 }
    ],
    price: 12000,
    maxDefense: 12,
    maxLowRankDefense: 16
  }),
  deepFreeze<ChestArmor>({
    id: 52,
    type: 'chest',
    name: 'Leather Mail+',
    blade: true,
    gunner: false,
    defense: 26,
    fireRes: -2,
    waterRes: 0,
    iceRes: -2,
    thunderRes: 3,
    dragonRes: 2,
    slots: 1,
    rarity: 4,
    skillPoints: [
      { skillId: 40, points: 5 },
      { skillId: 41, points: 1 },
      { skillId: 69, points: 2 }
    ],
    price: 4600,
    maxDefense: 26
  }),
  deepFreeze<ChestArmor>({
    id: 53,
    type: 'chest',
    name: 'Leather Vest+',
    blade: false,
    gunner: true,
    defense: 15,
    fireRes: -2,
    waterRes: 0,
    iceRes: -2,
    thunderRes: 3,
    dragonRes: 2,
    slots: 1,
    rarity: 4,
    skillPoints: [
      { skillId: 40, points: 5 },
      { skillId: 41, points: 2 },
      { skillId: 69, points: 1 }
    ],
    price: 4600,
    maxDefense: 15
  }),
  deepFreeze<ChestArmor>({
    id: 54,
    type: 'chest',
    name: 'Chainmail Armor+',
    blade: true,
    gunner: false,
    defense: 30,
    fireRes: -1,
    waterRes: -2,
    iceRes: 4,
    thunderRes: -1,
    dragonRes: 1,
    slots: 2,
    rarity: 4,
    skillPoints: [
      { skillId: 23, points: 5 },
      { skillId: 71, points: 1 },
      { skillId: 72, points: 1 }
    ],
    price: 5400,
    maxDefense: 30
  }),
  deepFreeze<ChestArmor>({
    id: 55,
    type: 'chest',
    name: 'Chainmail Vest+',
    blade: false,
    gunner: true,
    defense: 18,
    fireRes: -1,
    waterRes: -2,
    iceRes: 4,
    thunderRes: -1,
    dragonRes: 1,
    slots: 2,
    rarity: 4,
    skillPoints: [
      { skillId: 23, points: 2 },
      { skillId: 71, points: 4 },
      { skillId: 72, points: 1 }
    ],
    price: 5400,
    maxDefense: 18
  }),
  deepFreeze<ChestArmor>({
    id: 56,
    type: 'chest',
    name: 'Loc Lac Shawl+',
    blade: true,
    gunner: false,
    defense: 30,
    fireRes: 5,
    waterRes: -4,
    iceRes: -5,
    thunderRes: 2,
    dragonRes: 0,
    slots: 0,
    rarity: 4,
    skillPoints: [
      { skillId: 24, points: 2 },
      { skillId: 60, points: 3 },
      { skillId: 66, points: 6 }
    ],
    price: 5400,
    maxDefense: 30
  }),
  deepFreeze<ChestArmor>({
    id: 57,
    type: 'chest',
    name: 'Loc Lac Vest+',
    blade: false,
    gunner: true,
    defense: 18,
    fireRes: 5,
    waterRes: -4,
    iceRes: -5,
    thunderRes: 2,
    dragonRes: 0,
    slots: 0,
    rarity: 4,
    skillPoints: [
      { skillId: 24, points: 2 },
      { skillId: 60, points: 3 },
      { skillId: 66, points: 6 }
    ],
    price: 5400,
    maxDefense: 18
  }),
  deepFreeze<ChestArmor>({
    id: 58,
    type: 'chest',
    name: "Hunter's Mail+",
    blade: true,
    gunner: false,
    defense: 30,
    fireRes: 0,
    waterRes: -2,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 1,
    rarity: 4,
    skillPoints: [
      { skillId: 25, points: 1 },
      { skillId: 42, points: 5 },
      { skillId: 44, points: 1 },
      { skillId: 62, points: -1 },
      { skillId: 68, points: 1 }
    ],
    price: 5400,
    maxDefense: 30
  }),
  deepFreeze<ChestArmor>({
    id: 59,
    type: 'chest',
    name: "Hunter's Vest+",
    blade: false,
    gunner: true,
    defense: 18,
    fireRes: 0,
    waterRes: -2,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 1,
    rarity: 4,
    skillPoints: [
      { skillId: 25, points: 1 },
      { skillId: 42, points: 5 },
      { skillId: 44, points: 1 },
      { skillId: 62, points: -1 },
      { skillId: 68, points: 1 }
    ],
    price: 5400,
    maxDefense: 18
  }),
  deepFreeze<ChestArmor>({
    id: 60,
    type: 'chest',
    name: 'Bone Mail+',
    blade: true,
    gunner: false,
    defense: 34,
    fireRes: 3,
    waterRes: -2,
    iceRes: -1,
    thunderRes: 2,
    dragonRes: 3,
    slots: 1,
    rarity: 4,
    skillPoints: [
      { skillId: 13, points: 1 },
      { skillId: 25, points: 2 },
      { skillId: 34, points: 1 },
      { skillId: 54, points: -1 },
      { skillId: 77, points: 4 }
    ],
    price: 6400,
    maxDefense: 34
  }),
  deepFreeze<ChestArmor>({
    id: 61,
    type: 'chest',
    name: 'Bone Vest+',
    blade: false,
    gunner: true,
    defense: 20,
    fireRes: 3,
    waterRes: -2,
    iceRes: -1,
    thunderRes: 2,
    dragonRes: 3,
    slots: 1,
    rarity: 4,
    skillPoints: [
      { skillId: 13, points: 2 },
      { skillId: 25, points: 2 },
      { skillId: 34, points: 2 },
      { skillId: 54, points: -1 },
      { skillId: 77, points: 2 }
    ],
    price: 6400,
    maxDefense: 20
  }),
  deepFreeze<ChestArmor>({
    id: 62,
    type: 'chest',
    name: 'Alloy Mail+',
    blade: true,
    gunner: false,
    defense: 34,
    fireRes: 1,
    waterRes: 2,
    iceRes: -1,
    thunderRes: -2,
    dragonRes: -1,
    slots: 2,
    rarity: 4,
    skillPoints: [
      { skillId: 25, points: 3 },
      { skillId: 26, points: 2 },
      { skillId: 76, points: 1 },
      { skillId: 78, points: -1 }
    ],
    price: 7100,
    maxDefense: 34
  }),
  deepFreeze<ChestArmor>({
    id: 63,
    type: 'chest',
    name: 'Alloy Vest+',
    blade: false,
    gunner: true,
    defense: 20,
    fireRes: 1,
    waterRes: 2,
    iceRes: -1,
    thunderRes: -2,
    dragonRes: -1,
    slots: 2,
    rarity: 4,
    skillPoints: [
      { skillId: 7, points: 2 },
      { skillId: 25, points: 3 },
      { skillId: 76, points: 1 },
      { skillId: 78, points: -1 }
    ],
    price: 7100,
    maxDefense: 20
  }),
  deepFreeze<ChestArmor>({
    id: 64,
    type: 'chest',
    name: 'Jaggi Mail+',
    blade: true,
    gunner: false,
    defense: 38,
    fireRes: -3,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: 2,
    slots: 0,
    rarity: 5,
    skillPoints: [
      { skillId: 25, points: 2 },
      { skillId: 35, points: 4 },
      { skillId: 55, points: 3 },
      { skillId: 58, points: 1 },
      { skillId: 67, points: -1 }
    ],
    price: 8000,
    maxDefense: 38
  }),
  deepFreeze<ChestArmor>({
    id: 65,
    type: 'chest',
    name: 'Jaggi Vest+',
    blade: false,
    gunner: true,
    defense: 22,
    fireRes: -3,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: 2,
    slots: 0,
    rarity: 5,
    skillPoints: [
      { skillId: 25, points: 2 },
      { skillId: 35, points: 5 },
      { skillId: 55, points: 1 },
      { skillId: 58, points: 2 },
      { skillId: 67, points: -1 }
    ],
    price: 8000,
    maxDefense: 22
  }),
  deepFreeze<ChestArmor>({
    id: 66,
    type: 'chest',
    name: 'Bnahabra Mail+',
    blade: true,
    gunner: false,
    defense: 38,
    fireRes: -5,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 2,
    dragonRes: 6,
    slots: 1,
    rarity: 5,
    skillPoints: [
      { skillId: 0, points: 1 },
      { skillId: 9, points: 3 },
      { skillId: 22, points: -5 }
    ],
    price: 10500,
    maxDefense: 38
  }),
  deepFreeze<ChestArmor>({
    id: 67,
    type: 'chest',
    name: 'Bnahabra Vest+',
    blade: false,
    gunner: true,
    defense: 22,
    fireRes: -5,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 2,
    dragonRes: 6,
    slots: 1,
    rarity: 5,
    skillPoints: [
      { skillId: 9, points: 3 },
      { skillId: 22, points: -5 },
      { skillId: 29, points: 1 }
    ],
    price: 10500,
    maxDefense: 22
  }),
  deepFreeze<ChestArmor>({
    id: 68,
    type: 'chest',
    name: 'Rhenoplos Mail+',
    blade: true,
    gunner: false,
    defense: 38,
    fireRes: 3,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -2,
    dragonRes: 2,
    slots: 1,
    rarity: 5,
    skillPoints: [
      { skillId: 25, points: 2 },
      { skillId: 39, points: 4 },
      { skillId: 46, points: 1 },
      { skillId: 56, points: 1 },
      { skillId: 63, points: -1 }
    ],
    price: 8500,
    maxDefense: 38
  }),
  deepFreeze<ChestArmor>({
    id: 69,
    type: 'chest',
    name: 'Rhenoplos Vest+',
    blade: false,
    gunner: true,
    defense: 22,
    fireRes: 3,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -2,
    dragonRes: 2,
    slots: 1,
    rarity: 5,
    skillPoints: [
      { skillId: 3, points: 4 },
      { skillId: 25, points: 2 },
      { skillId: 31, points: 1 },
      { skillId: 46, points: 1 },
      { skillId: 63, points: -1 }
    ],
    price: 8500,
    maxDefense: 22
  }),
  deepFreeze<ChestArmor>({
    id: 70,
    type: 'chest',
    name: 'Qurupeco Mail+',
    blade: true,
    gunner: false,
    defense: 42,
    fireRes: 4,
    waterRes: -3,
    iceRes: -4,
    thunderRes: 0,
    dragonRes: 1,
    slots: 1,
    rarity: 5,
    skillPoints: [
      { skillId: 25, points: 1 },
      { skillId: 36, points: 2 },
      { skillId: 38, points: 4 },
      { skillId: 43, points: 1 },
      { skillId: 64, points: -1 }
    ],
    price: 10000,
    maxDefense: 42
  }),
  deepFreeze<ChestArmor>({
    id: 71,
    type: 'chest',
    name: 'Qurupeco Vest+',
    blade: false,
    gunner: true,
    defense: 25,
    fireRes: 4,
    waterRes: -3,
    iceRes: -4,
    thunderRes: 0,
    dragonRes: 1,
    slots: 1,
    rarity: 5,
    skillPoints: [
      { skillId: 25, points: 1 },
      { skillId: 36, points: 1 },
      { skillId: 38, points: 4 },
      { skillId: 43, points: 1 },
      { skillId: 64, points: -2 }
    ],
    price: 10000,
    maxDefense: 25
  }),
  deepFreeze<ChestArmor>({
    id: 72,
    type: 'chest',
    name: 'Ludroth Mail+',
    blade: true,
    gunner: false,
    defense: 44,
    fireRes: -4,
    waterRes: 4,
    iceRes: 0,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 5,
    skillPoints: [
      { skillId: 25, points: 1 },
      { skillId: 34, points: -1 },
      { skillId: 37, points: 1 },
      { skillId: 49, points: 4 },
      { skillId: 79, points: 2 }
    ],
    price: 11800,
    maxDefense: 44
  }),
  deepFreeze<ChestArmor>({
    id: 73,
    type: 'chest',
    name: 'Ludroth Vest+',
    blade: false,
    gunner: true,
    defense: 26,
    fireRes: -4,
    waterRes: 4,
    iceRes: 0,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 5,
    skillPoints: [
      { skillId: 25, points: 1 },
      { skillId: 30, points: 1 },
      { skillId: 34, points: -2 },
      { skillId: 37, points: 1 },
      { skillId: 49, points: 4 }
    ],
    price: 11800,
    maxDefense: 26
  }),
  deepFreeze<ChestArmor>({
    id: 74,
    type: 'chest',
    name: 'Steel Mail+',
    blade: true,
    gunner: false,
    defense: 42,
    fireRes: -1,
    waterRes: 1,
    iceRes: 1,
    thunderRes: -1,
    dragonRes: 0,
    slots: 1,
    rarity: 5,
    skillPoints: [
      { skillId: 26, points: 2 },
      { skillId: 27, points: 2 },
      { skillId: 50, points: -5 }
    ],
    price: 11000,
    maxDefense: 42
  }),
  deepFreeze<ChestArmor>({
    id: 75,
    type: 'chest',
    name: 'Baggi Mail+',
    blade: true,
    gunner: false,
    defense: 44,
    fireRes: -4,
    waterRes: -1,
    iceRes: 4,
    thunderRes: -1,
    dragonRes: 1,
    slots: 0,
    rarity: 5,
    skillPoints: [
      { skillId: 17, points: 2 },
      { skillId: 18, points: 1 },
      { skillId: 25, points: 2 },
      { skillId: 55, points: -2 },
      { skillId: 64, points: 4 }
    ],
    price: 12300,
    maxDefense: 44
  }),
  deepFreeze<ChestArmor>({
    id: 76,
    type: 'chest',
    name: 'Baggi Vest+',
    blade: false,
    gunner: true,
    defense: 26,
    fireRes: -4,
    waterRes: -1,
    iceRes: 4,
    thunderRes: -1,
    dragonRes: 1,
    slots: 0,
    rarity: 5,
    skillPoints: [
      { skillId: 6, points: 1 },
      { skillId: 17, points: 2 },
      { skillId: 25, points: 2 },
      { skillId: 55, points: -2 },
      { skillId: 64, points: 4 }
    ],
    price: 12300,
    maxDefense: 26
  }),
  deepFreeze<ChestArmor>({
    id: 77,
    type: 'chest',
    name: 'Barroth Mail+',
    blade: true,
    gunner: false,
    defense: 48,
    fireRes: -5,
    waterRes: 5,
    iceRes: -4,
    thunderRes: 4,
    dragonRes: 0,
    slots: 0,
    rarity: 5,
    skillPoints: [
      { skillId: 13, points: 1 },
      { skillId: 25, points: -2 },
      { skillId: 35, points: 6 },
      { skillId: 45, points: 2 }
    ],
    price: 13800,
    maxDefense: 48
  }),
  deepFreeze<ChestArmor>({
    id: 78,
    type: 'chest',
    name: 'Barroth Vest+',
    blade: false,
    gunner: true,
    defense: 28,
    fireRes: -5,
    waterRes: 5,
    iceRes: -4,
    thunderRes: 4,
    dragonRes: 0,
    slots: 0,
    rarity: 5,
    skillPoints: [
      { skillId: 13, points: 1 },
      { skillId: 25, points: -3 },
      { skillId: 35, points: 5 },
      { skillId: 45, points: 2 }
    ],
    price: 13800,
    maxDefense: 28
  }),
  deepFreeze<ChestArmor>({
    id: 79,
    type: 'chest',
    name: 'Gobul Mail+',
    blade: true,
    gunner: false,
    defense: 50,
    fireRes: -2,
    waterRes: 4,
    iceRes: 0,
    thunderRes: -4,
    dragonRes: 2,
    slots: 1,
    rarity: 5,
    skillPoints: [
      { skillId: 24, points: -2 },
      { skillId: 25, points: 3 },
      { skillId: 46, points: 2 },
      { skillId: 55, points: 2 }
    ],
    price: 14800,
    maxDefense: 50
  }),
  deepFreeze<ChestArmor>({
    id: 80,
    type: 'chest',
    name: 'Gobul Vest+',
    blade: false,
    gunner: true,
    defense: 30,
    fireRes: -2,
    waterRes: 4,
    iceRes: 0,
    thunderRes: -4,
    dragonRes: 2,
    slots: 1,
    rarity: 5,
    skillPoints: [
      { skillId: 24, points: -2 },
      { skillId: 25, points: 3 },
      { skillId: 46, points: 2 },
      { skillId: 55, points: 2 }
    ],
    price: 14800,
    maxDefense: 30
  }),
  deepFreeze<ChestArmor>({
    id: 81,
    type: 'chest',
    name: 'Guild Bard Bolero+',
    blade: true,
    gunner: false,
    defense: 36,
    fireRes: 0,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 0,
    rarity: 6,
    skillPoints: [
      { skillId: 12, points: 3 },
      { skillId: 15, points: 2 },
      { skillId: 17, points: 2 },
      { skillId: 37, points: -4 }
    ],
    price: 25000,
    maxDefense: 36
  }),
  deepFreeze<ChestArmor>({
    id: 82,
    type: 'chest',
    name: 'Guild Bard Vest+',
    blade: false,
    gunner: true,
    defense: 22,
    fireRes: 0,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 0,
    rarity: 6,
    skillPoints: [
      { skillId: 12, points: 3 },
      { skillId: 15, points: 2 },
      { skillId: 17, points: 2 },
      { skillId: 37, points: -4 }
    ],
    price: 25000,
    maxDefense: 22
  }),
  deepFreeze<ChestArmor>({
    id: 83,
    type: 'chest',
    name: 'Rathian Mail+',
    blade: true,
    gunner: false,
    defense: 50,
    fireRes: 4,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 1,
    rarity: 5,
    skillPoints: [
      { skillId: 11, points: 2 },
      { skillId: 23, points: 3 },
      { skillId: 37, points: -3 },
      { skillId: 61, points: 1 }
    ],
    price: 14800,
    maxDefense: 50
  }),
  deepFreeze<ChestArmor>({
    id: 84,
    type: 'chest',
    name: 'Rathian Vest+',
    blade: false,
    gunner: true,
    defense: 30,
    fireRes: 4,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 1,
    rarity: 5,
    skillPoints: [
      { skillId: 11, points: 1 },
      { skillId: 23, points: 3 },
      { skillId: 37, points: -3 },
      { skillId: 61, points: 2 }
    ],
    price: 14800,
    maxDefense: 30
  }),
  deepFreeze<ChestArmor>({
    id: 85,
    type: 'chest',
    name: 'Gigginox Mail+',
    blade: true,
    gunner: false,
    defense: 54,
    fireRes: -4,
    waterRes: -1,
    iceRes: 2,
    thunderRes: 3,
    dragonRes: 0,
    slots: 1,
    rarity: 5,
    skillPoints: [
      { skillId: 9, points: 2 },
      { skillId: 22, points: 2 },
      { skillId: 23, points: -1 },
      { skillId: 49, points: 4 }
    ],
    price: 15800,
    maxDefense: 54
  }),
  deepFreeze<ChestArmor>({
    id: 86,
    type: 'chest',
    name: 'Gigginox Vest+',
    blade: false,
    gunner: true,
    defense: 32,
    fireRes: -4,
    waterRes: -1,
    iceRes: 2,
    thunderRes: 3,
    dragonRes: 0,
    slots: 1,
    rarity: 5,
    skillPoints: [
      { skillId: 9, points: 1 },
      { skillId: 22, points: 1 },
      { skillId: 23, points: -2 },
      { skillId: 49, points: 5 }
    ],
    price: 15800,
    maxDefense: 32
  }),
  deepFreeze<ChestArmor>({
    id: 87,
    type: 'chest',
    name: 'Ingot Mail+',
    blade: true,
    gunner: false,
    defense: 54,
    fireRes: -2,
    waterRes: -1,
    iceRes: 1,
    thunderRes: 3,
    dragonRes: 2,
    slots: 1,
    rarity: 5,
    skillPoints: [
      { skillId: 26, points: -1 },
      { skillId: 28, points: 2 },
      { skillId: 39, points: 4 },
      { skillId: 63, points: 2 }
    ],
    price: 17500,
    maxDefense: 54
  }),
  deepFreeze<ChestArmor>({
    id: 88,
    type: 'chest',
    name: 'Ingot Vest+',
    blade: false,
    gunner: true,
    defense: 32,
    fireRes: -2,
    waterRes: -1,
    iceRes: 1,
    thunderRes: 3,
    dragonRes: 2,
    slots: 1,
    rarity: 5,
    skillPoints: [
      { skillId: 3, points: 4 },
      { skillId: 28, points: 2 },
      { skillId: 29, points: -1 },
      { skillId: 63, points: 2 }
    ],
    price: 17500,
    maxDefense: 32
  }),
  deepFreeze<ChestArmor>({
    id: 89,
    type: 'chest',
    name: 'Dober Mail',
    blade: true,
    gunner: false,
    defense: 58,
    fireRes: -2,
    waterRes: -2,
    iceRes: 1,
    thunderRes: 1,
    dragonRes: 5,
    slots: 1,
    rarity: 6,
    skillPoints: [
      { skillId: 13, points: 2 },
      { skillId: 45, points: -1 },
      { skillId: 48, points: 4 },
      { skillId: 65, points: 2 }
    ],
    price: 19000,
    maxDefense: 58
  }),
  deepFreeze<ChestArmor>({
    id: 90,
    type: 'chest',
    name: 'Dober Vest',
    blade: false,
    gunner: true,
    defense: 34,
    fireRes: -2,
    waterRes: -2,
    iceRes: 1,
    thunderRes: 1,
    dragonRes: 5,
    slots: 1,
    rarity: 6,
    skillPoints: [
      { skillId: 6, points: 3 },
      { skillId: 30, points: 3 },
      { skillId: 45, points: -1 },
      { skillId: 65, points: 2 }
    ],
    price: 19000,
    maxDefense: 34
  }),
  deepFreeze<ChestArmor>({
    id: 91,
    type: 'chest',
    name: 'Lagiacrus Mail+',
    blade: true,
    gunner: false,
    defense: 58,
    fireRes: -4,
    waterRes: 2,
    iceRes: -1,
    thunderRes: 5,
    dragonRes: -2,
    slots: 3,
    rarity: 6,
    skillPoints: [
      { skillId: 9, points: -2 },
      { skillId: 10, points: 1 },
      { skillId: 20, points: 1 },
      { skillId: 50, points: 1 }
    ],
    price: 18000,
    maxDefense: 58
  }),
  deepFreeze<ChestArmor>({
    id: 92,
    type: 'chest',
    name: 'Lagiacrus Vest+',
    blade: false,
    gunner: true,
    defense: 34,
    fireRes: -4,
    waterRes: 2,
    iceRes: -1,
    thunderRes: 5,
    dragonRes: -2,
    slots: 3,
    rarity: 6,
    skillPoints: [
      { skillId: 9, points: -2 },
      { skillId: 10, points: 1 },
      { skillId: 21, points: 1 },
      { skillId: 50, points: 1 }
    ],
    price: 18000,
    maxDefense: 34
  }),
  deepFreeze<ChestArmor>({
    id: 93,
    type: 'chest',
    name: 'Rathalos Mail+',
    blade: true,
    gunner: false,
    defense: 58,
    fireRes: 4,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 1,
    rarity: 6,
    skillPoints: [
      { skillId: 2, points: 3 },
      { skillId: 25, points: 2 },
      { skillId: 36, points: -3 },
      { skillId: 66, points: 1 }
    ],
    price: 18000,
    maxDefense: 58
  }),
  deepFreeze<ChestArmor>({
    id: 94,
    type: 'chest',
    name: 'Rathalos Vest+',
    blade: false,
    gunner: true,
    defense: 34,
    fireRes: 4,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 1,
    rarity: 6,
    skillPoints: [
      { skillId: 4, points: 3 },
      { skillId: 25, points: 2 },
      { skillId: 36, points: -3 },
      { skillId: 66, points: 1 }
    ],
    price: 18000,
    maxDefense: 34
  }),
  deepFreeze<ChestArmor>({
    id: 95,
    type: 'chest',
    name: 'Barioth Mail+',
    blade: true,
    gunner: false,
    defense: 58,
    fireRes: -4,
    waterRes: 2,
    iceRes: 5,
    thunderRes: -3,
    dragonRes: 0,
    slots: 0,
    rarity: 6,
    skillPoints: [
      { skillId: 16, points: 3 },
      { skillId: 44, points: 4 },
      { skillId: 66, points: -2 },
      { skillId: 67, points: 2 }
    ],
    price: 18000,
    maxDefense: 58
  }),
  deepFreeze<ChestArmor>({
    id: 96,
    type: 'chest',
    name: 'Barioth Vest+',
    blade: false,
    gunner: true,
    defense: 34,
    fireRes: -4,
    waterRes: 2,
    iceRes: 5,
    thunderRes: -3,
    dragonRes: 0,
    slots: 0,
    rarity: 6,
    skillPoints: [
      { skillId: 16, points: 2 },
      { skillId: 44, points: 4 },
      { skillId: 66, points: -3 },
      { skillId: 67, points: 2 }
    ],
    price: 18000,
    maxDefense: 34
  }),
  deepFreeze<ChestArmor>({
    id: 97,
    type: 'chest',
    name: 'Diablos Mail+',
    blade: true,
    gunner: false,
    defense: 62,
    fireRes: 3,
    waterRes: -1,
    iceRes: -4,
    thunderRes: -1,
    dragonRes: -1,
    slots: 0,
    rarity: 6,
    skillPoints: [
      { skillId: 10, points: -4 },
      { skillId: 47, points: 4 },
      { skillId: 48, points: 3 }
    ],
    price: 18800,
    maxDefense: 62
  }),
  deepFreeze<ChestArmor>({
    id: 98,
    type: 'chest',
    name: 'Diablos Vest+',
    blade: false,
    gunner: true,
    defense: 37,
    fireRes: 3,
    waterRes: -1,
    iceRes: -4,
    thunderRes: -1,
    dragonRes: -1,
    slots: 0,
    rarity: 6,
    skillPoints: [
      { skillId: 5, points: 4 },
      { skillId: 8, points: 3 },
      { skillId: 10, points: -4 }
    ],
    price: 18800,
    maxDefense: 37
  }),
  deepFreeze<ChestArmor>({
    id: 99,
    type: 'chest',
    name: 'Uragaan Mail+',
    blade: true,
    gunner: false,
    defense: 62,
    fireRes: 4,
    waterRes: -4,
    iceRes: -1,
    thunderRes: 1,
    dragonRes: -2,
    slots: 1,
    rarity: 6,
    skillPoints: [
      { skillId: 19, points: 3 },
      { skillId: 33, points: 3 },
      { skillId: 36, points: 2 },
      { skillId: 46, points: -1 }
    ],
    price: 18800,
    maxDefense: 62
  }),
  deepFreeze<ChestArmor>({
    id: 100,
    type: 'chest',
    name: 'Uragaan Vest+',
    blade: false,
    gunner: true,
    defense: 37,
    fireRes: 4,
    waterRes: -4,
    iceRes: -1,
    thunderRes: 1,
    dragonRes: -2,
    slots: 1,
    rarity: 6,
    skillPoints: [
      { skillId: 3, points: 1 },
      { skillId: 33, points: 4 },
      { skillId: 36, points: 2 },
      { skillId: 46, points: -2 }
    ],
    price: 18800,
    maxDefense: 37
  }),
  deepFreeze<ChestArmor>({
    id: 101,
    type: 'chest',
    name: 'Agnaktor Mail+',
    blade: true,
    gunner: false,
    defense: 62,
    fireRes: 5,
    waterRes: -4,
    iceRes: -2,
    thunderRes: 1,
    dragonRes: 0,
    slots: 1,
    rarity: 6,
    skillPoints: [
      { skillId: 0, points: 2 },
      { skillId: 13, points: -1 },
      { skillId: 27, points: 5 },
      { skillId: 52, points: 1 }
    ],
    price: 19800,
    maxDefense: 62
  }),
  deepFreeze<ChestArmor>({
    id: 102,
    type: 'chest',
    name: 'Agnaktor Vest+',
    blade: false,
    gunner: true,
    defense: 37,
    fireRes: 5,
    waterRes: -4,
    iceRes: -2,
    thunderRes: 1,
    dragonRes: 0,
    slots: 1,
    rarity: 6,
    skillPoints: [
      { skillId: 4, points: 3 },
      { skillId: 7, points: 3 },
      { skillId: 13, points: -2 },
      { skillId: 52, points: 1 }
    ],
    price: 19800,
    maxDefense: 37
  }),
  deepFreeze<ChestArmor>({
    id: 103,
    type: 'chest',
    name: 'Vangis Mail',
    blade: true,
    gunner: false,
    defense: 64,
    fireRes: 0,
    waterRes: 0,
    iceRes: 3,
    thunderRes: -4,
    dragonRes: -4,
    slots: 0,
    rarity: 7,
    skillPoints: [
      { skillId: 1, points: 3 },
      { skillId: 34, points: -2 },
      { skillId: 35, points: 3 },
      { skillId: 42, points: 3 }
    ],
    price: 41500,
    maxDefense: 64
  }),
  deepFreeze<ChestArmor>({
    id: 104,
    type: 'chest',
    name: 'Vangis Vest',
    blade: false,
    gunner: true,
    defense: 38,
    fireRes: 0,
    waterRes: 0,
    iceRes: 3,
    thunderRes: -4,
    dragonRes: -4,
    slots: 0,
    rarity: 7,
    skillPoints: [
      { skillId: 14, points: 3 },
      { skillId: 34, points: -2 },
      { skillId: 35, points: 3 },
      { skillId: 42, points: 3 }
    ],
    price: 41500,
    maxDefense: 38
  }),
  deepFreeze<ChestArmor>({
    id: 105,
    type: 'chest',
    name: 'Damascus Mail',
    blade: true,
    gunner: false,
    defense: 62,
    fireRes: -2,
    waterRes: 0,
    iceRes: 2,
    thunderRes: -2,
    dragonRes: 3,
    slots: 3,
    rarity: 6,
    skillPoints: [
      { skillId: 13, points: -2 },
      { skillId: 19, points: 1 },
      { skillId: 23, points: 1 },
      { skillId: 28, points: 1 }
    ],
    price: 32300,
    maxDefense: 62
  }),
  deepFreeze<ChestArmor>({
    id: 106,
    type: 'chest',
    name: 'Damascus Vest',
    blade: false,
    gunner: true,
    defense: 37,
    fireRes: -2,
    waterRes: 0,
    iceRes: 2,
    thunderRes: -2,
    dragonRes: 3,
    slots: 3,
    rarity: 6,
    skillPoints: [
      { skillId: 13, points: -2 },
      { skillId: 23, points: 1 },
      { skillId: 28, points: 1 },
      { skillId: 29, points: 1 }
    ],
    price: 32300,
    maxDefense: 37
  }),
  deepFreeze<ChestArmor>({
    id: 107,
    type: 'chest',
    name: 'Helios Mail+',
    blade: true,
    gunner: false,
    defense: 66,
    fireRes: 0,
    waterRes: 5,
    iceRes: 3,
    thunderRes: -3,
    dragonRes: -4,
    slots: 0,
    rarity: 6,
    skillPoints: [
      { skillId: 0, points: -2 },
      { skillId: 1, points: 5 },
      { skillId: 11, points: 3 },
      { skillId: 37, points: -1 }
    ],
    price: 26200,
    maxDefense: 66
  }),
  deepFreeze<ChestArmor>({
    id: 108,
    type: 'chest',
    name: 'Helios Vest+',
    blade: false,
    gunner: true,
    defense: 39,
    fireRes: 0,
    waterRes: 5,
    iceRes: 3,
    thunderRes: -3,
    dragonRes: -4,
    slots: 0,
    rarity: 6,
    skillPoints: [
      { skillId: 3, points: -2 },
      { skillId: 11, points: 3 },
      { skillId: 14, points: 5 },
      { skillId: 37, points: -1 }
    ],
    price: 26200,
    maxDefense: 39
  }),
  deepFreeze<ChestArmor>({
    id: 109,
    type: 'chest',
    name: 'Yamato Muneate+',
    blade: true,
    gunner: false,
    defense: 66,
    fireRes: 4,
    waterRes: 0,
    iceRes: -3,
    thunderRes: 0,
    dragonRes: -4,
    slots: 1,
    rarity: 6,
    skillPoints: [
      { skillId: 0, points: 1 },
      { skillId: 18, points: 2 },
      { skillId: 24, points: 4 },
      { skillId: 71, points: -2 }
    ],
    price: 27500,
    maxDefense: 66
  }),
  deepFreeze<ChestArmor>({
    id: 110,
    type: 'chest',
    name: 'Mutsu Muneate+',
    blade: false,
    gunner: true,
    defense: 39,
    fireRes: 4,
    waterRes: 0,
    iceRes: -3,
    thunderRes: 0,
    dragonRes: -4,
    slots: 1,
    rarity: 6,
    skillPoints: [
      { skillId: 3, points: 2 },
      { skillId: 24, points: 2 },
      { skillId: 32, points: 4 },
      { skillId: 71, points: -1 }
    ],
    price: 27500,
    maxDefense: 39
  }),
  deepFreeze<ChestArmor>({
    id: 111,
    type: 'chest',
    name: 'Escadora Soul',
    blade: true,
    gunner: false,
    defense: 70,
    fireRes: -1,
    waterRes: -1,
    iceRes: -1,
    thunderRes: 0,
    dragonRes: -5,
    slots: 2,
    rarity: 7,
    skillPoints: [
      { skillId: 16, points: 2 },
      { skillId: 20, points: 2 },
      { skillId: 43, points: -1 },
      { skillId: 81, points: 2 }
    ],
    price: 66666,
    maxDefense: 70
  }),
  deepFreeze<ChestArmor>({
    id: 112,
    type: 'chest',
    name: 'Escadora Seele',
    blade: false,
    gunner: true,
    defense: 42,
    fireRes: -1,
    waterRes: -1,
    iceRes: -1,
    thunderRes: 0,
    dragonRes: -5,
    slots: 2,
    rarity: 7,
    skillPoints: [
      { skillId: 16, points: 2 },
      { skillId: 21, points: 2 },
      { skillId: 43, points: -1 },
      { skillId: 81, points: 2 }
    ],
    price: 66666,
    maxDefense: 42
  }),
  deepFreeze<ChestArmor>({
    id: 113,
    type: 'chest',
    name: 'Chakra Necklace',
    blade: true,
    gunner: true,
    defense: 18,
    fireRes: 0,
    waterRes: 10,
    iceRes: 0,
    thunderRes: -10,
    dragonRes: 0,
    slots: 3,
    rarity: 7,
    skillPoints: [],
    price: 33333,
    maxDefense: 18
  }),
  deepFreeze<ChestArmor>({
    id: 114,
    type: 'chest',
    name: 'HellHunter Jacket',
    blade: true,
    gunner: false,
    defense: 15,
    fireRes: 2,
    waterRes: 2,
    iceRes: 2,
    thunderRes: 2,
    dragonRes: 2,
    slots: 3,
    rarity: 3,
    skillPoints: [{ skillId: 80, points: 5 }],
    price: 10000,
    maxDefense: 15,
    maxLowRankDefense: 27
  }),
  deepFreeze<ChestArmor>({
    id: 115,
    type: 'chest',
    name: 'HellHunter Leather',
    blade: false,
    gunner: true,
    defense: 8,
    fireRes: 2,
    waterRes: 2,
    iceRes: 2,
    thunderRes: 2,
    dragonRes: 2,
    slots: 3,
    rarity: 3,
    skillPoints: [{ skillId: 80, points: 5 }],
    price: 10000,
    maxDefense: 8,
    maxLowRankDefense: 14
  }),
  deepFreeze<ChestArmor>({
    id: 116,
    type: 'chest',
    name: 'SoulHunter Jacket',
    blade: true,
    gunner: false,
    defense: 48,
    fireRes: 2,
    waterRes: 2,
    iceRes: 2,
    thunderRes: 2,
    dragonRes: 2,
    slots: 0,
    rarity: 6,
    skillPoints: [{ skillId: 80, points: 10 }],
    price: 15000,
    maxDefense: 48
  }),
  deepFreeze<ChestArmor>({
    id: 117,
    type: 'chest',
    name: 'SoulHunter Leather',
    blade: false,
    gunner: true,
    defense: 28,
    fireRes: 2,
    waterRes: 2,
    iceRes: 2,
    thunderRes: 2,
    dragonRes: 2,
    slots: 0,
    rarity: 6,
    skillPoints: [{ skillId: 80, points: 10 }],
    price: 15000,
    maxDefense: 28
  })
];
