import { deepFreeze } from '../../utils';
import type { ChestArmor } from './types';

export const ChestArmors: ChestArmor[] = [
  deepFreeze<ChestArmor>({
    id: 0,
    type: 'chest',
    name: 'Leather Vest',
    blade: true,
    gunner: true,
    defense: 1,
    fireRes: -1,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 3,
    dragonRes: 2,
    slots: 1,
    rarity: 1,
    price: 150,
    maxDefense: 1,
    maxLowRankDefense: 9,
    skillPoints: { gathering: 2, spd_gather: 3, whim: 2 }
  }),
  deepFreeze<ChestArmor>({
    id: 1,
    type: 'chest',
    name: 'Chainmail Vest',
    blade: true,
    gunner: true,
    defense: 2,
    fireRes: -1,
    waterRes: -1,
    iceRes: 3,
    thunderRes: -1,
    dragonRes: 1,
    slots: 0,
    rarity: 1,
    price: 200,
    maxDefense: 2,
    maxLowRankDefense: 9,
    skillPoints: {
      health: 3,
      fishing: 1,
      combo_rate: 4,
      combo_plus: 1
    }
  }),
  deepFreeze<ChestArmor>({
    id: 2,
    type: 'chest',
    name: 'Loc Lac Shawl',
    blade: true,
    gunner: true,
    defense: 4,
    fireRes: 4,
    waterRes: -3,
    iceRes: -4,
    thunderRes: 2,
    dragonRes: 0,
    slots: 0,
    rarity: 1,
    price: 500,
    maxDefense: 4,
    maxLowRankDefense: 11,
    skillPoints: { rec_speed: 2, transportr: 2, heat_res: 5 }
  }),
  deepFreeze<ChestArmor>({
    id: 3,
    type: 'chest',
    name: "Hunter's Mail",
    blade: true,
    gunner: false,
    defense: 6,
    fireRes: -1,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: -1,
    slots: 1,
    rarity: 1,
    price: 500,
    maxDefense: 6,
    maxLowRankDefense: 20,
    skillPoints: {
      attack: 1,
      psychic: 3,
      water_res: -1,
      map: 1,
      bbq: 1
    }
  }),
  deepFreeze<ChestArmor>({
    id: 4,
    type: 'chest',
    name: "Hunter's Vest",
    blade: false,
    gunner: true,
    defense: 3,
    fireRes: -1,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: -1,
    slots: 1,
    rarity: 1,
    price: 500,
    maxDefense: 3,
    maxLowRankDefense: 10,
    skillPoints: {
      attack: 1,
      psychic: 3,
      water_res: -1,
      map: 1,
      bbq: 1
    }
  }),
  deepFreeze<ChestArmor>({
    id: 5,
    type: 'chest',
    name: 'Bone Mail',
    blade: true,
    gunner: false,
    defense: 8,
    fireRes: 2,
    waterRes: -2,
    iceRes: -1,
    thunderRes: 2,
    dragonRes: 3,
    slots: 1,
    rarity: 1,
    price: 750,
    maxDefense: 8,
    maxLowRankDefense: 22,
    skillPoints: {
      hunger: 4,
      sleep: -1,
      lastingpwr: 1,
      perception: 1
    }
  }),
  deepFreeze<ChestArmor>({
    id: 6,
    type: 'chest',
    name: 'Bone Vest',
    blade: false,
    gunner: true,
    defense: 4,
    fireRes: 2,
    waterRes: -2,
    iceRes: -1,
    thunderRes: 2,
    dragonRes: 3,
    slots: 1,
    rarity: 1,
    price: 750,
    maxDefense: 4,
    maxLowRankDefense: 11,
    skillPoints: {
      hunger: 3,
      sleep: -2,
      lastingpwr: 1,
      perception: 1
    }
  }),
  deepFreeze<ChestArmor>({
    id: 7,
    type: 'chest',
    name: 'Alloy Mail',
    blade: true,
    gunner: false,
    defense: 8,
    fireRes: 1,
    waterRes: 1,
    iceRes: -1,
    thunderRes: -2,
    dragonRes: -1,
    slots: 1,
    rarity: 1,
    price: 1000,
    maxDefense: 8,
    maxLowRankDefense: 22,
    skillPoints: {
      expert: 3,
      sharpener: 2,
      speedsetup: 1,
      oxygen: -1
    }
  }),
  deepFreeze<ChestArmor>({
    id: 8,
    type: 'chest',
    name: 'Alloy Vest',
    blade: false,
    gunner: true,
    defense: 4,
    fireRes: 1,
    waterRes: 1,
    iceRes: -1,
    thunderRes: -2,
    dragonRes: -1,
    slots: 1,
    rarity: 1,
    price: 1000,
    maxDefense: 4,
    maxLowRankDefense: 11,
    skillPoints: {
      'normal_s+': 2,
      expert: 3,
      speedsetup: 1,
      oxygen: -1
    }
  }),
  deepFreeze<ChestArmor>({
    id: 9,
    type: 'chest',
    name: 'Jaggi Mail',
    blade: true,
    gunner: false,
    defense: 10,
    fireRes: -3,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    price: 1200,
    maxDefense: 10,
    maxLowRankDefense: 24,
    skillPoints: { attack: 2, stun: 1, gluttony: 1, cold_res: -3 }
  }),
  deepFreeze<ChestArmor>({
    id: 10,
    type: 'chest',
    name: 'Jaggi Vest',
    blade: false,
    gunner: true,
    defense: 5,
    fireRes: -3,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    price: 1200,
    maxDefense: 5,
    maxLowRankDefense: 12,
    skillPoints: { attack: 2, stun: 2, gluttony: 1, cold_res: -2 }
  }),
  deepFreeze<ChestArmor>({
    id: 11,
    type: 'chest',
    name: 'Bnahabra Suit',
    blade: true,
    gunner: false,
    defense: 10,
    fireRes: -4,
    waterRes: -1,
    iceRes: -1,
    thunderRes: 2,
    dragonRes: 5,
    slots: 0,
    rarity: 2,
    price: 1800,
    maxDefense: 10,
    maxLowRankDefense: 24,
    skillPoints: { sharpness: 3, status: 4, poison: -2 }
  }),
  deepFreeze<ChestArmor>({
    id: 12,
    type: 'chest',
    name: 'Bnahabra Vest',
    blade: false,
    gunner: true,
    defense: 5,
    fireRes: -4,
    waterRes: -1,
    iceRes: -1,
    thunderRes: 2,
    dragonRes: 5,
    slots: 0,
    rarity: 2,
    price: 1800,
    maxDefense: 5,
    maxLowRankDefense: 12,
    skillPoints: { status: 4, poison: -2, reload_spd: 3 }
  }),
  deepFreeze<ChestArmor>({
    id: 13,
    type: 'chest',
    name: 'Rhenoplos Mail',
    blade: true,
    gunner: false,
    defense: 12,
    fireRes: 2,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: 2,
    slots: 1,
    rarity: 2,
    price: 1400,
    maxDefense: 12,
    maxLowRankDefense: 24,
    skillPoints: {
      attack: 1,
      wind_res: 2,
      eating: 2,
      'mud/snow': 1,
      thunderres: -1
    }
  }),
  deepFreeze<ChestArmor>({
    id: 14,
    type: 'chest',
    name: 'Rhenoplos Vest',
    blade: false,
    gunner: true,
    defense: 6,
    fireRes: 2,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: 2,
    slots: 1,
    rarity: 2,
    price: 1400,
    maxDefense: 6,
    maxLowRankDefense: 12,
    skillPoints: {
      recoil: 2,
      'crag_s+': 1,
      attack: 1,
      eating: 2,
      thunderres: -1
    }
  }),
  deepFreeze<ChestArmor>({
    id: 15,
    type: 'chest',
    name: 'Qurupeco Mail',
    blade: true,
    gunner: false,
    defense: 12,
    fireRes: 2,
    waterRes: -2,
    iceRes: -3,
    thunderRes: 0,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    price: 1700,
    maxDefense: 12,
    maxLowRankDefense: 24,
    skillPoints: {
      defense: 2,
      rec_level: 2,
      evasion: 2,
      ice_res: -1
    }
  }),
  deepFreeze<ChestArmor>({
    id: 16,
    type: 'chest',
    name: 'Qurupeco Vest',
    blade: false,
    gunner: true,
    defense: 6,
    fireRes: 2,
    waterRes: -2,
    iceRes: -3,
    thunderRes: 0,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    price: 1700,
    maxDefense: 6,
    maxLowRankDefense: 12,
    skillPoints: {
      defense: 1,
      rec_level: 2,
      evasion: 2,
      ice_res: -2
    }
  }),
  deepFreeze<ChestArmor>({
    id: 17,
    type: 'chest',
    name: 'Ludroth Mail',
    blade: true,
    gunner: false,
    defense: 13,
    fireRes: -3,
    waterRes: 2,
    iceRes: 0,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    price: 2200,
    maxDefense: 13,
    maxLowRankDefense: 25,
    skillPoints: {
      attack: 2,
      protection: 2,
      constitutn: 1,
      fire_res: -1,
      currentres: 1
    }
  }),
  deepFreeze<ChestArmor>({
    id: 18,
    type: 'chest',
    name: 'Ludroth Vest',
    blade: false,
    gunner: true,
    defense: 7,
    fireRes: -3,
    waterRes: 2,
    iceRes: 0,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    price: 2200,
    maxDefense: 7,
    maxLowRankDefense: 13,
    skillPoints: {
      'pellet_s+': 1,
      attack: 2,
      protection: 2,
      constitutn: 1,
      fire_res: -1
    }
  }),
  deepFreeze<ChestArmor>({
    id: 19,
    type: 'chest',
    name: 'Steel Mail',
    blade: true,
    gunner: false,
    defense: 12,
    fireRes: -1,
    waterRes: 1,
    iceRes: 1,
    thunderRes: -1,
    dragonRes: 0,
    slots: 0,
    rarity: 2,
    price: 2000,
    maxDefense: 12,
    maxLowRankDefense: 24,
    skillPoints: { sharpener: 3, guard: 4, swimming: -3 }
  }),
  deepFreeze<ChestArmor>({
    id: 20,
    type: 'chest',
    name: 'Baggi Mail',
    blade: true,
    gunner: false,
    defense: 13,
    fireRes: -3,
    waterRes: -1,
    iceRes: 3,
    thunderRes: -1,
    dragonRes: 1,
    slots: 2,
    rarity: 2,
    price: 2400,
    maxDefense: 13,
    maxLowRankDefense: 25,
    skillPoints: {
      tranquilzr: 1,
      fastcharge: 1,
      attack: 1,
      stun: -1,
      ice_res: 1
    }
  }),
  deepFreeze<ChestArmor>({
    id: 21,
    type: 'chest',
    name: 'Baggi Vest',
    blade: false,
    gunner: true,
    defense: 7,
    fireRes: -3,
    waterRes: -1,
    iceRes: 3,
    thunderRes: -1,
    dragonRes: 1,
    slots: 2,
    rarity: 2,
    price: 2400,
    maxDefense: 7,
    maxLowRankDefense: 13,
    skillPoints: {
      pellets_up: 1,
      tranquilzr: 1,
      attack: 1,
      stun: -1,
      ice_res: 1
    }
  }),
  deepFreeze<ChestArmor>({
    id: 22,
    type: 'chest',
    name: 'Barroth Mail',
    blade: true,
    gunner: false,
    defense: 15,
    fireRes: -4,
    waterRes: 4,
    iceRes: -3,
    thunderRes: 3,
    dragonRes: 0,
    slots: 0,
    rarity: 2,
    price: 3200,
    maxDefense: 15,
    maxLowRankDefense: 27,
    skillPoints: { stamina: 1, expert: -3, attack: 3, potential: 2 }
  }),
  deepFreeze<ChestArmor>({
    id: 23,
    type: 'chest',
    name: 'Barroth Vest',
    blade: false,
    gunner: true,
    defense: 8,
    fireRes: -4,
    waterRes: 4,
    iceRes: -3,
    thunderRes: 3,
    dragonRes: 0,
    slots: 0,
    rarity: 2,
    price: 3200,
    maxDefense: 8,
    maxLowRankDefense: 14,
    skillPoints: { stamina: 1, expert: -3, attack: 3, potential: 2 }
  }),
  deepFreeze<ChestArmor>({
    id: 24,
    type: 'chest',
    name: 'Gobul Mail',
    blade: true,
    gunner: false,
    defense: 16,
    fireRes: -2,
    waterRes: 3,
    iceRes: 0,
    thunderRes: -3,
    dragonRes: 2,
    slots: 0,
    rarity: 2,
    price: 3600,
    maxDefense: 16,
    maxLowRankDefense: 28,
    skillPoints: {
      rec_speed: -1,
      attack: 1,
      eating: 2,
      stun: 2,
      water_res: 3
    }
  }),
  deepFreeze<ChestArmor>({
    id: 25,
    type: 'chest',
    name: 'Gobul Vest',
    blade: false,
    gunner: true,
    defense: 8,
    fireRes: -2,
    waterRes: 3,
    iceRes: 0,
    thunderRes: -3,
    dragonRes: 2,
    slots: 0,
    rarity: 2,
    price: 3600,
    maxDefense: 8,
    maxLowRankDefense: 14,
    skillPoints: {
      rec_speed: -2,
      attack: 1,
      eating: 2,
      stun: 1,
      water_res: 3
    }
  }),
  deepFreeze<ChestArmor>({
    id: 26,
    type: 'chest',
    name: "Ranger's Girdle",
    blade: true,
    gunner: false,
    defense: 15,
    fireRes: 0,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 0,
    rarity: 3,
    price: 10000,
    maxDefense: 15,
    maxLowRankDefense: 27,
    skillPoints: {
      fate: -3,
      carving: 1,
      'wide-range': 2,
      spd_gather: 4
    }
  }),
  deepFreeze<ChestArmor>({
    id: 27,
    type: 'chest',
    name: "Archer's Girdle",
    blade: false,
    gunner: true,
    defense: 8,
    fireRes: 0,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 0,
    rarity: 3,
    price: 10000,
    maxDefense: 8,
    maxLowRankDefense: 14,
    skillPoints: {
      fate: -3,
      carving: 1,
      'wide-range': 2,
      spd_gather: 4
    }
  }),
  deepFreeze<ChestArmor>({
    id: 28,
    type: 'chest',
    name: 'Guild Bard Bolero',
    blade: true,
    gunner: false,
    defense: 15,
    fireRes: 0,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 0,
    rarity: 3,
    price: 10000,
    maxDefense: 15,
    maxLowRankDefense: 27,
    skillPoints: { fate: 1, psychic: 2, evasion: 3, sense: -3 }
  }),
  deepFreeze<ChestArmor>({
    id: 29,
    type: 'chest',
    name: 'Guild Bard Vest',
    blade: false,
    gunner: true,
    defense: 8,
    fireRes: 0,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 0,
    rarity: 3,
    price: 10000,
    maxDefense: 8,
    maxLowRankDefense: 14,
    skillPoints: { fate: 2, psychic: 2, evasion: 3, sense: -2 }
  }),
  deepFreeze<ChestArmor>({
    id: 30,
    type: 'chest',
    name: 'Rathian Mail',
    blade: true,
    gunner: false,
    defense: 16,
    fireRes: 3,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 1,
    rarity: 2,
    price: 3600,
    maxDefense: 16,
    maxLowRankDefense: 28,
    skillPoints: {
      hearing: 1,
      health: 2,
      protection: -2,
      fire_res: 2
    }
  }),
  deepFreeze<ChestArmor>({
    id: 31,
    type: 'chest',
    name: 'Rathian Vest',
    blade: false,
    gunner: true,
    defense: 8,
    fireRes: 3,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 1,
    rarity: 2,
    price: 3600,
    maxDefense: 8,
    maxLowRankDefense: 14,
    skillPoints: {
      hearing: 1,
      health: 2,
      protection: -2,
      fire_res: 2
    }
  }),
  deepFreeze<ChestArmor>({
    id: 32,
    type: 'chest',
    name: 'Gigginox Mail',
    blade: true,
    gunner: false,
    defense: 18,
    fireRes: -4,
    waterRes: 0,
    iceRes: 2,
    thunderRes: 2,
    dragonRes: -1,
    slots: 0,
    rarity: 2,
    price: 4100,
    maxDefense: 18,
    maxLowRankDefense: 30,
    skillPoints: { status: 1, poison: 2, health: -2, constitutn: 4 }
  }),
  deepFreeze<ChestArmor>({
    id: 33,
    type: 'chest',
    name: 'Gigginox Vest',
    blade: false,
    gunner: true,
    defense: 9,
    fireRes: -4,
    waterRes: 0,
    iceRes: 2,
    thunderRes: 2,
    dragonRes: -1,
    slots: 0,
    rarity: 2,
    price: 4100,
    maxDefense: 9,
    maxLowRankDefense: 15,
    skillPoints: { status: 1, poison: 3, health: -2, constitutn: 3 }
  }),
  deepFreeze<ChestArmor>({
    id: 34,
    type: 'chest',
    name: 'Ingot Mail',
    blade: true,
    gunner: false,
    defense: 18,
    fireRes: -2,
    waterRes: -1,
    iceRes: 1,
    thunderRes: 3,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    price: 5000,
    maxDefense: 18,
    maxLowRankDefense: 28,
    skillPoints: {
      sharpener: -2,
      guard_up: 1,
      wind_res: 3,
      thunderres: 1
    }
  }),
  deepFreeze<ChestArmor>({
    id: 35,
    type: 'chest',
    name: 'Ingot Vest',
    blade: false,
    gunner: true,
    defense: 9,
    fireRes: -2,
    waterRes: -1,
    iceRes: 1,
    thunderRes: 3,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    price: 5000,
    maxDefense: 9,
    maxLowRankDefense: 14,
    skillPoints: {
      recoil: 3,
      guard_up: 1,
      reload_spd: -2,
      thunderres: 1
    }
  }),
  deepFreeze<ChestArmor>({
    id: 36,
    type: 'chest',
    name: 'Lagiacrus Mail',
    blade: true,
    gunner: false,
    defense: 20,
    fireRes: -3,
    waterRes: 2,
    iceRes: -1,
    thunderRes: 4,
    dragonRes: -2,
    slots: 1,
    rarity: 3,
    price: 5600,
    maxDefense: 20,
    maxLowRankDefense: 30,
    skillPoints: {
      sharpness: 1,
      status: -3,
      elemental: 3,
      swimming: 1
    }
  }),
  deepFreeze<ChestArmor>({
    id: 37,
    type: 'chest',
    name: 'Lagiacrus Vest',
    blade: false,
    gunner: true,
    defense: 10,
    fireRes: -3,
    waterRes: 2,
    iceRes: -1,
    thunderRes: 4,
    dragonRes: -2,
    slots: 1,
    rarity: 3,
    price: 5600,
    maxDefense: 10,
    maxLowRankDefense: 15,
    skillPoints: {
      normals_up: 1,
      status: -3,
      elemental: 3,
      swimming: 1
    }
  }),
  deepFreeze<ChestArmor>({
    id: 38,
    type: 'chest',
    name: 'Rathalos Mail',
    blade: true,
    gunner: false,
    defense: 20,
    fireRes: 3,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 1,
    rarity: 3,
    price: 5600,
    maxDefense: 20,
    maxLowRankDefense: 30,
    skillPoints: { expert: 1, attack: 2, defense: -2, heat_res: 2 }
  }),
  deepFreeze<ChestArmor>({
    id: 39,
    type: 'chest',
    name: 'Rathalos Vest',
    blade: false,
    gunner: true,
    defense: 10,
    fireRes: 3,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 1,
    rarity: 3,
    price: 5600,
    maxDefense: 10,
    maxLowRankDefense: 15,
    skillPoints: { expert: 1, attack: 2, defense: -2, heat_res: 2 }
  }),
  deepFreeze<ChestArmor>({
    id: 40,
    type: 'chest',
    name: 'Barioth Mail',
    blade: true,
    gunner: false,
    defense: 20,
    fireRes: -4,
    waterRes: 2,
    iceRes: 4,
    thunderRes: -3,
    dragonRes: 0,
    slots: 1,
    rarity: 3,
    price: 5600,
    maxDefense: 20,
    maxLowRankDefense: 30,
    skillPoints: {
      stamina: 2,
      evasion: 2,
      heat_res: -2,
      cold_res: 1
    }
  }),
  deepFreeze<ChestArmor>({
    id: 41,
    type: 'chest',
    name: 'Barioth Vest',
    blade: false,
    gunner: true,
    defense: 10,
    fireRes: -4,
    waterRes: 2,
    iceRes: 4,
    thunderRes: -3,
    dragonRes: 0,
    slots: 1,
    rarity: 3,
    price: 5600,
    maxDefense: 10,
    maxLowRankDefense: 15,
    skillPoints: {
      stamina: 2,
      evasion: 2,
      heat_res: -2,
      cold_res: 1
    }
  }),
  deepFreeze<ChestArmor>({
    id: 42,
    type: 'chest',
    name: 'Diablos Mail',
    blade: true,
    gunner: false,
    defense: 22,
    fireRes: 2,
    waterRes: -1,
    iceRes: -3,
    thunderRes: -1,
    dragonRes: -1,
    slots: 0,
    rarity: 3,
    price: 6300,
    maxDefense: 22,
    maxLowRankDefense: 30,
    skillPoints: { elemental: -4, tremor_res: 3, crit_draw: 3 }
  }),
  deepFreeze<ChestArmor>({
    id: 43,
    type: 'chest',
    name: 'Diablos Vest',
    blade: false,
    gunner: true,
    defense: 11,
    fireRes: 2,
    waterRes: -1,
    iceRes: -3,
    thunderRes: -1,
    dragonRes: -1,
    slots: 0,
    rarity: 3,
    price: 6300,
    maxDefense: 11,
    maxLowRankDefense: 15,
    skillPoints: { pierces_up: 3, 'pierce_s+': 3, elemental: -4 }
  }),
  deepFreeze<ChestArmor>({
    id: 44,
    type: 'chest',
    name: 'Uragaan Mail',
    blade: true,
    gunner: false,
    defense: 22,
    fireRes: 3,
    waterRes: -4,
    iceRes: -1,
    thunderRes: 1,
    dragonRes: -2,
    slots: 0,
    rarity: 3,
    price: 6300,
    maxDefense: 22,
    maxLowRankDefense: 30,
    skillPoints: {
      punishdraw: 3,
      bomb_boost: 2,
      defense: 3,
      eating: -1
    }
  }),
  deepFreeze<ChestArmor>({
    id: 45,
    type: 'chest',
    name: 'Uragaan Vest',
    blade: false,
    gunner: true,
    defense: 11,
    fireRes: 3,
    waterRes: -4,
    iceRes: -1,
    thunderRes: 1,
    dragonRes: -2,
    slots: 0,
    rarity: 3,
    price: 6300,
    maxDefense: 11,
    maxLowRankDefense: 15,
    skillPoints: {
      recoil: 4,
      bomb_boost: 2,
      defense: 2,
      eating: -1
    }
  }),
  deepFreeze<ChestArmor>({
    id: 46,
    type: 'chest',
    name: 'Agnaktor Mail',
    blade: true,
    gunner: false,
    defense: 22,
    fireRes: 4,
    waterRes: -4,
    iceRes: -2,
    thunderRes: 1,
    dragonRes: 0,
    slots: 1,
    rarity: 3,
    price: 7200,
    maxDefense: 22,
    maxLowRankDefense: 30,
    skillPoints: {
      stamina: -2,
      guard: 3,
      guard_up: 1,
      flame_aura: 1
    }
  }),
  deepFreeze<ChestArmor>({
    id: 47,
    type: 'chest',
    name: 'Agnaktor Vest',
    blade: false,
    gunner: true,
    defense: 11,
    fireRes: 4,
    waterRes: -4,
    iceRes: -2,
    thunderRes: 1,
    dragonRes: 0,
    slots: 1,
    rarity: 3,
    price: 7200,
    maxDefense: 11,
    maxLowRankDefense: 15,
    skillPoints: {
      stamina: -2,
      guard_up: 1,
      reload_spd: 3,
      flame_aura: 1
    }
  }),
  deepFreeze<ChestArmor>({
    id: 48,
    type: 'chest',
    name: 'Helios Mail',
    blade: true,
    gunner: false,
    defense: 24,
    fireRes: 0,
    waterRes: 4,
    iceRes: 3,
    thunderRes: -3,
    dragonRes: -4,
    slots: 0,
    rarity: 3,
    price: 11000,
    maxDefense: 24,
    maxLowRankDefense: 32,
    skillPoints: {
      sharpness: -2,
      handicraft: 2,
      hearing: 2,
      protection: -2
    }
  }),
  deepFreeze<ChestArmor>({
    id: 49,
    type: 'chest',
    name: 'Helios Vest',
    blade: false,
    gunner: true,
    defense: 12,
    fireRes: 0,
    waterRes: 4,
    iceRes: 3,
    thunderRes: -3,
    dragonRes: -4,
    slots: 0,
    rarity: 3,
    price: 11000,
    maxDefense: 12,
    maxLowRankDefense: 16,
    skillPoints: {
      recoil: -3,
      hearing: 2,
      loading: 2,
      protection: -2
    }
  }),
  deepFreeze<ChestArmor>({
    id: 50,
    type: 'chest',
    name: 'Yamato Muneate',
    blade: true,
    gunner: false,
    defense: 24,
    fireRes: 3,
    waterRes: 0,
    iceRes: -3,
    thunderRes: 0,
    dragonRes: -3,
    slots: 1,
    rarity: 3,
    price: 12000,
    maxDefense: 24,
    maxLowRankDefense: 32,
    skillPoints: {
      sharpness: 1,
      fastcharge: 2,
      rec_speed: 3,
      combo_rate: -1
    }
  }),
  deepFreeze<ChestArmor>({
    id: 51,
    type: 'chest',
    name: 'Mutsu Muneate',
    blade: false,
    gunner: true,
    defense: 12,
    fireRes: 3,
    waterRes: 0,
    iceRes: -3,
    thunderRes: 0,
    dragonRes: -3,
    slots: 1,
    rarity: 3,
    price: 12000,
    maxDefense: 12,
    maxLowRankDefense: 16,
    skillPoints: {
      recoil: 1,
      rec_speed: 3,
      'clust_s+': 1,
      combo_rate: -2
    }
  }),
  deepFreeze<ChestArmor>({
    id: 52,
    type: 'chest',
    name: 'Leather Mail+',
    blade: true,
    gunner: false,
    defense: 26,
    fireRes: -2,
    waterRes: 0,
    iceRes: -2,
    thunderRes: 3,
    dragonRes: 2,
    slots: 1,
    rarity: 4,
    price: 4600,
    maxDefense: 26,
    skillPoints: { gathering: 5, spd_gather: 1, whim: 2 }
  }),
  deepFreeze<ChestArmor>({
    id: 53,
    type: 'chest',
    name: 'Leather Vest+',
    blade: false,
    gunner: true,
    defense: 15,
    fireRes: -2,
    waterRes: 0,
    iceRes: -2,
    thunderRes: 3,
    dragonRes: 2,
    slots: 1,
    rarity: 4,
    price: 4600,
    maxDefense: 15,
    skillPoints: { gathering: 5, spd_gather: 2, whim: 1 }
  }),
  deepFreeze<ChestArmor>({
    id: 54,
    type: 'chest',
    name: 'Chainmail Armor+',
    blade: true,
    gunner: false,
    defense: 30,
    fireRes: -1,
    waterRes: -2,
    iceRes: 4,
    thunderRes: -1,
    dragonRes: 1,
    slots: 2,
    rarity: 4,
    price: 5400,
    maxDefense: 30,
    skillPoints: { health: 5, combo_rate: 1, combo_plus: 1 }
  }),
  deepFreeze<ChestArmor>({
    id: 55,
    type: 'chest',
    name: 'Chainmail Vest+',
    blade: false,
    gunner: true,
    defense: 18,
    fireRes: -1,
    waterRes: -2,
    iceRes: 4,
    thunderRes: -1,
    dragonRes: 1,
    slots: 2,
    rarity: 4,
    price: 5400,
    maxDefense: 18,
    skillPoints: { health: 2, combo_rate: 4, combo_plus: 1 }
  }),
  deepFreeze<ChestArmor>({
    id: 56,
    type: 'chest',
    name: 'Loc Lac Shawl+',
    blade: true,
    gunner: false,
    defense: 30,
    fireRes: 5,
    waterRes: -4,
    iceRes: -5,
    thunderRes: 2,
    dragonRes: 0,
    slots: 0,
    rarity: 4,
    price: 5400,
    maxDefense: 30,
    skillPoints: { rec_speed: 2, transportr: 3, heat_res: 6 }
  }),
  deepFreeze<ChestArmor>({
    id: 57,
    type: 'chest',
    name: 'Loc Lac Vest+',
    blade: false,
    gunner: true,
    defense: 18,
    fireRes: 5,
    waterRes: -4,
    iceRes: -5,
    thunderRes: 2,
    dragonRes: 0,
    slots: 0,
    rarity: 4,
    price: 5400,
    maxDefense: 18,
    skillPoints: { rec_speed: 2, transportr: 3, heat_res: 6 }
  }),
  deepFreeze<ChestArmor>({
    id: 58,
    type: 'chest',
    name: "Hunter's Mail+",
    blade: true,
    gunner: false,
    defense: 30,
    fireRes: 0,
    waterRes: -2,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 1,
    rarity: 4,
    price: 5400,
    maxDefense: 30,
    skillPoints: {
      expert: 1,
      psychic: 5,
      evasion: 1,
      water_res: -1,
      map: 1
    }
  }),
  deepFreeze<ChestArmor>({
    id: 59,
    type: 'chest',
    name: "Hunter's Vest+",
    blade: false,
    gunner: true,
    defense: 18,
    fireRes: 0,
    waterRes: -2,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 1,
    rarity: 4,
    price: 5400,
    maxDefense: 18,
    skillPoints: {
      expert: 1,
      psychic: 5,
      evasion: 1,
      water_res: -1,
      map: 1
    }
  }),
  deepFreeze<ChestArmor>({
    id: 60,
    type: 'chest',
    name: 'Bone Mail+',
    blade: true,
    gunner: false,
    defense: 34,
    fireRes: 3,
    waterRes: -2,
    iceRes: -1,
    thunderRes: 2,
    dragonRes: 3,
    slots: 1,
    rarity: 4,
    price: 6400,
    maxDefense: 34,
    skillPoints: {
      stamina: 1,
      expert: 2,
      hunger: 1,
      sleep: -1,
      perception: 4
    }
  }),
  deepFreeze<ChestArmor>({
    id: 61,
    type: 'chest',
    name: 'Bone Vest+',
    blade: false,
    gunner: true,
    defense: 20,
    fireRes: 3,
    waterRes: -2,
    iceRes: -1,
    thunderRes: 2,
    dragonRes: 3,
    slots: 1,
    rarity: 4,
    price: 6400,
    maxDefense: 20,
    skillPoints: {
      stamina: 2,
      expert: 2,
      hunger: 2,
      sleep: -1,
      perception: 2
    }
  }),
  deepFreeze<ChestArmor>({
    id: 62,
    type: 'chest',
    name: 'Alloy Mail+',
    blade: true,
    gunner: false,
    defense: 34,
    fireRes: 1,
    waterRes: 2,
    iceRes: -1,
    thunderRes: -2,
    dragonRes: -1,
    slots: 2,
    rarity: 4,
    price: 7100,
    maxDefense: 34,
    skillPoints: {
      expert: 3,
      sharpener: 2,
      speedsetup: 1,
      oxygen: -1
    }
  }),
  deepFreeze<ChestArmor>({
    id: 63,
    type: 'chest',
    name: 'Alloy Vest+',
    blade: false,
    gunner: true,
    defense: 20,
    fireRes: 1,
    waterRes: 2,
    iceRes: -1,
    thunderRes: -2,
    dragonRes: -1,
    slots: 2,
    rarity: 4,
    price: 7100,
    maxDefense: 20,
    skillPoints: {
      'normal_s+': 2,
      expert: 3,
      speedsetup: 1,
      oxygen: -1
    }
  }),
  deepFreeze<ChestArmor>({
    id: 64,
    type: 'chest',
    name: 'Jaggi Mail+',
    blade: true,
    gunner: false,
    defense: 38,
    fireRes: -3,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: 2,
    slots: 0,
    rarity: 5,
    price: 8000,
    maxDefense: 38,
    skillPoints: {
      expert: 2,
      attack: 4,
      stun: 3,
      gluttony: 1,
      cold_res: -1
    }
  }),
  deepFreeze<ChestArmor>({
    id: 65,
    type: 'chest',
    name: 'Jaggi Vest+',
    blade: false,
    gunner: true,
    defense: 22,
    fireRes: -3,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: 2,
    slots: 0,
    rarity: 5,
    price: 8000,
    maxDefense: 22,
    skillPoints: {
      expert: 2,
      attack: 5,
      stun: 1,
      gluttony: 2,
      cold_res: -1
    }
  }),
  deepFreeze<ChestArmor>({
    id: 66,
    type: 'chest',
    name: 'Bnahabra Mail+',
    blade: true,
    gunner: false,
    defense: 38,
    fireRes: -5,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 2,
    dragonRes: 6,
    slots: 1,
    rarity: 5,
    price: 10500,
    maxDefense: 38,
    skillPoints: { sharpness: 1, status: 3, poison: -5 }
  }),
  deepFreeze<ChestArmor>({
    id: 67,
    type: 'chest',
    name: 'Bnahabra Vest+',
    blade: false,
    gunner: true,
    defense: 22,
    fireRes: -5,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 2,
    dragonRes: 6,
    slots: 1,
    rarity: 5,
    price: 10500,
    maxDefense: 22,
    skillPoints: { status: 3, poison: -5, reload_spd: 1 }
  }),
  deepFreeze<ChestArmor>({
    id: 68,
    type: 'chest',
    name: 'Rhenoplos Mail+',
    blade: true,
    gunner: false,
    defense: 38,
    fireRes: 3,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -2,
    dragonRes: 2,
    slots: 1,
    rarity: 5,
    price: 8500,
    maxDefense: 38,
    skillPoints: {
      expert: 2,
      wind_res: 4,
      eating: 1,
      'mud/snow': 1,
      thunderres: -1
    }
  }),
  deepFreeze<ChestArmor>({
    id: 69,
    type: 'chest',
    name: 'Rhenoplos Vest+',
    blade: false,
    gunner: true,
    defense: 22,
    fireRes: 3,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -2,
    dragonRes: 2,
    slots: 1,
    rarity: 5,
    price: 8500,
    maxDefense: 22,
    skillPoints: {
      recoil: 4,
      expert: 2,
      'crag_s+': 1,
      eating: 1,
      thunderres: -1
    }
  }),
  deepFreeze<ChestArmor>({
    id: 70,
    type: 'chest',
    name: 'Qurupeco Mail+',
    blade: true,
    gunner: false,
    defense: 42,
    fireRes: 4,
    waterRes: -3,
    iceRes: -4,
    thunderRes: 0,
    dragonRes: 1,
    slots: 1,
    rarity: 5,
    price: 10000,
    maxDefense: 42,
    skillPoints: {
      expert: 1,
      defense: 2,
      'wide-range': 4,
      rec_level: 1,
      ice_res: -1
    }
  }),
  deepFreeze<ChestArmor>({
    id: 71,
    type: 'chest',
    name: 'Qurupeco Vest+',
    blade: false,
    gunner: true,
    defense: 25,
    fireRes: 4,
    waterRes: -3,
    iceRes: -4,
    thunderRes: 0,
    dragonRes: 1,
    slots: 1,
    rarity: 5,
    price: 10000,
    maxDefense: 25,
    skillPoints: {
      expert: 1,
      defense: 1,
      'wide-range': 4,
      rec_level: 1,
      ice_res: -2
    }
  }),
  deepFreeze<ChestArmor>({
    id: 72,
    type: 'chest',
    name: 'Ludroth Mail+',
    blade: true,
    gunner: false,
    defense: 44,
    fireRes: -4,
    waterRes: 4,
    iceRes: 0,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 5,
    price: 11800,
    maxDefense: 44,
    skillPoints: {
      expert: 1,
      hunger: -1,
      protection: 1,
      constitutn: 4,
      currentres: 2
    }
  }),
  deepFreeze<ChestArmor>({
    id: 73,
    type: 'chest',
    name: 'Ludroth Vest+',
    blade: false,
    gunner: true,
    defense: 26,
    fireRes: -4,
    waterRes: 4,
    iceRes: 0,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 5,
    price: 11800,
    maxDefense: 26,
    skillPoints: {
      expert: 1,
      'pellet_s+': 1,
      hunger: -2,
      protection: 1,
      constitutn: 4
    }
  }),
  deepFreeze<ChestArmor>({
    id: 74,
    type: 'chest',
    name: 'Steel Mail+',
    blade: true,
    gunner: false,
    defense: 42,
    fireRes: -1,
    waterRes: 1,
    iceRes: 1,
    thunderRes: -1,
    dragonRes: 0,
    slots: 1,
    rarity: 5,
    price: 11000,
    maxDefense: 42,
    skillPoints: { sharpener: 2, guard: 2, swimming: -5 }
  }),
  deepFreeze<ChestArmor>({
    id: 75,
    type: 'chest',
    name: 'Baggi Mail+',
    blade: true,
    gunner: false,
    defense: 44,
    fireRes: -4,
    waterRes: -1,
    iceRes: 4,
    thunderRes: -1,
    dragonRes: 1,
    slots: 0,
    rarity: 5,
    price: 12300,
    maxDefense: 44,
    skillPoints: {
      tranquilzr: 2,
      fastcharge: 1,
      expert: 2,
      stun: -2,
      ice_res: 4
    }
  }),
  deepFreeze<ChestArmor>({
    id: 76,
    type: 'chest',
    name: 'Baggi Vest+',
    blade: false,
    gunner: true,
    defense: 26,
    fireRes: -4,
    waterRes: -1,
    iceRes: 4,
    thunderRes: -1,
    dragonRes: 1,
    slots: 0,
    rarity: 5,
    price: 12300,
    maxDefense: 26,
    skillPoints: {
      pellets_up: 1,
      tranquilzr: 2,
      expert: 2,
      stun: -2,
      ice_res: 4
    }
  }),
  deepFreeze<ChestArmor>({
    id: 77,
    type: 'chest',
    name: 'Barroth Mail+',
    blade: true,
    gunner: false,
    defense: 48,
    fireRes: -5,
    waterRes: 5,
    iceRes: -4,
    thunderRes: 4,
    dragonRes: 0,
    slots: 0,
    rarity: 5,
    price: 13800,
    maxDefense: 48,
    skillPoints: { stamina: 1, expert: -2, attack: 6, potential: 2 }
  }),
  deepFreeze<ChestArmor>({
    id: 78,
    type: 'chest',
    name: 'Barroth Vest+',
    blade: false,
    gunner: true,
    defense: 28,
    fireRes: -5,
    waterRes: 5,
    iceRes: -4,
    thunderRes: 4,
    dragonRes: 0,
    slots: 0,
    rarity: 5,
    price: 13800,
    maxDefense: 28,
    skillPoints: { stamina: 1, expert: -3, attack: 5, potential: 2 }
  }),
  deepFreeze<ChestArmor>({
    id: 79,
    type: 'chest',
    name: 'Gobul Mail+',
    blade: true,
    gunner: false,
    defense: 50,
    fireRes: -2,
    waterRes: 4,
    iceRes: 0,
    thunderRes: -4,
    dragonRes: 2,
    slots: 1,
    rarity: 5,
    price: 14800,
    maxDefense: 50,
    skillPoints: { rec_speed: -2, expert: 3, eating: 2, stun: 2 }
  }),
  deepFreeze<ChestArmor>({
    id: 80,
    type: 'chest',
    name: 'Gobul Vest+',
    blade: false,
    gunner: true,
    defense: 30,
    fireRes: -2,
    waterRes: 4,
    iceRes: 0,
    thunderRes: -4,
    dragonRes: 2,
    slots: 1,
    rarity: 5,
    price: 14800,
    maxDefense: 30,
    skillPoints: { rec_speed: -2, expert: 3, eating: 2, stun: 2 }
  }),
  deepFreeze<ChestArmor>({
    id: 81,
    type: 'chest',
    name: 'Guild Bard Bolero+',
    blade: true,
    gunner: false,
    defense: 36,
    fireRes: 0,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 0,
    rarity: 6,
    price: 25000,
    maxDefense: 36,
    skillPoints: {
      fate: 3,
      carving: 2,
      tranquilzr: 2,
      protection: -4
    }
  }),
  deepFreeze<ChestArmor>({
    id: 82,
    type: 'chest',
    name: 'Guild Bard Vest+',
    blade: false,
    gunner: true,
    defense: 22,
    fireRes: 0,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 0,
    rarity: 6,
    price: 25000,
    maxDefense: 22,
    skillPoints: {
      fate: 3,
      carving: 2,
      tranquilzr: 2,
      protection: -4
    }
  }),
  deepFreeze<ChestArmor>({
    id: 83,
    type: 'chest',
    name: 'Rathian Mail+',
    blade: true,
    gunner: false,
    defense: 50,
    fireRes: 4,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 1,
    rarity: 5,
    price: 14800,
    maxDefense: 50,
    skillPoints: {
      hearing: 2,
      health: 3,
      protection: -3,
      fire_res: 1
    }
  }),
  deepFreeze<ChestArmor>({
    id: 84,
    type: 'chest',
    name: 'Rathian Vest+',
    blade: false,
    gunner: true,
    defense: 30,
    fireRes: 4,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 1,
    rarity: 5,
    price: 14800,
    maxDefense: 30,
    skillPoints: {
      hearing: 1,
      health: 3,
      protection: -3,
      fire_res: 2
    }
  }),
  deepFreeze<ChestArmor>({
    id: 85,
    type: 'chest',
    name: 'Gigginox Mail+',
    blade: true,
    gunner: false,
    defense: 54,
    fireRes: -4,
    waterRes: -1,
    iceRes: 2,
    thunderRes: 3,
    dragonRes: 0,
    slots: 1,
    rarity: 5,
    price: 15800,
    maxDefense: 54,
    skillPoints: { status: 2, poison: 2, health: -1, constitutn: 4 }
  }),
  deepFreeze<ChestArmor>({
    id: 86,
    type: 'chest',
    name: 'Gigginox Vest+',
    blade: false,
    gunner: true,
    defense: 32,
    fireRes: -4,
    waterRes: -1,
    iceRes: 2,
    thunderRes: 3,
    dragonRes: 0,
    slots: 1,
    rarity: 5,
    price: 15800,
    maxDefense: 32,
    skillPoints: { status: 1, poison: 1, health: -2, constitutn: 5 }
  }),
  deepFreeze<ChestArmor>({
    id: 87,
    type: 'chest',
    name: 'Ingot Mail+',
    blade: true,
    gunner: false,
    defense: 54,
    fireRes: -2,
    waterRes: -1,
    iceRes: 1,
    thunderRes: 3,
    dragonRes: 2,
    slots: 1,
    rarity: 5,
    price: 17500,
    maxDefense: 54,
    skillPoints: {
      sharpener: -1,
      guard_up: 2,
      wind_res: 4,
      thunderres: 2
    }
  }),
  deepFreeze<ChestArmor>({
    id: 88,
    type: 'chest',
    name: 'Ingot Vest+',
    blade: false,
    gunner: true,
    defense: 32,
    fireRes: -2,
    waterRes: -1,
    iceRes: 1,
    thunderRes: 3,
    dragonRes: 2,
    slots: 1,
    rarity: 5,
    price: 17500,
    maxDefense: 32,
    skillPoints: {
      recoil: 4,
      guard_up: 2,
      reload_spd: -1,
      thunderres: 2
    }
  }),
  deepFreeze<ChestArmor>({
    id: 89,
    type: 'chest',
    name: 'Dober Mail',
    blade: true,
    gunner: false,
    defense: 58,
    fireRes: -2,
    waterRes: -2,
    iceRes: 1,
    thunderRes: 1,
    dragonRes: 5,
    slots: 1,
    rarity: 6,
    price: 19000,
    maxDefense: 58,
    skillPoints: {
      stamina: 2,
      potential: -1,
      crit_draw: 4,
      dragon_res: 2
    }
  }),
  deepFreeze<ChestArmor>({
    id: 90,
    type: 'chest',
    name: 'Dober Vest',
    blade: false,
    gunner: true,
    defense: 34,
    fireRes: -2,
    waterRes: -2,
    iceRes: 1,
    thunderRes: 1,
    dragonRes: 5,
    slots: 1,
    rarity: 6,
    price: 19000,
    maxDefense: 34,
    skillPoints: {
      pellets_up: 3,
      'pellet_s+': 3,
      potential: -1,
      dragon_res: 2
    }
  }),
  deepFreeze<ChestArmor>({
    id: 91,
    type: 'chest',
    name: 'Lagiacrus Mail+',
    blade: true,
    gunner: false,
    defense: 58,
    fireRes: -4,
    waterRes: 2,
    iceRes: -1,
    thunderRes: 5,
    dragonRes: -2,
    slots: 3,
    rarity: 6,
    price: 18000,
    maxDefense: 58,
    skillPoints: {
      status: -2,
      elemental: 1,
      freeelemnt: 1,
      swimming: 1
    }
  }),
  deepFreeze<ChestArmor>({
    id: 92,
    type: 'chest',
    name: 'Lagiacrus Vest+',
    blade: false,
    gunner: true,
    defense: 34,
    fireRes: -4,
    waterRes: 2,
    iceRes: -1,
    thunderRes: 5,
    dragonRes: -2,
    slots: 3,
    rarity: 6,
    price: 18000,
    maxDefense: 34,
    skillPoints: {
      status: -2,
      elemental: 1,
      rapid_fire: 1,
      swimming: 1
    }
  }),
  deepFreeze<ChestArmor>({
    id: 93,
    type: 'chest',
    name: 'Rathalos Mail+',
    blade: true,
    gunner: false,
    defense: 58,
    fireRes: 4,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 1,
    rarity: 6,
    price: 18000,
    maxDefense: 58,
    skillPoints: { fencing: 3, expert: 2, defense: -3, heat_res: 1 }
  }),
  deepFreeze<ChestArmor>({
    id: 94,
    type: 'chest',
    name: 'Rathalos Vest+',
    blade: false,
    gunner: true,
    defense: 34,
    fireRes: 4,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 1,
    rarity: 6,
    price: 18000,
    maxDefense: 34,
    skillPoints: {
      normals_up: 3,
      expert: 2,
      defense: -3,
      heat_res: 1
    }
  }),
  deepFreeze<ChestArmor>({
    id: 95,
    type: 'chest',
    name: 'Barioth Mail+',
    blade: true,
    gunner: false,
    defense: 58,
    fireRes: -4,
    waterRes: 2,
    iceRes: 5,
    thunderRes: -3,
    dragonRes: 0,
    slots: 0,
    rarity: 6,
    price: 18000,
    maxDefense: 58,
    skillPoints: {
      evade_dist: 3,
      evasion: 4,
      heat_res: -2,
      cold_res: 2
    }
  }),
  deepFreeze<ChestArmor>({
    id: 96,
    type: 'chest',
    name: 'Barioth Vest+',
    blade: false,
    gunner: true,
    defense: 34,
    fireRes: -4,
    waterRes: 2,
    iceRes: 5,
    thunderRes: -3,
    dragonRes: 0,
    slots: 0,
    rarity: 6,
    price: 18000,
    maxDefense: 34,
    skillPoints: {
      evade_dist: 2,
      evasion: 4,
      heat_res: -3,
      cold_res: 2
    }
  }),
  deepFreeze<ChestArmor>({
    id: 97,
    type: 'chest',
    name: 'Diablos Mail+',
    blade: true,
    gunner: false,
    defense: 62,
    fireRes: 3,
    waterRes: -1,
    iceRes: -4,
    thunderRes: -1,
    dragonRes: -1,
    slots: 0,
    rarity: 6,
    price: 18800,
    maxDefense: 62,
    skillPoints: { elemental: -4, tremor_res: 4, crit_draw: 3 }
  }),
  deepFreeze<ChestArmor>({
    id: 98,
    type: 'chest',
    name: 'Diablos Vest+',
    blade: false,
    gunner: true,
    defense: 37,
    fireRes: 3,
    waterRes: -1,
    iceRes: -4,
    thunderRes: -1,
    dragonRes: -1,
    slots: 0,
    rarity: 6,
    price: 18800,
    maxDefense: 37,
    skillPoints: { pierces_up: 4, 'pierce_s+': 3, elemental: -4 }
  }),
  deepFreeze<ChestArmor>({
    id: 99,
    type: 'chest',
    name: 'Uragaan Mail+',
    blade: true,
    gunner: false,
    defense: 62,
    fireRes: 4,
    waterRes: -4,
    iceRes: -1,
    thunderRes: 1,
    dragonRes: -2,
    slots: 1,
    rarity: 6,
    price: 18800,
    maxDefense: 62,
    skillPoints: {
      punishdraw: 3,
      bomb_boost: 3,
      defense: 2,
      eating: -1
    }
  }),
  deepFreeze<ChestArmor>({
    id: 100,
    type: 'chest',
    name: 'Uragaan Vest+',
    blade: false,
    gunner: true,
    defense: 37,
    fireRes: 4,
    waterRes: -4,
    iceRes: -1,
    thunderRes: 1,
    dragonRes: -2,
    slots: 1,
    rarity: 6,
    price: 18800,
    maxDefense: 37,
    skillPoints: {
      recoil: 1,
      bomb_boost: 4,
      defense: 2,
      eating: -2
    }
  }),
  deepFreeze<ChestArmor>({
    id: 101,
    type: 'chest',
    name: 'Agnaktor Mail+',
    blade: true,
    gunner: false,
    defense: 62,
    fireRes: 5,
    waterRes: -4,
    iceRes: -2,
    thunderRes: 1,
    dragonRes: 0,
    slots: 1,
    rarity: 6,
    price: 19800,
    maxDefense: 62,
    skillPoints: {
      sharpness: 2,
      stamina: -1,
      guard: 5,
      flame_aura: 1
    }
  }),
  deepFreeze<ChestArmor>({
    id: 102,
    type: 'chest',
    name: 'Agnaktor Vest+',
    blade: false,
    gunner: true,
    defense: 37,
    fireRes: 5,
    waterRes: -4,
    iceRes: -2,
    thunderRes: 1,
    dragonRes: 0,
    slots: 1,
    rarity: 6,
    price: 19800,
    maxDefense: 37,
    skillPoints: {
      normals_up: 3,
      'normal_s+': 3,
      stamina: -2,
      flame_aura: 1
    }
  }),
  deepFreeze<ChestArmor>({
    id: 103,
    type: 'chest',
    name: 'Vangis Mail',
    blade: true,
    gunner: false,
    defense: 64,
    fireRes: 0,
    waterRes: 0,
    iceRes: 3,
    thunderRes: -4,
    dragonRes: -4,
    slots: 0,
    rarity: 7,
    price: 41500,
    maxDefense: 64,
    skillPoints: {
      handicraft: 3,
      hunger: -2,
      attack: 3,
      psychic: 3
    }
  }),
  deepFreeze<ChestArmor>({
    id: 104,
    type: 'chest',
    name: 'Vangis Vest',
    blade: false,
    gunner: true,
    defense: 38,
    fireRes: 0,
    waterRes: 0,
    iceRes: 3,
    thunderRes: -4,
    dragonRes: -4,
    slots: 0,
    rarity: 7,
    price: 41500,
    maxDefense: 38,
    skillPoints: { loading: 3, hunger: -2, attack: 3, psychic: 3 }
  }),
  deepFreeze<ChestArmor>({
    id: 105,
    type: 'chest',
    name: 'Damascus Mail',
    blade: true,
    gunner: false,
    defense: 62,
    fireRes: -2,
    waterRes: 0,
    iceRes: 2,
    thunderRes: -2,
    dragonRes: 3,
    slots: 3,
    rarity: 6,
    price: 32300,
    maxDefense: 62,
    skillPoints: {
      stamina: -2,
      punishdraw: 1,
      health: 1,
      guard_up: 1
    }
  }),
  deepFreeze<ChestArmor>({
    id: 106,
    type: 'chest',
    name: 'Damascus Vest',
    blade: false,
    gunner: true,
    defense: 37,
    fireRes: -2,
    waterRes: 0,
    iceRes: 2,
    thunderRes: -2,
    dragonRes: 3,
    slots: 3,
    rarity: 6,
    price: 32300,
    maxDefense: 37,
    skillPoints: {
      stamina: -2,
      health: 1,
      guard_up: 1,
      reload_spd: 1
    }
  }),
  deepFreeze<ChestArmor>({
    id: 107,
    type: 'chest',
    name: 'Helios Mail+',
    blade: true,
    gunner: false,
    defense: 66,
    fireRes: 0,
    waterRes: 5,
    iceRes: 3,
    thunderRes: -3,
    dragonRes: -4,
    slots: 0,
    rarity: 6,
    price: 26200,
    maxDefense: 66,
    skillPoints: {
      sharpness: -2,
      handicraft: 5,
      hearing: 3,
      protection: -1
    }
  }),
  deepFreeze<ChestArmor>({
    id: 108,
    type: 'chest',
    name: 'Helios Vest+',
    blade: false,
    gunner: true,
    defense: 39,
    fireRes: 0,
    waterRes: 5,
    iceRes: 3,
    thunderRes: -3,
    dragonRes: -4,
    slots: 0,
    rarity: 6,
    price: 26200,
    maxDefense: 39,
    skillPoints: {
      recoil: -2,
      hearing: 3,
      loading: 5,
      protection: -1
    }
  }),
  deepFreeze<ChestArmor>({
    id: 109,
    type: 'chest',
    name: 'Yamato Muneate+',
    blade: true,
    gunner: false,
    defense: 66,
    fireRes: 4,
    waterRes: 0,
    iceRes: -3,
    thunderRes: 0,
    dragonRes: -4,
    slots: 1,
    rarity: 6,
    price: 27500,
    maxDefense: 66,
    skillPoints: {
      sharpness: 1,
      fastcharge: 2,
      rec_speed: 4,
      combo_rate: -2
    }
  }),
  deepFreeze<ChestArmor>({
    id: 110,
    type: 'chest',
    name: 'Mutsu Muneate+',
    blade: false,
    gunner: true,
    defense: 39,
    fireRes: 4,
    waterRes: 0,
    iceRes: -3,
    thunderRes: 0,
    dragonRes: -4,
    slots: 1,
    rarity: 6,
    price: 27500,
    maxDefense: 39,
    skillPoints: {
      recoil: 2,
      rec_speed: 2,
      'clust_s+': 4,
      combo_rate: -1
    }
  }),
  deepFreeze<ChestArmor>({
    id: 111,
    type: 'chest',
    name: 'Escadora Soul',
    blade: true,
    gunner: false,
    defense: 70,
    fireRes: -1,
    waterRes: -1,
    iceRes: -1,
    thunderRes: 0,
    dragonRes: -5,
    slots: 2,
    rarity: 7,
    price: 66666,
    maxDefense: 70,
    skillPoints: {
      evade_dist: 2,
      freeelemnt: 2,
      rec_level: -1,
      blight_res: 2
    }
  }),
  deepFreeze<ChestArmor>({
    id: 112,
    type: 'chest',
    name: 'Escadora Seele',
    blade: false,
    gunner: true,
    defense: 42,
    fireRes: -1,
    waterRes: -1,
    iceRes: -1,
    thunderRes: 0,
    dragonRes: -5,
    slots: 2,
    rarity: 7,
    price: 66666,
    maxDefense: 42,
    skillPoints: {
      evade_dist: 2,
      rapid_fire: 2,
      rec_level: -1,
      blight_res: 2
    }
  }),
  deepFreeze<ChestArmor>({
    id: 113,
    type: 'chest',
    name: 'Chakra Necklace',
    blade: true,
    gunner: true,
    defense: 18,
    fireRes: 0,
    waterRes: 10,
    iceRes: 0,
    thunderRes: -10,
    dragonRes: 0,
    slots: 3,
    rarity: 7,
    price: 33333,
    maxDefense: 18,
    skillPoints: {}
  }),
  deepFreeze<ChestArmor>({
    id: 114,
    type: 'chest',
    name: 'HellHunter Jacket',
    blade: true,
    gunner: false,
    defense: 15,
    fireRes: 2,
    waterRes: 2,
    iceRes: 2,
    thunderRes: 2,
    dragonRes: 2,
    slots: 3,
    rarity: 3,
    price: 10000,
    maxDefense: 15,
    maxLowRankDefense: 27,
    skillPoints: { survivor: 5 }
  }),
  deepFreeze<ChestArmor>({
    id: 115,
    type: 'chest',
    name: 'HellHunter Leather',
    blade: false,
    gunner: true,
    defense: 8,
    fireRes: 2,
    waterRes: 2,
    iceRes: 2,
    thunderRes: 2,
    dragonRes: 2,
    slots: 3,
    rarity: 3,
    price: 10000,
    maxDefense: 8,
    maxLowRankDefense: 14,
    skillPoints: { survivor: 5 }
  }),
  deepFreeze<ChestArmor>({
    id: 116,
    type: 'chest',
    name: 'SoulHunter Jacket',
    blade: true,
    gunner: false,
    defense: 48,
    fireRes: 2,
    waterRes: 2,
    iceRes: 2,
    thunderRes: 2,
    dragonRes: 2,
    slots: 0,
    rarity: 6,
    price: 15000,
    maxDefense: 48,
    skillPoints: { survivor: 10 }
  }),
  deepFreeze<ChestArmor>({
    id: 117,
    type: 'chest',
    name: 'SoulHunter Leather',
    blade: false,
    gunner: true,
    defense: 28,
    fireRes: 2,
    waterRes: 2,
    iceRes: 2,
    thunderRes: 2,
    dragonRes: 2,
    slots: 0,
    rarity: 6,
    price: 15000,
    maxDefense: 28,
    skillPoints: { survivor: 10 }
  })
];
