import { deepFreeze } from '../../utils';
import type { HeadArmor } from './types';

export const HeadArmors: HeadArmor[] = [
  deepFreeze<HeadArmor>({
    id: 0,
    type: 'head',
    name: 'Leather Headgear',
    blade: true,
    gunner: true,
    defense: 1,
    fireRes: -1,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 3,
    dragonRes: 2,
    slots: 1,
    rarity: 1,
    price: 150,
    maxDefense: 1,
    maxLowRankDefense: 9,
    skillPoints: { attack: 1, gathering: 2, spd_gather: 2, whim: 3 }
  }),
  deepFreeze<HeadArmor>({
    id: 1,
    type: 'head',
    name: 'Piscine Mask',
    blade: true,
    gunner: true,
    defense: 3,
    fireRes: -2,
    waterRes: 4,
    iceRes: 2,
    thunderRes: -3,
    dragonRes: 0,
    slots: 0,
    rarity: 1,
    price: 300,
    maxDefense: 3,
    maxLowRankDefense: 9,
    skillPoints: { oxygen: 10, currentres: 1 }
  }),
  deepFreeze<HeadArmor>({
    id: 2,
    type: 'head',
    name: 'Chainmail Headgear',
    blade: true,
    gunner: true,
    defense: 2,
    fireRes: -1,
    waterRes: -1,
    iceRes: 3,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 1,
    price: 200,
    maxDefense: 2,
    maxLowRankDefense: 9,
    skillPoints: {
      health: 1,
      fishing: 1,
      combo_rate: 6,
      combo_plus: 1
    }
  }),
  deepFreeze<HeadArmor>({
    id: 3,
    type: 'head',
    name: "Hunter's Helm",
    blade: true,
    gunner: true,
    defense: 6,
    fireRes: -1,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: -1,
    slots: 1,
    rarity: 1,
    price: 500,
    maxDefense: 6,
    maxLowRankDefense: 20,
    skillPoints: { psychic: 4, water_res: -2, map: 2, bbq: 1 }
  }),
  deepFreeze<HeadArmor>({
    id: 4,
    type: 'head',
    name: "Hunter's Cap",
    blade: true,
    gunner: true,
    defense: 3,
    fireRes: 4,
    waterRes: -1,
    iceRes: 4,
    thunderRes: 4,
    dragonRes: 4,
    slots: 1,
    rarity: 1,
    price: 500,
    maxDefense: 3,
    maxLowRankDefense: 10,
    skillPoints: { psychic: 5, water_res: -1, map: 1, bbq: 2 }
  }),
  deepFreeze<HeadArmor>({
    id: 5,
    type: 'head',
    name: 'Bone Helm',
    blade: true,
    gunner: true,
    defense: 8,
    fireRes: 2,
    waterRes: -2,
    iceRes: -1,
    thunderRes: 2,
    dragonRes: 3,
    slots: 1,
    rarity: 1,
    price: 750,
    maxDefense: 8,
    maxLowRankDefense: 22,
    skillPoints: {
      hunger: 4,
      sleep: -2,
      lastingpwr: 1,
      perception: 2
    }
  }),
  deepFreeze<HeadArmor>({
    id: 6,
    type: 'head',
    name: 'Bone Cap',
    blade: true,
    gunner: true,
    defense: 4,
    fireRes: 7,
    waterRes: -2,
    iceRes: -1,
    thunderRes: 2,
    dragonRes: 3,
    slots: 1,
    rarity: 1,
    price: 750,
    maxDefense: 4,
    maxLowRankDefense: 11,
    skillPoints: {
      hunger: 5,
      sleep: -1,
      lastingpwr: 2,
      perception: 1
    }
  }),
  deepFreeze<HeadArmor>({
    id: 7,
    type: 'head',
    name: 'Alloy Helm',
    blade: true,
    gunner: true,
    defense: 8,
    fireRes: 1,
    waterRes: 1,
    iceRes: -1,
    thunderRes: -2,
    dragonRes: -1,
    slots: 2,
    rarity: 1,
    price: 1000,
    maxDefense: 8,
    maxLowRankDefense: 22,
    skillPoints: {
      expert: 1,
      sharpener: 3,
      speedsetup: 1,
      oxygen: -2
    }
  }),
  deepFreeze<HeadArmor>({
    id: 8,
    type: 'head',
    name: 'Alloy Cap',
    blade: true,
    gunner: true,
    defense: 4,
    fireRes: 1,
    waterRes: 6,
    iceRes: -1,
    thunderRes: -2,
    dragonRes: -1,
    slots: 2,
    rarity: 1,
    price: 1000,
    maxDefense: 4,
    maxLowRankDefense: 11,
    skillPoints: {
      'normal_s+': 3,
      expert: 1,
      speedsetup: 2,
      oxygen: -1
    }
  }),
  deepFreeze<HeadArmor>({
    id: 9,
    type: 'head',
    name: 'Jaggi Helm',
    blade: true,
    gunner: true,
    defense: 10,
    fireRes: -3,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    price: 1200,
    maxDefense: 10,
    maxLowRankDefense: 24,
    skillPoints: { attack: 3, stun: 2, gluttony: 2, cold_res: -2 }
  }),
  deepFreeze<HeadArmor>({
    id: 10,
    type: 'head',
    name: 'Jaggi Cap',
    blade: true,
    gunner: true,
    defense: 5,
    fireRes: -3,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: 6,
    slots: 1,
    rarity: 2,
    price: 1200,
    maxDefense: 5,
    maxLowRankDefense: 12,
    skillPoints: { attack: 4, stun: 1, gluttony: 3, cold_res: -1 }
  }),
  deepFreeze<HeadArmor>({
    id: 11,
    type: 'head',
    name: 'Rhenoplos Helm',
    blade: true,
    gunner: true,
    defense: 12,
    fireRes: 2,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: 2,
    slots: 1,
    rarity: 2,
    price: 1400,
    maxDefense: 12,
    maxLowRankDefense: 24,
    skillPoints: {
      attack: 1,
      wind_res: 3,
      eating: 1,
      'mud/snow': 2,
      thunderres: -2
    }
  }),
  deepFreeze<HeadArmor>({
    id: 12,
    type: 'head',
    name: 'Rhenoplos Cap',
    blade: true,
    gunner: true,
    defense: 6,
    fireRes: 7,
    waterRes: 4,
    iceRes: 4,
    thunderRes: -1,
    dragonRes: 2,
    slots: 1,
    rarity: 2,
    price: 1400,
    maxDefense: 6,
    maxLowRankDefense: 12,
    skillPoints: {
      recoil: 3,
      'crag_s+': 3,
      attack: 1,
      eating: 1,
      thunderres: -1
    }
  }),
  deepFreeze<HeadArmor>({
    id: 13,
    type: 'head',
    name: 'Qurupeco Helm',
    blade: true,
    gunner: true,
    defense: 12,
    fireRes: 2,
    waterRes: -2,
    iceRes: -3,
    thunderRes: 0,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    price: 1700,
    maxDefense: 12,
    maxLowRankDefense: 24,
    skillPoints: {
      defense: 4,
      rec_level: 1,
      evasion: 1,
      ice_res: -3
    }
  }),
  deepFreeze<HeadArmor>({
    id: 14,
    type: 'head',
    name: 'Qurupeco Cap',
    blade: true,
    gunner: true,
    defense: 6,
    fireRes: 7,
    waterRes: -2,
    iceRes: -3,
    thunderRes: 0,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    price: 1700,
    maxDefense: 6,
    maxLowRankDefense: 12,
    skillPoints: {
      defense: 3,
      rec_level: 3,
      evasion: 2,
      ice_res: -1
    }
  }),
  deepFreeze<HeadArmor>({
    id: 15,
    type: 'head',
    name: 'Ludroth Helm',
    blade: true,
    gunner: true,
    defense: 13,
    fireRes: -3,
    waterRes: 2,
    iceRes: 0,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    price: 2200,
    maxDefense: 13,
    maxLowRankDefense: 25,
    skillPoints: {
      protection: 1,
      constitutn: 3,
      fire_res: -4,
      currentres: 1
    }
  }),
  deepFreeze<HeadArmor>({
    id: 16,
    type: 'head',
    name: 'Ludroth Cap',
    blade: true,
    gunner: true,
    defense: 7,
    fireRes: -3,
    waterRes: 7,
    iceRes: 0,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    price: 2200,
    maxDefense: 7,
    maxLowRankDefense: 13,
    skillPoints: {
      'pellet_s+': 2,
      protection: 2,
      constitutn: 3,
      fire_res: -2
    }
  }),
  deepFreeze<HeadArmor>({
    id: 17,
    type: 'head',
    name: 'Baggi Helm',
    blade: true,
    gunner: true,
    defense: 13,
    fireRes: -3,
    waterRes: -1,
    iceRes: 3,
    thunderRes: -1,
    dragonRes: 1,
    slots: 0,
    rarity: 2,
    price: 2400,
    maxDefense: 13,
    maxLowRankDefense: 25,
    skillPoints: {
      tranquilzr: 4,
      fastcharge: 2,
      attack: 1,
      stun: -2,
      ice_res: 2
    }
  }),
  deepFreeze<HeadArmor>({
    id: 18,
    type: 'head',
    name: 'Baggi Cap',
    blade: true,
    gunner: true,
    defense: 7,
    fireRes: -3,
    waterRes: 1,
    iceRes: 8,
    thunderRes: -1,
    dragonRes: 1,
    slots: 0,
    rarity: 2,
    price: 2400,
    maxDefense: 7,
    maxLowRankDefense: 13,
    skillPoints: {
      pellets_up: 3,
      tranquilzr: 2,
      attack: 1,
      stun: -2,
      ice_res: 3
    }
  }),
  deepFreeze<HeadArmor>({
    id: 19,
    type: 'head',
    name: 'Barroth Helm',
    blade: true,
    gunner: true,
    defense: 15,
    fireRes: 0,
    waterRes: 0,
    iceRes: -3,
    thunderRes: 3,
    dragonRes: 0,
    slots: 1,
    rarity: 2,
    price: 3200,
    maxDefense: 15,
    maxLowRankDefense: 27,
    skillPoints: { stamina: 2, expert: -2, attack: 4, potential: 1 }
  }),
  deepFreeze<HeadArmor>({
    id: 20,
    type: 'head',
    name: 'Barroth Cap',
    blade: true,
    gunner: true,
    defense: 8,
    fireRes: 5,
    waterRes: 5,
    iceRes: -3,
    thunderRes: 3,
    dragonRes: 0,
    slots: 1,
    rarity: 2,
    price: 3200,
    maxDefense: 8,
    maxLowRankDefense: 14,
    skillPoints: { stamina: 2, expert: -2, attack: 4, potential: 1 }
  }),
  deepFreeze<HeadArmor>({
    id: 21,
    type: 'head',
    name: 'Gobul Helm',
    blade: true,
    gunner: true,
    defense: 16,
    fireRes: -2,
    waterRes: 3,
    iceRes: 0,
    thunderRes: -3,
    dragonRes: 2,
    slots: 2,
    rarity: 2,
    price: 3600,
    maxDefense: 16,
    maxLowRankDefense: 28,
    skillPoints: { rec_speed: -2, eating: 3, stun: 1, water_res: 1 }
  }),
  deepFreeze<HeadArmor>({
    id: 22,
    type: 'head',
    name: 'Gobul Cap',
    blade: true,
    gunner: true,
    defense: 8,
    fireRes: -2,
    waterRes: 8,
    iceRes: 0,
    thunderRes: -3,
    dragonRes: 2,
    slots: 2,
    rarity: 2,
    price: 3600,
    maxDefense: 8,
    maxLowRankDefense: 14,
    skillPoints: { rec_speed: -1, eating: 4, stun: 1, water_res: 1 }
  }),
  deepFreeze<HeadArmor>({
    id: 23,
    type: 'head',
    name: "Ranger's Headgear",
    blade: true,
    gunner: true,
    defense: 15,
    fireRes: 0,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 0,
    rarity: 3,
    price: 10000,
    maxDefense: 15,
    maxLowRankDefense: 27,
    skillPoints: {
      fate: -3,
      carving: 2,
      'wide-range': 5,
      spd_gather: 2
    }
  }),
  deepFreeze<HeadArmor>({
    id: 24,
    type: 'head',
    name: "Archer's Turban",
    blade: true,
    gunner: true,
    defense: 8,
    fireRes: 10,
    waterRes: -10,
    iceRes: 5,
    thunderRes: -10,
    dragonRes: 10,
    slots: 0,
    rarity: 3,
    price: 10000,
    maxDefense: 8,
    maxLowRankDefense: 14,
    skillPoints: {
      fate: -1,
      carving: 4,
      'wide-range': 5,
      spd_gather: 2
    }
  }),
  deepFreeze<HeadArmor>({
    id: 25,
    type: 'head',
    name: 'Guild Bard Lobos',
    blade: true,
    gunner: true,
    defense: 15,
    fireRes: 0,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 0,
    rarity: 3,
    price: 10000,
    maxDefense: 15,
    maxLowRankDefense: 27,
    skillPoints: { fate: 2, psychic: 2, evasion: 4, sense: -3 }
  }),
  deepFreeze<HeadArmor>({
    id: 26,
    type: 'head',
    name: 'Guild Bard Hat',
    blade: true,
    gunner: true,
    defense: 8,
    fireRes: -10,
    waterRes: 10,
    iceRes: -10,
    thunderRes: 5,
    dragonRes: 10,
    slots: 0,
    rarity: 3,
    price: 10000,
    maxDefense: 8,
    maxLowRankDefense: 14,
    skillPoints: { fate: 3, psychic: 3, evasion: 4, sense: -1 }
  }),
  deepFreeze<HeadArmor>({
    id: 27,
    type: 'head',
    name: 'Rathian Helm',
    blade: true,
    gunner: true,
    defense: 16,
    fireRes: 3,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 1,
    rarity: 2,
    price: 3600,
    maxDefense: 16,
    maxLowRankDefense: 28,
    skillPoints: {
      hearing: 1,
      health: 2,
      protection: -2,
      fire_res: 4
    }
  }),
  deepFreeze<HeadArmor>({
    id: 28,
    type: 'head',
    name: 'Rathian Cap',
    blade: true,
    gunner: true,
    defense: 8,
    fireRes: 8,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 1,
    rarity: 2,
    price: 3600,
    maxDefense: 8,
    maxLowRankDefense: 14,
    skillPoints: {
      hearing: 1,
      health: 2,
      protection: -1,
      fire_res: 5
    }
  }),
  deepFreeze<HeadArmor>({
    id: 29,
    type: 'head',
    name: 'Gigginox Helm',
    blade: true,
    gunner: true,
    defense: 18,
    fireRes: -4,
    waterRes: 0,
    iceRes: 2,
    thunderRes: 2,
    dragonRes: -1,
    slots: 1,
    rarity: 2,
    price: 4100,
    maxDefense: 18,
    maxLowRankDefense: 30,
    skillPoints: { status: 2, poison: 2, health: -2, constitutn: 3 }
  }),
  deepFreeze<HeadArmor>({
    id: 30,
    type: 'head',
    name: 'Gigginox Cap',
    blade: true,
    gunner: true,
    defense: 9,
    fireRes: -4,
    waterRes: 0,
    iceRes: 2,
    thunderRes: 7,
    dragonRes: -1,
    slots: 1,
    rarity: 2,
    price: 4100,
    maxDefense: 9,
    maxLowRankDefense: 15,
    skillPoints: { status: 2, poison: 2, health: -1, constitutn: 4 }
  }),
  deepFreeze<HeadArmor>({
    id: 31,
    type: 'head',
    name: 'Ingot Helm',
    blade: true,
    gunner: true,
    defense: 18,
    fireRes: -2,
    waterRes: -1,
    iceRes: 1,
    thunderRes: 3,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    price: 5000,
    maxDefense: 18,
    maxLowRankDefense: 28,
    skillPoints: {
      sharpener: -2,
      guard_up: 2,
      wind_res: 4,
      thunderres: 1
    }
  }),
  deepFreeze<HeadArmor>({
    id: 32,
    type: 'head',
    name: 'Ingot Cap',
    blade: true,
    gunner: true,
    defense: 9,
    fireRes: -2,
    waterRes: -1,
    iceRes: 1,
    thunderRes: 3,
    dragonRes: 6,
    slots: 1,
    rarity: 2,
    price: 5000,
    maxDefense: 9,
    maxLowRankDefense: 14,
    skillPoints: {
      recoil: 4,
      guard_up: 2,
      reload_spd: -2,
      thunderres: 1
    }
  }),
  deepFreeze<HeadArmor>({
    id: 33,
    type: 'head',
    name: 'Lagiacrus Helm',
    blade: true,
    gunner: true,
    defense: 20,
    fireRes: -3,
    waterRes: 2,
    iceRes: -1,
    thunderRes: 4,
    dragonRes: -2,
    slots: 2,
    rarity: 3,
    price: 5600,
    maxDefense: 20,
    maxLowRankDefense: 30,
    skillPoints: {
      sharpness: 2,
      status: -2,
      elemental: 1,
      swimming: 3
    }
  }),
  deepFreeze<HeadArmor>({
    id: 34,
    type: 'head',
    name: 'Lagiacrus Cap',
    blade: true,
    gunner: true,
    defense: 10,
    fireRes: -3,
    waterRes: 2,
    iceRes: -1,
    thunderRes: 9,
    dragonRes: -2,
    slots: 2,
    rarity: 3,
    price: 5600,
    maxDefense: 10,
    maxLowRankDefense: 15,
    skillPoints: {
      normals_up: 2,
      status: -2,
      elemental: 1,
      swimming: 3
    }
  }),
  deepFreeze<HeadArmor>({
    id: 35,
    type: 'head',
    name: 'Rathalos Helm',
    blade: true,
    gunner: true,
    defense: 20,
    fireRes: 3,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 1,
    rarity: 3,
    price: 5600,
    maxDefense: 20,
    maxLowRankDefense: 30,
    skillPoints: { expert: 2, attack: 1, defense: -4, heat_res: 2 }
  }),
  deepFreeze<HeadArmor>({
    id: 36,
    type: 'head',
    name: 'Rathalos Cap',
    blade: true,
    gunner: true,
    defense: 10,
    fireRes: 8,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 1,
    rarity: 3,
    price: 5600,
    maxDefense: 10,
    maxLowRankDefense: 15,
    skillPoints: { expert: 2, attack: 2, defense: -2, heat_res: 3 }
  }),
  deepFreeze<HeadArmor>({
    id: 37,
    type: 'head',
    name: 'Barioth Helm',
    blade: true,
    gunner: true,
    defense: 20,
    fireRes: -4,
    waterRes: 2,
    iceRes: 4,
    thunderRes: -3,
    dragonRes: 0,
    slots: 1,
    rarity: 3,
    price: 5600,
    maxDefense: 20,
    maxLowRankDefense: 30,
    skillPoints: {
      stamina: 1,
      evasion: 3,
      heat_res: -4,
      cold_res: 1
    }
  }),
  deepFreeze<HeadArmor>({
    id: 38,
    type: 'head',
    name: 'Barioth Cap',
    blade: true,
    gunner: true,
    defense: 10,
    fireRes: -4,
    waterRes: 2,
    iceRes: 9,
    thunderRes: -3,
    dragonRes: 0,
    slots: 1,
    rarity: 3,
    price: 5600,
    maxDefense: 10,
    maxLowRankDefense: 15,
    skillPoints: {
      stamina: 1,
      evasion: 1,
      heat_res: -2,
      cold_res: 5
    }
  }),
  deepFreeze<HeadArmor>({
    id: 39,
    type: 'head',
    name: 'Diablos Helm',
    blade: true,
    gunner: true,
    defense: 22,
    fireRes: 2,
    waterRes: -1,
    iceRes: -3,
    thunderRes: -1,
    dragonRes: -1,
    slots: 1,
    rarity: 3,
    price: 6300,
    maxDefense: 22,
    maxLowRankDefense: 30,
    skillPoints: { elemental: -3, tremor_res: 4, crit_draw: 2 }
  }),
  deepFreeze<HeadArmor>({
    id: 40,
    type: 'head',
    name: 'Diablos Cap',
    blade: true,
    gunner: true,
    defense: 11,
    fireRes: 2,
    waterRes: 2,
    iceRes: -3,
    thunderRes: 2,
    dragonRes: 2,
    slots: 1,
    rarity: 3,
    price: 6300,
    maxDefense: 11,
    maxLowRankDefense: 15,
    skillPoints: { pierces_up: 4, 'pierce_s+': 2, elemental: -3 }
  }),
  deepFreeze<HeadArmor>({
    id: 41,
    type: 'head',
    name: 'Uragaan Helm',
    blade: true,
    gunner: true,
    defense: 22,
    fireRes: 3,
    waterRes: -4,
    iceRes: -1,
    thunderRes: 1,
    dragonRes: -2,
    slots: 1,
    rarity: 3,
    price: 6300,
    maxDefense: 22,
    maxLowRankDefense: 30,
    skillPoints: {
      punishdraw: 2,
      bomb_boost: 2,
      defense: 2,
      eating: -3
    }
  }),
  deepFreeze<HeadArmor>({
    id: 42,
    type: 'head',
    name: 'Uragaan Cap',
    blade: true,
    gunner: true,
    defense: 11,
    fireRes: 3,
    waterRes: -4,
    iceRes: -1,
    thunderRes: 1,
    dragonRes: -2,
    slots: 1,
    rarity: 3,
    price: 6300,
    maxDefense: 11,
    maxLowRankDefense: 15,
    skillPoints: {
      recoil: 3,
      bomb_boost: 2,
      defense: 3,
      eating: -1
    }
  }),
  deepFreeze<HeadArmor>({
    id: 43,
    type: 'head',
    name: 'Agnaktor Helm',
    blade: true,
    gunner: true,
    defense: 22,
    fireRes: 4,
    waterRes: -4,
    iceRes: -2,
    thunderRes: 1,
    dragonRes: 0,
    slots: 0,
    rarity: 3,
    price: 7200,
    maxDefense: 22,
    maxLowRankDefense: 30,
    skillPoints: {
      stamina: -3,
      guard: 3,
      guard_up: 2,
      flame_aura: 3
    }
  }),
  deepFreeze<HeadArmor>({
    id: 44,
    type: 'head',
    name: 'Agnaktor Cap',
    blade: true,
    gunner: true,
    defense: 11,
    fireRes: 9,
    waterRes: -4,
    iceRes: -2,
    thunderRes: 1,
    dragonRes: 0,
    slots: 0,
    rarity: 3,
    price: 7200,
    maxDefense: 11,
    maxLowRankDefense: 15,
    skillPoints: {
      stamina: -1,
      guard_up: 3,
      reload_spd: 4,
      flame_aura: 3
    }
  }),
  deepFreeze<HeadArmor>({
    id: 45,
    type: 'head',
    name: 'Helios Helm',
    blade: true,
    gunner: true,
    defense: 24,
    fireRes: 0,
    waterRes: 4,
    iceRes: 3,
    thunderRes: -3,
    dragonRes: -4,
    slots: 0,
    rarity: 3,
    price: 11000,
    maxDefense: 24,
    maxLowRankDefense: 32,
    skillPoints: {
      sharpness: -2,
      handicraft: 2,
      hearing: 3,
      protection: -4
    }
  }),
  deepFreeze<HeadArmor>({
    id: 46,
    type: 'head',
    name: 'Helios Cap',
    blade: true,
    gunner: true,
    defense: 12,
    fireRes: 0,
    waterRes: 9,
    iceRes: 3,
    thunderRes: -3,
    dragonRes: -4,
    slots: 0,
    rarity: 3,
    price: 11000,
    maxDefense: 12,
    maxLowRankDefense: 16,
    skillPoints: {
      recoil: -2,
      hearing: 3,
      loading: 2,
      protection: -4
    }
  }),
  deepFreeze<HeadArmor>({
    id: 47,
    type: 'head',
    name: 'Yamato Kabuto',
    blade: true,
    gunner: true,
    defense: 24,
    fireRes: 3,
    waterRes: 0,
    iceRes: -3,
    thunderRes: 0,
    dragonRes: -3,
    slots: 1,
    rarity: 3,
    price: 12000,
    maxDefense: 24,
    maxLowRankDefense: 32,
    skillPoints: {
      sharpness: 1,
      fastcharge: 1,
      rec_speed: 2,
      combo_rate: -5
    }
  }),
  deepFreeze<HeadArmor>({
    id: 48,
    type: 'head',
    name: 'Mutsu Eboshi',
    blade: true,
    gunner: true,
    defense: 12,
    fireRes: 3,
    waterRes: 10,
    iceRes: -3,
    thunderRes: 10,
    dragonRes: -3,
    slots: 1,
    rarity: 3,
    price: 12000,
    maxDefense: 12,
    maxLowRankDefense: 16,
    skillPoints: {
      recoil: 1,
      rec_speed: 2,
      'clust_s+': 3,
      combo_rate: -3
    }
  }),
  deepFreeze<HeadArmor>({
    id: 49,
    type: 'head',
    name: 'Leather Helm+',
    blade: true,
    gunner: true,
    defense: 26,
    fireRes: -2,
    waterRes: 0,
    iceRes: -2,
    thunderRes: 3,
    dragonRes: 2,
    slots: 2,
    rarity: 4,
    price: 4600,
    maxDefense: 26,
    skillPoints: { gathering: 2, spd_gather: 2, whim: 4 }
  }),
  deepFreeze<HeadArmor>({
    id: 50,
    type: 'head',
    name: 'Leather Cap+',
    blade: true,
    gunner: true,
    defense: 15,
    fireRes: -2,
    waterRes: 0,
    iceRes: -2,
    thunderRes: 8,
    dragonRes: 2,
    slots: 2,
    rarity: 4,
    price: 4600,
    maxDefense: 15,
    skillPoints: { gathering: 1, spd_gather: 1, whim: 6 }
  }),
  deepFreeze<HeadArmor>({
    id: 51,
    type: 'head',
    name: 'Piscine Mask+',
    blade: true,
    gunner: true,
    defense: 26,
    fireRes: -3,
    waterRes: 5,
    iceRes: 2,
    thunderRes: -4,
    dragonRes: 0,
    slots: 1,
    rarity: 4,
    price: 4700,
    maxDefense: 26,
    skillPoints: { oxygen: 10, currentres: 1 }
  }),
  deepFreeze<HeadArmor>({
    id: 52,
    type: 'head',
    name: 'Piscine Snorkel+',
    blade: true,
    gunner: true,
    defense: 15,
    fireRes: -3,
    waterRes: 10,
    iceRes: 2,
    thunderRes: -4,
    dragonRes: 0,
    slots: 0,
    rarity: 4,
    price: 4700,
    maxDefense: 15,
    skillPoints: { oxygen: 10, currentres: 3 }
  }),
  deepFreeze<HeadArmor>({
    id: 53,
    type: 'head',
    name: 'Chainmail Helm+',
    blade: true,
    gunner: true,
    defense: 30,
    fireRes: -1,
    waterRes: -2,
    iceRes: 4,
    thunderRes: -1,
    dragonRes: 1,
    slots: 2,
    rarity: 4,
    price: 5400,
    maxDefense: 30,
    skillPoints: { health: 2, combo_rate: 4, combo_plus: 3 }
  }),
  deepFreeze<HeadArmor>({
    id: 54,
    type: 'head',
    name: 'Chainmail Cap+',
    blade: true,
    gunner: true,
    defense: 18,
    fireRes: -1,
    waterRes: -1,
    iceRes: 9,
    thunderRes: -1,
    dragonRes: 1,
    slots: 2,
    rarity: 4,
    price: 5400,
    maxDefense: 18,
    skillPoints: { health: 3, combo_rate: 4, combo_plus: 2 }
  }),
  deepFreeze<HeadArmor>({
    id: 55,
    type: 'head',
    name: "Hunter's Helm+",
    blade: true,
    gunner: true,
    defense: 30,
    fireRes: 0,
    waterRes: -2,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 2,
    rarity: 4,
    price: 5400,
    maxDefense: 30,
    skillPoints: { psychic: 3, evasion: 1, water_res: -3, map: 2 }
  }),
  deepFreeze<HeadArmor>({
    id: 56,
    type: 'head',
    name: "Hunter's Cap+",
    blade: true,
    gunner: true,
    defense: 18,
    fireRes: 5,
    waterRes: -2,
    iceRes: 5,
    thunderRes: 5,
    dragonRes: 5,
    slots: 2,
    rarity: 4,
    price: 5400,
    maxDefense: 18,
    skillPoints: { psychic: 4, evasion: 2, water_res: -1, map: 2 }
  }),
  deepFreeze<HeadArmor>({
    id: 57,
    type: 'head',
    name: 'Bone Helm+',
    blade: true,
    gunner: true,
    defense: 34,
    fireRes: 3,
    waterRes: -2,
    iceRes: -1,
    thunderRes: 2,
    dragonRes: 3,
    slots: 2,
    rarity: 4,
    price: 6400,
    maxDefense: 34,
    skillPoints: {
      stamina: 1,
      expert: 2,
      hunger: 3,
      sleep: -2,
      perception: 1
    }
  }),
  deepFreeze<HeadArmor>({
    id: 58,
    type: 'head',
    name: 'Bone Cap+',
    blade: true,
    gunner: true,
    defense: 20,
    fireRes: 8,
    waterRes: -2,
    iceRes: -1,
    thunderRes: 2,
    dragonRes: 3,
    slots: 2,
    rarity: 4,
    price: 6400,
    maxDefense: 20,
    skillPoints: {
      stamina: 1,
      expert: 2,
      hunger: 3,
      sleep: -1,
      perception: 2
    }
  }),
  deepFreeze<HeadArmor>({
    id: 59,
    type: 'head',
    name: 'Alloy Helm+',
    blade: true,
    gunner: true,
    defense: 34,
    fireRes: 1,
    waterRes: 2,
    iceRes: -1,
    thunderRes: -2,
    dragonRes: -1,
    slots: 2,
    rarity: 4,
    price: 7100,
    maxDefense: 34,
    skillPoints: {
      expert: 3,
      sharpener: 2,
      speedsetup: 3,
      oxygen: -1
    }
  }),
  deepFreeze<HeadArmor>({
    id: 60,
    type: 'head',
    name: 'Alloy Cap+',
    blade: true,
    gunner: true,
    defense: 20,
    fireRes: 1,
    waterRes: 7,
    iceRes: -1,
    thunderRes: -2,
    dragonRes: -1,
    slots: 2,
    rarity: 4,
    price: 7100,
    maxDefense: 20,
    skillPoints: {
      'normal_s+': 2,
      expert: 3,
      speedsetup: 3,
      oxygen: -1
    }
  }),
  deepFreeze<HeadArmor>({
    id: 61,
    type: 'head',
    name: 'Jaggi Helm+',
    blade: true,
    gunner: true,
    defense: 38,
    fireRes: -3,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: 2,
    slots: 1,
    rarity: 5,
    price: 8000,
    maxDefense: 38,
    skillPoints: { attack: 4, stun: 2, gluttony: 2, cold_res: -3 }
  }),
  deepFreeze<HeadArmor>({
    id: 62,
    type: 'head',
    name: 'Jaggi Cap+',
    blade: true,
    gunner: true,
    defense: 22,
    fireRes: -3,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: 7,
    slots: 1,
    rarity: 5,
    price: 8000,
    maxDefense: 22,
    skillPoints: { attack: 5, stun: 3, gluttony: 2, cold_res: -1 }
  }),
  deepFreeze<HeadArmor>({
    id: 63,
    type: 'head',
    name: 'Rhenoplos Helm+',
    blade: true,
    gunner: true,
    defense: 38,
    fireRes: 3,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -2,
    dragonRes: 2,
    slots: 2,
    rarity: 5,
    price: 8500,
    maxDefense: 38,
    skillPoints: {
      expert: 1,
      wind_res: 3,
      eating: 1,
      'mud/snow': 2,
      thunderres: -2
    }
  }),
  deepFreeze<HeadArmor>({
    id: 64,
    type: 'head',
    name: 'Rhenoplos Cap+',
    blade: true,
    gunner: true,
    defense: 22,
    fireRes: 8,
    waterRes: 4,
    iceRes: 4,
    thunderRes: -2,
    dragonRes: 2,
    slots: 2,
    rarity: 5,
    price: 8500,
    maxDefense: 22,
    skillPoints: {
      recoil: 1,
      expert: 1,
      'crag_s+': 3,
      eating: 3,
      thunderres: -1
    }
  }),
  deepFreeze<HeadArmor>({
    id: 65,
    type: 'head',
    name: 'Qurupeco Helm+',
    blade: true,
    gunner: true,
    defense: 42,
    fireRes: 4,
    waterRes: -3,
    iceRes: -4,
    thunderRes: 0,
    dragonRes: 1,
    slots: 1,
    rarity: 5,
    price: 10000,
    maxDefense: 42,
    skillPoints: {
      expert: 1,
      defense: 2,
      'wide-range': 3,
      rec_level: 3,
      ice_res: -2
    }
  }),
  deepFreeze<HeadArmor>({
    id: 66,
    type: 'head',
    name: 'Qurupeco Cap+',
    blade: true,
    gunner: true,
    defense: 25,
    fireRes: 9,
    waterRes: -3,
    iceRes: -4,
    thunderRes: 0,
    dragonRes: 1,
    slots: 1,
    rarity: 5,
    price: 10000,
    maxDefense: 25,
    skillPoints: {
      expert: 1,
      defense: 1,
      'wide-range': 5,
      rec_level: 3,
      ice_res: -1
    }
  }),
  deepFreeze<HeadArmor>({
    id: 67,
    type: 'head',
    name: 'Ludroth Helm+',
    blade: true,
    gunner: true,
    defense: 44,
    fireRes: -4,
    waterRes: 4,
    iceRes: 0,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 5,
    price: 11800,
    maxDefense: 44,
    skillPoints: {
      expert: 1,
      hunger: -2,
      protection: 2,
      constitutn: 4,
      currentres: 2
    }
  }),
  deepFreeze<HeadArmor>({
    id: 68,
    type: 'head',
    name: 'Ludroth Cap+',
    blade: true,
    gunner: true,
    defense: 26,
    fireRes: -4,
    waterRes: 9,
    iceRes: 0,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 5,
    price: 11800,
    maxDefense: 26,
    skillPoints: {
      expert: 1,
      'pellet_s+': 4,
      hunger: -1,
      protection: 1,
      constitutn: 4
    }
  }),
  deepFreeze<HeadArmor>({
    id: 69,
    type: 'head',
    name: 'Baggi Helm+',
    blade: true,
    gunner: true,
    defense: 44,
    fireRes: -4,
    waterRes: -1,
    iceRes: 4,
    thunderRes: -1,
    dragonRes: 1,
    slots: 3,
    rarity: 5,
    price: 12300,
    maxDefense: 44,
    skillPoints: {
      tranquilzr: 1,
      fastcharge: 2,
      stun: -3,
      ice_res: 1
    }
  }),
  deepFreeze<HeadArmor>({
    id: 70,
    type: 'head',
    name: 'Baggi Cap+',
    blade: true,
    gunner: true,
    defense: 26,
    fireRes: -4,
    waterRes: -1,
    iceRes: 9,
    thunderRes: -1,
    dragonRes: 1,
    slots: 3,
    rarity: 5,
    price: 12300,
    maxDefense: 26,
    skillPoints: {
      pellets_up: 2,
      tranquilzr: 2,
      stun: -2,
      ice_res: 1
    }
  }),
  deepFreeze<HeadArmor>({
    id: 71,
    type: 'head',
    name: 'Barroth Helm+',
    blade: true,
    gunner: true,
    defense: 48,
    fireRes: 0,
    waterRes: 0,
    iceRes: -4,
    thunderRes: 4,
    dragonRes: 0,
    slots: 2,
    rarity: 5,
    price: 13800,
    maxDefense: 48,
    skillPoints: { stamina: 1, expert: -3, attack: 3, potential: 2 }
  }),
  deepFreeze<HeadArmor>({
    id: 72,
    type: 'head',
    name: 'Barroth Cap+',
    blade: true,
    gunner: true,
    defense: 28,
    fireRes: 5,
    waterRes: 5,
    iceRes: -4,
    thunderRes: 4,
    dragonRes: 0,
    slots: 2,
    rarity: 5,
    price: 13800,
    maxDefense: 28,
    skillPoints: { stamina: 1, expert: -1, attack: 4, potential: 3 }
  }),
  deepFreeze<HeadArmor>({
    id: 73,
    type: 'head',
    name: 'Gobul Helm+',
    blade: true,
    gunner: true,
    defense: 50,
    fireRes: -2,
    waterRes: 4,
    iceRes: 0,
    thunderRes: -4,
    dragonRes: 2,
    slots: 1,
    rarity: 5,
    price: 14800,
    maxDefense: 50,
    skillPoints: { rec_speed: -2, expert: 3, eating: 3, stun: 3 }
  }),
  deepFreeze<HeadArmor>({
    id: 74,
    type: 'head',
    name: 'Gobul Cap+',
    blade: true,
    gunner: true,
    defense: 30,
    fireRes: -2,
    waterRes: 9,
    iceRes: 0,
    thunderRes: -4,
    dragonRes: 2,
    slots: 1,
    rarity: 5,
    price: 14800,
    maxDefense: 30,
    skillPoints: { expert: 3, rec_level: -1, eating: 3, stun: 4 }
  }),
  deepFreeze<HeadArmor>({
    id: 75,
    type: 'head',
    name: 'Guild Bard Lobos+',
    blade: true,
    gunner: true,
    defense: 36,
    fireRes: 0,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 1,
    rarity: 6,
    price: 25000,
    maxDefense: 36,
    skillPoints: {
      fate: 1,
      carving: 1,
      tranquilzr: 4,
      protection: -5
    }
  }),
  deepFreeze<HeadArmor>({
    id: 76,
    type: 'head',
    name: 'Guild Bard Hat+',
    blade: true,
    gunner: true,
    defense: 22,
    fireRes: -10,
    waterRes: 10,
    iceRes: -10,
    thunderRes: 5,
    dragonRes: 10,
    slots: 1,
    rarity: 6,
    price: 25000,
    maxDefense: 22,
    skillPoints: {
      fate: 2,
      carving: 2,
      tranquilzr: 2,
      protection: -5
    }
  }),
  deepFreeze<HeadArmor>({
    id: 77,
    type: 'head',
    name: 'Rathian Helm+',
    blade: true,
    gunner: true,
    defense: 50,
    fireRes: 4,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 3,
    rarity: 5,
    price: 14800,
    maxDefense: 50,
    skillPoints: {
      hearing: 1,
      health: 1,
      protection: -3,
      fire_res: 2
    }
  }),
  deepFreeze<HeadArmor>({
    id: 78,
    type: 'head',
    name: 'Rathian Cap+',
    blade: true,
    gunner: true,
    defense: 30,
    fireRes: 9,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 3,
    rarity: 5,
    price: 14800,
    maxDefense: 30,
    skillPoints: {
      hearing: 2,
      health: 2,
      protection: -2,
      fire_res: 1
    }
  }),
  deepFreeze<HeadArmor>({
    id: 79,
    type: 'head',
    name: 'Gigginox Helm+',
    blade: true,
    gunner: true,
    defense: 54,
    fireRes: -4,
    waterRes: -1,
    iceRes: 2,
    thunderRes: 3,
    dragonRes: 0,
    slots: 1,
    rarity: 5,
    price: 15800,
    maxDefense: 54,
    skillPoints: { status: 2, poison: 3, health: -3, constitutn: 3 }
  }),
  deepFreeze<HeadArmor>({
    id: 80,
    type: 'head',
    name: 'Gigginox Cap+',
    blade: true,
    gunner: true,
    defense: 32,
    fireRes: -4,
    waterRes: -1,
    iceRes: 2,
    thunderRes: 8,
    dragonRes: 0,
    slots: 1,
    rarity: 5,
    price: 15800,
    maxDefense: 32,
    skillPoints: { status: 3, poison: 3, health: -1, constitutn: 4 }
  }),
  deepFreeze<HeadArmor>({
    id: 81,
    type: 'head',
    name: 'Ingot Helm+',
    blade: true,
    gunner: true,
    defense: 54,
    fireRes: -2,
    waterRes: -1,
    iceRes: 1,
    thunderRes: 3,
    dragonRes: 2,
    slots: 1,
    rarity: 5,
    price: 17500,
    maxDefense: 54,
    skillPoints: {
      sharpener: -1,
      guard_up: 3,
      wind_res: 3,
      thunderres: 4
    }
  }),
  deepFreeze<HeadArmor>({
    id: 82,
    type: 'head',
    name: 'Ingot Cap+',
    blade: true,
    gunner: true,
    defense: 32,
    fireRes: -2,
    waterRes: -1,
    iceRes: 1,
    thunderRes: 3,
    dragonRes: 7,
    slots: 1,
    rarity: 5,
    price: 17500,
    maxDefense: 32,
    skillPoints: {
      recoil: 3,
      guard_up: 3,
      reload_spd: -1,
      thunderres: 4
    }
  }),
  deepFreeze<HeadArmor>({
    id: 83,
    type: 'head',
    name: 'Dober Helm',
    blade: true,
    gunner: true,
    defense: 58,
    fireRes: -2,
    waterRes: -2,
    iceRes: 1,
    thunderRes: 1,
    dragonRes: 5,
    slots: 3,
    rarity: 6,
    price: 19000,
    maxDefense: 58,
    skillPoints: {
      stamina: 2,
      potential: -3,
      crit_draw: 1,
      dragon_res: 1
    }
  }),
  deepFreeze<HeadArmor>({
    id: 84,
    type: 'head',
    name: 'Dober Cap',
    blade: true,
    gunner: true,
    defense: 34,
    fireRes: -2,
    waterRes: -2,
    iceRes: 1,
    thunderRes: 1,
    dragonRes: 10,
    slots: 3,
    rarity: 6,
    price: 19000,
    maxDefense: 34,
    skillPoints: {
      pellets_up: 2,
      'pellet_s+': 2,
      potential: -2,
      dragon_res: 1
    }
  }),
  deepFreeze<HeadArmor>({
    id: 85,
    type: 'head',
    name: 'Lagiacrus Helm+',
    blade: true,
    gunner: true,
    defense: 58,
    fireRes: -4,
    waterRes: 2,
    iceRes: -1,
    thunderRes: 5,
    dragonRes: -2,
    slots: 1,
    rarity: 6,
    price: 18000,
    maxDefense: 58,
    skillPoints: {
      status: -3,
      elemental: 2,
      freeelemnt: 3,
      swimming: 3
    }
  }),
  deepFreeze<HeadArmor>({
    id: 86,
    type: 'head',
    name: 'Lagiacrus Cap+',
    blade: true,
    gunner: true,
    defense: 34,
    fireRes: -4,
    waterRes: 2,
    iceRes: -1,
    thunderRes: 10,
    dragonRes: -2,
    slots: 1,
    rarity: 6,
    price: 18000,
    maxDefense: 34,
    skillPoints: {
      status: -2,
      elemental: 2,
      rapid_fire: 2,
      swimming: 5
    }
  }),
  deepFreeze<HeadArmor>({
    id: 87,
    type: 'head',
    name: 'Rathalos Helm+',
    blade: true,
    gunner: true,
    defense: 58,
    fireRes: 4,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 3,
    rarity: 6,
    price: 18000,
    maxDefense: 58,
    skillPoints: { fencing: 1, expert: 2, defense: -3, heat_res: 1 }
  }),
  deepFreeze<HeadArmor>({
    id: 88,
    type: 'head',
    name: 'Rathalos Cap+',
    blade: true,
    gunner: true,
    defense: 34,
    fireRes: 9,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 3,
    rarity: 6,
    price: 18000,
    maxDefense: 34,
    skillPoints: {
      normals_up: 1,
      expert: 3,
      defense: -2,
      heat_res: 1
    }
  }),
  deepFreeze<HeadArmor>({
    id: 89,
    type: 'head',
    name: 'Barioth Helm+',
    blade: true,
    gunner: true,
    defense: 58,
    fireRes: -4,
    waterRes: 2,
    iceRes: 5,
    thunderRes: -3,
    dragonRes: 0,
    slots: 1,
    rarity: 6,
    price: 18000,
    maxDefense: 58,
    skillPoints: {
      evade_dist: 3,
      evasion: 2,
      heat_res: -3,
      cold_res: 3
    }
  }),
  deepFreeze<HeadArmor>({
    id: 90,
    type: 'head',
    name: 'Barioth Cap+',
    blade: true,
    gunner: true,
    defense: 34,
    fireRes: -4,
    waterRes: 2,
    iceRes: 10,
    thunderRes: -3,
    dragonRes: 0,
    slots: 1,
    rarity: 6,
    price: 18000,
    maxDefense: 34,
    skillPoints: {
      evade_dist: 4,
      evasion: 2,
      heat_res: -1,
      cold_res: 4
    }
  }),
  deepFreeze<HeadArmor>({
    id: 91,
    type: 'head',
    name: 'Diablos Helm+',
    blade: true,
    gunner: true,
    defense: 62,
    fireRes: 3,
    waterRes: -1,
    iceRes: -4,
    thunderRes: -1,
    dragonRes: -1,
    slots: 0,
    rarity: 6,
    price: 18800,
    maxDefense: 62,
    skillPoints: { elemental: -3, tremor_res: 5, crit_draw: 5 }
  }),
  deepFreeze<HeadArmor>({
    id: 92,
    type: 'head',
    name: 'Diablos Cap+',
    blade: true,
    gunner: true,
    defense: 37,
    fireRes: 3,
    waterRes: 2,
    iceRes: -4,
    thunderRes: 2,
    dragonRes: 2,
    slots: 0,
    rarity: 6,
    price: 18800,
    maxDefense: 37,
    skillPoints: { pierces_up: 5, 'pierce_s+': 5, elemental: -3 }
  }),
  deepFreeze<HeadArmor>({
    id: 93,
    type: 'head',
    name: 'Uragaan Helm+',
    blade: true,
    gunner: true,
    defense: 62,
    fireRes: 4,
    waterRes: -4,
    iceRes: -1,
    thunderRes: 1,
    dragonRes: -2,
    slots: 1,
    rarity: 6,
    price: 18800,
    maxDefense: 62,
    skillPoints: {
      punishdraw: 2,
      bomb_boost: 2,
      defense: 4,
      eating: -3
    }
  }),
  deepFreeze<HeadArmor>({
    id: 94,
    type: 'head',
    name: 'Uragaan Cap+',
    blade: true,
    gunner: true,
    defense: 37,
    fireRes: 9,
    waterRes: -4,
    iceRes: -1,
    thunderRes: 1,
    dragonRes: -2,
    slots: 1,
    rarity: 6,
    price: 18800,
    maxDefense: 37,
    skillPoints: {
      recoil: 6,
      bomb_boost: 1,
      defense: 3,
      eating: -1
    }
  }),
  deepFreeze<HeadArmor>({
    id: 95,
    type: 'head',
    name: 'Agnaktor Helm+',
    blade: true,
    gunner: true,
    defense: 62,
    fireRes: 5,
    waterRes: -4,
    iceRes: -2,
    thunderRes: 1,
    dragonRes: 0,
    slots: 0,
    rarity: 6,
    price: 19800,
    maxDefense: 62,
    skillPoints: {
      sharpness: 3,
      stamina: -2,
      guard: 5,
      flame_aura: 3
    }
  }),
  deepFreeze<HeadArmor>({
    id: 96,
    type: 'head',
    name: 'Agnaktor Cap+',
    blade: true,
    gunner: true,
    defense: 37,
    fireRes: 10,
    waterRes: -4,
    iceRes: -2,
    thunderRes: 1,
    dragonRes: 0,
    slots: 0,
    rarity: 6,
    price: 19800,
    maxDefense: 37,
    skillPoints: {
      normals_up: 4,
      'normal_s+': 4,
      stamina: -1,
      flame_aura: 4
    }
  }),
  deepFreeze<HeadArmor>({
    id: 97,
    type: 'head',
    name: 'Vangis Helm',
    blade: true,
    gunner: true,
    defense: 64,
    fireRes: 0,
    waterRes: 0,
    iceRes: 3,
    thunderRes: -4,
    dragonRes: -4,
    slots: 0,
    rarity: 7,
    price: 41500,
    maxDefense: 64,
    skillPoints: {
      handicraft: 4,
      hunger: -2,
      attack: 3,
      psychic: 4
    }
  }),
  deepFreeze<HeadArmor>({
    id: 98,
    type: 'head',
    name: 'Vangis Cap',
    blade: true,
    gunner: true,
    defense: 38,
    fireRes: 5,
    waterRes: 5,
    iceRes: 3,
    thunderRes: -4,
    dragonRes: -4,
    slots: 0,
    rarity: 7,
    price: 41500,
    maxDefense: 38,
    skillPoints: { loading: 5, hunger: -1, attack: 2, psychic: 5 }
  }),
  deepFreeze<HeadArmor>({
    id: 99,
    type: 'head',
    name: 'Damascus Helm',
    blade: true,
    gunner: true,
    defense: 62,
    fireRes: -2,
    waterRes: 0,
    iceRes: 2,
    thunderRes: -2,
    dragonRes: 3,
    slots: 3,
    rarity: 6,
    price: 32300,
    maxDefense: 62,
    skillPoints: {
      stamina: -3,
      punishdraw: 2,
      health: 1,
      guard_up: 1
    }
  }),
  deepFreeze<HeadArmor>({
    id: 100,
    type: 'head',
    name: 'Damascus Cap',
    blade: true,
    gunner: true,
    defense: 37,
    fireRes: -2,
    waterRes: 0,
    iceRes: 2,
    thunderRes: -2,
    dragonRes: 8,
    slots: 3,
    rarity: 6,
    price: 32300,
    maxDefense: 37,
    skillPoints: {
      stamina: -3,
      health: 1,
      guard_up: 1,
      reload_spd: 2
    }
  }),
  deepFreeze<HeadArmor>({
    id: 101,
    type: 'head',
    name: 'Helios Helm+',
    blade: true,
    gunner: true,
    defense: 66,
    fireRes: 0,
    waterRes: 5,
    iceRes: 3,
    thunderRes: -3,
    dragonRes: -4,
    slots: 3,
    rarity: 6,
    price: 26200,
    maxDefense: 66,
    skillPoints: {
      sharpness: -1,
      handicraft: 1,
      hearing: 2,
      protection: -3
    }
  }),
  deepFreeze<HeadArmor>({
    id: 102,
    type: 'head',
    name: 'Helios Cap+',
    blade: true,
    gunner: true,
    defense: 39,
    fireRes: 0,
    waterRes: 10,
    iceRes: 3,
    thunderRes: -3,
    dragonRes: -4,
    slots: 3,
    rarity: 6,
    price: 26200,
    maxDefense: 39,
    skillPoints: {
      recoil: -1,
      hearing: 2,
      loading: 1,
      protection: -3
    }
  }),
  deepFreeze<HeadArmor>({
    id: 103,
    type: 'head',
    name: 'Yamato Kabuto+',
    blade: true,
    gunner: true,
    defense: 66,
    fireRes: 4,
    waterRes: 0,
    iceRes: -3,
    thunderRes: 0,
    dragonRes: -4,
    slots: 3,
    rarity: 6,
    price: 27500,
    maxDefense: 66,
    skillPoints: {
      sharpness: 1,
      fastcharge: 1,
      rec_speed: 2,
      combo_rate: -3
    }
  }),
  deepFreeze<HeadArmor>({
    id: 104,
    type: 'head',
    name: 'Mutsu Eboshi+',
    blade: true,
    gunner: true,
    defense: 39,
    fireRes: 4,
    waterRes: 10,
    iceRes: -3,
    thunderRes: 10,
    dragonRes: -4,
    slots: 3,
    rarity: 6,
    price: 27500,
    maxDefense: 39,
    skillPoints: {
      recoil: 1,
      rec_speed: 1,
      'clust_s+': 2,
      combo_rate: -3
    }
  }),
  deepFreeze<HeadArmor>({
    id: 105,
    type: 'head',
    name: 'Escadora Wisdom',
    blade: true,
    gunner: true,
    defense: 70,
    fireRes: -1,
    waterRes: -1,
    iceRes: -1,
    thunderRes: 0,
    dragonRes: -5,
    slots: 2,
    rarity: 7,
    price: 66666,
    maxDefense: 70,
    skillPoints: {
      evade_dist: 2,
      freeelemnt: 1,
      rec_level: -3,
      blight_res: 3
    }
  }),
  deepFreeze<HeadArmor>({
    id: 106,
    type: 'head',
    name: 'Escadora Sagesse',
    blade: true,
    gunner: true,
    defense: 42,
    fireRes: 4,
    waterRes: 4,
    iceRes: 4,
    thunderRes: 0,
    dragonRes: -5,
    slots: 2,
    rarity: 7,
    price: 66666,
    maxDefense: 42,
    skillPoints: {
      evade_dist: 2,
      rapid_fire: 1,
      rec_level: -3,
      blight_res: 3
    }
  }),
  deepFreeze<HeadArmor>({
    id: 107,
    type: 'head',
    name: 'Chakra Earring',
    blade: true,
    gunner: true,
    defense: 18,
    fireRes: -10,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 10,
    slots: 3,
    rarity: 7,
    price: 33333,
    maxDefense: 18,
    skillPoints: {}
  }),
  deepFreeze<HeadArmor>({
    id: 108,
    type: 'head',
    name: 'Skull Mask',
    blade: true,
    gunner: true,
    defense: 7,
    fireRes: 3,
    waterRes: -2,
    iceRes: -2,
    thunderRes: -2,
    dragonRes: 3,
    slots: 0,
    rarity: 3,
    price: 5000,
    maxDefense: 7,
    maxLowRankDefense: 13,
    skillPoints: {},
    torsoUp: true
  }),
  deepFreeze<HeadArmor>({
    id: 109,
    type: 'head',
    name: 'Jaggi Mask',
    blade: true,
    gunner: true,
    defense: 5,
    fireRes: -4,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: -1,
    slots: 0,
    rarity: 3,
    price: 30000,
    maxDefense: 5,
    maxLowRankDefense: 12,
    skillPoints: { fate: 10 }
  }),
  deepFreeze<HeadArmor>({
    id: 110,
    type: 'head',
    name: 'Wyvernking Eyepatch',
    blade: true,
    gunner: true,
    defense: 8,
    fireRes: 2,
    waterRes: 2,
    iceRes: 2,
    thunderRes: 2,
    dragonRes: 2,
    slots: 3,
    rarity: 3,
    price: 10000,
    maxDefense: 8,
    maxLowRankDefense: 14,
    skillPoints: {}
  }),
  deepFreeze<HeadArmor>({
    id: 111,
    type: 'head',
    name: 'Shadow Shades',
    blade: true,
    gunner: true,
    defense: 28,
    fireRes: 2,
    waterRes: 2,
    iceRes: 2,
    thunderRes: 2,
    dragonRes: 2,
    slots: 3,
    rarity: 6,
    price: 15000,
    maxDefense: 28,
    skillPoints: { stun: 7 }
  }),
  deepFreeze<HeadArmor>({
    id: 112,
    type: 'head',
    name: 'Blast Earring',
    blade: true,
    gunner: true,
    defense: 10,
    fireRes: 0,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 0,
    rarity: 2,
    price: 5000,
    maxDefense: 10,
    skillPoints: { bomb_boost: 10 }
  }),
  deepFreeze<HeadArmor>({
    id: 113,
    type: 'head',
    name: 'Pursuit Earring',
    blade: true,
    gunner: true,
    defense: 10,
    fireRes: 0,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 0,
    rarity: 3,
    price: 10000,
    maxDefense: 10,
    skillPoints: { combo_rate: 20 }
  }),
  deepFreeze<HeadArmor>({
    id: 114,
    type: 'head',
    name: 'Hawkeye Earring',
    blade: true,
    gunner: true,
    defense: 10,
    fireRes: 0,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 0,
    rarity: 4,
    price: 15000,
    maxDefense: 10,
    skillPoints: { psychic: 15 }
  }),
  deepFreeze<HeadArmor>({
    id: 115,
    type: 'head',
    name: 'Grace Earring',
    blade: true,
    gunner: true,
    defense: 10,
    fireRes: 0,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 0,
    rarity: 5,
    price: 20000,
    maxDefense: 10,
    skillPoints: { 'wide-range': 20 }
  }),
  deepFreeze<HeadArmor>({
    id: 116,
    type: 'head',
    name: 'Sword Saint Earring',
    blade: true,
    gunner: true,
    defense: 10,
    fireRes: 0,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 0,
    rarity: 6,
    price: 25000,
    maxDefense: 10,
    skillPoints: { fencing: 10 }
  }),
  deepFreeze<HeadArmor>({
    id: 117,
    type: 'head',
    name: 'Barrage Earring',
    blade: true,
    gunner: true,
    defense: 10,
    fireRes: 0,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 0,
    rarity: 7,
    price: 30000,
    maxDefense: 10,
    skillPoints: { loading: 15 }
  })
];
