import { deepFreeze } from '../../utils';
import { HeadArmor } from './types';

export const HeadArmors: HeadArmor[] = [
  deepFreeze<HeadArmor>({
    id: 0,
    type: 'head',
    name: 'Leather Headgear',
    blade: true,
    gunner: true,
    defense: 1,
    fireRes: -1,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 3,
    dragonRes: 2,
    slots: 1,
    rarity: 1,
    skillPoints: [
      { skillId: 35, points: 1 },
      { skillId: 40, points: 2 },
      { skillId: 41, points: 2 },
      { skillId: 69, points: 3 }
    ],
    price: 150,
    maxDefense: 1,
    maxLowRankDefense: 9
  }),
  deepFreeze<HeadArmor>({
    id: 1,
    type: 'head',
    name: 'Piscine Mask',
    blade: true,
    gunner: true,
    defense: 3,
    fireRes: -2,
    waterRes: 4,
    iceRes: 2,
    thunderRes: -3,
    dragonRes: 0,
    slots: 0,
    rarity: 1,
    skillPoints: [
      { skillId: 78, points: 10 },
      { skillId: 79, points: 1 }
    ],
    price: 300,
    maxDefense: 3,
    maxLowRankDefense: 9
  }),
  deepFreeze<HeadArmor>({
    id: 2,
    type: 'head',
    name: 'Chainmail Headgear',
    blade: true,
    gunner: true,
    defense: 2,
    fireRes: -1,
    waterRes: -1,
    iceRes: 3,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 1,
    skillPoints: [
      { skillId: 23, points: 1 },
      { skillId: 70, points: 1 },
      { skillId: 71, points: 6 },
      { skillId: 72, points: 1 }
    ],
    price: 200,
    maxDefense: 2,
    maxLowRankDefense: 9
  }),
  deepFreeze<HeadArmor>({
    id: 3,
    type: 'head',
    name: "Hunter's Helm",
    blade: true,
    gunner: true,
    defense: 6,
    fireRes: -1,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: -1,
    slots: 1,
    rarity: 1,
    skillPoints: [
      { skillId: 42, points: 4 },
      { skillId: 62, points: -2 },
      { skillId: 68, points: 2 },
      { skillId: 75, points: 1 }
    ],
    price: 500,
    maxDefense: 6,
    maxLowRankDefense: 20
  }),
  deepFreeze<HeadArmor>({
    id: 4,
    type: 'head',
    name: "Hunter's Cap",
    blade: true,
    gunner: true,
    defense: 3,
    fireRes: 4,
    waterRes: -1,
    iceRes: 4,
    thunderRes: 4,
    dragonRes: 4,
    slots: 1,
    rarity: 1,
    skillPoints: [
      { skillId: 42, points: 5 },
      { skillId: 62, points: -1 },
      { skillId: 68, points: 1 },
      { skillId: 75, points: 2 }
    ],
    price: 500,
    maxDefense: 3,
    maxLowRankDefense: 10
  }),
  deepFreeze<HeadArmor>({
    id: 5,
    type: 'head',
    name: 'Bone Helm',
    blade: true,
    gunner: true,
    defense: 8,
    fireRes: 2,
    waterRes: -2,
    iceRes: -1,
    thunderRes: 2,
    dragonRes: 3,
    slots: 1,
    rarity: 1,
    skillPoints: [
      { skillId: 34, points: 4 },
      { skillId: 54, points: -2 },
      { skillId: 73, points: 1 },
      { skillId: 77, points: 2 }
    ],
    price: 750,
    maxDefense: 8,
    maxLowRankDefense: 22
  }),
  deepFreeze<HeadArmor>({
    id: 6,
    type: 'head',
    name: 'Bone Cap',
    blade: true,
    gunner: true,
    defense: 4,
    fireRes: 7,
    waterRes: -2,
    iceRes: -1,
    thunderRes: 2,
    dragonRes: 3,
    slots: 1,
    rarity: 1,
    skillPoints: [
      { skillId: 34, points: 5 },
      { skillId: 54, points: -1 },
      { skillId: 73, points: 2 },
      { skillId: 77, points: 1 }
    ],
    price: 750,
    maxDefense: 4,
    maxLowRankDefense: 11
  }),
  deepFreeze<HeadArmor>({
    id: 7,
    type: 'head',
    name: 'Alloy Helm',
    blade: true,
    gunner: true,
    defense: 8,
    fireRes: 1,
    waterRes: 1,
    iceRes: -1,
    thunderRes: -2,
    dragonRes: -1,
    slots: 2,
    rarity: 1,
    skillPoints: [
      { skillId: 25, points: 1 },
      { skillId: 26, points: 3 },
      { skillId: 76, points: 1 },
      { skillId: 78, points: -2 }
    ],
    price: 1000,
    maxDefense: 8,
    maxLowRankDefense: 22
  }),
  deepFreeze<HeadArmor>({
    id: 8,
    type: 'head',
    name: 'Alloy Cap',
    blade: true,
    gunner: true,
    defense: 4,
    fireRes: 1,
    waterRes: 6,
    iceRes: -1,
    thunderRes: -2,
    dragonRes: -1,
    slots: 2,
    rarity: 1,
    skillPoints: [
      { skillId: 7, points: 3 },
      { skillId: 25, points: 1 },
      { skillId: 76, points: 2 },
      { skillId: 78, points: -1 }
    ],
    price: 1000,
    maxDefense: 4,
    maxLowRankDefense: 11
  }),
  deepFreeze<HeadArmor>({
    id: 9,
    type: 'head',
    name: 'Jaggi Helm',
    blade: true,
    gunner: true,
    defense: 10,
    fireRes: -3,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 35, points: 3 },
      { skillId: 55, points: 2 },
      { skillId: 58, points: 2 },
      { skillId: 67, points: -2 }
    ],
    price: 1200,
    maxDefense: 10,
    maxLowRankDefense: 24
  }),
  deepFreeze<HeadArmor>({
    id: 10,
    type: 'head',
    name: 'Jaggi Cap',
    blade: true,
    gunner: true,
    defense: 5,
    fireRes: -3,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: 6,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 35, points: 4 },
      { skillId: 55, points: 1 },
      { skillId: 58, points: 3 },
      { skillId: 67, points: -1 }
    ],
    price: 1200,
    maxDefense: 5,
    maxLowRankDefense: 12
  }),
  deepFreeze<HeadArmor>({
    id: 11,
    type: 'head',
    name: 'Rhenoplos Helm',
    blade: true,
    gunner: true,
    defense: 12,
    fireRes: 2,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: 2,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 35, points: 1 },
      { skillId: 39, points: 3 },
      { skillId: 46, points: 1 },
      { skillId: 56, points: 2 },
      { skillId: 63, points: -2 }
    ],
    price: 1400,
    maxDefense: 12,
    maxLowRankDefense: 24
  }),
  deepFreeze<HeadArmor>({
    id: 12,
    type: 'head',
    name: 'Rhenoplos Cap',
    blade: true,
    gunner: true,
    defense: 6,
    fireRes: 7,
    waterRes: 4,
    iceRes: 4,
    thunderRes: -1,
    dragonRes: 2,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 3, points: 3 },
      { skillId: 31, points: 3 },
      { skillId: 35, points: 1 },
      { skillId: 46, points: 1 },
      { skillId: 63, points: -1 }
    ],
    price: 1400,
    maxDefense: 6,
    maxLowRankDefense: 12
  }),
  deepFreeze<HeadArmor>({
    id: 13,
    type: 'head',
    name: 'Qurupeco Helm',
    blade: true,
    gunner: true,
    defense: 12,
    fireRes: 2,
    waterRes: -2,
    iceRes: -3,
    thunderRes: 0,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 36, points: 4 },
      { skillId: 43, points: 1 },
      { skillId: 44, points: 1 },
      { skillId: 64, points: -3 }
    ],
    price: 1700,
    maxDefense: 12,
    maxLowRankDefense: 24
  }),
  deepFreeze<HeadArmor>({
    id: 14,
    type: 'head',
    name: 'Qurupeco Cap',
    blade: true,
    gunner: true,
    defense: 6,
    fireRes: 7,
    waterRes: -2,
    iceRes: -3,
    thunderRes: 0,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 36, points: 3 },
      { skillId: 43, points: 3 },
      { skillId: 44, points: 2 },
      { skillId: 64, points: -1 }
    ],
    price: 1700,
    maxDefense: 6,
    maxLowRankDefense: 12
  }),
  deepFreeze<HeadArmor>({
    id: 15,
    type: 'head',
    name: 'Ludroth Helm',
    blade: true,
    gunner: true,
    defense: 13,
    fireRes: -3,
    waterRes: 2,
    iceRes: 0,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 37, points: 1 },
      { skillId: 49, points: 3 },
      { skillId: 61, points: -4 },
      { skillId: 79, points: 1 }
    ],
    price: 2200,
    maxDefense: 13,
    maxLowRankDefense: 25
  }),
  deepFreeze<HeadArmor>({
    id: 16,
    type: 'head',
    name: 'Ludroth Cap',
    blade: true,
    gunner: true,
    defense: 7,
    fireRes: -3,
    waterRes: 7,
    iceRes: 0,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 30, points: 2 },
      { skillId: 37, points: 2 },
      { skillId: 49, points: 3 },
      { skillId: 61, points: -2 }
    ],
    price: 2200,
    maxDefense: 7,
    maxLowRankDefense: 13
  }),
  deepFreeze<HeadArmor>({
    id: 17,
    type: 'head',
    name: 'Baggi Helm',
    blade: true,
    gunner: true,
    defense: 13,
    fireRes: -3,
    waterRes: -1,
    iceRes: 3,
    thunderRes: -1,
    dragonRes: 1,
    slots: 0,
    rarity: 2,
    skillPoints: [
      { skillId: 17, points: 4 },
      { skillId: 18, points: 2 },
      { skillId: 35, points: 1 },
      { skillId: 55, points: -2 },
      { skillId: 64, points: 2 }
    ],
    price: 2400,
    maxDefense: 13,
    maxLowRankDefense: 25
  }),
  deepFreeze<HeadArmor>({
    id: 18,
    type: 'head',
    name: 'Baggi Cap',
    blade: true,
    gunner: true,
    defense: 7,
    fireRes: -3,
    waterRes: 1,
    iceRes: 8,
    thunderRes: -1,
    dragonRes: 1,
    slots: 0,
    rarity: 2,
    skillPoints: [
      { skillId: 6, points: 3 },
      { skillId: 17, points: 2 },
      { skillId: 35, points: 1 },
      { skillId: 55, points: -2 },
      { skillId: 64, points: 3 }
    ],
    price: 2400,
    maxDefense: 7,
    maxLowRankDefense: 13
  }),
  deepFreeze<HeadArmor>({
    id: 19,
    type: 'head',
    name: 'Barroth Helm',
    blade: true,
    gunner: true,
    defense: 15,
    fireRes: 0,
    waterRes: 0,
    iceRes: -3,
    thunderRes: 3,
    dragonRes: 0,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 13, points: 2 },
      { skillId: 25, points: -2 },
      { skillId: 35, points: 4 },
      { skillId: 45, points: 1 }
    ],
    price: 3200,
    maxDefense: 15,
    maxLowRankDefense: 27
  }),
  deepFreeze<HeadArmor>({
    id: 20,
    type: 'head',
    name: 'Barroth Cap',
    blade: true,
    gunner: true,
    defense: 8,
    fireRes: 5,
    waterRes: 5,
    iceRes: -3,
    thunderRes: 3,
    dragonRes: 0,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 13, points: 2 },
      { skillId: 25, points: -2 },
      { skillId: 35, points: 4 },
      { skillId: 45, points: 1 }
    ],
    price: 3200,
    maxDefense: 8,
    maxLowRankDefense: 14
  }),
  deepFreeze<HeadArmor>({
    id: 21,
    type: 'head',
    name: 'Gobul Helm',
    blade: true,
    gunner: true,
    defense: 16,
    fireRes: -2,
    waterRes: 3,
    iceRes: 0,
    thunderRes: -3,
    dragonRes: 2,
    slots: 2,
    rarity: 2,
    skillPoints: [
      { skillId: 24, points: -2 },
      { skillId: 46, points: 3 },
      { skillId: 55, points: 1 },
      { skillId: 62, points: 1 }
    ],
    price: 3600,
    maxDefense: 16,
    maxLowRankDefense: 28
  }),
  deepFreeze<HeadArmor>({
    id: 22,
    type: 'head',
    name: 'Gobul Cap',
    blade: true,
    gunner: true,
    defense: 8,
    fireRes: -2,
    waterRes: 8,
    iceRes: 0,
    thunderRes: -3,
    dragonRes: 2,
    slots: 2,
    rarity: 2,
    skillPoints: [
      { skillId: 24, points: -1 },
      { skillId: 46, points: 4 },
      { skillId: 55, points: 1 },
      { skillId: 62, points: 1 }
    ],
    price: 3600,
    maxDefense: 8,
    maxLowRankDefense: 14
  }),
  deepFreeze<HeadArmor>({
    id: 23,
    type: 'head',
    name: "Ranger's Headgear",
    blade: true,
    gunner: true,
    defense: 15,
    fireRes: 0,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 0,
    rarity: 3,
    skillPoints: [
      { skillId: 12, points: -3 },
      { skillId: 15, points: 2 },
      { skillId: 38, points: 5 },
      { skillId: 41, points: 2 }
    ],
    price: 10000,
    maxDefense: 15,
    maxLowRankDefense: 27
  }),
  deepFreeze<HeadArmor>({
    id: 24,
    type: 'head',
    name: "Archer's Turban",
    blade: true,
    gunner: true,
    defense: 8,
    fireRes: 10,
    waterRes: -10,
    iceRes: 5,
    thunderRes: -10,
    dragonRes: 10,
    slots: 0,
    rarity: 3,
    skillPoints: [
      { skillId: 12, points: -1 },
      { skillId: 15, points: 4 },
      { skillId: 38, points: 5 },
      { skillId: 41, points: 2 }
    ],
    price: 10000,
    maxDefense: 8,
    maxLowRankDefense: 14
  }),
  deepFreeze<HeadArmor>({
    id: 25,
    type: 'head',
    name: 'Guild Bard Lobos',
    blade: true,
    gunner: true,
    defense: 15,
    fireRes: 0,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 0,
    rarity: 3,
    skillPoints: [
      { skillId: 12, points: 2 },
      { skillId: 42, points: 2 },
      { skillId: 44, points: 4 },
      { skillId: 57, points: -3 }
    ],
    price: 10000,
    maxDefense: 15,
    maxLowRankDefense: 27
  }),
  deepFreeze<HeadArmor>({
    id: 26,
    type: 'head',
    name: 'Guild Bard Hat',
    blade: true,
    gunner: true,
    defense: 8,
    fireRes: -10,
    waterRes: 10,
    iceRes: -10,
    thunderRes: 5,
    dragonRes: 10,
    slots: 0,
    rarity: 3,
    skillPoints: [
      { skillId: 12, points: 3 },
      { skillId: 42, points: 3 },
      { skillId: 44, points: 4 },
      { skillId: 57, points: -1 }
    ],
    price: 10000,
    maxDefense: 8,
    maxLowRankDefense: 14
  }),
  deepFreeze<HeadArmor>({
    id: 27,
    type: 'head',
    name: 'Rathian Helm',
    blade: true,
    gunner: true,
    defense: 16,
    fireRes: 3,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 11, points: 1 },
      { skillId: 23, points: 2 },
      { skillId: 37, points: -2 },
      { skillId: 61, points: 4 }
    ],
    price: 3600,
    maxDefense: 16,
    maxLowRankDefense: 28
  }),
  deepFreeze<HeadArmor>({
    id: 28,
    type: 'head',
    name: 'Rathian Cap',
    blade: true,
    gunner: true,
    defense: 8,
    fireRes: 8,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 11, points: 1 },
      { skillId: 23, points: 2 },
      { skillId: 37, points: -1 },
      { skillId: 61, points: 5 }
    ],
    price: 3600,
    maxDefense: 8,
    maxLowRankDefense: 14
  }),
  deepFreeze<HeadArmor>({
    id: 29,
    type: 'head',
    name: 'Gigginox Helm',
    blade: true,
    gunner: true,
    defense: 18,
    fireRes: -4,
    waterRes: 0,
    iceRes: 2,
    thunderRes: 2,
    dragonRes: -1,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 9, points: 2 },
      { skillId: 22, points: 2 },
      { skillId: 23, points: -2 },
      { skillId: 49, points: 3 }
    ],
    price: 4100,
    maxDefense: 18,
    maxLowRankDefense: 30
  }),
  deepFreeze<HeadArmor>({
    id: 30,
    type: 'head',
    name: 'Gigginox Cap',
    blade: true,
    gunner: true,
    defense: 9,
    fireRes: -4,
    waterRes: 0,
    iceRes: 2,
    thunderRes: 7,
    dragonRes: -1,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 9, points: 2 },
      { skillId: 22, points: 2 },
      { skillId: 23, points: -1 },
      { skillId: 49, points: 4 }
    ],
    price: 4100,
    maxDefense: 9,
    maxLowRankDefense: 15
  }),
  deepFreeze<HeadArmor>({
    id: 31,
    type: 'head',
    name: 'Ingot Helm',
    blade: true,
    gunner: true,
    defense: 18,
    fireRes: -2,
    waterRes: -1,
    iceRes: 1,
    thunderRes: 3,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 26, points: -2 },
      { skillId: 28, points: 2 },
      { skillId: 39, points: 4 },
      { skillId: 63, points: 1 }
    ],
    price: 5000,
    maxDefense: 18,
    maxLowRankDefense: 28
  }),
  deepFreeze<HeadArmor>({
    id: 32,
    type: 'head',
    name: 'Ingot Cap',
    blade: true,
    gunner: true,
    defense: 9,
    fireRes: -2,
    waterRes: -1,
    iceRes: 1,
    thunderRes: 3,
    dragonRes: 6,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 3, points: 4 },
      { skillId: 28, points: 2 },
      { skillId: 29, points: -2 },
      { skillId: 63, points: 1 }
    ],
    price: 5000,
    maxDefense: 9,
    maxLowRankDefense: 14
  }),
  deepFreeze<HeadArmor>({
    id: 33,
    type: 'head',
    name: 'Lagiacrus Helm',
    blade: true,
    gunner: true,
    defense: 20,
    fireRes: -3,
    waterRes: 2,
    iceRes: -1,
    thunderRes: 4,
    dragonRes: -2,
    slots: 2,
    rarity: 3,
    skillPoints: [
      { skillId: 0, points: 2 },
      { skillId: 9, points: -2 },
      { skillId: 10, points: 1 },
      { skillId: 50, points: 3 }
    ],
    price: 5600,
    maxDefense: 20,
    maxLowRankDefense: 30
  }),
  deepFreeze<HeadArmor>({
    id: 34,
    type: 'head',
    name: 'Lagiacrus Cap',
    blade: true,
    gunner: true,
    defense: 10,
    fireRes: -3,
    waterRes: 2,
    iceRes: -1,
    thunderRes: 9,
    dragonRes: -2,
    slots: 2,
    rarity: 3,
    skillPoints: [
      { skillId: 4, points: 2 },
      { skillId: 9, points: -2 },
      { skillId: 10, points: 1 },
      { skillId: 50, points: 3 }
    ],
    price: 5600,
    maxDefense: 10,
    maxLowRankDefense: 15
  }),
  deepFreeze<HeadArmor>({
    id: 35,
    type: 'head',
    name: 'Rathalos Helm',
    blade: true,
    gunner: true,
    defense: 20,
    fireRes: 3,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 1,
    rarity: 3,
    skillPoints: [
      { skillId: 25, points: 2 },
      { skillId: 35, points: 1 },
      { skillId: 36, points: -4 },
      { skillId: 66, points: 2 }
    ],
    price: 5600,
    maxDefense: 20,
    maxLowRankDefense: 30
  }),
  deepFreeze<HeadArmor>({
    id: 36,
    type: 'head',
    name: 'Rathalos Cap',
    blade: true,
    gunner: true,
    defense: 10,
    fireRes: 8,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 1,
    rarity: 3,
    skillPoints: [
      { skillId: 25, points: 2 },
      { skillId: 35, points: 2 },
      { skillId: 36, points: -2 },
      { skillId: 66, points: 3 }
    ],
    price: 5600,
    maxDefense: 10,
    maxLowRankDefense: 15
  }),
  deepFreeze<HeadArmor>({
    id: 37,
    type: 'head',
    name: 'Barioth Helm',
    blade: true,
    gunner: true,
    defense: 20,
    fireRes: -4,
    waterRes: 2,
    iceRes: 4,
    thunderRes: -3,
    dragonRes: 0,
    slots: 1,
    rarity: 3,
    skillPoints: [
      { skillId: 13, points: 1 },
      { skillId: 44, points: 3 },
      { skillId: 66, points: -4 },
      { skillId: 67, points: 1 }
    ],
    price: 5600,
    maxDefense: 20,
    maxLowRankDefense: 30
  }),
  deepFreeze<HeadArmor>({
    id: 38,
    type: 'head',
    name: 'Barioth Cap',
    blade: true,
    gunner: true,
    defense: 10,
    fireRes: -4,
    waterRes: 2,
    iceRes: 9,
    thunderRes: -3,
    dragonRes: 0,
    slots: 1,
    rarity: 3,
    skillPoints: [
      { skillId: 13, points: 1 },
      { skillId: 44, points: 1 },
      { skillId: 66, points: -2 },
      { skillId: 67, points: 5 }
    ],
    price: 5600,
    maxDefense: 10,
    maxLowRankDefense: 15
  }),
  deepFreeze<HeadArmor>({
    id: 39,
    type: 'head',
    name: 'Diablos Helm',
    blade: true,
    gunner: true,
    defense: 22,
    fireRes: 2,
    waterRes: -1,
    iceRes: -3,
    thunderRes: -1,
    dragonRes: -1,
    slots: 1,
    rarity: 3,
    skillPoints: [
      { skillId: 10, points: -3 },
      { skillId: 47, points: 4 },
      { skillId: 48, points: 2 }
    ],
    price: 6300,
    maxDefense: 22,
    maxLowRankDefense: 30
  }),
  deepFreeze<HeadArmor>({
    id: 40,
    type: 'head',
    name: 'Diablos Cap',
    blade: true,
    gunner: true,
    defense: 11,
    fireRes: 2,
    waterRes: 2,
    iceRes: -3,
    thunderRes: 2,
    dragonRes: 2,
    slots: 1,
    rarity: 3,
    skillPoints: [
      { skillId: 5, points: 4 },
      { skillId: 8, points: 2 },
      { skillId: 10, points: -3 }
    ],
    price: 6300,
    maxDefense: 11,
    maxLowRankDefense: 15
  }),
  deepFreeze<HeadArmor>({
    id: 41,
    type: 'head',
    name: 'Uragaan Helm',
    blade: true,
    gunner: true,
    defense: 22,
    fireRes: 3,
    waterRes: -4,
    iceRes: -1,
    thunderRes: 1,
    dragonRes: -2,
    slots: 1,
    rarity: 3,
    skillPoints: [
      { skillId: 19, points: 2 },
      { skillId: 33, points: 2 },
      { skillId: 36, points: 2 },
      { skillId: 46, points: -3 }
    ],
    price: 6300,
    maxDefense: 22,
    maxLowRankDefense: 30
  }),
  deepFreeze<HeadArmor>({
    id: 42,
    type: 'head',
    name: 'Uragaan Cap',
    blade: true,
    gunner: true,
    defense: 11,
    fireRes: 3,
    waterRes: -4,
    iceRes: -1,
    thunderRes: 1,
    dragonRes: -2,
    slots: 1,
    rarity: 3,
    skillPoints: [
      { skillId: 3, points: 3 },
      { skillId: 33, points: 2 },
      { skillId: 36, points: 3 },
      { skillId: 46, points: -1 }
    ],
    price: 6300,
    maxDefense: 11,
    maxLowRankDefense: 15
  }),
  deepFreeze<HeadArmor>({
    id: 43,
    type: 'head',
    name: 'Agnaktor Helm',
    blade: true,
    gunner: true,
    defense: 22,
    fireRes: 4,
    waterRes: -4,
    iceRes: -2,
    thunderRes: 1,
    dragonRes: 0,
    slots: 0,
    rarity: 3,
    skillPoints: [
      { skillId: 13, points: -3 },
      { skillId: 27, points: 3 },
      { skillId: 28, points: 2 },
      { skillId: 52, points: 3 }
    ],
    price: 7200,
    maxDefense: 22,
    maxLowRankDefense: 30
  }),
  deepFreeze<HeadArmor>({
    id: 44,
    type: 'head',
    name: 'Agnaktor Cap',
    blade: true,
    gunner: true,
    defense: 11,
    fireRes: 9,
    waterRes: -4,
    iceRes: -2,
    thunderRes: 1,
    dragonRes: 0,
    slots: 0,
    rarity: 3,
    skillPoints: [
      { skillId: 13, points: -1 },
      { skillId: 28, points: 3 },
      { skillId: 29, points: 4 },
      { skillId: 52, points: 3 }
    ],
    price: 7200,
    maxDefense: 11,
    maxLowRankDefense: 15
  }),
  deepFreeze<HeadArmor>({
    id: 45,
    type: 'head',
    name: 'Helios Helm',
    blade: true,
    gunner: true,
    defense: 24,
    fireRes: 0,
    waterRes: 4,
    iceRes: 3,
    thunderRes: -3,
    dragonRes: -4,
    slots: 0,
    rarity: 3,
    skillPoints: [
      { skillId: 0, points: -2 },
      { skillId: 1, points: 2 },
      { skillId: 11, points: 3 },
      { skillId: 37, points: -4 }
    ],
    price: 11000,
    maxDefense: 24,
    maxLowRankDefense: 32
  }),
  deepFreeze<HeadArmor>({
    id: 46,
    type: 'head',
    name: 'Helios Cap',
    blade: true,
    gunner: true,
    defense: 12,
    fireRes: 0,
    waterRes: 9,
    iceRes: 3,
    thunderRes: -3,
    dragonRes: -4,
    slots: 0,
    rarity: 3,
    skillPoints: [
      { skillId: 3, points: -2 },
      { skillId: 11, points: 3 },
      { skillId: 14, points: 2 },
      { skillId: 37, points: -4 }
    ],
    price: 11000,
    maxDefense: 12,
    maxLowRankDefense: 16
  }),
  deepFreeze<HeadArmor>({
    id: 47,
    type: 'head',
    name: 'Yamato Kabuto',
    blade: true,
    gunner: true,
    defense: 24,
    fireRes: 3,
    waterRes: 0,
    iceRes: -3,
    thunderRes: 0,
    dragonRes: -3,
    slots: 1,
    rarity: 3,
    skillPoints: [
      { skillId: 0, points: 1 },
      { skillId: 18, points: 1 },
      { skillId: 24, points: 2 },
      { skillId: 71, points: -5 }
    ],
    price: 12000,
    maxDefense: 24,
    maxLowRankDefense: 32
  }),
  deepFreeze<HeadArmor>({
    id: 48,
    type: 'head',
    name: 'Mutsu Eboshi',
    blade: true,
    gunner: true,
    defense: 12,
    fireRes: 3,
    waterRes: 10,
    iceRes: -3,
    thunderRes: 10,
    dragonRes: -3,
    slots: 1,
    rarity: 3,
    skillPoints: [
      { skillId: 3, points: 1 },
      { skillId: 24, points: 2 },
      { skillId: 32, points: 3 },
      { skillId: 71, points: -3 }
    ],
    price: 12000,
    maxDefense: 12,
    maxLowRankDefense: 16
  }),
  deepFreeze<HeadArmor>({
    id: 49,
    type: 'head',
    name: 'Leather Helm+',
    blade: true,
    gunner: true,
    defense: 26,
    fireRes: -2,
    waterRes: 0,
    iceRes: -2,
    thunderRes: 3,
    dragonRes: 2,
    slots: 2,
    rarity: 4,
    skillPoints: [
      { skillId: 40, points: 2 },
      { skillId: 41, points: 2 },
      { skillId: 69, points: 4 }
    ],
    price: 4600,
    maxDefense: 26
  }),
  deepFreeze<HeadArmor>({
    id: 50,
    type: 'head',
    name: 'Leather Cap+',
    blade: true,
    gunner: true,
    defense: 15,
    fireRes: -2,
    waterRes: 0,
    iceRes: -2,
    thunderRes: 8,
    dragonRes: 2,
    slots: 2,
    rarity: 4,
    skillPoints: [
      { skillId: 40, points: 1 },
      { skillId: 41, points: 1 },
      { skillId: 69, points: 6 }
    ],
    price: 4600,
    maxDefense: 15
  }),
  deepFreeze<HeadArmor>({
    id: 51,
    type: 'head',
    name: 'Piscine Mask+',
    blade: true,
    gunner: true,
    defense: 26,
    fireRes: -3,
    waterRes: 5,
    iceRes: 2,
    thunderRes: -4,
    dragonRes: 0,
    slots: 1,
    rarity: 4,
    skillPoints: [
      { skillId: 78, points: 10 },
      { skillId: 79, points: 1 }
    ],
    price: 4700,
    maxDefense: 26
  }),
  deepFreeze<HeadArmor>({
    id: 52,
    type: 'head',
    name: 'Piscine Snorkel+',
    blade: true,
    gunner: true,
    defense: 15,
    fireRes: -3,
    waterRes: 10,
    iceRes: 2,
    thunderRes: -4,
    dragonRes: 0,
    slots: 0,
    rarity: 4,
    skillPoints: [
      { skillId: 78, points: 10 },
      { skillId: 79, points: 3 }
    ],
    price: 4700,
    maxDefense: 15
  }),
  deepFreeze<HeadArmor>({
    id: 53,
    type: 'head',
    name: 'Chainmail Helm+',
    blade: true,
    gunner: true,
    defense: 30,
    fireRes: -1,
    waterRes: -2,
    iceRes: 4,
    thunderRes: -1,
    dragonRes: 1,
    slots: 2,
    rarity: 4,
    skillPoints: [
      { skillId: 23, points: 2 },
      { skillId: 71, points: 4 },
      { skillId: 72, points: 3 }
    ],
    price: 5400,
    maxDefense: 30
  }),
  deepFreeze<HeadArmor>({
    id: 54,
    type: 'head',
    name: 'Chainmail Cap+',
    blade: true,
    gunner: true,
    defense: 18,
    fireRes: -1,
    waterRes: -1,
    iceRes: 9,
    thunderRes: -1,
    dragonRes: 1,
    slots: 2,
    rarity: 4,
    skillPoints: [
      { skillId: 23, points: 3 },
      { skillId: 71, points: 4 },
      { skillId: 72, points: 2 }
    ],
    price: 5400,
    maxDefense: 18
  }),
  deepFreeze<HeadArmor>({
    id: 55,
    type: 'head',
    name: "Hunter's Helm+",
    blade: true,
    gunner: true,
    defense: 30,
    fireRes: 0,
    waterRes: -2,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 2,
    rarity: 4,
    skillPoints: [
      { skillId: 42, points: 3 },
      { skillId: 44, points: 1 },
      { skillId: 62, points: -3 },
      { skillId: 68, points: 2 }
    ],
    price: 5400,
    maxDefense: 30
  }),
  deepFreeze<HeadArmor>({
    id: 56,
    type: 'head',
    name: "Hunter's Cap+",
    blade: true,
    gunner: true,
    defense: 18,
    fireRes: 5,
    waterRes: -2,
    iceRes: 5,
    thunderRes: 5,
    dragonRes: 5,
    slots: 2,
    rarity: 4,
    skillPoints: [
      { skillId: 42, points: 4 },
      { skillId: 44, points: 2 },
      { skillId: 62, points: -1 },
      { skillId: 68, points: 2 }
    ],
    price: 5400,
    maxDefense: 18
  }),
  deepFreeze<HeadArmor>({
    id: 57,
    type: 'head',
    name: 'Bone Helm+',
    blade: true,
    gunner: true,
    defense: 34,
    fireRes: 3,
    waterRes: -2,
    iceRes: -1,
    thunderRes: 2,
    dragonRes: 3,
    slots: 2,
    rarity: 4,
    skillPoints: [
      { skillId: 13, points: 1 },
      { skillId: 25, points: 2 },
      { skillId: 34, points: 3 },
      { skillId: 54, points: -2 },
      { skillId: 77, points: 1 }
    ],
    price: 6400,
    maxDefense: 34
  }),
  deepFreeze<HeadArmor>({
    id: 58,
    type: 'head',
    name: 'Bone Cap+',
    blade: true,
    gunner: true,
    defense: 20,
    fireRes: 8,
    waterRes: -2,
    iceRes: -1,
    thunderRes: 2,
    dragonRes: 3,
    slots: 2,
    rarity: 4,
    skillPoints: [
      { skillId: 13, points: 1 },
      { skillId: 25, points: 2 },
      { skillId: 34, points: 3 },
      { skillId: 54, points: -1 },
      { skillId: 77, points: 2 }
    ],
    price: 6400,
    maxDefense: 20
  }),
  deepFreeze<HeadArmor>({
    id: 59,
    type: 'head',
    name: 'Alloy Helm+',
    blade: true,
    gunner: true,
    defense: 34,
    fireRes: 1,
    waterRes: 2,
    iceRes: -1,
    thunderRes: -2,
    dragonRes: -1,
    slots: 2,
    rarity: 4,
    skillPoints: [
      { skillId: 25, points: 3 },
      { skillId: 26, points: 2 },
      { skillId: 76, points: 3 },
      { skillId: 78, points: -1 }
    ],
    price: 7100,
    maxDefense: 34
  }),
  deepFreeze<HeadArmor>({
    id: 60,
    type: 'head',
    name: 'Alloy Cap+',
    blade: true,
    gunner: true,
    defense: 20,
    fireRes: 1,
    waterRes: 7,
    iceRes: -1,
    thunderRes: -2,
    dragonRes: -1,
    slots: 2,
    rarity: 4,
    skillPoints: [
      { skillId: 7, points: 2 },
      { skillId: 25, points: 3 },
      { skillId: 76, points: 3 },
      { skillId: 78, points: -1 }
    ],
    price: 7100,
    maxDefense: 20
  }),
  deepFreeze<HeadArmor>({
    id: 61,
    type: 'head',
    name: 'Jaggi Helm+',
    blade: true,
    gunner: true,
    defense: 38,
    fireRes: -3,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: 2,
    slots: 1,
    rarity: 5,
    skillPoints: [
      { skillId: 35, points: 4 },
      { skillId: 55, points: 2 },
      { skillId: 58, points: 2 },
      { skillId: 67, points: -3 }
    ],
    price: 8000,
    maxDefense: 38
  }),
  deepFreeze<HeadArmor>({
    id: 62,
    type: 'head',
    name: 'Jaggi Cap+',
    blade: true,
    gunner: true,
    defense: 22,
    fireRes: -3,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: 7,
    slots: 1,
    rarity: 5,
    skillPoints: [
      { skillId: 35, points: 5 },
      { skillId: 55, points: 3 },
      { skillId: 58, points: 2 },
      { skillId: 67, points: -1 }
    ],
    price: 8000,
    maxDefense: 22
  }),
  deepFreeze<HeadArmor>({
    id: 63,
    type: 'head',
    name: 'Rhenoplos Helm+',
    blade: true,
    gunner: true,
    defense: 38,
    fireRes: 3,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -2,
    dragonRes: 2,
    slots: 2,
    rarity: 5,
    skillPoints: [
      { skillId: 25, points: 1 },
      { skillId: 39, points: 3 },
      { skillId: 46, points: 1 },
      { skillId: 56, points: 2 },
      { skillId: 63, points: -2 }
    ],
    price: 8500,
    maxDefense: 38
  }),
  deepFreeze<HeadArmor>({
    id: 64,
    type: 'head',
    name: 'Rhenoplos Cap+',
    blade: true,
    gunner: true,
    defense: 22,
    fireRes: 8,
    waterRes: 4,
    iceRes: 4,
    thunderRes: -2,
    dragonRes: 2,
    slots: 2,
    rarity: 5,
    skillPoints: [
      { skillId: 3, points: 1 },
      { skillId: 25, points: 1 },
      { skillId: 31, points: 3 },
      { skillId: 46, points: 3 },
      { skillId: 63, points: -1 }
    ],
    price: 8500,
    maxDefense: 22
  }),
  deepFreeze<HeadArmor>({
    id: 65,
    type: 'head',
    name: 'Qurupeco Helm+',
    blade: true,
    gunner: true,
    defense: 42,
    fireRes: 4,
    waterRes: -3,
    iceRes: -4,
    thunderRes: 0,
    dragonRes: 1,
    slots: 1,
    rarity: 5,
    skillPoints: [
      { skillId: 25, points: 1 },
      { skillId: 36, points: 2 },
      { skillId: 38, points: 3 },
      { skillId: 43, points: 3 },
      { skillId: 64, points: -2 }
    ],
    price: 10000,
    maxDefense: 42
  }),
  deepFreeze<HeadArmor>({
    id: 66,
    type: 'head',
    name: 'Qurupeco Cap+',
    blade: true,
    gunner: true,
    defense: 25,
    fireRes: 9,
    waterRes: -3,
    iceRes: -4,
    thunderRes: 0,
    dragonRes: 1,
    slots: 1,
    rarity: 5,
    skillPoints: [
      { skillId: 25, points: 1 },
      { skillId: 36, points: 1 },
      { skillId: 38, points: 5 },
      { skillId: 43, points: 3 },
      { skillId: 64, points: -1 }
    ],
    price: 10000,
    maxDefense: 25
  }),
  deepFreeze<HeadArmor>({
    id: 67,
    type: 'head',
    name: 'Ludroth Helm+',
    blade: true,
    gunner: true,
    defense: 44,
    fireRes: -4,
    waterRes: 4,
    iceRes: 0,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 5,
    skillPoints: [
      { skillId: 25, points: 1 },
      { skillId: 34, points: -2 },
      { skillId: 37, points: 2 },
      { skillId: 49, points: 4 },
      { skillId: 79, points: 2 }
    ],
    price: 11800,
    maxDefense: 44
  }),
  deepFreeze<HeadArmor>({
    id: 68,
    type: 'head',
    name: 'Ludroth Cap+',
    blade: true,
    gunner: true,
    defense: 26,
    fireRes: -4,
    waterRes: 9,
    iceRes: 0,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 5,
    skillPoints: [
      { skillId: 25, points: 1 },
      { skillId: 30, points: 4 },
      { skillId: 34, points: -1 },
      { skillId: 37, points: 1 },
      { skillId: 49, points: 4 }
    ],
    price: 11800,
    maxDefense: 26
  }),
  deepFreeze<HeadArmor>({
    id: 69,
    type: 'head',
    name: 'Baggi Helm+',
    blade: true,
    gunner: true,
    defense: 44,
    fireRes: -4,
    waterRes: -1,
    iceRes: 4,
    thunderRes: -1,
    dragonRes: 1,
    slots: 3,
    rarity: 5,
    skillPoints: [
      { skillId: 17, points: 1 },
      { skillId: 18, points: 2 },
      { skillId: 55, points: -3 },
      { skillId: 64, points: 1 }
    ],
    price: 12300,
    maxDefense: 44
  }),
  deepFreeze<HeadArmor>({
    id: 70,
    type: 'head',
    name: 'Baggi Cap+',
    blade: true,
    gunner: true,
    defense: 26,
    fireRes: -4,
    waterRes: -1,
    iceRes: 9,
    thunderRes: -1,
    dragonRes: 1,
    slots: 3,
    rarity: 5,
    skillPoints: [
      { skillId: 6, points: 2 },
      { skillId: 17, points: 2 },
      { skillId: 55, points: -2 },
      { skillId: 64, points: 1 }
    ],
    price: 12300,
    maxDefense: 26
  }),
  deepFreeze<HeadArmor>({
    id: 71,
    type: 'head',
    name: 'Barroth Helm+',
    blade: true,
    gunner: true,
    defense: 48,
    fireRes: 0,
    waterRes: 0,
    iceRes: -4,
    thunderRes: 4,
    dragonRes: 0,
    slots: 2,
    rarity: 5,
    skillPoints: [
      { skillId: 13, points: 1 },
      { skillId: 25, points: -3 },
      { skillId: 35, points: 3 },
      { skillId: 45, points: 2 }
    ],
    price: 13800,
    maxDefense: 48
  }),
  deepFreeze<HeadArmor>({
    id: 72,
    type: 'head',
    name: 'Barroth Cap+',
    blade: true,
    gunner: true,
    defense: 28,
    fireRes: 5,
    waterRes: 5,
    iceRes: -4,
    thunderRes: 4,
    dragonRes: 0,
    slots: 2,
    rarity: 5,
    skillPoints: [
      { skillId: 13, points: 1 },
      { skillId: 25, points: -1 },
      { skillId: 35, points: 4 },
      { skillId: 45, points: 3 }
    ],
    price: 13800,
    maxDefense: 28
  }),
  deepFreeze<HeadArmor>({
    id: 73,
    type: 'head',
    name: 'Gobul Helm+',
    blade: true,
    gunner: true,
    defense: 50,
    fireRes: -2,
    waterRes: 4,
    iceRes: 0,
    thunderRes: -4,
    dragonRes: 2,
    slots: 1,
    rarity: 5,
    skillPoints: [
      { skillId: 24, points: -2 },
      { skillId: 25, points: 3 },
      { skillId: 46, points: 3 },
      { skillId: 55, points: 3 }
    ],
    price: 14800,
    maxDefense: 50
  }),
  deepFreeze<HeadArmor>({
    id: 74,
    type: 'head',
    name: 'Gobul Cap+',
    blade: true,
    gunner: true,
    defense: 30,
    fireRes: -2,
    waterRes: 9,
    iceRes: 0,
    thunderRes: -4,
    dragonRes: 2,
    slots: 1,
    rarity: 5,
    skillPoints: [
      { skillId: 25, points: 3 },
      { skillId: 43, points: -1 },
      { skillId: 46, points: 3 },
      { skillId: 55, points: 4 }
    ],
    price: 14800,
    maxDefense: 30
  }),
  deepFreeze<HeadArmor>({
    id: 75,
    type: 'head',
    name: 'Guild Bard Lobos+',
    blade: true,
    gunner: true,
    defense: 36,
    fireRes: 0,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 1,
    rarity: 6,
    skillPoints: [
      { skillId: 12, points: 1 },
      { skillId: 15, points: 1 },
      { skillId: 17, points: 4 },
      { skillId: 37, points: -5 }
    ],
    price: 25000,
    maxDefense: 36
  }),
  deepFreeze<HeadArmor>({
    id: 76,
    type: 'head',
    name: 'Guild Bard Hat+',
    blade: true,
    gunner: true,
    defense: 22,
    fireRes: -10,
    waterRes: 10,
    iceRes: -10,
    thunderRes: 5,
    dragonRes: 10,
    slots: 1,
    rarity: 6,
    skillPoints: [
      { skillId: 12, points: 2 },
      { skillId: 15, points: 2 },
      { skillId: 17, points: 2 },
      { skillId: 37, points: -5 }
    ],
    price: 25000,
    maxDefense: 22
  }),
  deepFreeze<HeadArmor>({
    id: 77,
    type: 'head',
    name: 'Rathian Helm+',
    blade: true,
    gunner: true,
    defense: 50,
    fireRes: 4,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 3,
    rarity: 5,
    skillPoints: [
      { skillId: 11, points: 1 },
      { skillId: 23, points: 1 },
      { skillId: 37, points: -3 },
      { skillId: 61, points: 2 }
    ],
    price: 14800,
    maxDefense: 50
  }),
  deepFreeze<HeadArmor>({
    id: 78,
    type: 'head',
    name: 'Rathian Cap+',
    blade: true,
    gunner: true,
    defense: 30,
    fireRes: 9,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 3,
    rarity: 5,
    skillPoints: [
      { skillId: 11, points: 2 },
      { skillId: 23, points: 2 },
      { skillId: 37, points: -2 },
      { skillId: 61, points: 1 }
    ],
    price: 14800,
    maxDefense: 30
  }),
  deepFreeze<HeadArmor>({
    id: 79,
    type: 'head',
    name: 'Gigginox Helm+',
    blade: true,
    gunner: true,
    defense: 54,
    fireRes: -4,
    waterRes: -1,
    iceRes: 2,
    thunderRes: 3,
    dragonRes: 0,
    slots: 1,
    rarity: 5,
    skillPoints: [
      { skillId: 9, points: 2 },
      { skillId: 22, points: 3 },
      { skillId: 23, points: -3 },
      { skillId: 49, points: 3 }
    ],
    price: 15800,
    maxDefense: 54
  }),
  deepFreeze<HeadArmor>({
    id: 80,
    type: 'head',
    name: 'Gigginox Cap+',
    blade: true,
    gunner: true,
    defense: 32,
    fireRes: -4,
    waterRes: -1,
    iceRes: 2,
    thunderRes: 8,
    dragonRes: 0,
    slots: 1,
    rarity: 5,
    skillPoints: [
      { skillId: 9, points: 3 },
      { skillId: 22, points: 3 },
      { skillId: 23, points: -1 },
      { skillId: 49, points: 4 }
    ],
    price: 15800,
    maxDefense: 32
  }),
  deepFreeze<HeadArmor>({
    id: 81,
    type: 'head',
    name: 'Ingot Helm+',
    blade: true,
    gunner: true,
    defense: 54,
    fireRes: -2,
    waterRes: -1,
    iceRes: 1,
    thunderRes: 3,
    dragonRes: 2,
    slots: 1,
    rarity: 5,
    skillPoints: [
      { skillId: 26, points: -1 },
      { skillId: 28, points: 3 },
      { skillId: 39, points: 3 },
      { skillId: 63, points: 4 }
    ],
    price: 17500,
    maxDefense: 54
  }),
  deepFreeze<HeadArmor>({
    id: 82,
    type: 'head',
    name: 'Ingot Cap+',
    blade: true,
    gunner: true,
    defense: 32,
    fireRes: -2,
    waterRes: -1,
    iceRes: 1,
    thunderRes: 3,
    dragonRes: 7,
    slots: 1,
    rarity: 5,
    skillPoints: [
      { skillId: 3, points: 3 },
      { skillId: 28, points: 3 },
      { skillId: 29, points: -1 },
      { skillId: 63, points: 4 }
    ],
    price: 17500,
    maxDefense: 32
  }),
  deepFreeze<HeadArmor>({
    id: 83,
    type: 'head',
    name: 'Dober Helm',
    blade: true,
    gunner: true,
    defense: 58,
    fireRes: -2,
    waterRes: -2,
    iceRes: 1,
    thunderRes: 1,
    dragonRes: 5,
    slots: 3,
    rarity: 6,
    skillPoints: [
      { skillId: 13, points: 2 },
      { skillId: 45, points: -3 },
      { skillId: 48, points: 1 },
      { skillId: 65, points: 1 }
    ],
    price: 19000,
    maxDefense: 58
  }),
  deepFreeze<HeadArmor>({
    id: 84,
    type: 'head',
    name: 'Dober Cap',
    blade: true,
    gunner: true,
    defense: 34,
    fireRes: -2,
    waterRes: -2,
    iceRes: 1,
    thunderRes: 1,
    dragonRes: 10,
    slots: 3,
    rarity: 6,
    skillPoints: [
      { skillId: 6, points: 2 },
      { skillId: 30, points: 2 },
      { skillId: 45, points: -2 },
      { skillId: 65, points: 1 }
    ],
    price: 19000,
    maxDefense: 34
  }),
  deepFreeze<HeadArmor>({
    id: 85,
    type: 'head',
    name: 'Lagiacrus Helm+',
    blade: true,
    gunner: true,
    defense: 58,
    fireRes: -4,
    waterRes: 2,
    iceRes: -1,
    thunderRes: 5,
    dragonRes: -2,
    slots: 1,
    rarity: 6,
    skillPoints: [
      { skillId: 9, points: -3 },
      { skillId: 10, points: 2 },
      { skillId: 20, points: 3 },
      { skillId: 50, points: 3 }
    ],
    price: 18000,
    maxDefense: 58
  }),
  deepFreeze<HeadArmor>({
    id: 86,
    type: 'head',
    name: 'Lagiacrus Cap+',
    blade: true,
    gunner: true,
    defense: 34,
    fireRes: -4,
    waterRes: 2,
    iceRes: -1,
    thunderRes: 10,
    dragonRes: -2,
    slots: 1,
    rarity: 6,
    skillPoints: [
      { skillId: 9, points: -2 },
      { skillId: 10, points: 2 },
      { skillId: 21, points: 2 },
      { skillId: 50, points: 5 }
    ],
    price: 18000,
    maxDefense: 34
  }),
  deepFreeze<HeadArmor>({
    id: 87,
    type: 'head',
    name: 'Rathalos Helm+',
    blade: true,
    gunner: true,
    defense: 58,
    fireRes: 4,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 3,
    rarity: 6,
    skillPoints: [
      { skillId: 2, points: 1 },
      { skillId: 25, points: 2 },
      { skillId: 36, points: -3 },
      { skillId: 66, points: 1 }
    ],
    price: 18000,
    maxDefense: 58
  }),
  deepFreeze<HeadArmor>({
    id: 88,
    type: 'head',
    name: 'Rathalos Cap+',
    blade: true,
    gunner: true,
    defense: 34,
    fireRes: 9,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 3,
    rarity: 6,
    skillPoints: [
      { skillId: 4, points: 1 },
      { skillId: 25, points: 3 },
      { skillId: 36, points: -2 },
      { skillId: 66, points: 1 }
    ],
    price: 18000,
    maxDefense: 34
  }),
  deepFreeze<HeadArmor>({
    id: 89,
    type: 'head',
    name: 'Barioth Helm+',
    blade: true,
    gunner: true,
    defense: 58,
    fireRes: -4,
    waterRes: 2,
    iceRes: 5,
    thunderRes: -3,
    dragonRes: 0,
    slots: 1,
    rarity: 6,
    skillPoints: [
      { skillId: 16, points: 3 },
      { skillId: 44, points: 2 },
      { skillId: 66, points: -3 },
      { skillId: 67, points: 3 }
    ],
    price: 18000,
    maxDefense: 58
  }),
  deepFreeze<HeadArmor>({
    id: 90,
    type: 'head',
    name: 'Barioth Cap+',
    blade: true,
    gunner: true,
    defense: 34,
    fireRes: -4,
    waterRes: 2,
    iceRes: 10,
    thunderRes: -3,
    dragonRes: 0,
    slots: 1,
    rarity: 6,
    skillPoints: [
      { skillId: 16, points: 4 },
      { skillId: 44, points: 2 },
      { skillId: 66, points: -1 },
      { skillId: 67, points: 4 }
    ],
    price: 18000,
    maxDefense: 34
  }),
  deepFreeze<HeadArmor>({
    id: 91,
    type: 'head',
    name: 'Diablos Helm+',
    blade: true,
    gunner: true,
    defense: 62,
    fireRes: 3,
    waterRes: -1,
    iceRes: -4,
    thunderRes: -1,
    dragonRes: -1,
    slots: 0,
    rarity: 6,
    skillPoints: [
      { skillId: 10, points: -3 },
      { skillId: 47, points: 5 },
      { skillId: 48, points: 5 }
    ],
    price: 18800,
    maxDefense: 62
  }),
  deepFreeze<HeadArmor>({
    id: 92,
    type: 'head',
    name: 'Diablos Cap+',
    blade: true,
    gunner: true,
    defense: 37,
    fireRes: 3,
    waterRes: 2,
    iceRes: -4,
    thunderRes: 2,
    dragonRes: 2,
    slots: 0,
    rarity: 6,
    skillPoints: [
      { skillId: 5, points: 5 },
      { skillId: 8, points: 5 },
      { skillId: 10, points: -3 }
    ],
    price: 18800,
    maxDefense: 37
  }),
  deepFreeze<HeadArmor>({
    id: 93,
    type: 'head',
    name: 'Uragaan Helm+',
    blade: true,
    gunner: true,
    defense: 62,
    fireRes: 4,
    waterRes: -4,
    iceRes: -1,
    thunderRes: 1,
    dragonRes: -2,
    slots: 1,
    rarity: 6,
    skillPoints: [
      { skillId: 19, points: 2 },
      { skillId: 33, points: 2 },
      { skillId: 36, points: 4 },
      { skillId: 46, points: -3 }
    ],
    price: 18800,
    maxDefense: 62
  }),
  deepFreeze<HeadArmor>({
    id: 94,
    type: 'head',
    name: 'Uragaan Cap+',
    blade: true,
    gunner: true,
    defense: 37,
    fireRes: 9,
    waterRes: -4,
    iceRes: -1,
    thunderRes: 1,
    dragonRes: -2,
    slots: 1,
    rarity: 6,
    skillPoints: [
      { skillId: 3, points: 6 },
      { skillId: 33, points: 1 },
      { skillId: 36, points: 3 },
      { skillId: 46, points: -1 }
    ],
    price: 18800,
    maxDefense: 37
  }),
  deepFreeze<HeadArmor>({
    id: 95,
    type: 'head',
    name: 'Agnaktor Helm+',
    blade: true,
    gunner: true,
    defense: 62,
    fireRes: 5,
    waterRes: -4,
    iceRes: -2,
    thunderRes: 1,
    dragonRes: 0,
    slots: 0,
    rarity: 6,
    skillPoints: [
      { skillId: 0, points: 3 },
      { skillId: 13, points: -2 },
      { skillId: 27, points: 5 },
      { skillId: 52, points: 3 }
    ],
    price: 19800,
    maxDefense: 62
  }),
  deepFreeze<HeadArmor>({
    id: 96,
    type: 'head',
    name: 'Agnaktor Cap+',
    blade: true,
    gunner: true,
    defense: 37,
    fireRes: 10,
    waterRes: -4,
    iceRes: -2,
    thunderRes: 1,
    dragonRes: 0,
    slots: 0,
    rarity: 6,
    skillPoints: [
      { skillId: 4, points: 4 },
      { skillId: 7, points: 4 },
      { skillId: 13, points: -1 },
      { skillId: 52, points: 4 }
    ],
    price: 19800,
    maxDefense: 37
  }),
  deepFreeze<HeadArmor>({
    id: 97,
    type: 'head',
    name: 'Vangis Helm',
    blade: true,
    gunner: true,
    defense: 64,
    fireRes: 0,
    waterRes: 0,
    iceRes: 3,
    thunderRes: -4,
    dragonRes: -4,
    slots: 0,
    rarity: 7,
    skillPoints: [
      { skillId: 1, points: 4 },
      { skillId: 34, points: -2 },
      { skillId: 35, points: 3 },
      { skillId: 42, points: 4 }
    ],
    price: 41500,
    maxDefense: 64
  }),
  deepFreeze<HeadArmor>({
    id: 98,
    type: 'head',
    name: 'Vangis Cap',
    blade: true,
    gunner: true,
    defense: 38,
    fireRes: 5,
    waterRes: 5,
    iceRes: 3,
    thunderRes: -4,
    dragonRes: -4,
    slots: 0,
    rarity: 7,
    skillPoints: [
      { skillId: 14, points: 5 },
      { skillId: 34, points: -1 },
      { skillId: 35, points: 2 },
      { skillId: 42, points: 5 }
    ],
    price: 41500,
    maxDefense: 38
  }),
  deepFreeze<HeadArmor>({
    id: 99,
    type: 'head',
    name: 'Damascus Helm',
    blade: true,
    gunner: true,
    defense: 62,
    fireRes: -2,
    waterRes: 0,
    iceRes: 2,
    thunderRes: -2,
    dragonRes: 3,
    slots: 3,
    rarity: 6,
    skillPoints: [
      { skillId: 13, points: -3 },
      { skillId: 19, points: 2 },
      { skillId: 23, points: 1 },
      { skillId: 28, points: 1 }
    ],
    price: 32300,
    maxDefense: 62
  }),
  deepFreeze<HeadArmor>({
    id: 100,
    type: 'head',
    name: 'Damascus Cap',
    blade: true,
    gunner: true,
    defense: 37,
    fireRes: -2,
    waterRes: 0,
    iceRes: 2,
    thunderRes: -2,
    dragonRes: 8,
    slots: 3,
    rarity: 6,
    skillPoints: [
      { skillId: 13, points: -3 },
      { skillId: 23, points: 1 },
      { skillId: 28, points: 1 },
      { skillId: 29, points: 2 }
    ],
    price: 32300,
    maxDefense: 37
  }),
  deepFreeze<HeadArmor>({
    id: 101,
    type: 'head',
    name: 'Helios Helm+',
    blade: true,
    gunner: true,
    defense: 66,
    fireRes: 0,
    waterRes: 5,
    iceRes: 3,
    thunderRes: -3,
    dragonRes: -4,
    slots: 3,
    rarity: 6,
    skillPoints: [
      { skillId: 0, points: -1 },
      { skillId: 1, points: 1 },
      { skillId: 11, points: 2 },
      { skillId: 37, points: -3 }
    ],
    price: 26200,
    maxDefense: 66
  }),
  deepFreeze<HeadArmor>({
    id: 102,
    type: 'head',
    name: 'Helios Cap+',
    blade: true,
    gunner: true,
    defense: 39,
    fireRes: 0,
    waterRes: 10,
    iceRes: 3,
    thunderRes: -3,
    dragonRes: -4,
    slots: 3,
    rarity: 6,
    skillPoints: [
      { skillId: 3, points: -1 },
      { skillId: 11, points: 2 },
      { skillId: 14, points: 1 },
      { skillId: 37, points: -3 }
    ],
    price: 26200,
    maxDefense: 39
  }),
  deepFreeze<HeadArmor>({
    id: 103,
    type: 'head',
    name: 'Yamato Kabuto+',
    blade: true,
    gunner: true,
    defense: 66,
    fireRes: 4,
    waterRes: 0,
    iceRes: -3,
    thunderRes: 0,
    dragonRes: -4,
    slots: 3,
    rarity: 6,
    skillPoints: [
      { skillId: 0, points: 1 },
      { skillId: 18, points: 1 },
      { skillId: 24, points: 2 },
      { skillId: 71, points: -3 }
    ],
    price: 27500,
    maxDefense: 66
  }),
  deepFreeze<HeadArmor>({
    id: 104,
    type: 'head',
    name: 'Mutsu Eboshi+',
    blade: true,
    gunner: true,
    defense: 39,
    fireRes: 4,
    waterRes: 10,
    iceRes: -3,
    thunderRes: 10,
    dragonRes: -4,
    slots: 3,
    rarity: 6,
    skillPoints: [
      { skillId: 3, points: 1 },
      { skillId: 24, points: 1 },
      { skillId: 32, points: 2 },
      { skillId: 71, points: -3 }
    ],
    price: 27500,
    maxDefense: 39
  }),
  deepFreeze<HeadArmor>({
    id: 105,
    type: 'head',
    name: 'Escadora Wisdom',
    blade: true,
    gunner: true,
    defense: 70,
    fireRes: -1,
    waterRes: -1,
    iceRes: -1,
    thunderRes: 0,
    dragonRes: -5,
    slots: 2,
    rarity: 7,
    skillPoints: [
      { skillId: 16, points: 2 },
      { skillId: 20, points: 1 },
      { skillId: 43, points: -3 },
      { skillId: 81, points: 3 }
    ],
    price: 66666,
    maxDefense: 70
  }),
  deepFreeze<HeadArmor>({
    id: 106,
    type: 'head',
    name: 'Escadora Sagesse',
    blade: true,
    gunner: true,
    defense: 42,
    fireRes: 4,
    waterRes: 4,
    iceRes: 4,
    thunderRes: 0,
    dragonRes: -5,
    slots: 2,
    rarity: 7,
    skillPoints: [
      { skillId: 16, points: 2 },
      { skillId: 21, points: 1 },
      { skillId: 43, points: -3 },
      { skillId: 81, points: 3 }
    ],
    price: 66666,
    maxDefense: 42
  }),
  deepFreeze<HeadArmor>({
    id: 107,
    type: 'head',
    name: 'Chakra Earring',
    blade: true,
    gunner: true,
    defense: 18,
    fireRes: -10,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 10,
    slots: 3,
    rarity: 7,
    skillPoints: [],
    price: 33333,
    maxDefense: 18
  }),
  deepFreeze<HeadArmor>({
    id: 108,
    type: 'head',
    name: 'Skull Mask',
    blade: true,
    gunner: true,
    defense: 7,
    fireRes: 3,
    waterRes: -2,
    iceRes: -2,
    thunderRes: -2,
    dragonRes: 3,
    slots: 0,
    rarity: 3,
    skillPoints: [],
    torsoUp: true,
    price: 5000,
    maxDefense: 7,
    maxLowRankDefense: 13
  }),
  deepFreeze<HeadArmor>({
    id: 109,
    type: 'head',
    name: 'Jaggi Mask',
    blade: true,
    gunner: true,
    defense: 5,
    fireRes: -4,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: -1,
    slots: 0,
    rarity: 3,
    skillPoints: [{ skillId: 12, points: 10 }],
    price: 30000,
    maxDefense: 5,
    maxLowRankDefense: 12
  }),
  deepFreeze<HeadArmor>({
    id: 110,
    type: 'head',
    name: 'Wyvernking Eyepatch',
    blade: true,
    gunner: true,
    defense: 8,
    fireRes: 2,
    waterRes: 2,
    iceRes: 2,
    thunderRes: 2,
    dragonRes: 2,
    slots: 3,
    rarity: 3,
    skillPoints: [],
    price: 10000,
    maxDefense: 8,
    maxLowRankDefense: 14
  }),
  deepFreeze<HeadArmor>({
    id: 111,
    type: 'head',
    name: 'Shadow Shades',
    blade: true,
    gunner: true,
    defense: 28,
    fireRes: 2,
    waterRes: 2,
    iceRes: 2,
    thunderRes: 2,
    dragonRes: 2,
    slots: 3,
    rarity: 6,
    skillPoints: [{ skillId: 55, points: 7 }],
    price: 15000,
    maxDefense: 28
  }),
  deepFreeze<HeadArmor>({
    id: 112,
    type: 'head',
    name: 'Blast Earring',
    blade: true,
    gunner: true,
    defense: 10,
    fireRes: 0,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 0,
    rarity: 2,
    skillPoints: [{ skillId: 33, points: 10 }],
    price: 5000,
    maxDefense: 10
  }),
  deepFreeze<HeadArmor>({
    id: 113,
    type: 'head',
    name: 'Pursuit Earring',
    blade: true,
    gunner: true,
    defense: 10,
    fireRes: 0,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 0,
    rarity: 3,
    skillPoints: [{ skillId: 71, points: 20 }],
    price: 10000,
    maxDefense: 10
  }),
  deepFreeze<HeadArmor>({
    id: 114,
    type: 'head',
    name: 'Hawkeye Earring',
    blade: true,
    gunner: true,
    defense: 10,
    fireRes: 0,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 0,
    rarity: 4,
    skillPoints: [{ skillId: 42, points: 15 }],
    price: 15000,
    maxDefense: 10
  }),
  deepFreeze<HeadArmor>({
    id: 115,
    type: 'head',
    name: 'Grace Earring',
    blade: true,
    gunner: true,
    defense: 10,
    fireRes: 0,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 0,
    rarity: 5,
    skillPoints: [{ skillId: 38, points: 20 }],
    price: 20000,
    maxDefense: 10
  }),
  deepFreeze<HeadArmor>({
    id: 116,
    type: 'head',
    name: 'Sword Saint Earring',
    blade: true,
    gunner: true,
    defense: 10,
    fireRes: 0,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 0,
    rarity: 6,
    skillPoints: [{ skillId: 2, points: 10 }],
    price: 25000,
    maxDefense: 10
  }),
  deepFreeze<HeadArmor>({
    id: 117,
    type: 'head',
    name: 'Barrage Earring',
    blade: true,
    gunner: true,
    defense: 10,
    fireRes: 0,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 0,
    rarity: 7,
    skillPoints: [{ skillId: 14, points: 15 }],
    price: 30000,
    maxDefense: 10
  })
];
