import { deepFreeze } from '../../utils';
import type { LegArmor } from './types';

export const LegArmors: LegArmor[] = [
  deepFreeze<LegArmor>({
    id: 0,
    type: 'legs',
    name: 'Leather Pants',
    blade: true,
    gunner: true,
    defense: 1,
    fireRes: -1,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 3,
    dragonRes: 2,
    slots: 1,
    rarity: 1,
    price: 150,
    maxDefense: 1,
    maxLowRankDefense: 9,
    skillPoints: { attack: 1, gathering: 3, spd_gather: 1, whim: 3 }
  }),
  deepFreeze<LegArmor>({
    id: 1,
    type: 'legs',
    name: 'Piscine Leggings',
    blade: true,
    gunner: true,
    defense: 3,
    fireRes: -2,
    waterRes: 4,
    iceRes: 2,
    thunderRes: -3,
    dragonRes: 0,
    slots: 1,
    rarity: 1,
    price: 300,
    maxDefense: 3,
    maxLowRankDefense: 11,
    skillPoints: { swimming: 8, currentres: 1 }
  }),
  deepFreeze<LegArmor>({
    id: 2,
    type: 'legs',
    name: 'Chainmail Pants',
    blade: true,
    gunner: true,
    defense: 2,
    fireRes: -1,
    waterRes: -1,
    iceRes: 3,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 1,
    price: 200,
    maxDefense: 2,
    maxLowRankDefense: 9,
    skillPoints: {
      health: 2,
      fishing: 4,
      combo_rate: 1,
      combo_plus: 2
    }
  }),
  deepFreeze<LegArmor>({
    id: 3,
    type: 'legs',
    name: 'Loc Lac Boots',
    blade: true,
    gunner: true,
    defense: 4,
    fireRes: 4,
    waterRes: -3,
    iceRes: -4,
    thunderRes: 2,
    dragonRes: 0,
    slots: 0,
    rarity: 1,
    price: 500,
    maxDefense: 4,
    maxLowRankDefense: 11,
    skillPoints: { rec_speed: 3, transportr: 5, heat_res: 3 }
  }),
  deepFreeze<LegArmor>({
    id: 4,
    type: 'legs',
    name: "Hunter's Greaves",
    blade: true,
    gunner: false,
    defense: 6,
    fireRes: -1,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: -1,
    slots: 1,
    rarity: 1,
    price: 500,
    maxDefense: 6,
    maxLowRankDefense: 20,
    skillPoints: { psychic: 2, water_res: -1, map: 4, bbq: 2 }
  }),
  deepFreeze<LegArmor>({
    id: 5,
    type: 'legs',
    name: "Hunter's Leggings",
    blade: false,
    gunner: true,
    defense: 3,
    fireRes: -1,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: -1,
    slots: 1,
    rarity: 1,
    price: 500,
    maxDefense: 3,
    maxLowRankDefense: 10,
    skillPoints: { psychic: 2, water_res: -1, map: 4, bbq: 2 }
  }),
  deepFreeze<LegArmor>({
    id: 6,
    type: 'legs',
    name: 'Bone Greaves',
    blade: true,
    gunner: false,
    defense: 8,
    fireRes: 2,
    waterRes: -2,
    iceRes: -1,
    thunderRes: 2,
    dragonRes: 3,
    slots: 1,
    rarity: 1,
    price: 750,
    maxDefense: 8,
    maxLowRankDefense: 22,
    skillPoints: {
      hunger: 1,
      attack: 1,
      sleep: -1,
      lastingpwr: 2,
      perception: 4
    }
  }),
  deepFreeze<LegArmor>({
    id: 7,
    type: 'legs',
    name: 'Bone Leggings',
    blade: false,
    gunner: true,
    defense: 4,
    fireRes: 2,
    waterRes: -2,
    iceRes: -1,
    thunderRes: 2,
    dragonRes: 3,
    slots: 1,
    rarity: 1,
    price: 750,
    maxDefense: 4,
    maxLowRankDefense: 11,
    skillPoints: {
      hunger: 1,
      attack: 1,
      sleep: -1,
      lastingpwr: 2,
      perception: 4
    }
  }),
  deepFreeze<LegArmor>({
    id: 8,
    type: 'legs',
    name: 'Alloy Greaves',
    blade: true,
    gunner: false,
    defense: 8,
    fireRes: 1,
    waterRes: 1,
    iceRes: -1,
    thunderRes: -2,
    dragonRes: -1,
    slots: 0,
    rarity: 1,
    price: 1000,
    maxDefense: 8,
    maxLowRankDefense: 22,
    skillPoints: {},
    torsoUp: true
  }),
  deepFreeze<LegArmor>({
    id: 9,
    type: 'legs',
    name: 'Alloy Leggings',
    blade: false,
    gunner: true,
    defense: 4,
    fireRes: 1,
    waterRes: 1,
    iceRes: -1,
    thunderRes: -2,
    dragonRes: -1,
    slots: 0,
    rarity: 1,
    price: 1000,
    maxDefense: 4,
    maxLowRankDefense: 11,
    skillPoints: {},
    torsoUp: true
  }),
  deepFreeze<LegArmor>({
    id: 10,
    type: 'legs',
    name: 'Jaggi Greaves',
    blade: true,
    gunner: false,
    defense: 10,
    fireRes: -3,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    price: 1200,
    maxDefense: 10,
    maxLowRankDefense: 24,
    skillPoints: { attack: 3, stun: 2, gluttony: 2, cold_res: -2 }
  }),
  deepFreeze<LegArmor>({
    id: 11,
    type: 'legs',
    name: 'Jaggi Leggings',
    blade: false,
    gunner: true,
    defense: 5,
    fireRes: -3,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    price: 1200,
    maxDefense: 5,
    maxLowRankDefense: 12,
    skillPoints: { attack: 3, stun: 3, gluttony: 1, cold_res: -2 }
  }),
  deepFreeze<LegArmor>({
    id: 12,
    type: 'legs',
    name: 'Bnahabra Boots',
    blade: true,
    gunner: false,
    defense: 10,
    fireRes: -4,
    waterRes: -1,
    iceRes: -1,
    thunderRes: 2,
    dragonRes: 5,
    slots: 0,
    rarity: 2,
    price: 1800,
    maxDefense: 10,
    maxLowRankDefense: 24,
    skillPoints: { sharpness: 4, status: 4, poison: -3 }
  }),
  deepFreeze<LegArmor>({
    id: 13,
    type: 'legs',
    name: 'Bnahabra Pants',
    blade: false,
    gunner: true,
    defense: 5,
    fireRes: -4,
    waterRes: -1,
    iceRes: -1,
    thunderRes: 2,
    dragonRes: 5,
    slots: 0,
    rarity: 2,
    price: 1800,
    maxDefense: 5,
    maxLowRankDefense: 12,
    skillPoints: { status: 4, poison: -3, reload_spd: 4 }
  }),
  deepFreeze<LegArmor>({
    id: 14,
    type: 'legs',
    name: 'Rhenoplos Greaves',
    blade: true,
    gunner: false,
    defense: 12,
    fireRes: 2,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: 2,
    slots: 1,
    rarity: 2,
    price: 1400,
    maxDefense: 12,
    maxLowRankDefense: 24,
    skillPoints: {
      wind_res: 3,
      eating: 2,
      'mud/snow': 3,
      thunderres: -1
    }
  }),
  deepFreeze<LegArmor>({
    id: 15,
    type: 'legs',
    name: 'Rhenoplos Leggings',
    blade: false,
    gunner: true,
    defense: 6,
    fireRes: 2,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: 2,
    slots: 1,
    rarity: 2,
    price: 1400,
    maxDefense: 6,
    maxLowRankDefense: 12,
    skillPoints: {
      recoil: 1,
      'crag_s+': 2,
      eating: 4,
      thunderres: -2
    }
  }),
  deepFreeze<LegArmor>({
    id: 16,
    type: 'legs',
    name: 'Qurupeco Greaves',
    blade: true,
    gunner: false,
    defense: 12,
    fireRes: 2,
    waterRes: -2,
    iceRes: -3,
    thunderRes: 0,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    price: 1700,
    maxDefense: 12,
    maxLowRankDefense: 24,
    skillPoints: {
      defense: 1,
      rec_level: 4,
      evasion: 3,
      ice_res: -1
    }
  }),
  deepFreeze<LegArmor>({
    id: 17,
    type: 'legs',
    name: 'Qurupeco Leggings',
    blade: false,
    gunner: true,
    defense: 6,
    fireRes: 2,
    waterRes: -2,
    iceRes: -3,
    thunderRes: 0,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    price: 1700,
    maxDefense: 6,
    maxLowRankDefense: 12,
    skillPoints: {
      defense: 4,
      rec_level: 2,
      evasion: 2,
      ice_res: -1
    }
  }),
  deepFreeze<LegArmor>({
    id: 18,
    type: 'legs',
    name: 'Ludroth Greaves',
    blade: true,
    gunner: false,
    defense: 13,
    fireRes: -3,
    waterRes: 2,
    iceRes: 0,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    price: 2200,
    maxDefense: 13,
    maxLowRankDefense: 25,
    skillPoints: {
      attack: 2,
      protection: 2,
      constitutn: 2,
      fire_res: -1,
      currentres: 2
    }
  }),
  deepFreeze<LegArmor>({
    id: 19,
    type: 'legs',
    name: 'Ludroth Leggings',
    blade: false,
    gunner: true,
    defense: 7,
    fireRes: -3,
    waterRes: 2,
    iceRes: 0,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    price: 2200,
    maxDefense: 7,
    maxLowRankDefense: 13,
    skillPoints: {
      'pellet_s+': 2,
      attack: 2,
      protection: 2,
      constitutn: 2,
      fire_res: -1
    }
  }),
  deepFreeze<LegArmor>({
    id: 20,
    type: 'legs',
    name: 'Baggi Greaves',
    blade: true,
    gunner: false,
    defense: 13,
    fireRes: -3,
    waterRes: -1,
    iceRes: 3,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    price: 2400,
    maxDefense: 13,
    maxLowRankDefense: 25,
    skillPoints: {
      tranquilzr: 4,
      fastcharge: 3,
      stun: -1,
      ice_res: 1
    }
  }),
  deepFreeze<LegArmor>({
    id: 21,
    type: 'legs',
    name: 'Baggi Leggings',
    blade: false,
    gunner: true,
    defense: 7,
    fireRes: -3,
    waterRes: -1,
    iceRes: 3,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    price: 2400,
    maxDefense: 7,
    maxLowRankDefense: 13,
    skillPoints: {
      pellets_up: 2,
      tranquilzr: 4,
      stun: -1,
      ice_res: 2
    }
  }),
  deepFreeze<LegArmor>({
    id: 22,
    type: 'legs',
    name: 'Barroth Greaves',
    blade: true,
    gunner: false,
    defense: 15,
    fireRes: 4,
    waterRes: -4,
    iceRes: -3,
    thunderRes: 3,
    dragonRes: 0,
    slots: 1,
    rarity: 2,
    price: 3200,
    maxDefense: 15,
    maxLowRankDefense: 27,
    skillPoints: { stamina: 4, expert: -2, attack: 1, potential: 2 }
  }),
  deepFreeze<LegArmor>({
    id: 23,
    type: 'legs',
    name: 'Barroth Leggings',
    blade: false,
    gunner: true,
    defense: 8,
    fireRes: 4,
    waterRes: -4,
    iceRes: -3,
    thunderRes: 3,
    dragonRes: 0,
    slots: 1,
    rarity: 2,
    price: 3200,
    maxDefense: 8,
    maxLowRankDefense: 14,
    skillPoints: { stamina: 4, expert: -2, attack: 1, potential: 2 }
  }),
  deepFreeze<LegArmor>({
    id: 24,
    type: 'legs',
    name: 'Gobul Greaves',
    blade: true,
    gunner: false,
    defense: 16,
    fireRes: -2,
    waterRes: 3,
    iceRes: 0,
    thunderRes: -3,
    dragonRes: 2,
    slots: 1,
    rarity: 2,
    price: 3600,
    maxDefense: 16,
    maxLowRankDefense: 28,
    skillPoints: {
      rec_speed: -1,
      attack: 1,
      eating: 4,
      stun: 2,
      water_res: 1
    }
  }),
  deepFreeze<LegArmor>({
    id: 25,
    type: 'legs',
    name: 'Gobul Leggings',
    blade: false,
    gunner: true,
    defense: 8,
    fireRes: -2,
    waterRes: 3,
    iceRes: 0,
    thunderRes: -3,
    dragonRes: 2,
    slots: 1,
    rarity: 2,
    price: 3600,
    maxDefense: 8,
    maxLowRankDefense: 14,
    skillPoints: {
      rec_speed: -1,
      attack: 1,
      eating: 3,
      stun: 3,
      water_res: 1
    }
  }),
  deepFreeze<LegArmor>({
    id: 26,
    type: 'legs',
    name: "Ranger's Espadrilles",
    blade: true,
    gunner: false,
    defense: 15,
    fireRes: 0,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 1,
    rarity: 3,
    price: 10000,
    maxDefense: 15,
    maxLowRankDefense: 27,
    skillPoints: {
      fate: -3,
      carving: 3,
      'wide-range': 3,
      spd_gather: 1
    }
  }),
  deepFreeze<LegArmor>({
    id: 27,
    type: 'legs',
    name: "Archer's Espadrilles",
    blade: false,
    gunner: true,
    defense: 8,
    fireRes: 0,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 1,
    rarity: 3,
    price: 10000,
    maxDefense: 8,
    maxLowRankDefense: 14,
    skillPoints: {
      fate: -3,
      carving: 3,
      'wide-range': 3,
      spd_gather: 1
    }
  }),
  deepFreeze<LegArmor>({
    id: 28,
    type: 'legs',
    name: 'Guild Bard Boots',
    blade: true,
    gunner: false,
    defense: 15,
    fireRes: 0,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 0,
    rarity: 3,
    price: 10000,
    maxDefense: 15,
    maxLowRankDefense: 27,
    skillPoints: {},
    torsoUp: true
  }),
  deepFreeze<LegArmor>({
    id: 29,
    type: 'legs',
    name: 'Guild Bard Gaiters',
    blade: false,
    gunner: true,
    defense: 8,
    fireRes: 0,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 0,
    rarity: 3,
    price: 10000,
    maxDefense: 8,
    maxLowRankDefense: 14,
    skillPoints: {},
    torsoUp: true
  }),
  deepFreeze<LegArmor>({
    id: 30,
    type: 'legs',
    name: 'Rathian Greaves',
    blade: true,
    gunner: false,
    defense: 16,
    fireRes: 3,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 2,
    rarity: 2,
    price: 3600,
    maxDefense: 16,
    maxLowRankDefense: 28,
    skillPoints: {
      hearing: 2,
      health: 2,
      protection: -1,
      fire_res: 2
    }
  }),
  deepFreeze<LegArmor>({
    id: 31,
    type: 'legs',
    name: 'Rathian Leggings',
    blade: false,
    gunner: true,
    defense: 8,
    fireRes: 3,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 2,
    rarity: 2,
    price: 3600,
    maxDefense: 8,
    maxLowRankDefense: 14,
    skillPoints: {
      hearing: 2,
      health: 1,
      protection: -1,
      fire_res: 3
    }
  }),
  deepFreeze<LegArmor>({
    id: 32,
    type: 'legs',
    name: 'Gigginox Greaves',
    blade: true,
    gunner: false,
    defense: 18,
    fireRes: -4,
    waterRes: 0,
    iceRes: 2,
    thunderRes: 2,
    dragonRes: -1,
    slots: 1,
    rarity: 2,
    price: 4100,
    maxDefense: 18,
    maxLowRankDefense: 30,
    skillPoints: { status: 4, poison: 2, health: -1, constitutn: 2 }
  }),
  deepFreeze<LegArmor>({
    id: 33,
    type: 'legs',
    name: 'Gigginox Leggings',
    blade: false,
    gunner: true,
    defense: 9,
    fireRes: -4,
    waterRes: 0,
    iceRes: 2,
    thunderRes: 2,
    dragonRes: -1,
    slots: 1,
    rarity: 2,
    price: 4100,
    maxDefense: 9,
    maxLowRankDefense: 15,
    skillPoints: { status: 3, poison: 3, health: -1, constitutn: 2 }
  }),
  deepFreeze<LegArmor>({
    id: 34,
    type: 'legs',
    name: 'Ingot Greaves',
    blade: true,
    gunner: false,
    defense: 18,
    fireRes: -2,
    waterRes: -1,
    iceRes: 1,
    thunderRes: 3,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    price: 5000,
    maxDefense: 18,
    maxLowRankDefense: 28,
    skillPoints: {
      sharpener: -1,
      guard_up: 3,
      wind_res: 2,
      thunderres: 3
    }
  }),
  deepFreeze<LegArmor>({
    id: 35,
    type: 'legs',
    name: 'Ingot Leggings',
    blade: false,
    gunner: true,
    defense: 9,
    fireRes: -2,
    waterRes: -1,
    iceRes: 1,
    thunderRes: 3,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    price: 5000,
    maxDefense: 9,
    maxLowRankDefense: 14,
    skillPoints: {
      recoil: 2,
      guard_up: 3,
      reload_spd: -1,
      thunderres: 3
    }
  }),
  deepFreeze<LegArmor>({
    id: 36,
    type: 'legs',
    name: 'Lagiacrus Greaves',
    blade: true,
    gunner: false,
    defense: 20,
    fireRes: -3,
    waterRes: 2,
    iceRes: -1,
    thunderRes: 4,
    dragonRes: -2,
    slots: 2,
    rarity: 3,
    price: 5600,
    maxDefense: 20,
    maxLowRankDefense: 30,
    skillPoints: {
      sharpness: 2,
      status: -2,
      elemental: 3,
      swimming: 1
    }
  }),
  deepFreeze<LegArmor>({
    id: 37,
    type: 'legs',
    name: 'Lagiacrus Leggings',
    blade: false,
    gunner: true,
    defense: 10,
    fireRes: -3,
    waterRes: 2,
    iceRes: -1,
    thunderRes: 4,
    dragonRes: -2,
    slots: 2,
    rarity: 3,
    price: 5600,
    maxDefense: 10,
    maxLowRankDefense: 15,
    skillPoints: {
      normals_up: 2,
      status: -2,
      elemental: 3,
      swimming: 1
    }
  }),
  deepFreeze<LegArmor>({
    id: 38,
    type: 'legs',
    name: 'Rathalos Greaves',
    blade: true,
    gunner: false,
    defense: 20,
    fireRes: 3,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 2,
    rarity: 3,
    price: 5600,
    maxDefense: 20,
    maxLowRankDefense: 30,
    skillPoints: { expert: 2, attack: 2, defense: -1, heat_res: 2 }
  }),
  deepFreeze<LegArmor>({
    id: 39,
    type: 'legs',
    name: 'Rathalos Leggings',
    blade: false,
    gunner: true,
    defense: 10,
    fireRes: 3,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 2,
    rarity: 3,
    price: 5600,
    maxDefense: 10,
    maxLowRankDefense: 15,
    skillPoints: { expert: 2, attack: 2, defense: -1, heat_res: 2 }
  }),
  deepFreeze<LegArmor>({
    id: 40,
    type: 'legs',
    name: 'Barioth Greaves',
    blade: true,
    gunner: false,
    defense: 20,
    fireRes: -4,
    waterRes: 2,
    iceRes: 4,
    thunderRes: -3,
    dragonRes: 0,
    slots: 2,
    rarity: 3,
    price: 5600,
    maxDefense: 20,
    maxLowRankDefense: 30,
    skillPoints: {
      stamina: 1,
      evasion: 3,
      heat_res: -1,
      cold_res: 2
    }
  }),
  deepFreeze<LegArmor>({
    id: 41,
    type: 'legs',
    name: 'Barioth Leggings',
    blade: false,
    gunner: true,
    defense: 10,
    fireRes: -4,
    waterRes: 2,
    iceRes: 4,
    thunderRes: -3,
    dragonRes: 0,
    slots: 2,
    rarity: 3,
    price: 5600,
    maxDefense: 10,
    maxLowRankDefense: 15,
    skillPoints: {
      stamina: 1,
      evasion: 2,
      heat_res: -2,
      cold_res: 2
    }
  }),
  deepFreeze<LegArmor>({
    id: 42,
    type: 'legs',
    name: 'Uragaan Greaves',
    blade: true,
    gunner: false,
    defense: 22,
    fireRes: 3,
    waterRes: -4,
    iceRes: -1,
    thunderRes: 1,
    dragonRes: -2,
    slots: 0,
    rarity: 3,
    price: 6300,
    maxDefense: 22,
    maxLowRankDefense: 30,
    skillPoints: {},
    torsoUp: true
  }),
  deepFreeze<LegArmor>({
    id: 43,
    type: 'legs',
    name: 'Uragaan Leggings',
    blade: false,
    gunner: true,
    defense: 11,
    fireRes: 3,
    waterRes: -4,
    iceRes: -1,
    thunderRes: 1,
    dragonRes: -2,
    slots: 0,
    rarity: 3,
    price: 6300,
    maxDefense: 11,
    maxLowRankDefense: 15,
    skillPoints: {},
    torsoUp: true
  }),
  deepFreeze<LegArmor>({
    id: 44,
    type: 'legs',
    name: 'Agnaktor Greaves',
    blade: true,
    gunner: false,
    defense: 22,
    fireRes: 4,
    waterRes: -4,
    iceRes: -2,
    thunderRes: 1,
    dragonRes: 0,
    slots: 0,
    rarity: 3,
    price: 7200,
    maxDefense: 22,
    maxLowRankDefense: 30,
    skillPoints: {
      stamina: -2,
      guard: 5,
      guard_up: 2,
      flame_aura: 2
    }
  }),
  deepFreeze<LegArmor>({
    id: 45,
    type: 'legs',
    name: 'Agnaktor Leggings',
    blade: false,
    gunner: true,
    defense: 11,
    fireRes: 4,
    waterRes: -4,
    iceRes: -2,
    thunderRes: 1,
    dragonRes: 0,
    slots: 0,
    rarity: 3,
    price: 7200,
    maxDefense: 11,
    maxLowRankDefense: 15,
    skillPoints: {
      stamina: -2,
      guard_up: 2,
      reload_spd: 4,
      flame_aura: 3
    }
  }),
  deepFreeze<LegArmor>({
    id: 46,
    type: 'legs',
    name: 'Helios Greaves',
    blade: true,
    gunner: false,
    defense: 24,
    fireRes: 0,
    waterRes: 4,
    iceRes: 3,
    thunderRes: -3,
    dragonRes: -4,
    slots: 0,
    rarity: 3,
    price: 11000,
    maxDefense: 24,
    maxLowRankDefense: 32,
    skillPoints: {
      sharpness: -1,
      handicraft: 5,
      hearing: 3,
      protection: -2
    }
  }),
  deepFreeze<LegArmor>({
    id: 47,
    type: 'legs',
    name: 'Helios Leggings',
    blade: false,
    gunner: true,
    defense: 12,
    fireRes: 0,
    waterRes: 4,
    iceRes: 3,
    thunderRes: -3,
    dragonRes: -4,
    slots: 0,
    rarity: 3,
    price: 11000,
    maxDefense: 12,
    maxLowRankDefense: 16,
    skillPoints: {
      recoil: -1,
      hearing: 3,
      loading: 5,
      protection: -2
    }
  }),
  deepFreeze<LegArmor>({
    id: 48,
    type: 'legs',
    name: 'Yamato Gusoku',
    blade: true,
    gunner: false,
    defense: 24,
    fireRes: 3,
    waterRes: 0,
    iceRes: -3,
    thunderRes: 0,
    dragonRes: -3,
    slots: 1,
    rarity: 3,
    price: 12000,
    maxDefense: 24,
    maxLowRankDefense: 32,
    skillPoints: {
      sharpness: 3,
      fastcharge: 3,
      rec_speed: 2,
      combo_rate: -1
    }
  }),
  deepFreeze<LegArmor>({
    id: 49,
    type: 'legs',
    name: 'Mutsu Gusoku',
    blade: false,
    gunner: true,
    defense: 12,
    fireRes: 3,
    waterRes: 0,
    iceRes: -3,
    thunderRes: 0,
    dragonRes: -3,
    slots: 1,
    rarity: 3,
    price: 12000,
    maxDefense: 12,
    maxLowRankDefense: 16,
    skillPoints: {
      recoil: 3,
      rec_speed: 3,
      'clust_s+': 2,
      combo_rate: -1
    }
  }),
  deepFreeze<LegArmor>({
    id: 50,
    type: 'legs',
    name: 'Leather Greaves+',
    blade: true,
    gunner: false,
    defense: 26,
    fireRes: -2,
    waterRes: 0,
    iceRes: -2,
    thunderRes: 3,
    dragonRes: 2,
    slots: 2,
    rarity: 4,
    price: 4600,
    maxDefense: 26,
    skillPoints: { gathering: 3, spd_gather: 3, whim: 2 }
  }),
  deepFreeze<LegArmor>({
    id: 51,
    type: 'legs',
    name: 'Leather Leggings+',
    blade: false,
    gunner: true,
    defense: 15,
    fireRes: -2,
    waterRes: 0,
    iceRes: -2,
    thunderRes: 3,
    dragonRes: 2,
    slots: 2,
    rarity: 4,
    price: 4600,
    maxDefense: 15,
    skillPoints: { gathering: 3, spd_gather: 3, whim: 2 }
  }),
  deepFreeze<LegArmor>({
    id: 52,
    type: 'legs',
    name: 'Piscine Leggings+',
    blade: true,
    gunner: false,
    defense: 26,
    fireRes: -3,
    waterRes: 5,
    iceRes: 2,
    thunderRes: -4,
    dragonRes: 0,
    slots: 1,
    rarity: 4,
    price: 4700,
    maxDefense: 26,
    skillPoints: { swimming: 10, currentres: 1 }
  }),
  deepFreeze<LegArmor>({
    id: 53,
    type: 'legs',
    name: 'Piscine Pants+',
    blade: false,
    gunner: true,
    defense: 15,
    fireRes: -3,
    waterRes: 5,
    iceRes: 2,
    thunderRes: -4,
    dragonRes: 0,
    slots: 1,
    rarity: 4,
    price: 4700,
    maxDefense: 15,
    skillPoints: { swimming: 10, currentres: 1 }
  }),
  deepFreeze<LegArmor>({
    id: 54,
    type: 'legs',
    name: 'Chainmail Greaves+',
    blade: true,
    gunner: false,
    defense: 30,
    fireRes: -1,
    waterRes: -2,
    iceRes: 4,
    thunderRes: -1,
    dragonRes: 1,
    slots: 2,
    rarity: 4,
    price: 5400,
    maxDefense: 30,
    skillPoints: { health: 3, combo_rate: 4, combo_plus: 1 }
  }),
  deepFreeze<LegArmor>({
    id: 55,
    type: 'legs',
    name: 'Chainmail Leggings+',
    blade: false,
    gunner: true,
    defense: 18,
    fireRes: -1,
    waterRes: -2,
    iceRes: 4,
    thunderRes: -1,
    dragonRes: 1,
    slots: 2,
    rarity: 4,
    price: 5400,
    maxDefense: 18,
    skillPoints: { health: 2, combo_rate: 4, combo_plus: 2 }
  }),
  deepFreeze<LegArmor>({
    id: 56,
    type: 'legs',
    name: 'Loc Lac Boots+',
    blade: true,
    gunner: false,
    defense: 30,
    fireRes: 5,
    waterRes: -4,
    iceRes: -5,
    thunderRes: 2,
    dragonRes: 0,
    slots: 1,
    rarity: 4,
    price: 5400,
    maxDefense: 30,
    skillPoints: { rec_speed: 2, transportr: 5, heat_res: 4 }
  }),
  deepFreeze<LegArmor>({
    id: 57,
    type: 'legs',
    name: 'Loc Lac Gaiters+',
    blade: false,
    gunner: true,
    defense: 18,
    fireRes: 5,
    waterRes: -4,
    iceRes: -5,
    thunderRes: 2,
    dragonRes: 0,
    slots: 1,
    rarity: 4,
    price: 5400,
    maxDefense: 18,
    skillPoints: { rec_speed: 2, transportr: 5, heat_res: 4 }
  }),
  deepFreeze<LegArmor>({
    id: 58,
    type: 'legs',
    name: "Hunter's Greaves+",
    blade: true,
    gunner: false,
    defense: 30,
    fireRes: 0,
    waterRes: -2,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 2,
    rarity: 4,
    price: 5400,
    maxDefense: 30,
    skillPoints: { psychic: 1, evasion: 2, water_res: -1, map: 5 }
  }),
  deepFreeze<LegArmor>({
    id: 59,
    type: 'legs',
    name: "Hunter's Leggings+",
    blade: false,
    gunner: true,
    defense: 18,
    fireRes: 0,
    waterRes: -2,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 2,
    rarity: 4,
    price: 5400,
    maxDefense: 18,
    skillPoints: { psychic: 1, evasion: 3, water_res: -2, map: 3 }
  }),
  deepFreeze<LegArmor>({
    id: 60,
    type: 'legs',
    name: 'Bone Greaves+',
    blade: true,
    gunner: false,
    defense: 34,
    fireRes: 3,
    waterRes: -2,
    iceRes: -1,
    thunderRes: 2,
    dragonRes: 3,
    slots: 2,
    rarity: 4,
    price: 6400,
    maxDefense: 34,
    skillPoints: { stamina: 3, hunger: 2, sleep: -1, perception: 3 }
  }),
  deepFreeze<LegArmor>({
    id: 61,
    type: 'legs',
    name: 'Bone Leggings+',
    blade: false,
    gunner: true,
    defense: 20,
    fireRes: 3,
    waterRes: -2,
    iceRes: -1,
    thunderRes: 2,
    dragonRes: 3,
    slots: 2,
    rarity: 4,
    price: 6400,
    maxDefense: 20,
    skillPoints: { stamina: 3, hunger: 2, sleep: -2, perception: 2 }
  }),
  deepFreeze<LegArmor>({
    id: 62,
    type: 'legs',
    name: 'Alloy Greaves+',
    blade: true,
    gunner: false,
    defense: 34,
    fireRes: 1,
    waterRes: 2,
    iceRes: -1,
    thunderRes: -2,
    dragonRes: -1,
    slots: 0,
    rarity: 4,
    price: 7100,
    maxDefense: 34,
    skillPoints: {},
    torsoUp: true
  }),
  deepFreeze<LegArmor>({
    id: 63,
    type: 'legs',
    name: 'Alloy Leggings+',
    blade: false,
    gunner: true,
    defense: 20,
    fireRes: 1,
    waterRes: 2,
    iceRes: -1,
    thunderRes: -2,
    dragonRes: -1,
    slots: 0,
    rarity: 4,
    price: 7100,
    maxDefense: 20,
    skillPoints: {},
    torsoUp: true
  }),
  deepFreeze<LegArmor>({
    id: 64,
    type: 'legs',
    name: 'Jaggi Greaves+',
    blade: true,
    gunner: false,
    defense: 38,
    fireRes: -3,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: 2,
    slots: 2,
    rarity: 5,
    price: 8000,
    maxDefense: 38,
    skillPoints: {
      expert: 2,
      attack: 2,
      stun: 3,
      gluttony: 1,
      cold_res: -1
    }
  }),
  deepFreeze<LegArmor>({
    id: 65,
    type: 'legs',
    name: 'Jaggi Leggings+',
    blade: false,
    gunner: true,
    defense: 22,
    fireRes: -3,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: 2,
    slots: 2,
    rarity: 5,
    price: 8000,
    maxDefense: 22,
    skillPoints: {
      expert: 2,
      attack: 2,
      stun: 2,
      gluttony: 2,
      cold_res: -1
    }
  }),
  deepFreeze<LegArmor>({
    id: 66,
    type: 'legs',
    name: 'Bnahabra Greaves+',
    blade: true,
    gunner: false,
    defense: 38,
    fireRes: -5,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 2,
    dragonRes: 6,
    slots: 1,
    rarity: 5,
    price: 10500,
    maxDefense: 38,
    skillPoints: { sharpness: 6, status: 2, poison: -3 }
  }),
  deepFreeze<LegArmor>({
    id: 67,
    type: 'legs',
    name: 'Bnahabra Leggings+',
    blade: false,
    gunner: true,
    defense: 22,
    fireRes: -5,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 2,
    dragonRes: 6,
    slots: 1,
    rarity: 5,
    price: 10500,
    maxDefense: 22,
    skillPoints: { status: 2, poison: -3, reload_spd: 6 }
  }),
  deepFreeze<LegArmor>({
    id: 68,
    type: 'legs',
    name: 'Rhenoplos Greaves+',
    blade: true,
    gunner: false,
    defense: 38,
    fireRes: 3,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -2,
    dragonRes: 2,
    slots: 2,
    rarity: 5,
    price: 8500,
    maxDefense: 38,
    skillPoints: {
      wind_res: 1,
      eating: 2,
      'mud/snow': 5,
      thunderres: -1
    }
  }),
  deepFreeze<LegArmor>({
    id: 69,
    type: 'legs',
    name: 'Rhenoplos Leggings+',
    blade: false,
    gunner: true,
    defense: 22,
    fireRes: 3,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -2,
    dragonRes: 2,
    slots: 2,
    rarity: 5,
    price: 8500,
    maxDefense: 22,
    skillPoints: {
      recoil: 3,
      'crag_s+': 3,
      eating: 2,
      thunderres: -1
    }
  }),
  deepFreeze<LegArmor>({
    id: 70,
    type: 'legs',
    name: 'Qurupeco Greaves+',
    blade: true,
    gunner: false,
    defense: 42,
    fireRes: 4,
    waterRes: -3,
    iceRes: -4,
    thunderRes: 0,
    dragonRes: 1,
    slots: 3,
    rarity: 5,
    price: 10000,
    maxDefense: 42,
    skillPoints: {
      defense: 1,
      'wide-range': 2,
      rec_level: 1,
      ice_res: -3
    }
  }),
  deepFreeze<LegArmor>({
    id: 71,
    type: 'legs',
    name: 'Qurupeco Leggings+',
    blade: false,
    gunner: true,
    defense: 25,
    fireRes: 4,
    waterRes: -3,
    iceRes: -4,
    thunderRes: 0,
    dragonRes: 1,
    slots: 3,
    rarity: 5,
    price: 10000,
    maxDefense: 25,
    skillPoints: {
      defense: 2,
      'wide-range': 1,
      rec_level: 1,
      ice_res: -3
    }
  }),
  deepFreeze<LegArmor>({
    id: 72,
    type: 'legs',
    name: 'Ludroth Greaves+',
    blade: true,
    gunner: false,
    defense: 44,
    fireRes: -4,
    waterRes: 4,
    iceRes: 0,
    thunderRes: -1,
    dragonRes: 1,
    slots: 2,
    rarity: 5,
    price: 11800,
    maxDefense: 44,
    skillPoints: {
      hunger: -1,
      protection: 2,
      constitutn: 3,
      currentres: 3
    }
  }),
  deepFreeze<LegArmor>({
    id: 73,
    type: 'legs',
    name: 'Ludroth Leggings+',
    blade: false,
    gunner: true,
    defense: 26,
    fireRes: -4,
    waterRes: 4,
    iceRes: 0,
    thunderRes: -1,
    dragonRes: 1,
    slots: 2,
    rarity: 5,
    price: 11800,
    maxDefense: 26,
    skillPoints: {
      'pellet_s+': 3,
      hunger: -1,
      protection: 3,
      constitutn: 2
    }
  }),
  deepFreeze<LegArmor>({
    id: 74,
    type: 'legs',
    name: 'Baggi Greaves+',
    blade: true,
    gunner: false,
    defense: 44,
    fireRes: -4,
    waterRes: -1,
    iceRes: 4,
    thunderRes: -1,
    dragonRes: 1,
    slots: 0,
    rarity: 5,
    price: 12300,
    maxDefense: 44,
    skillPoints: {
      tranquilzr: 3,
      fastcharge: 2,
      stun: -1,
      ice_res: 7
    }
  }),
  deepFreeze<LegArmor>({
    id: 75,
    type: 'legs',
    name: 'Baggi Leggings+',
    blade: false,
    gunner: true,
    defense: 26,
    fireRes: -4,
    waterRes: -1,
    iceRes: 4,
    thunderRes: -1,
    dragonRes: 1,
    slots: 0,
    rarity: 5,
    price: 12300,
    maxDefense: 26,
    skillPoints: {
      pellets_up: 2,
      tranquilzr: 3,
      stun: -2,
      ice_res: 6
    }
  }),
  deepFreeze<LegArmor>({
    id: 76,
    type: 'legs',
    name: 'Barroth Greaves+',
    blade: true,
    gunner: false,
    defense: 48,
    fireRes: 5,
    waterRes: -5,
    iceRes: -4,
    thunderRes: 4,
    dragonRes: 0,
    slots: 1,
    rarity: 5,
    price: 13800,
    maxDefense: 48,
    skillPoints: { stamina: 4, expert: -2, attack: 1, potential: 4 }
  }),
  deepFreeze<LegArmor>({
    id: 77,
    type: 'legs',
    name: 'Barroth Leggings+',
    blade: false,
    gunner: true,
    defense: 28,
    fireRes: 5,
    waterRes: -5,
    iceRes: -4,
    thunderRes: 4,
    dragonRes: 0,
    slots: 1,
    rarity: 5,
    price: 13800,
    maxDefense: 28,
    skillPoints: { stamina: 4, expert: -2, attack: 1, potential: 4 }
  }),
  deepFreeze<LegArmor>({
    id: 78,
    type: 'legs',
    name: 'Gobul Greaves+',
    blade: true,
    gunner: false,
    defense: 50,
    fireRes: -2,
    waterRes: 4,
    iceRes: 0,
    thunderRes: -4,
    dragonRes: 2,
    slots: 3,
    rarity: 5,
    price: 14800,
    maxDefense: 50,
    skillPoints: { rec_speed: -2, expert: 2, eating: 1, stun: 2 }
  }),
  deepFreeze<LegArmor>({
    id: 79,
    type: 'legs',
    name: 'Gobul Leggings+',
    blade: false,
    gunner: true,
    defense: 30,
    fireRes: -2,
    waterRes: 4,
    iceRes: 0,
    thunderRes: -4,
    dragonRes: 2,
    slots: 3,
    rarity: 5,
    price: 14800,
    maxDefense: 30,
    skillPoints: { rec_speed: -3, expert: 2, eating: 1, stun: 1 }
  }),
  deepFreeze<LegArmor>({
    id: 80,
    type: 'legs',
    name: 'Guild Bard Boots+',
    blade: true,
    gunner: false,
    defense: 36,
    fireRes: 0,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 0,
    rarity: 6,
    price: 25000,
    maxDefense: 36,
    skillPoints: {},
    torsoUp: true
  }),
  deepFreeze<LegArmor>({
    id: 81,
    type: 'legs',
    name: 'Guild Bard Gaiters+',
    blade: false,
    gunner: true,
    defense: 22,
    fireRes: 0,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 0,
    rarity: 6,
    price: 25000,
    maxDefense: 22,
    skillPoints: {},
    torsoUp: true
  }),
  deepFreeze<LegArmor>({
    id: 82,
    type: 'legs',
    name: 'Rathian Greaves+',
    blade: true,
    gunner: false,
    defense: 50,
    fireRes: 4,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 1,
    rarity: 5,
    price: 14800,
    maxDefense: 50,
    skillPoints: {
      hearing: 2,
      health: 3,
      protection: -3,
      fire_res: 3
    }
  }),
  deepFreeze<LegArmor>({
    id: 83,
    type: 'legs',
    name: 'Rathian Leggings+',
    blade: false,
    gunner: true,
    defense: 30,
    fireRes: 4,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 1,
    rarity: 5,
    price: 14800,
    maxDefense: 30,
    skillPoints: {
      hearing: 2,
      health: 2,
      protection: -3,
      fire_res: 4
    }
  }),
  deepFreeze<LegArmor>({
    id: 84,
    type: 'legs',
    name: 'Gigginox Greaves+',
    blade: true,
    gunner: false,
    defense: 54,
    fireRes: -4,
    waterRes: -1,
    iceRes: 2,
    thunderRes: 3,
    dragonRes: 0,
    slots: 3,
    rarity: 5,
    price: 15800,
    maxDefense: 54,
    skillPoints: { status: 2, poison: 1, health: -2, constitutn: 2 }
  }),
  deepFreeze<LegArmor>({
    id: 85,
    type: 'legs',
    name: 'Gigginox Leggings+',
    blade: false,
    gunner: true,
    defense: 32,
    fireRes: -4,
    waterRes: -1,
    iceRes: 2,
    thunderRes: 3,
    dragonRes: 0,
    slots: 3,
    rarity: 5,
    price: 15800,
    maxDefense: 32,
    skillPoints: { status: 2, poison: 1, health: -3, constitutn: 1 }
  }),
  deepFreeze<LegArmor>({
    id: 86,
    type: 'legs',
    name: 'Ingot Greaves+',
    blade: true,
    gunner: false,
    defense: 54,
    fireRes: -2,
    waterRes: -1,
    iceRes: 1,
    thunderRes: 3,
    dragonRes: 2,
    slots: 1,
    rarity: 5,
    price: 17500,
    maxDefense: 54,
    skillPoints: {
      sharpener: -1,
      guard_up: 2,
      wind_res: 5,
      thunderres: 3
    }
  }),
  deepFreeze<LegArmor>({
    id: 87,
    type: 'legs',
    name: 'Ingot Leggings+',
    blade: false,
    gunner: true,
    defense: 32,
    fireRes: -2,
    waterRes: -1,
    iceRes: 1,
    thunderRes: 3,
    dragonRes: 2,
    slots: 1,
    rarity: 5,
    price: 17500,
    maxDefense: 32,
    skillPoints: {
      recoil: 5,
      guard_up: 2,
      reload_spd: -1,
      thunderres: 3
    }
  }),
  deepFreeze<LegArmor>({
    id: 88,
    type: 'legs',
    name: 'Dober Greaves',
    blade: true,
    gunner: false,
    defense: 58,
    fireRes: -2,
    waterRes: -2,
    iceRes: 1,
    thunderRes: 1,
    dragonRes: 5,
    slots: 3,
    rarity: 6,
    price: 19000,
    maxDefense: 58,
    skillPoints: {
      stamina: 1,
      potential: -3,
      crit_draw: 1,
      dragon_res: 2
    }
  }),
  deepFreeze<LegArmor>({
    id: 89,
    type: 'legs',
    name: 'Dober Leggings',
    blade: false,
    gunner: true,
    defense: 34,
    fireRes: -2,
    waterRes: -2,
    iceRes: 1,
    thunderRes: 1,
    dragonRes: 5,
    slots: 3,
    rarity: 6,
    price: 19000,
    maxDefense: 34,
    skillPoints: {
      pellets_up: 1,
      'pellet_s+': 2,
      potential: -3,
      dragon_res: 1
    }
  }),
  deepFreeze<LegArmor>({
    id: 90,
    type: 'legs',
    name: 'Lagiacrus Greaves+',
    blade: true,
    gunner: false,
    defense: 58,
    fireRes: -4,
    waterRes: 2,
    iceRes: -1,
    thunderRes: 5,
    dragonRes: -2,
    slots: 1,
    rarity: 6,
    price: 18000,
    maxDefense: 58,
    skillPoints: {
      status: -2,
      elemental: 3,
      freeelemnt: 4,
      swimming: 2
    }
  }),
  deepFreeze<LegArmor>({
    id: 91,
    type: 'legs',
    name: 'Lagiacrus Leggings+',
    blade: false,
    gunner: true,
    defense: 34,
    fireRes: -4,
    waterRes: 2,
    iceRes: -1,
    thunderRes: 5,
    dragonRes: -2,
    slots: 1,
    rarity: 6,
    price: 18000,
    maxDefense: 34,
    skillPoints: {
      status: -2,
      elemental: 3,
      rapid_fire: 3,
      swimming: 3
    }
  }),
  deepFreeze<LegArmor>({
    id: 92,
    type: 'legs',
    name: 'Rathalos Greaves+',
    blade: true,
    gunner: false,
    defense: 58,
    fireRes: 4,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 0,
    rarity: 6,
    price: 18000,
    maxDefense: 58,
    skillPoints: { fencing: 3, expert: 3, defense: -2, heat_res: 5 }
  }),
  deepFreeze<LegArmor>({
    id: 93,
    type: 'legs',
    name: 'Rathalos Leggings+',
    blade: false,
    gunner: true,
    defense: 34,
    fireRes: 4,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 0,
    rarity: 6,
    price: 18000,
    maxDefense: 34,
    skillPoints: {
      normals_up: 2,
      expert: 3,
      defense: -2,
      heat_res: 6
    }
  }),
  deepFreeze<LegArmor>({
    id: 94,
    type: 'legs',
    name: 'Barioth Greaves+',
    blade: true,
    gunner: false,
    defense: 58,
    fireRes: -4,
    waterRes: 2,
    iceRes: 5,
    thunderRes: -3,
    dragonRes: 0,
    slots: 0,
    rarity: 6,
    price: 18000,
    maxDefense: 58,
    skillPoints: {
      evade_dist: 4,
      evasion: 3,
      heat_res: -2,
      cold_res: 4
    }
  }),
  deepFreeze<LegArmor>({
    id: 95,
    type: 'legs',
    name: 'Barioth Leggings+',
    blade: false,
    gunner: true,
    defense: 34,
    fireRes: -4,
    waterRes: 2,
    iceRes: 5,
    thunderRes: -3,
    dragonRes: 0,
    slots: 0,
    rarity: 6,
    price: 18000,
    maxDefense: 34,
    skillPoints: {
      evade_dist: 4,
      evasion: 3,
      heat_res: -2,
      cold_res: 4
    }
  }),
  deepFreeze<LegArmor>({
    id: 96,
    type: 'legs',
    name: 'Uragaan Greaves+',
    blade: true,
    gunner: false,
    defense: 62,
    fireRes: 4,
    waterRes: -4,
    iceRes: -1,
    thunderRes: 1,
    dragonRes: -2,
    slots: 3,
    rarity: 6,
    price: 18800,
    maxDefense: 62,
    skillPoints: {
      punishdraw: 2,
      bomb_boost: 1,
      defense: 1,
      eating: -3
    }
  }),
  deepFreeze<LegArmor>({
    id: 97,
    type: 'legs',
    name: 'Uragaan Leggings+',
    blade: false,
    gunner: true,
    defense: 37,
    fireRes: 4,
    waterRes: -4,
    iceRes: -1,
    thunderRes: 1,
    dragonRes: -2,
    slots: 3,
    rarity: 6,
    price: 18800,
    maxDefense: 37,
    skillPoints: {
      recoil: 1,
      bomb_boost: 1,
      defense: 2,
      eating: -3
    }
  }),
  deepFreeze<LegArmor>({
    id: 98,
    type: 'legs',
    name: 'Agnaktor Greaves+',
    blade: true,
    gunner: false,
    defense: 62,
    fireRes: 5,
    waterRes: -4,
    iceRes: -2,
    thunderRes: 1,
    dragonRes: 0,
    slots: 2,
    rarity: 6,
    price: 19800,
    maxDefense: 62,
    skillPoints: {
      sharpness: 2,
      stamina: -1,
      guard: 2,
      flame_aura: 4
    }
  }),
  deepFreeze<LegArmor>({
    id: 99,
    type: 'legs',
    name: 'Agnaktor Leggings+',
    blade: false,
    gunner: true,
    defense: 37,
    fireRes: 5,
    waterRes: -4,
    iceRes: -2,
    thunderRes: 1,
    dragonRes: 0,
    slots: 2,
    rarity: 6,
    price: 19800,
    maxDefense: 37,
    skillPoints: {
      normals_up: 2,
      'normal_s+': 1,
      stamina: -2,
      flame_aura: 4
    }
  }),
  deepFreeze<LegArmor>({
    id: 100,
    type: 'legs',
    name: 'Vangis Greaves',
    blade: true,
    gunner: false,
    defense: 64,
    fireRes: 0,
    waterRes: 0,
    iceRes: 3,
    thunderRes: -4,
    dragonRes: -4,
    slots: 3,
    rarity: 7,
    price: 41500,
    maxDefense: 64,
    skillPoints: {
      handicraft: 2,
      hunger: -3,
      attack: 1,
      psychic: 1
    }
  }),
  deepFreeze<LegArmor>({
    id: 101,
    type: 'legs',
    name: 'Vangis Leggings',
    blade: false,
    gunner: true,
    defense: 38,
    fireRes: 0,
    waterRes: 0,
    iceRes: 3,
    thunderRes: -4,
    dragonRes: -4,
    slots: 3,
    rarity: 7,
    price: 41500,
    maxDefense: 38,
    skillPoints: { loading: 2, hunger: -3, attack: 1, psychic: 1 }
  }),
  deepFreeze<LegArmor>({
    id: 102,
    type: 'legs',
    name: 'Damascus Greaves',
    blade: true,
    gunner: false,
    defense: 62,
    fireRes: -2,
    waterRes: 0,
    iceRes: 2,
    thunderRes: -2,
    dragonRes: 3,
    slots: 1,
    rarity: 6,
    price: 32300,
    maxDefense: 62,
    skillPoints: {
      stamina: -1,
      punishdraw: 2,
      health: 5,
      guard_up: 3
    }
  }),
  deepFreeze<LegArmor>({
    id: 103,
    type: 'legs',
    name: 'Damascus Leggings',
    blade: false,
    gunner: true,
    defense: 37,
    fireRes: -2,
    waterRes: 0,
    iceRes: 2,
    thunderRes: -2,
    dragonRes: 3,
    slots: 0,
    rarity: 6,
    price: 32300,
    maxDefense: 37,
    skillPoints: {
      stamina: -1,
      health: 6,
      guard_up: 2,
      reload_spd: 4
    }
  }),
  deepFreeze<LegArmor>({
    id: 104,
    type: 'legs',
    name: 'Helios Greaves+',
    blade: true,
    gunner: false,
    defense: 66,
    fireRes: 0,
    waterRes: 5,
    iceRes: 3,
    thunderRes: -3,
    dragonRes: -4,
    slots: 0,
    rarity: 6,
    price: 26200,
    maxDefense: 66,
    skillPoints: {
      sharpness: -3,
      handicraft: 4,
      hearing: 4,
      protection: -2
    }
  }),
  deepFreeze<LegArmor>({
    id: 105,
    type: 'legs',
    name: 'Helios Leggings+',
    blade: false,
    gunner: true,
    defense: 39,
    fireRes: 0,
    waterRes: 5,
    iceRes: 3,
    thunderRes: -3,
    dragonRes: -4,
    slots: 0,
    rarity: 6,
    price: 26200,
    maxDefense: 39,
    skillPoints: {
      recoil: -3,
      hearing: 4,
      loading: 4,
      protection: -2
    }
  }),
  deepFreeze<LegArmor>({
    id: 106,
    type: 'legs',
    name: 'Yamato Gusoku+',
    blade: true,
    gunner: false,
    defense: 66,
    fireRes: 4,
    waterRes: 0,
    iceRes: -3,
    thunderRes: 0,
    dragonRes: -4,
    slots: 0,
    rarity: 6,
    price: 27500,
    maxDefense: 66,
    skillPoints: {
      sharpness: 2,
      fastcharge: 3,
      rec_speed: 5,
      combo_rate: -3
    }
  }),
  deepFreeze<LegArmor>({
    id: 107,
    type: 'legs',
    name: 'Mutsu Gusoku+',
    blade: false,
    gunner: true,
    defense: 39,
    fireRes: 4,
    waterRes: 0,
    iceRes: -3,
    thunderRes: 0,
    dragonRes: -4,
    slots: 0,
    rarity: 6,
    price: 27500,
    maxDefense: 39,
    skillPoints: {
      recoil: 3,
      rec_speed: 4,
      'clust_s+': 4,
      combo_rate: -2
    }
  }),
  deepFreeze<LegArmor>({
    id: 108,
    type: 'legs',
    name: 'Escadora Scale',
    blade: true,
    gunner: false,
    defense: 70,
    fireRes: -1,
    waterRes: -1,
    iceRes: -1,
    thunderRes: 0,
    dragonRes: -5,
    slots: 0,
    rarity: 7,
    price: 66666,
    maxDefense: 70,
    skillPoints: {
      evade_dist: 4,
      freeelemnt: 5,
      rec_level: -2,
      blight_res: 2
    }
  }),
  deepFreeze<LegArmor>({
    id: 109,
    type: 'legs',
    name: 'Escadora Scala',
    blade: false,
    gunner: true,
    defense: 42,
    fireRes: -1,
    waterRes: -1,
    iceRes: -1,
    thunderRes: 0,
    dragonRes: -5,
    slots: 1,
    rarity: 7,
    price: 66666,
    maxDefense: 42,
    skillPoints: {
      evade_dist: 4,
      rapid_fire: 3,
      rec_level: -2,
      blight_res: 2
    }
  }),
  deepFreeze<LegArmor>({
    id: 110,
    type: 'legs',
    name: 'Chakra Anklet',
    blade: true,
    gunner: true,
    defense: 18,
    fireRes: 0,
    waterRes: -10,
    iceRes: 0,
    thunderRes: 10,
    dragonRes: 0,
    slots: 3,
    rarity: 7,
    price: 33333,
    maxDefense: 18,
    skillPoints: {}
  }),
  deepFreeze<LegArmor>({
    id: 111,
    type: 'legs',
    name: 'Black Leather Pants',
    blade: true,
    gunner: true,
    defense: 28,
    fireRes: 2,
    waterRes: 2,
    iceRes: 2,
    thunderRes: 2,
    dragonRes: 2,
    slots: 0,
    rarity: 6,
    price: 15000,
    maxDefense: 28,
    skillPoints: { potential: 13 }
  })
];
