import { deepFreeze } from '../../utils';
import { LegArmor } from './types';

export const LegArmors: LegArmor[] = [
  deepFreeze<LegArmor>({
    id: 0,
    type: 'legs',
    name: 'Leather Pants',
    blade: true,
    gunner: true,
    defense: 1,
    fireRes: -1,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 3,
    dragonRes: 2,
    slots: 1,
    rarity: 1,
    skillPoints: [
      { skillId: 35, points: 1 },
      { skillId: 40, points: 3 },
      { skillId: 41, points: 1 },
      { skillId: 69, points: 3 }
    ],
    price: 150,
    maxDefense: 1,
    maxLowRankDefense: 9
  }),
  deepFreeze<LegArmor>({
    id: 1,
    type: 'legs',
    name: 'Piscine Leggings',
    blade: true,
    gunner: true,
    defense: 3,
    fireRes: -2,
    waterRes: 4,
    iceRes: 2,
    thunderRes: -3,
    dragonRes: 0,
    slots: 1,
    rarity: 1,
    skillPoints: [
      { skillId: 50, points: 8 },
      { skillId: 79, points: 1 }
    ],
    price: 300,
    maxDefense: 3,
    maxLowRankDefense: 11
  }),
  deepFreeze<LegArmor>({
    id: 2,
    type: 'legs',
    name: 'Chainmail Pants',
    blade: true,
    gunner: true,
    defense: 2,
    fireRes: -1,
    waterRes: -1,
    iceRes: 3,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 1,
    skillPoints: [
      { skillId: 23, points: 2 },
      { skillId: 70, points: 4 },
      { skillId: 71, points: 1 },
      { skillId: 72, points: 2 }
    ],
    price: 200,
    maxDefense: 2,
    maxLowRankDefense: 9
  }),
  deepFreeze<LegArmor>({
    id: 3,
    type: 'legs',
    name: 'Loc Lac Boots',
    blade: true,
    gunner: true,
    defense: 4,
    fireRes: 4,
    waterRes: -3,
    iceRes: -4,
    thunderRes: 2,
    dragonRes: 0,
    slots: 0,
    rarity: 1,
    skillPoints: [
      { skillId: 24, points: 3 },
      { skillId: 60, points: 5 },
      { skillId: 66, points: 3 }
    ],
    price: 500,
    maxDefense: 4,
    maxLowRankDefense: 11
  }),
  deepFreeze<LegArmor>({
    id: 4,
    type: 'legs',
    name: "Hunter's Greaves",
    blade: true,
    gunner: false,
    defense: 6,
    fireRes: -1,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: -1,
    slots: 1,
    rarity: 1,
    skillPoints: [
      { skillId: 42, points: 2 },
      { skillId: 62, points: -1 },
      { skillId: 68, points: 4 },
      { skillId: 75, points: 2 }
    ],
    price: 500,
    maxDefense: 6,
    maxLowRankDefense: 20
  }),
  deepFreeze<LegArmor>({
    id: 5,
    type: 'legs',
    name: "Hunter's Leggings",
    blade: false,
    gunner: true,
    defense: 3,
    fireRes: -1,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: -1,
    slots: 1,
    rarity: 1,
    skillPoints: [
      { skillId: 42, points: 2 },
      { skillId: 62, points: -1 },
      { skillId: 68, points: 4 },
      { skillId: 75, points: 2 }
    ],
    price: 500,
    maxDefense: 3,
    maxLowRankDefense: 10
  }),
  deepFreeze<LegArmor>({
    id: 6,
    type: 'legs',
    name: 'Bone Greaves',
    blade: true,
    gunner: false,
    defense: 8,
    fireRes: 2,
    waterRes: -2,
    iceRes: -1,
    thunderRes: 2,
    dragonRes: 3,
    slots: 1,
    rarity: 1,
    skillPoints: [
      { skillId: 34, points: 1 },
      { skillId: 35, points: 1 },
      { skillId: 54, points: -1 },
      { skillId: 73, points: 2 },
      { skillId: 77, points: 4 }
    ],
    price: 750,
    maxDefense: 8,
    maxLowRankDefense: 22
  }),
  deepFreeze<LegArmor>({
    id: 7,
    type: 'legs',
    name: 'Bone Leggings',
    blade: false,
    gunner: true,
    defense: 4,
    fireRes: 2,
    waterRes: -2,
    iceRes: -1,
    thunderRes: 2,
    dragonRes: 3,
    slots: 1,
    rarity: 1,
    skillPoints: [
      { skillId: 34, points: 1 },
      { skillId: 35, points: 1 },
      { skillId: 54, points: -1 },
      { skillId: 73, points: 2 },
      { skillId: 77, points: 4 }
    ],
    price: 750,
    maxDefense: 4,
    maxLowRankDefense: 11
  }),
  deepFreeze<LegArmor>({
    id: 8,
    type: 'legs',
    name: 'Alloy Greaves',
    blade: true,
    gunner: false,
    defense: 8,
    fireRes: 1,
    waterRes: 1,
    iceRes: -1,
    thunderRes: -2,
    dragonRes: -1,
    slots: 0,
    rarity: 1,
    skillPoints: [{ skillId: 83, points: 0 }],
    price: 1000,
    maxDefense: 8,
    maxLowRankDefense: 22
  }),
  deepFreeze<LegArmor>({
    id: 9,
    type: 'legs',
    name: 'Alloy Leggings',
    blade: false,
    gunner: true,
    defense: 4,
    fireRes: 1,
    waterRes: 1,
    iceRes: -1,
    thunderRes: -2,
    dragonRes: -1,
    slots: 0,
    rarity: 1,
    skillPoints: [{ skillId: 83, points: 0 }],
    price: 1000,
    maxDefense: 4,
    maxLowRankDefense: 11
  }),
  deepFreeze<LegArmor>({
    id: 10,
    type: 'legs',
    name: 'Jaggi Greaves',
    blade: true,
    gunner: false,
    defense: 10,
    fireRes: -3,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 35, points: 3 },
      { skillId: 55, points: 2 },
      { skillId: 58, points: 2 },
      { skillId: 67, points: -2 }
    ],
    price: 1200,
    maxDefense: 10,
    maxLowRankDefense: 24
  }),
  deepFreeze<LegArmor>({
    id: 11,
    type: 'legs',
    name: 'Jaggi Leggings',
    blade: false,
    gunner: true,
    defense: 5,
    fireRes: -3,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 35, points: 3 },
      { skillId: 55, points: 3 },
      { skillId: 58, points: 1 },
      { skillId: 67, points: -2 }
    ],
    price: 1200,
    maxDefense: 5,
    maxLowRankDefense: 12
  }),
  deepFreeze<LegArmor>({
    id: 12,
    type: 'legs',
    name: 'Bnahabra Boots',
    blade: true,
    gunner: false,
    defense: 10,
    fireRes: -4,
    waterRes: -1,
    iceRes: -1,
    thunderRes: 2,
    dragonRes: 5,
    slots: 0,
    rarity: 2,
    skillPoints: [
      { skillId: 0, points: 4 },
      { skillId: 9, points: 4 },
      { skillId: 22, points: -3 }
    ],
    price: 1800,
    maxDefense: 10,
    maxLowRankDefense: 24
  }),
  deepFreeze<LegArmor>({
    id: 13,
    type: 'legs',
    name: 'Bnahabra Pants',
    blade: false,
    gunner: true,
    defense: 5,
    fireRes: -4,
    waterRes: -1,
    iceRes: -1,
    thunderRes: 2,
    dragonRes: 5,
    slots: 0,
    rarity: 2,
    skillPoints: [
      { skillId: 9, points: 4 },
      { skillId: 22, points: -3 },
      { skillId: 29, points: 4 }
    ],
    price: 1800,
    maxDefense: 5,
    maxLowRankDefense: 12
  }),
  deepFreeze<LegArmor>({
    id: 14,
    type: 'legs',
    name: 'Rhenoplos Greaves',
    blade: true,
    gunner: false,
    defense: 12,
    fireRes: 2,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: 2,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 39, points: 3 },
      { skillId: 46, points: 2 },
      { skillId: 56, points: 3 },
      { skillId: 63, points: -1 }
    ],
    price: 1400,
    maxDefense: 12,
    maxLowRankDefense: 24
  }),
  deepFreeze<LegArmor>({
    id: 15,
    type: 'legs',
    name: 'Rhenoplos Leggings',
    blade: false,
    gunner: true,
    defense: 6,
    fireRes: 2,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: 2,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 3, points: 1 },
      { skillId: 31, points: 2 },
      { skillId: 46, points: 4 },
      { skillId: 63, points: -2 }
    ],
    price: 1400,
    maxDefense: 6,
    maxLowRankDefense: 12
  }),
  deepFreeze<LegArmor>({
    id: 16,
    type: 'legs',
    name: 'Qurupeco Greaves',
    blade: true,
    gunner: false,
    defense: 12,
    fireRes: 2,
    waterRes: -2,
    iceRes: -3,
    thunderRes: 0,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 36, points: 1 },
      { skillId: 43, points: 4 },
      { skillId: 44, points: 3 },
      { skillId: 64, points: -1 }
    ],
    price: 1700,
    maxDefense: 12,
    maxLowRankDefense: 24
  }),
  deepFreeze<LegArmor>({
    id: 17,
    type: 'legs',
    name: 'Qurupeco Leggings',
    blade: false,
    gunner: true,
    defense: 6,
    fireRes: 2,
    waterRes: -2,
    iceRes: -3,
    thunderRes: 0,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 36, points: 4 },
      { skillId: 43, points: 2 },
      { skillId: 44, points: 2 },
      { skillId: 64, points: -1 }
    ],
    price: 1700,
    maxDefense: 6,
    maxLowRankDefense: 12
  }),
  deepFreeze<LegArmor>({
    id: 18,
    type: 'legs',
    name: 'Ludroth Greaves',
    blade: true,
    gunner: false,
    defense: 13,
    fireRes: -3,
    waterRes: 2,
    iceRes: 0,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 35, points: 2 },
      { skillId: 37, points: 2 },
      { skillId: 49, points: 2 },
      { skillId: 61, points: -1 },
      { skillId: 79, points: 2 }
    ],
    price: 2200,
    maxDefense: 13,
    maxLowRankDefense: 25
  }),
  deepFreeze<LegArmor>({
    id: 19,
    type: 'legs',
    name: 'Ludroth Leggings',
    blade: false,
    gunner: true,
    defense: 7,
    fireRes: -3,
    waterRes: 2,
    iceRes: 0,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 30, points: 2 },
      { skillId: 35, points: 2 },
      { skillId: 37, points: 2 },
      { skillId: 49, points: 2 },
      { skillId: 61, points: -1 }
    ],
    price: 2200,
    maxDefense: 7,
    maxLowRankDefense: 13
  }),
  deepFreeze<LegArmor>({
    id: 20,
    type: 'legs',
    name: 'Baggi Greaves',
    blade: true,
    gunner: false,
    defense: 13,
    fireRes: -3,
    waterRes: -1,
    iceRes: 3,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 17, points: 4 },
      { skillId: 18, points: 3 },
      { skillId: 55, points: -1 },
      { skillId: 64, points: 1 }
    ],
    price: 2400,
    maxDefense: 13,
    maxLowRankDefense: 25
  }),
  deepFreeze<LegArmor>({
    id: 21,
    type: 'legs',
    name: 'Baggi Leggings',
    blade: false,
    gunner: true,
    defense: 7,
    fireRes: -3,
    waterRes: -1,
    iceRes: 3,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 6, points: 2 },
      { skillId: 17, points: 4 },
      { skillId: 55, points: -1 },
      { skillId: 64, points: 2 }
    ],
    price: 2400,
    maxDefense: 7,
    maxLowRankDefense: 13
  }),
  deepFreeze<LegArmor>({
    id: 22,
    type: 'legs',
    name: 'Barroth Greaves',
    blade: true,
    gunner: false,
    defense: 15,
    fireRes: 4,
    waterRes: -4,
    iceRes: -3,
    thunderRes: 3,
    dragonRes: 0,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 13, points: 4 },
      { skillId: 25, points: -2 },
      { skillId: 35, points: 1 },
      { skillId: 45, points: 2 }
    ],
    price: 3200,
    maxDefense: 15,
    maxLowRankDefense: 27
  }),
  deepFreeze<LegArmor>({
    id: 23,
    type: 'legs',
    name: 'Barroth Leggings',
    blade: false,
    gunner: true,
    defense: 8,
    fireRes: 4,
    waterRes: -4,
    iceRes: -3,
    thunderRes: 3,
    dragonRes: 0,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 13, points: 4 },
      { skillId: 25, points: -2 },
      { skillId: 35, points: 1 },
      { skillId: 45, points: 2 }
    ],
    price: 3200,
    maxDefense: 8,
    maxLowRankDefense: 14
  }),
  deepFreeze<LegArmor>({
    id: 24,
    type: 'legs',
    name: 'Gobul Greaves',
    blade: true,
    gunner: false,
    defense: 16,
    fireRes: -2,
    waterRes: 3,
    iceRes: 0,
    thunderRes: -3,
    dragonRes: 2,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 24, points: -1 },
      { skillId: 35, points: 1 },
      { skillId: 46, points: 4 },
      { skillId: 55, points: 2 },
      { skillId: 62, points: 1 }
    ],
    price: 3600,
    maxDefense: 16,
    maxLowRankDefense: 28
  }),
  deepFreeze<LegArmor>({
    id: 25,
    type: 'legs',
    name: 'Gobul Leggings',
    blade: false,
    gunner: true,
    defense: 8,
    fireRes: -2,
    waterRes: 3,
    iceRes: 0,
    thunderRes: -3,
    dragonRes: 2,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 24, points: -1 },
      { skillId: 35, points: 1 },
      { skillId: 46, points: 3 },
      { skillId: 55, points: 3 },
      { skillId: 62, points: 1 }
    ],
    price: 3600,
    maxDefense: 8,
    maxLowRankDefense: 14
  }),
  deepFreeze<LegArmor>({
    id: 26,
    type: 'legs',
    name: "Ranger's Espadrilles",
    blade: true,
    gunner: false,
    defense: 15,
    fireRes: 0,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 1,
    rarity: 3,
    skillPoints: [
      { skillId: 12, points: -3 },
      { skillId: 15, points: 3 },
      { skillId: 38, points: 3 },
      { skillId: 41, points: 1 }
    ],
    price: 10000,
    maxDefense: 15,
    maxLowRankDefense: 27
  }),
  deepFreeze<LegArmor>({
    id: 27,
    type: 'legs',
    name: "Archer's Espadrilles",
    blade: false,
    gunner: true,
    defense: 8,
    fireRes: 0,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 1,
    rarity: 3,
    skillPoints: [
      { skillId: 12, points: -3 },
      { skillId: 15, points: 3 },
      { skillId: 38, points: 3 },
      { skillId: 41, points: 1 }
    ],
    price: 10000,
    maxDefense: 8,
    maxLowRankDefense: 14
  }),
  deepFreeze<LegArmor>({
    id: 28,
    type: 'legs',
    name: 'Guild Bard Boots',
    blade: true,
    gunner: false,
    defense: 15,
    fireRes: 0,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 0,
    rarity: 3,
    skillPoints: [{ skillId: 83, points: 0 }],
    price: 10000,
    maxDefense: 15,
    maxLowRankDefense: 27
  }),
  deepFreeze<LegArmor>({
    id: 29,
    type: 'legs',
    name: 'Guild Bard Gaiters',
    blade: false,
    gunner: true,
    defense: 8,
    fireRes: 0,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 0,
    rarity: 3,
    skillPoints: [{ skillId: 83, points: 0 }],
    price: 10000,
    maxDefense: 8,
    maxLowRankDefense: 14
  }),
  deepFreeze<LegArmor>({
    id: 30,
    type: 'legs',
    name: 'Rathian Greaves',
    blade: true,
    gunner: false,
    defense: 16,
    fireRes: 3,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 2,
    rarity: 2,
    skillPoints: [
      { skillId: 11, points: 2 },
      { skillId: 23, points: 2 },
      { skillId: 37, points: -1 },
      { skillId: 61, points: 2 }
    ],
    price: 3600,
    maxDefense: 16,
    maxLowRankDefense: 28
  }),
  deepFreeze<LegArmor>({
    id: 31,
    type: 'legs',
    name: 'Rathian Leggings',
    blade: false,
    gunner: true,
    defense: 8,
    fireRes: 3,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 2,
    rarity: 2,
    skillPoints: [
      { skillId: 11, points: 2 },
      { skillId: 23, points: 1 },
      { skillId: 37, points: -1 },
      { skillId: 61, points: 3 }
    ],
    price: 3600,
    maxDefense: 8,
    maxLowRankDefense: 14
  }),
  deepFreeze<LegArmor>({
    id: 32,
    type: 'legs',
    name: 'Gigginox Greaves',
    blade: true,
    gunner: false,
    defense: 18,
    fireRes: -4,
    waterRes: 0,
    iceRes: 2,
    thunderRes: 2,
    dragonRes: -1,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 9, points: 4 },
      { skillId: 22, points: 2 },
      { skillId: 23, points: -1 },
      { skillId: 49, points: 2 }
    ],
    price: 4100,
    maxDefense: 18,
    maxLowRankDefense: 30
  }),
  deepFreeze<LegArmor>({
    id: 33,
    type: 'legs',
    name: 'Gigginox Leggings',
    blade: false,
    gunner: true,
    defense: 9,
    fireRes: -4,
    waterRes: 0,
    iceRes: 2,
    thunderRes: 2,
    dragonRes: -1,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 9, points: 3 },
      { skillId: 22, points: 3 },
      { skillId: 23, points: -1 },
      { skillId: 49, points: 2 }
    ],
    price: 4100,
    maxDefense: 9,
    maxLowRankDefense: 15
  }),
  deepFreeze<LegArmor>({
    id: 34,
    type: 'legs',
    name: 'Ingot Greaves',
    blade: true,
    gunner: false,
    defense: 18,
    fireRes: -2,
    waterRes: -1,
    iceRes: 1,
    thunderRes: 3,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 26, points: -1 },
      { skillId: 28, points: 3 },
      { skillId: 39, points: 2 },
      { skillId: 63, points: 3 }
    ],
    price: 5000,
    maxDefense: 18,
    maxLowRankDefense: 28
  }),
  deepFreeze<LegArmor>({
    id: 35,
    type: 'legs',
    name: 'Ingot Leggings',
    blade: false,
    gunner: true,
    defense: 9,
    fireRes: -2,
    waterRes: -1,
    iceRes: 1,
    thunderRes: 3,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 3, points: 2 },
      { skillId: 28, points: 3 },
      { skillId: 29, points: -1 },
      { skillId: 63, points: 3 }
    ],
    price: 5000,
    maxDefense: 9,
    maxLowRankDefense: 14
  }),
  deepFreeze<LegArmor>({
    id: 36,
    type: 'legs',
    name: 'Lagiacrus Greaves',
    blade: true,
    gunner: false,
    defense: 20,
    fireRes: -3,
    waterRes: 2,
    iceRes: -1,
    thunderRes: 4,
    dragonRes: -2,
    slots: 2,
    rarity: 3,
    skillPoints: [
      { skillId: 0, points: 2 },
      { skillId: 9, points: -2 },
      { skillId: 10, points: 3 },
      { skillId: 50, points: 1 }
    ],
    price: 5600,
    maxDefense: 20,
    maxLowRankDefense: 30
  }),
  deepFreeze<LegArmor>({
    id: 37,
    type: 'legs',
    name: 'Lagiacrus Leggings',
    blade: false,
    gunner: true,
    defense: 10,
    fireRes: -3,
    waterRes: 2,
    iceRes: -1,
    thunderRes: 4,
    dragonRes: -2,
    slots: 2,
    rarity: 3,
    skillPoints: [
      { skillId: 4, points: 2 },
      { skillId: 9, points: -2 },
      { skillId: 10, points: 3 },
      { skillId: 50, points: 1 }
    ],
    price: 5600,
    maxDefense: 10,
    maxLowRankDefense: 15
  }),
  deepFreeze<LegArmor>({
    id: 38,
    type: 'legs',
    name: 'Rathalos Greaves',
    blade: true,
    gunner: false,
    defense: 20,
    fireRes: 3,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 2,
    rarity: 3,
    skillPoints: [
      { skillId: 25, points: 2 },
      { skillId: 35, points: 2 },
      { skillId: 36, points: -1 },
      { skillId: 66, points: 2 }
    ],
    price: 5600,
    maxDefense: 20,
    maxLowRankDefense: 30
  }),
  deepFreeze<LegArmor>({
    id: 39,
    type: 'legs',
    name: 'Rathalos Leggings',
    blade: false,
    gunner: true,
    defense: 10,
    fireRes: 3,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 2,
    rarity: 3,
    skillPoints: [
      { skillId: 25, points: 2 },
      { skillId: 35, points: 2 },
      { skillId: 36, points: -1 },
      { skillId: 66, points: 2 }
    ],
    price: 5600,
    maxDefense: 10,
    maxLowRankDefense: 15
  }),
  deepFreeze<LegArmor>({
    id: 40,
    type: 'legs',
    name: 'Barioth Greaves',
    blade: true,
    gunner: false,
    defense: 20,
    fireRes: -4,
    waterRes: 2,
    iceRes: 4,
    thunderRes: -3,
    dragonRes: 0,
    slots: 2,
    rarity: 3,
    skillPoints: [
      { skillId: 13, points: 1 },
      { skillId: 44, points: 3 },
      { skillId: 66, points: -1 },
      { skillId: 67, points: 2 }
    ],
    price: 5600,
    maxDefense: 20,
    maxLowRankDefense: 30
  }),
  deepFreeze<LegArmor>({
    id: 41,
    type: 'legs',
    name: 'Barioth Leggings',
    blade: false,
    gunner: true,
    defense: 10,
    fireRes: -4,
    waterRes: 2,
    iceRes: 4,
    thunderRes: -3,
    dragonRes: 0,
    slots: 2,
    rarity: 3,
    skillPoints: [
      { skillId: 13, points: 1 },
      { skillId: 44, points: 2 },
      { skillId: 66, points: -2 },
      { skillId: 67, points: 2 }
    ],
    price: 5600,
    maxDefense: 10,
    maxLowRankDefense: 15
  }),
  deepFreeze<LegArmor>({
    id: 42,
    type: 'legs',
    name: 'Uragaan Greaves',
    blade: true,
    gunner: false,
    defense: 22,
    fireRes: 3,
    waterRes: -4,
    iceRes: -1,
    thunderRes: 1,
    dragonRes: -2,
    slots: 0,
    rarity: 3,
    skillPoints: [{ skillId: 83, points: 0 }],
    price: 6300,
    maxDefense: 22,
    maxLowRankDefense: 30
  }),
  deepFreeze<LegArmor>({
    id: 43,
    type: 'legs',
    name: 'Uragaan Leggings',
    blade: false,
    gunner: true,
    defense: 11,
    fireRes: 3,
    waterRes: -4,
    iceRes: -1,
    thunderRes: 1,
    dragonRes: -2,
    slots: 0,
    rarity: 3,
    skillPoints: [{ skillId: 83, points: 0 }],
    price: 6300,
    maxDefense: 11,
    maxLowRankDefense: 15
  }),
  deepFreeze<LegArmor>({
    id: 44,
    type: 'legs',
    name: 'Agnaktor Greaves',
    blade: true,
    gunner: false,
    defense: 22,
    fireRes: 4,
    waterRes: -4,
    iceRes: -2,
    thunderRes: 1,
    dragonRes: 0,
    slots: 0,
    rarity: 3,
    skillPoints: [
      { skillId: 13, points: -2 },
      { skillId: 27, points: 5 },
      { skillId: 28, points: 2 },
      { skillId: 52, points: 2 }
    ],
    price: 7200,
    maxDefense: 22,
    maxLowRankDefense: 30
  }),
  deepFreeze<LegArmor>({
    id: 45,
    type: 'legs',
    name: 'Agnaktor Leggings',
    blade: false,
    gunner: true,
    defense: 11,
    fireRes: 4,
    waterRes: -4,
    iceRes: -2,
    thunderRes: 1,
    dragonRes: 0,
    slots: 0,
    rarity: 3,
    skillPoints: [
      { skillId: 13, points: -2 },
      { skillId: 28, points: 2 },
      { skillId: 29, points: 4 },
      { skillId: 52, points: 3 }
    ],
    price: 7200,
    maxDefense: 11,
    maxLowRankDefense: 15
  }),
  deepFreeze<LegArmor>({
    id: 46,
    type: 'legs',
    name: 'Helios Greaves',
    blade: true,
    gunner: false,
    defense: 24,
    fireRes: 0,
    waterRes: 4,
    iceRes: 3,
    thunderRes: -3,
    dragonRes: -4,
    slots: 0,
    rarity: 3,
    skillPoints: [
      { skillId: 0, points: -1 },
      { skillId: 1, points: 5 },
      { skillId: 11, points: 3 },
      { skillId: 37, points: -2 }
    ],
    price: 11000,
    maxDefense: 24,
    maxLowRankDefense: 32
  }),
  deepFreeze<LegArmor>({
    id: 47,
    type: 'legs',
    name: 'Helios Leggings',
    blade: false,
    gunner: true,
    defense: 12,
    fireRes: 0,
    waterRes: 4,
    iceRes: 3,
    thunderRes: -3,
    dragonRes: -4,
    slots: 0,
    rarity: 3,
    skillPoints: [
      { skillId: 3, points: -1 },
      { skillId: 11, points: 3 },
      { skillId: 14, points: 5 },
      { skillId: 37, points: -2 }
    ],
    price: 11000,
    maxDefense: 12,
    maxLowRankDefense: 16
  }),
  deepFreeze<LegArmor>({
    id: 48,
    type: 'legs',
    name: 'Yamato Gusoku',
    blade: true,
    gunner: false,
    defense: 24,
    fireRes: 3,
    waterRes: 0,
    iceRes: -3,
    thunderRes: 0,
    dragonRes: -3,
    slots: 1,
    rarity: 3,
    skillPoints: [
      { skillId: 0, points: 3 },
      { skillId: 18, points: 3 },
      { skillId: 24, points: 2 },
      { skillId: 71, points: -1 }
    ],
    price: 12000,
    maxDefense: 24,
    maxLowRankDefense: 32
  }),
  deepFreeze<LegArmor>({
    id: 49,
    type: 'legs',
    name: 'Mutsu Gusoku',
    blade: false,
    gunner: true,
    defense: 12,
    fireRes: 3,
    waterRes: 0,
    iceRes: -3,
    thunderRes: 0,
    dragonRes: -3,
    slots: 1,
    rarity: 3,
    skillPoints: [
      { skillId: 3, points: 3 },
      { skillId: 24, points: 3 },
      { skillId: 32, points: 2 },
      { skillId: 71, points: -1 }
    ],
    price: 12000,
    maxDefense: 12,
    maxLowRankDefense: 16
  }),
  deepFreeze<LegArmor>({
    id: 50,
    type: 'legs',
    name: 'Leather Greaves+',
    blade: true,
    gunner: false,
    defense: 26,
    fireRes: -2,
    waterRes: 0,
    iceRes: -2,
    thunderRes: 3,
    dragonRes: 2,
    slots: 2,
    rarity: 4,
    skillPoints: [
      { skillId: 40, points: 3 },
      { skillId: 41, points: 3 },
      { skillId: 69, points: 2 }
    ],
    price: 4600,
    maxDefense: 26
  }),
  deepFreeze<LegArmor>({
    id: 51,
    type: 'legs',
    name: 'Leather Leggings+',
    blade: false,
    gunner: true,
    defense: 15,
    fireRes: -2,
    waterRes: 0,
    iceRes: -2,
    thunderRes: 3,
    dragonRes: 2,
    slots: 2,
    rarity: 4,
    skillPoints: [
      { skillId: 40, points: 3 },
      { skillId: 41, points: 3 },
      { skillId: 69, points: 2 }
    ],
    price: 4600,
    maxDefense: 15
  }),
  deepFreeze<LegArmor>({
    id: 52,
    type: 'legs',
    name: 'Piscine Leggings+',
    blade: true,
    gunner: false,
    defense: 26,
    fireRes: -3,
    waterRes: 5,
    iceRes: 2,
    thunderRes: -4,
    dragonRes: 0,
    slots: 1,
    rarity: 4,
    skillPoints: [
      { skillId: 50, points: 10 },
      { skillId: 79, points: 1 }
    ],
    price: 4700,
    maxDefense: 26
  }),
  deepFreeze<LegArmor>({
    id: 53,
    type: 'legs',
    name: 'Piscine Pants+',
    blade: false,
    gunner: true,
    defense: 15,
    fireRes: -3,
    waterRes: 5,
    iceRes: 2,
    thunderRes: -4,
    dragonRes: 0,
    slots: 1,
    rarity: 4,
    skillPoints: [
      { skillId: 50, points: 10 },
      { skillId: 79, points: 1 }
    ],
    price: 4700,
    maxDefense: 15
  }),
  deepFreeze<LegArmor>({
    id: 54,
    type: 'legs',
    name: 'Chainmail Greaves+',
    blade: true,
    gunner: false,
    defense: 30,
    fireRes: -1,
    waterRes: -2,
    iceRes: 4,
    thunderRes: -1,
    dragonRes: 1,
    slots: 2,
    rarity: 4,
    skillPoints: [
      { skillId: 23, points: 3 },
      { skillId: 71, points: 4 },
      { skillId: 72, points: 1 }
    ],
    price: 5400,
    maxDefense: 30
  }),
  deepFreeze<LegArmor>({
    id: 55,
    type: 'legs',
    name: 'Chainmail Leggings+',
    blade: false,
    gunner: true,
    defense: 18,
    fireRes: -1,
    waterRes: -2,
    iceRes: 4,
    thunderRes: -1,
    dragonRes: 1,
    slots: 2,
    rarity: 4,
    skillPoints: [
      { skillId: 23, points: 2 },
      { skillId: 71, points: 4 },
      { skillId: 72, points: 2 }
    ],
    price: 5400,
    maxDefense: 18
  }),
  deepFreeze<LegArmor>({
    id: 56,
    type: 'legs',
    name: 'Loc Lac Boots+',
    blade: true,
    gunner: false,
    defense: 30,
    fireRes: 5,
    waterRes: -4,
    iceRes: -5,
    thunderRes: 2,
    dragonRes: 0,
    slots: 1,
    rarity: 4,
    skillPoints: [
      { skillId: 24, points: 2 },
      { skillId: 60, points: 5 },
      { skillId: 66, points: 4 }
    ],
    price: 5400,
    maxDefense: 30
  }),
  deepFreeze<LegArmor>({
    id: 57,
    type: 'legs',
    name: 'Loc Lac Gaiters+',
    blade: false,
    gunner: true,
    defense: 18,
    fireRes: 5,
    waterRes: -4,
    iceRes: -5,
    thunderRes: 2,
    dragonRes: 0,
    slots: 1,
    rarity: 4,
    skillPoints: [
      { skillId: 24, points: 2 },
      { skillId: 60, points: 5 },
      { skillId: 66, points: 4 }
    ],
    price: 5400,
    maxDefense: 18
  }),
  deepFreeze<LegArmor>({
    id: 58,
    type: 'legs',
    name: "Hunter's Greaves+",
    blade: true,
    gunner: false,
    defense: 30,
    fireRes: 0,
    waterRes: -2,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 2,
    rarity: 4,
    skillPoints: [
      { skillId: 42, points: 1 },
      { skillId: 44, points: 2 },
      { skillId: 62, points: -1 },
      { skillId: 68, points: 5 }
    ],
    price: 5400,
    maxDefense: 30
  }),
  deepFreeze<LegArmor>({
    id: 59,
    type: 'legs',
    name: "Hunter's Leggings+",
    blade: false,
    gunner: true,
    defense: 18,
    fireRes: 0,
    waterRes: -2,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 2,
    rarity: 4,
    skillPoints: [
      { skillId: 42, points: 1 },
      { skillId: 44, points: 3 },
      { skillId: 62, points: -2 },
      { skillId: 68, points: 3 }
    ],
    price: 5400,
    maxDefense: 18
  }),
  deepFreeze<LegArmor>({
    id: 60,
    type: 'legs',
    name: 'Bone Greaves+',
    blade: true,
    gunner: false,
    defense: 34,
    fireRes: 3,
    waterRes: -2,
    iceRes: -1,
    thunderRes: 2,
    dragonRes: 3,
    slots: 2,
    rarity: 4,
    skillPoints: [
      { skillId: 13, points: 3 },
      { skillId: 34, points: 2 },
      { skillId: 54, points: -1 },
      { skillId: 77, points: 3 }
    ],
    price: 6400,
    maxDefense: 34
  }),
  deepFreeze<LegArmor>({
    id: 61,
    type: 'legs',
    name: 'Bone Leggings+',
    blade: false,
    gunner: true,
    defense: 20,
    fireRes: 3,
    waterRes: -2,
    iceRes: -1,
    thunderRes: 2,
    dragonRes: 3,
    slots: 2,
    rarity: 4,
    skillPoints: [
      { skillId: 13, points: 3 },
      { skillId: 34, points: 2 },
      { skillId: 54, points: -2 },
      { skillId: 77, points: 2 }
    ],
    price: 6400,
    maxDefense: 20
  }),
  deepFreeze<LegArmor>({
    id: 62,
    type: 'legs',
    name: 'Alloy Greaves+',
    blade: true,
    gunner: false,
    defense: 34,
    fireRes: 1,
    waterRes: 2,
    iceRes: -1,
    thunderRes: -2,
    dragonRes: -1,
    slots: 0,
    rarity: 4,
    skillPoints: [{ skillId: 83, points: 0 }],
    price: 7100,
    maxDefense: 34
  }),
  deepFreeze<LegArmor>({
    id: 63,
    type: 'legs',
    name: 'Alloy Leggings+',
    blade: false,
    gunner: true,
    defense: 20,
    fireRes: 1,
    waterRes: 2,
    iceRes: -1,
    thunderRes: -2,
    dragonRes: -1,
    slots: 0,
    rarity: 4,
    skillPoints: [{ skillId: 83, points: 0 }],
    price: 7100,
    maxDefense: 20
  }),
  deepFreeze<LegArmor>({
    id: 64,
    type: 'legs',
    name: 'Jaggi Greaves+',
    blade: true,
    gunner: false,
    defense: 38,
    fireRes: -3,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: 2,
    slots: 2,
    rarity: 5,
    skillPoints: [
      { skillId: 25, points: 2 },
      { skillId: 35, points: 2 },
      { skillId: 55, points: 3 },
      { skillId: 58, points: 1 },
      { skillId: 67, points: -1 }
    ],
    price: 8000,
    maxDefense: 38
  }),
  deepFreeze<LegArmor>({
    id: 65,
    type: 'legs',
    name: 'Jaggi Leggings+',
    blade: false,
    gunner: true,
    defense: 22,
    fireRes: -3,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: 2,
    slots: 2,
    rarity: 5,
    skillPoints: [
      { skillId: 25, points: 2 },
      { skillId: 35, points: 2 },
      { skillId: 55, points: 2 },
      { skillId: 58, points: 2 },
      { skillId: 67, points: -1 }
    ],
    price: 8000,
    maxDefense: 22
  }),
  deepFreeze<LegArmor>({
    id: 66,
    type: 'legs',
    name: 'Bnahabra Greaves+',
    blade: true,
    gunner: false,
    defense: 38,
    fireRes: -5,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 2,
    dragonRes: 6,
    slots: 1,
    rarity: 5,
    skillPoints: [
      { skillId: 0, points: 6 },
      { skillId: 9, points: 2 },
      { skillId: 22, points: -3 }
    ],
    price: 10500,
    maxDefense: 38
  }),
  deepFreeze<LegArmor>({
    id: 67,
    type: 'legs',
    name: 'Bnahabra Leggings+',
    blade: false,
    gunner: true,
    defense: 22,
    fireRes: -5,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 2,
    dragonRes: 6,
    slots: 1,
    rarity: 5,
    skillPoints: [
      { skillId: 9, points: 2 },
      { skillId: 22, points: -3 },
      { skillId: 29, points: 6 }
    ],
    price: 10500,
    maxDefense: 22
  }),
  deepFreeze<LegArmor>({
    id: 68,
    type: 'legs',
    name: 'Rhenoplos Greaves+',
    blade: true,
    gunner: false,
    defense: 38,
    fireRes: 3,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -2,
    dragonRes: 2,
    slots: 2,
    rarity: 5,
    skillPoints: [
      { skillId: 39, points: 1 },
      { skillId: 46, points: 2 },
      { skillId: 56, points: 5 },
      { skillId: 63, points: -1 }
    ],
    price: 8500,
    maxDefense: 38
  }),
  deepFreeze<LegArmor>({
    id: 69,
    type: 'legs',
    name: 'Rhenoplos Leggings+',
    blade: false,
    gunner: true,
    defense: 22,
    fireRes: 3,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -2,
    dragonRes: 2,
    slots: 2,
    rarity: 5,
    skillPoints: [
      { skillId: 3, points: 3 },
      { skillId: 31, points: 3 },
      { skillId: 46, points: 2 },
      { skillId: 63, points: -1 }
    ],
    price: 8500,
    maxDefense: 22
  }),
  deepFreeze<LegArmor>({
    id: 70,
    type: 'legs',
    name: 'Qurupeco Greaves+',
    blade: true,
    gunner: false,
    defense: 42,
    fireRes: 4,
    waterRes: -3,
    iceRes: -4,
    thunderRes: 0,
    dragonRes: 1,
    slots: 3,
    rarity: 5,
    skillPoints: [
      { skillId: 36, points: 1 },
      { skillId: 38, points: 2 },
      { skillId: 43, points: 1 },
      { skillId: 64, points: -3 }
    ],
    price: 10000,
    maxDefense: 42
  }),
  deepFreeze<LegArmor>({
    id: 71,
    type: 'legs',
    name: 'Qurupeco Leggings+',
    blade: false,
    gunner: true,
    defense: 25,
    fireRes: 4,
    waterRes: -3,
    iceRes: -4,
    thunderRes: 0,
    dragonRes: 1,
    slots: 3,
    rarity: 5,
    skillPoints: [
      { skillId: 36, points: 2 },
      { skillId: 38, points: 1 },
      { skillId: 43, points: 1 },
      { skillId: 64, points: -3 }
    ],
    price: 10000,
    maxDefense: 25
  }),
  deepFreeze<LegArmor>({
    id: 72,
    type: 'legs',
    name: 'Ludroth Greaves+',
    blade: true,
    gunner: false,
    defense: 44,
    fireRes: -4,
    waterRes: 4,
    iceRes: 0,
    thunderRes: -1,
    dragonRes: 1,
    slots: 2,
    rarity: 5,
    skillPoints: [
      { skillId: 34, points: -1 },
      { skillId: 37, points: 2 },
      { skillId: 49, points: 3 },
      { skillId: 79, points: 3 }
    ],
    price: 11800,
    maxDefense: 44
  }),
  deepFreeze<LegArmor>({
    id: 73,
    type: 'legs',
    name: 'Ludroth Leggings+',
    blade: false,
    gunner: true,
    defense: 26,
    fireRes: -4,
    waterRes: 4,
    iceRes: 0,
    thunderRes: -1,
    dragonRes: 1,
    slots: 2,
    rarity: 5,
    skillPoints: [
      { skillId: 30, points: 3 },
      { skillId: 34, points: -1 },
      { skillId: 37, points: 3 },
      { skillId: 49, points: 2 }
    ],
    price: 11800,
    maxDefense: 26
  }),
  deepFreeze<LegArmor>({
    id: 74,
    type: 'legs',
    name: 'Baggi Greaves+',
    blade: true,
    gunner: false,
    defense: 44,
    fireRes: -4,
    waterRes: -1,
    iceRes: 4,
    thunderRes: -1,
    dragonRes: 1,
    slots: 0,
    rarity: 5,
    skillPoints: [
      { skillId: 17, points: 3 },
      { skillId: 18, points: 2 },
      { skillId: 55, points: -1 },
      { skillId: 64, points: 7 }
    ],
    price: 12300,
    maxDefense: 44
  }),
  deepFreeze<LegArmor>({
    id: 75,
    type: 'legs',
    name: 'Baggi Leggings+',
    blade: false,
    gunner: true,
    defense: 26,
    fireRes: -4,
    waterRes: -1,
    iceRes: 4,
    thunderRes: -1,
    dragonRes: 1,
    slots: 0,
    rarity: 5,
    skillPoints: [
      { skillId: 6, points: 2 },
      { skillId: 17, points: 3 },
      { skillId: 55, points: -2 },
      { skillId: 64, points: 6 }
    ],
    price: 12300,
    maxDefense: 26
  }),
  deepFreeze<LegArmor>({
    id: 76,
    type: 'legs',
    name: 'Barroth Greaves+',
    blade: true,
    gunner: false,
    defense: 48,
    fireRes: 5,
    waterRes: -5,
    iceRes: -4,
    thunderRes: 4,
    dragonRes: 0,
    slots: 1,
    rarity: 5,
    skillPoints: [
      { skillId: 13, points: 4 },
      { skillId: 25, points: -2 },
      { skillId: 35, points: 1 },
      { skillId: 45, points: 4 }
    ],
    price: 13800,
    maxDefense: 48
  }),
  deepFreeze<LegArmor>({
    id: 77,
    type: 'legs',
    name: 'Barroth Leggings+',
    blade: false,
    gunner: true,
    defense: 28,
    fireRes: 5,
    waterRes: -5,
    iceRes: -4,
    thunderRes: 4,
    dragonRes: 0,
    slots: 1,
    rarity: 5,
    skillPoints: [
      { skillId: 13, points: 4 },
      { skillId: 25, points: -2 },
      { skillId: 35, points: 1 },
      { skillId: 45, points: 4 }
    ],
    price: 13800,
    maxDefense: 28
  }),
  deepFreeze<LegArmor>({
    id: 78,
    type: 'legs',
    name: 'Gobul Greaves+',
    blade: true,
    gunner: false,
    defense: 50,
    fireRes: -2,
    waterRes: 4,
    iceRes: 0,
    thunderRes: -4,
    dragonRes: 2,
    slots: 3,
    rarity: 5,
    skillPoints: [
      { skillId: 24, points: -2 },
      { skillId: 25, points: 2 },
      { skillId: 46, points: 1 },
      { skillId: 55, points: 2 }
    ],
    price: 14800,
    maxDefense: 50
  }),
  deepFreeze<LegArmor>({
    id: 79,
    type: 'legs',
    name: 'Gobul Leggings+',
    blade: false,
    gunner: true,
    defense: 30,
    fireRes: -2,
    waterRes: 4,
    iceRes: 0,
    thunderRes: -4,
    dragonRes: 2,
    slots: 3,
    rarity: 5,
    skillPoints: [
      { skillId: 24, points: -3 },
      { skillId: 25, points: 2 },
      { skillId: 46, points: 1 },
      { skillId: 55, points: 1 }
    ],
    price: 14800,
    maxDefense: 30
  }),
  deepFreeze<LegArmor>({
    id: 80,
    type: 'legs',
    name: 'Guild Bard Boots+',
    blade: true,
    gunner: false,
    defense: 36,
    fireRes: 0,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 0,
    rarity: 6,
    skillPoints: [{ skillId: 83, points: 0 }],
    price: 25000,
    maxDefense: 36
  }),
  deepFreeze<LegArmor>({
    id: 81,
    type: 'legs',
    name: 'Guild Bard Gaiters+',
    blade: false,
    gunner: true,
    defense: 22,
    fireRes: 0,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 0,
    rarity: 6,
    skillPoints: [{ skillId: 83, points: 0 }],
    price: 25000,
    maxDefense: 22
  }),
  deepFreeze<LegArmor>({
    id: 82,
    type: 'legs',
    name: 'Rathian Greaves+',
    blade: true,
    gunner: false,
    defense: 50,
    fireRes: 4,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 1,
    rarity: 5,
    skillPoints: [
      { skillId: 11, points: 2 },
      { skillId: 23, points: 3 },
      { skillId: 37, points: -3 },
      { skillId: 61, points: 3 }
    ],
    price: 14800,
    maxDefense: 50
  }),
  deepFreeze<LegArmor>({
    id: 83,
    type: 'legs',
    name: 'Rathian Leggings+',
    blade: false,
    gunner: true,
    defense: 30,
    fireRes: 4,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 1,
    rarity: 5,
    skillPoints: [
      { skillId: 11, points: 2 },
      { skillId: 23, points: 2 },
      { skillId: 37, points: -3 },
      { skillId: 61, points: 4 }
    ],
    price: 14800,
    maxDefense: 30
  }),
  deepFreeze<LegArmor>({
    id: 84,
    type: 'legs',
    name: 'Gigginox Greaves+',
    blade: true,
    gunner: false,
    defense: 54,
    fireRes: -4,
    waterRes: -1,
    iceRes: 2,
    thunderRes: 3,
    dragonRes: 0,
    slots: 3,
    rarity: 5,
    skillPoints: [
      { skillId: 9, points: 2 },
      { skillId: 22, points: 1 },
      { skillId: 23, points: -2 },
      { skillId: 49, points: 2 }
    ],
    price: 15800,
    maxDefense: 54
  }),
  deepFreeze<LegArmor>({
    id: 85,
    type: 'legs',
    name: 'Gigginox Leggings+',
    blade: false,
    gunner: true,
    defense: 32,
    fireRes: -4,
    waterRes: -1,
    iceRes: 2,
    thunderRes: 3,
    dragonRes: 0,
    slots: 3,
    rarity: 5,
    skillPoints: [
      { skillId: 9, points: 2 },
      { skillId: 22, points: 1 },
      { skillId: 23, points: -3 },
      { skillId: 49, points: 1 }
    ],
    price: 15800,
    maxDefense: 32
  }),
  deepFreeze<LegArmor>({
    id: 86,
    type: 'legs',
    name: 'Ingot Greaves+',
    blade: true,
    gunner: false,
    defense: 54,
    fireRes: -2,
    waterRes: -1,
    iceRes: 1,
    thunderRes: 3,
    dragonRes: 2,
    slots: 1,
    rarity: 5,
    skillPoints: [
      { skillId: 26, points: -1 },
      { skillId: 28, points: 2 },
      { skillId: 39, points: 5 },
      { skillId: 63, points: 3 }
    ],
    price: 17500,
    maxDefense: 54
  }),
  deepFreeze<LegArmor>({
    id: 87,
    type: 'legs',
    name: 'Ingot Leggings+',
    blade: false,
    gunner: true,
    defense: 32,
    fireRes: -2,
    waterRes: -1,
    iceRes: 1,
    thunderRes: 3,
    dragonRes: 2,
    slots: 1,
    rarity: 5,
    skillPoints: [
      { skillId: 3, points: 5 },
      { skillId: 28, points: 2 },
      { skillId: 29, points: -1 },
      { skillId: 63, points: 3 }
    ],
    price: 17500,
    maxDefense: 32
  }),
  deepFreeze<LegArmor>({
    id: 88,
    type: 'legs',
    name: 'Dober Greaves',
    blade: true,
    gunner: false,
    defense: 58,
    fireRes: -2,
    waterRes: -2,
    iceRes: 1,
    thunderRes: 1,
    dragonRes: 5,
    slots: 3,
    rarity: 6,
    skillPoints: [
      { skillId: 13, points: 1 },
      { skillId: 45, points: -3 },
      { skillId: 48, points: 1 },
      { skillId: 65, points: 2 }
    ],
    price: 19000,
    maxDefense: 58
  }),
  deepFreeze<LegArmor>({
    id: 89,
    type: 'legs',
    name: 'Dober Leggings',
    blade: false,
    gunner: true,
    defense: 34,
    fireRes: -2,
    waterRes: -2,
    iceRes: 1,
    thunderRes: 1,
    dragonRes: 5,
    slots: 3,
    rarity: 6,
    skillPoints: [
      { skillId: 6, points: 1 },
      { skillId: 30, points: 2 },
      { skillId: 45, points: -3 },
      { skillId: 65, points: 1 }
    ],
    price: 19000,
    maxDefense: 34
  }),
  deepFreeze<LegArmor>({
    id: 90,
    type: 'legs',
    name: 'Lagiacrus Greaves+',
    blade: true,
    gunner: false,
    defense: 58,
    fireRes: -4,
    waterRes: 2,
    iceRes: -1,
    thunderRes: 5,
    dragonRes: -2,
    slots: 1,
    rarity: 6,
    skillPoints: [
      { skillId: 9, points: -2 },
      { skillId: 10, points: 3 },
      { skillId: 20, points: 4 },
      { skillId: 50, points: 2 }
    ],
    price: 18000,
    maxDefense: 58
  }),
  deepFreeze<LegArmor>({
    id: 91,
    type: 'legs',
    name: 'Lagiacrus Leggings+',
    blade: false,
    gunner: true,
    defense: 34,
    fireRes: -4,
    waterRes: 2,
    iceRes: -1,
    thunderRes: 5,
    dragonRes: -2,
    slots: 1,
    rarity: 6,
    skillPoints: [
      { skillId: 9, points: -2 },
      { skillId: 10, points: 3 },
      { skillId: 21, points: 3 },
      { skillId: 50, points: 3 }
    ],
    price: 18000,
    maxDefense: 34
  }),
  deepFreeze<LegArmor>({
    id: 92,
    type: 'legs',
    name: 'Rathalos Greaves+',
    blade: true,
    gunner: false,
    defense: 58,
    fireRes: 4,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 0,
    rarity: 6,
    skillPoints: [
      { skillId: 2, points: 3 },
      { skillId: 25, points: 3 },
      { skillId: 36, points: -2 },
      { skillId: 66, points: 5 }
    ],
    price: 18000,
    maxDefense: 58
  }),
  deepFreeze<LegArmor>({
    id: 93,
    type: 'legs',
    name: 'Rathalos Leggings+',
    blade: false,
    gunner: true,
    defense: 34,
    fireRes: 4,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 0,
    rarity: 6,
    skillPoints: [
      { skillId: 4, points: 2 },
      { skillId: 25, points: 3 },
      { skillId: 36, points: -2 },
      { skillId: 66, points: 6 }
    ],
    price: 18000,
    maxDefense: 34
  }),
  deepFreeze<LegArmor>({
    id: 94,
    type: 'legs',
    name: 'Barioth Greaves+',
    blade: true,
    gunner: false,
    defense: 58,
    fireRes: -4,
    waterRes: 2,
    iceRes: 5,
    thunderRes: -3,
    dragonRes: 0,
    slots: 0,
    rarity: 6,
    skillPoints: [
      { skillId: 16, points: 4 },
      { skillId: 44, points: 3 },
      { skillId: 66, points: -2 },
      { skillId: 67, points: 4 }
    ],
    price: 18000,
    maxDefense: 58
  }),
  deepFreeze<LegArmor>({
    id: 95,
    type: 'legs',
    name: 'Barioth Leggings+',
    blade: false,
    gunner: true,
    defense: 34,
    fireRes: -4,
    waterRes: 2,
    iceRes: 5,
    thunderRes: -3,
    dragonRes: 0,
    slots: 0,
    rarity: 6,
    skillPoints: [
      { skillId: 16, points: 4 },
      { skillId: 44, points: 3 },
      { skillId: 66, points: -2 },
      { skillId: 67, points: 4 }
    ],
    price: 18000,
    maxDefense: 34
  }),
  deepFreeze<LegArmor>({
    id: 96,
    type: 'legs',
    name: 'Uragaan Greaves+',
    blade: true,
    gunner: false,
    defense: 62,
    fireRes: 4,
    waterRes: -4,
    iceRes: -1,
    thunderRes: 1,
    dragonRes: -2,
    slots: 3,
    rarity: 6,
    skillPoints: [
      { skillId: 19, points: 2 },
      { skillId: 33, points: 1 },
      { skillId: 36, points: 1 },
      { skillId: 46, points: -3 }
    ],
    price: 18800,
    maxDefense: 62
  }),
  deepFreeze<LegArmor>({
    id: 97,
    type: 'legs',
    name: 'Uragaan Leggings+',
    blade: false,
    gunner: true,
    defense: 37,
    fireRes: 4,
    waterRes: -4,
    iceRes: -1,
    thunderRes: 1,
    dragonRes: -2,
    slots: 3,
    rarity: 6,
    skillPoints: [
      { skillId: 3, points: 1 },
      { skillId: 33, points: 1 },
      { skillId: 36, points: 2 },
      { skillId: 46, points: -3 }
    ],
    price: 18800,
    maxDefense: 37
  }),
  deepFreeze<LegArmor>({
    id: 98,
    type: 'legs',
    name: 'Agnaktor Greaves+',
    blade: true,
    gunner: false,
    defense: 62,
    fireRes: 5,
    waterRes: -4,
    iceRes: -2,
    thunderRes: 1,
    dragonRes: 0,
    slots: 2,
    rarity: 6,
    skillPoints: [
      { skillId: 0, points: 2 },
      { skillId: 13, points: -1 },
      { skillId: 27, points: 2 },
      { skillId: 52, points: 4 }
    ],
    price: 19800,
    maxDefense: 62
  }),
  deepFreeze<LegArmor>({
    id: 99,
    type: 'legs',
    name: 'Agnaktor Leggings+',
    blade: false,
    gunner: true,
    defense: 37,
    fireRes: 5,
    waterRes: -4,
    iceRes: -2,
    thunderRes: 1,
    dragonRes: 0,
    slots: 2,
    rarity: 6,
    skillPoints: [
      { skillId: 4, points: 2 },
      { skillId: 7, points: 1 },
      { skillId: 13, points: -2 },
      { skillId: 52, points: 4 }
    ],
    price: 19800,
    maxDefense: 37
  }),
  deepFreeze<LegArmor>({
    id: 100,
    type: 'legs',
    name: 'Vangis Greaves',
    blade: true,
    gunner: false,
    defense: 64,
    fireRes: 0,
    waterRes: 0,
    iceRes: 3,
    thunderRes: -4,
    dragonRes: -4,
    slots: 3,
    rarity: 7,
    skillPoints: [
      { skillId: 1, points: 2 },
      { skillId: 34, points: -3 },
      { skillId: 35, points: 1 },
      { skillId: 42, points: 1 }
    ],
    price: 41500,
    maxDefense: 64
  }),
  deepFreeze<LegArmor>({
    id: 101,
    type: 'legs',
    name: 'Vangis Leggings',
    blade: false,
    gunner: true,
    defense: 38,
    fireRes: 0,
    waterRes: 0,
    iceRes: 3,
    thunderRes: -4,
    dragonRes: -4,
    slots: 3,
    rarity: 7,
    skillPoints: [
      { skillId: 14, points: 2 },
      { skillId: 34, points: -3 },
      { skillId: 35, points: 1 },
      { skillId: 42, points: 1 }
    ],
    price: 41500,
    maxDefense: 38
  }),
  deepFreeze<LegArmor>({
    id: 102,
    type: 'legs',
    name: 'Damascus Greaves',
    blade: true,
    gunner: false,
    defense: 62,
    fireRes: -2,
    waterRes: 0,
    iceRes: 2,
    thunderRes: -2,
    dragonRes: 3,
    slots: 1,
    rarity: 6,
    skillPoints: [
      { skillId: 13, points: -1 },
      { skillId: 19, points: 2 },
      { skillId: 23, points: 5 },
      { skillId: 28, points: 3 }
    ],
    price: 32300,
    maxDefense: 62
  }),
  deepFreeze<LegArmor>({
    id: 103,
    type: 'legs',
    name: 'Damascus Leggings',
    blade: false,
    gunner: true,
    defense: 37,
    fireRes: -2,
    waterRes: 0,
    iceRes: 2,
    thunderRes: -2,
    dragonRes: 3,
    slots: 0,
    rarity: 6,
    skillPoints: [
      { skillId: 13, points: -1 },
      { skillId: 23, points: 6 },
      { skillId: 28, points: 2 },
      { skillId: 29, points: 4 }
    ],
    price: 32300,
    maxDefense: 37
  }),
  deepFreeze<LegArmor>({
    id: 104,
    type: 'legs',
    name: 'Helios Greaves+',
    blade: true,
    gunner: false,
    defense: 66,
    fireRes: 0,
    waterRes: 5,
    iceRes: 3,
    thunderRes: -3,
    dragonRes: -4,
    slots: 0,
    rarity: 6,
    skillPoints: [
      { skillId: 0, points: -3 },
      { skillId: 1, points: 4 },
      { skillId: 11, points: 4 },
      { skillId: 37, points: -2 }
    ],
    price: 26200,
    maxDefense: 66
  }),
  deepFreeze<LegArmor>({
    id: 105,
    type: 'legs',
    name: 'Helios Leggings+',
    blade: false,
    gunner: true,
    defense: 39,
    fireRes: 0,
    waterRes: 5,
    iceRes: 3,
    thunderRes: -3,
    dragonRes: -4,
    slots: 0,
    rarity: 6,
    skillPoints: [
      { skillId: 3, points: -3 },
      { skillId: 11, points: 4 },
      { skillId: 14, points: 4 },
      { skillId: 37, points: -2 }
    ],
    price: 26200,
    maxDefense: 39
  }),
  deepFreeze<LegArmor>({
    id: 106,
    type: 'legs',
    name: 'Yamato Gusoku+',
    blade: true,
    gunner: false,
    defense: 66,
    fireRes: 4,
    waterRes: 0,
    iceRes: -3,
    thunderRes: 0,
    dragonRes: -4,
    slots: 0,
    rarity: 6,
    skillPoints: [
      { skillId: 0, points: 2 },
      { skillId: 18, points: 3 },
      { skillId: 24, points: 5 },
      { skillId: 71, points: -3 }
    ],
    price: 27500,
    maxDefense: 66
  }),
  deepFreeze<LegArmor>({
    id: 107,
    type: 'legs',
    name: 'Mutsu Gusoku+',
    blade: false,
    gunner: true,
    defense: 39,
    fireRes: 4,
    waterRes: 0,
    iceRes: -3,
    thunderRes: 0,
    dragonRes: -4,
    slots: 0,
    rarity: 6,
    skillPoints: [
      { skillId: 3, points: 3 },
      { skillId: 24, points: 4 },
      { skillId: 32, points: 4 },
      { skillId: 71, points: -2 }
    ],
    price: 27500,
    maxDefense: 39
  }),
  deepFreeze<LegArmor>({
    id: 108,
    type: 'legs',
    name: 'Escadora Scale',
    blade: true,
    gunner: false,
    defense: 70,
    fireRes: -1,
    waterRes: -1,
    iceRes: -1,
    thunderRes: 0,
    dragonRes: -5,
    slots: 0,
    rarity: 7,
    skillPoints: [
      { skillId: 16, points: 4 },
      { skillId: 20, points: 5 },
      { skillId: 43, points: -2 },
      { skillId: 81, points: 2 }
    ],
    price: 66666,
    maxDefense: 70
  }),
  deepFreeze<LegArmor>({
    id: 109,
    type: 'legs',
    name: 'Escadora Scala',
    blade: false,
    gunner: true,
    defense: 42,
    fireRes: -1,
    waterRes: -1,
    iceRes: -1,
    thunderRes: 0,
    dragonRes: -5,
    slots: 1,
    rarity: 7,
    skillPoints: [
      { skillId: 16, points: 4 },
      { skillId: 21, points: 3 },
      { skillId: 43, points: -2 },
      { skillId: 81, points: 2 }
    ],
    price: 66666,
    maxDefense: 42
  }),
  deepFreeze<LegArmor>({
    id: 110,
    type: 'legs',
    name: 'Chakra Anklet',
    blade: true,
    gunner: true,
    defense: 18,
    fireRes: 0,
    waterRes: -10,
    iceRes: 0,
    thunderRes: 10,
    dragonRes: 0,
    slots: 3,
    rarity: 7,
    skillPoints: [],
    price: 33333,
    maxDefense: 18
  }),
  deepFreeze<LegArmor>({
    id: 111,
    type: 'legs',
    name: 'Black Leather Pants',
    blade: true,
    gunner: true,
    defense: 28,
    fireRes: 2,
    waterRes: 2,
    iceRes: 2,
    thunderRes: 2,
    dragonRes: 2,
    slots: 0,
    rarity: 6,
    skillPoints: [{ skillId: 45, points: 13 }],
    price: 15000,
    maxDefense: 28
  })
];
