import { deepFreeze } from '../../utils';
import { WaistArmor } from './types';

export const WaistArmors: WaistArmor[] = [
  deepFreeze<WaistArmor>({
    id: 0,
    type: 'waist',
    name: 'Leather Belt',
    blade: true,
    gunner: true,
    defense: 1,
    fireRes: -1,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 3,
    dragonRes: 2,
    slots: 1,
    rarity: 1,
    skillPoints: [
      { skillId: 35, points: 1 },
      { skillId: 40, points: 4 },
      { skillId: 41, points: 2 },
      { skillId: 69, points: 1 }
    ],
    price: 150,
    maxDefense: 1,
    maxLowRankDefense: 9
  }),
  deepFreeze<WaistArmor>({
    id: 1,
    type: 'waist',
    name: 'Piscine Belt',
    blade: true,
    gunner: true,
    defense: 3,
    fireRes: -2,
    waterRes: 4,
    iceRes: 2,
    thunderRes: -3,
    dragonRes: 0,
    slots: 0,
    rarity: 1,
    skillPoints: [
      { skillId: 50, points: 2 },
      { skillId: 79, points: 9 }
    ],
    price: 300,
    maxDefense: 3,
    maxLowRankDefense: 11
  }),
  deepFreeze<WaistArmor>({
    id: 2,
    type: 'waist',
    name: 'Chainmail Belt',
    blade: true,
    gunner: true,
    defense: 2,
    fireRes: -1,
    waterRes: -1,
    iceRes: 3,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 1,
    skillPoints: [
      { skillId: 23, points: 1 },
      { skillId: 70, points: 2 },
      { skillId: 71, points: 2 },
      { skillId: 72, points: 4 }
    ],
    price: 200,
    maxDefense: 2,
    maxLowRankDefense: 9
  }),
  deepFreeze<WaistArmor>({
    id: 3,
    type: 'waist',
    name: 'Loc Lac Kilt',
    blade: true,
    gunner: true,
    defense: 4,
    fireRes: 4,
    waterRes: -3,
    iceRes: -4,
    thunderRes: 2,
    dragonRes: 0,
    slots: 0,
    rarity: 1,
    skillPoints: [
      { skillId: 24, points: 5 },
      { skillId: 60, points: 3 },
      { skillId: 66, points: 3 }
    ],
    price: 500,
    maxDefense: 4,
    maxLowRankDefense: 11
  }),
  deepFreeze<WaistArmor>({
    id: 4,
    type: 'waist',
    name: "Hunter's Faulds",
    blade: true,
    gunner: false,
    defense: 6,
    fireRes: -1,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: -1,
    slots: 1,
    rarity: 1,
    skillPoints: [
      { skillId: 35, points: 1 },
      { skillId: 42, points: 1 },
      { skillId: 62, points: -1 },
      { skillId: 68, points: 2 },
      { skillId: 75, points: 4 }
    ],
    price: 500,
    maxDefense: 6,
    maxLowRankDefense: 20
  }),
  deepFreeze<WaistArmor>({
    id: 5,
    type: 'waist',
    name: "Hunter's Coat",
    blade: false,
    gunner: true,
    defense: 3,
    fireRes: -1,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: -1,
    slots: 1,
    rarity: 1,
    skillPoints: [
      { skillId: 35, points: 1 },
      { skillId: 42, points: 1 },
      { skillId: 62, points: -1 },
      { skillId: 68, points: 3 },
      { skillId: 75, points: 3 }
    ],
    price: 500,
    maxDefense: 3,
    maxLowRankDefense: 10
  }),
  deepFreeze<WaistArmor>({
    id: 6,
    type: 'waist',
    name: 'Bone Faulds',
    blade: true,
    gunner: false,
    defense: 8,
    fireRes: 2,
    waterRes: -2,
    iceRes: -1,
    thunderRes: 2,
    dragonRes: 3,
    slots: 1,
    rarity: 1,
    skillPoints: [
      { skillId: 34, points: 2 },
      { skillId: 54, points: -1 },
      { skillId: 73, points: 4 },
      { skillId: 77, points: 2 }
    ],
    price: 750,
    maxDefense: 8,
    maxLowRankDefense: 22
  }),
  deepFreeze<WaistArmor>({
    id: 7,
    type: 'waist',
    name: 'Bone Coat',
    blade: false,
    gunner: true,
    defense: 4,
    fireRes: 2,
    waterRes: -2,
    iceRes: -1,
    thunderRes: 2,
    dragonRes: 3,
    slots: 1,
    rarity: 1,
    skillPoints: [
      { skillId: 34, points: 2 },
      { skillId: 54, points: -1 },
      { skillId: 73, points: 3 },
      { skillId: 77, points: 3 }
    ],
    price: 750,
    maxDefense: 4,
    maxLowRankDefense: 11
  }),
  deepFreeze<WaistArmor>({
    id: 8,
    type: 'waist',
    name: 'Alloy Coil',
    blade: true,
    gunner: false,
    defense: 8,
    fireRes: 1,
    waterRes: 1,
    iceRes: -1,
    thunderRes: -2,
    dragonRes: -1,
    slots: 1,
    rarity: 1,
    skillPoints: [
      { skillId: 25, points: 3 },
      { skillId: 26, points: 1 },
      { skillId: 76, points: 3 },
      { skillId: 78, points: -2 }
    ],
    price: 1000,
    maxDefense: 8,
    maxLowRankDefense: 22
  }),
  deepFreeze<WaistArmor>({
    id: 9,
    type: 'waist',
    name: 'Alloy Coat',
    blade: false,
    gunner: true,
    defense: 4,
    fireRes: 1,
    waterRes: 1,
    iceRes: -1,
    thunderRes: -2,
    dragonRes: -1,
    slots: 1,
    rarity: 1,
    skillPoints: [
      { skillId: 7, points: 1 },
      { skillId: 25, points: 3 },
      { skillId: 76, points: 3 },
      { skillId: 78, points: -2 }
    ],
    price: 1000,
    maxDefense: 4,
    maxLowRankDefense: 11
  }),
  deepFreeze<WaistArmor>({
    id: 10,
    type: 'waist',
    name: 'Jaggi Faulds',
    blade: true,
    gunner: false,
    defense: 10,
    fireRes: -3,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 35, points: 1 },
      { skillId: 55, points: 3 },
      { skillId: 58, points: 4 },
      { skillId: 67, points: -1 }
    ],
    price: 1200,
    maxDefense: 10,
    maxLowRankDefense: 24
  }),
  deepFreeze<WaistArmor>({
    id: 11,
    type: 'waist',
    name: 'Jaggi Coat',
    blade: false,
    gunner: true,
    defense: 5,
    fireRes: -3,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 35, points: 1 },
      { skillId: 55, points: 3 },
      { skillId: 58, points: 4 },
      { skillId: 67, points: -1 }
    ],
    price: 1200,
    maxDefense: 5,
    maxLowRankDefense: 12
  }),
  deepFreeze<WaistArmor>({
    id: 12,
    type: 'waist',
    name: 'Bnahabra Coil',
    blade: true,
    gunner: false,
    defense: 10,
    fireRes: -4,
    waterRes: -1,
    iceRes: -1,
    thunderRes: 2,
    dragonRes: 5,
    slots: 0,
    rarity: 2,
    skillPoints: [
      { skillId: 0, points: 3 },
      { skillId: 9, points: 3 },
      { skillId: 22, points: -5 }
    ],
    price: 1800,
    maxDefense: 10,
    maxLowRankDefense: 24
  }),
  deepFreeze<WaistArmor>({
    id: 13,
    type: 'waist',
    name: 'Bnahabra Coat',
    blade: false,
    gunner: true,
    defense: 5,
    fireRes: -4,
    waterRes: -1,
    iceRes: -1,
    thunderRes: 2,
    dragonRes: 5,
    slots: 0,
    rarity: 2,
    skillPoints: [
      { skillId: 9, points: 3 },
      { skillId: 22, points: -5 },
      { skillId: 29, points: 3 }
    ],
    price: 1800,
    maxDefense: 5,
    maxLowRankDefense: 12
  }),
  deepFreeze<WaistArmor>({
    id: 14,
    type: 'waist',
    name: 'Rhenoplos Coil',
    blade: true,
    gunner: false,
    defense: 12,
    fireRes: 2,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: 2,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 35, points: 1 },
      { skillId: 39, points: 2 },
      { skillId: 46, points: 4 },
      { skillId: 56, points: 1 },
      { skillId: 63, points: -1 }
    ],
    price: 1400,
    maxDefense: 12,
    maxLowRankDefense: 24
  }),
  deepFreeze<WaistArmor>({
    id: 15,
    type: 'waist',
    name: 'Rhenoplos Coat',
    blade: false,
    gunner: true,
    defense: 6,
    fireRes: 2,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: 2,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 3, points: 3 },
      { skillId: 31, points: 1 },
      { skillId: 35, points: 1 },
      { skillId: 46, points: 3 },
      { skillId: 63, points: -1 }
    ],
    price: 1400,
    maxDefense: 6,
    maxLowRankDefense: 12
  }),
  deepFreeze<WaistArmor>({
    id: 16,
    type: 'waist',
    name: 'Qurupeco Coil',
    blade: true,
    gunner: false,
    defense: 12,
    fireRes: 2,
    waterRes: -2,
    iceRes: -3,
    thunderRes: 0,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 35, points: 2 },
      { skillId: 36, points: 1 },
      { skillId: 43, points: 2 },
      { skillId: 44, points: 2 },
      { skillId: 64, points: -2 }
    ],
    price: 1700,
    maxDefense: 12,
    maxLowRankDefense: 24
  }),
  deepFreeze<WaistArmor>({
    id: 17,
    type: 'waist',
    name: 'Qurupeco Coat',
    blade: false,
    gunner: true,
    defense: 6,
    fireRes: 2,
    waterRes: -2,
    iceRes: -3,
    thunderRes: 0,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 35, points: 2 },
      { skillId: 36, points: 2 },
      { skillId: 43, points: 1 },
      { skillId: 44, points: 1 },
      { skillId: 64, points: -3 }
    ],
    price: 1700,
    maxDefense: 6,
    maxLowRankDefense: 12
  }),
  deepFreeze<WaistArmor>({
    id: 18,
    type: 'waist',
    name: 'Ludroth Faulds',
    blade: true,
    gunner: false,
    defense: 13,
    fireRes: -3,
    waterRes: 2,
    iceRes: 0,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 37, points: 1 },
      { skillId: 49, points: 3 },
      { skillId: 61, points: -1 },
      { skillId: 79, points: 4 }
    ],
    price: 2200,
    maxDefense: 13,
    maxLowRankDefense: 25
  }),
  deepFreeze<WaistArmor>({
    id: 19,
    type: 'waist',
    name: 'Ludroth Coat',
    blade: false,
    gunner: true,
    defense: 7,
    fireRes: -3,
    waterRes: 2,
    iceRes: 0,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 30, points: 3 },
      { skillId: 37, points: 3 },
      { skillId: 49, points: 1 },
      { skillId: 61, points: -2 }
    ],
    price: 2200,
    maxDefense: 7,
    maxLowRankDefense: 13
  }),
  deepFreeze<WaistArmor>({
    id: 20,
    type: 'waist',
    name: 'Steel Faulds',
    blade: true,
    gunner: false,
    defense: 12,
    fireRes: -1,
    waterRes: 1,
    iceRes: 1,
    thunderRes: -1,
    dragonRes: 0,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 26, points: 3 },
      { skillId: 27, points: 3 },
      { skillId: 50, points: -3 }
    ],
    price: 2000,
    maxDefense: 12,
    maxLowRankDefense: 24
  }),
  deepFreeze<WaistArmor>({
    id: 21,
    type: 'waist',
    name: 'Baggi Coil',
    blade: true,
    gunner: false,
    defense: 13,
    fireRes: -3,
    waterRes: -1,
    iceRes: 3,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 17, points: 3 },
      { skillId: 18, points: 2 },
      { skillId: 55, points: -1 },
      { skillId: 64, points: 3 }
    ],
    price: 2400,
    maxDefense: 13,
    maxLowRankDefense: 25
  }),
  deepFreeze<WaistArmor>({
    id: 22,
    type: 'waist',
    name: 'Baggi Coat',
    blade: false,
    gunner: true,
    defense: 7,
    fireRes: -3,
    waterRes: -1,
    iceRes: 3,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 6, points: 2 },
      { skillId: 17, points: 4 },
      { skillId: 55, points: -1 },
      { skillId: 64, points: 2 }
    ],
    price: 2400,
    maxDefense: 7,
    maxLowRankDefense: 13
  }),
  deepFreeze<WaistArmor>({
    id: 23,
    type: 'waist',
    name: 'Barroth Faulds',
    blade: true,
    gunner: false,
    defense: 15,
    fireRes: 4,
    waterRes: -4,
    iceRes: -3,
    thunderRes: 3,
    dragonRes: 0,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 13, points: 3 },
      { skillId: 25, points: -2 },
      { skillId: 35, points: 1 },
      { skillId: 45, points: 3 }
    ],
    price: 3200,
    maxDefense: 15,
    maxLowRankDefense: 27
  }),
  deepFreeze<WaistArmor>({
    id: 24,
    type: 'waist',
    name: 'Barroth Coat',
    blade: false,
    gunner: true,
    defense: 8,
    fireRes: 4,
    waterRes: -4,
    iceRes: -3,
    thunderRes: 3,
    dragonRes: 0,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 13, points: 3 },
      { skillId: 25, points: -2 },
      { skillId: 35, points: 1 },
      { skillId: 45, points: 3 }
    ],
    price: 3200,
    maxDefense: 8,
    maxLowRankDefense: 14
  }),
  deepFreeze<WaistArmor>({
    id: 25,
    type: 'waist',
    name: 'Gobul Faulds',
    blade: true,
    gunner: false,
    defense: 16,
    fireRes: -2,
    waterRes: 3,
    iceRes: 0,
    thunderRes: -3,
    dragonRes: 2,
    slots: 0,
    rarity: 2,
    skillPoints: [
      { skillId: 24, points: -1 },
      { skillId: 46, points: 4 },
      { skillId: 55, points: 4 },
      { skillId: 62, points: 2 }
    ],
    price: 3600,
    maxDefense: 16,
    maxLowRankDefense: 28
  }),
  deepFreeze<WaistArmor>({
    id: 26,
    type: 'waist',
    name: 'Gobul Coat',
    blade: false,
    gunner: true,
    defense: 8,
    fireRes: -2,
    waterRes: 3,
    iceRes: 0,
    thunderRes: -3,
    dragonRes: 2,
    slots: 0,
    rarity: 2,
    skillPoints: [
      { skillId: 24, points: -1 },
      { skillId: 46, points: 4 },
      { skillId: 55, points: 4 },
      { skillId: 62, points: 2 }
    ],
    price: 3600,
    maxDefense: 8,
    maxLowRankDefense: 14
  }),
  deepFreeze<WaistArmor>({
    id: 27,
    type: 'waist',
    name: "Ranger's Faulds",
    blade: true,
    gunner: false,
    defense: 15,
    fireRes: 0,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 0,
    rarity: 3,
    skillPoints: [
      { skillId: 12, points: -2 },
      { skillId: 15, points: 4 },
      { skillId: 38, points: 4 },
      { skillId: 41, points: 2 }
    ],
    price: 10000,
    maxDefense: 15,
    maxLowRankDefense: 27
  }),
  deepFreeze<WaistArmor>({
    id: 28,
    type: 'waist',
    name: "Archer's Bandolier",
    blade: false,
    gunner: true,
    defense: 8,
    fireRes: 0,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 0,
    rarity: 3,
    skillPoints: [
      { skillId: 12, points: -3 },
      { skillId: 15, points: 3 },
      { skillId: 38, points: 4 },
      { skillId: 41, points: 2 }
    ],
    price: 10000,
    maxDefense: 8,
    maxLowRankDefense: 14
  }),
  deepFreeze<WaistArmor>({
    id: 29,
    type: 'waist',
    name: 'Guild Bard Coil',
    blade: true,
    gunner: false,
    defense: 15,
    fireRes: 0,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 0,
    rarity: 3,
    skillPoints: [
      { skillId: 12, points: 4 },
      { skillId: 42, points: 4 },
      { skillId: 44, points: 2 },
      { skillId: 57, points: -1 }
    ],
    price: 10000,
    maxDefense: 15,
    maxLowRankDefense: 27
  }),
  deepFreeze<WaistArmor>({
    id: 30,
    type: 'waist',
    name: 'Guild Bard Coat',
    blade: false,
    gunner: true,
    defense: 8,
    fireRes: 0,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 0,
    rarity: 3,
    skillPoints: [
      { skillId: 12, points: 2 },
      { skillId: 42, points: 4 },
      { skillId: 44, points: 3 },
      { skillId: 57, points: -2 }
    ],
    price: 10000,
    maxDefense: 8,
    maxLowRankDefense: 14
  }),
  deepFreeze<WaistArmor>({
    id: 31,
    type: 'waist',
    name: 'Rathian Faulds',
    blade: true,
    gunner: false,
    defense: 16,
    fireRes: 3,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 11, points: 3 },
      { skillId: 23, points: 2 },
      { skillId: 37, points: -2 },
      { skillId: 61, points: 2 }
    ],
    price: 3600,
    maxDefense: 16,
    maxLowRankDefense: 28
  }),
  deepFreeze<WaistArmor>({
    id: 32,
    type: 'waist',
    name: 'Rathian Coat',
    blade: false,
    gunner: true,
    defense: 8,
    fireRes: 3,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 11, points: 3 },
      { skillId: 23, points: 3 },
      { skillId: 37, points: -1 },
      { skillId: 61, points: 2 }
    ],
    price: 3600,
    maxDefense: 8,
    maxLowRankDefense: 14
  }),
  deepFreeze<WaistArmor>({
    id: 33,
    type: 'waist',
    name: 'Gigginox Faulds',
    blade: true,
    gunner: false,
    defense: 18,
    fireRes: -4,
    waterRes: 0,
    iceRes: 2,
    thunderRes: 2,
    dragonRes: -1,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 9, points: 2 },
      { skillId: 22, points: 3 },
      { skillId: 23, points: -1 },
      { skillId: 49, points: 3 }
    ],
    price: 4100,
    maxDefense: 18,
    maxLowRankDefense: 30
  }),
  deepFreeze<WaistArmor>({
    id: 34,
    type: 'waist',
    name: 'Gigginox Coat',
    blade: false,
    gunner: true,
    defense: 9,
    fireRes: -4,
    waterRes: 0,
    iceRes: 2,
    thunderRes: 2,
    dragonRes: -1,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 9, points: 2 },
      { skillId: 22, points: 1 },
      { skillId: 23, points: -2 },
      { skillId: 49, points: 4 }
    ],
    price: 4100,
    maxDefense: 9,
    maxLowRankDefense: 15
  }),
  deepFreeze<WaistArmor>({
    id: 35,
    type: 'waist',
    name: 'Ingot Coil',
    blade: true,
    gunner: false,
    defense: 18,
    fireRes: -2,
    waterRes: -1,
    iceRes: 1,
    thunderRes: 3,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 26, points: -2 },
      { skillId: 28, points: 3 },
      { skillId: 39, points: 1 },
      { skillId: 63, points: 3 }
    ],
    price: 5000,
    maxDefense: 18,
    maxLowRankDefense: 28
  }),
  deepFreeze<WaistArmor>({
    id: 36,
    type: 'waist',
    name: 'Ingot Coat',
    blade: false,
    gunner: true,
    defense: 9,
    fireRes: -2,
    waterRes: -1,
    iceRes: 1,
    thunderRes: 3,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    skillPoints: [
      { skillId: 3, points: 1 },
      { skillId: 28, points: 3 },
      { skillId: 29, points: -2 },
      { skillId: 63, points: 3 }
    ],
    price: 5000,
    maxDefense: 9,
    maxLowRankDefense: 14
  }),
  deepFreeze<WaistArmor>({
    id: 37,
    type: 'waist',
    name: 'Lagiacrus Faulds',
    blade: true,
    gunner: false,
    defense: 20,
    fireRes: -3,
    waterRes: 2,
    iceRes: -1,
    thunderRes: 4,
    dragonRes: -2,
    slots: 2,
    rarity: 3,
    skillPoints: [
      { skillId: 0, points: 2 },
      { skillId: 9, points: -2 },
      { skillId: 10, points: 1 },
      { skillId: 50, points: 3 }
    ],
    price: 5600,
    maxDefense: 20,
    maxLowRankDefense: 30
  }),
  deepFreeze<WaistArmor>({
    id: 38,
    type: 'waist',
    name: 'Lagiacrus Coat',
    blade: false,
    gunner: true,
    defense: 10,
    fireRes: -3,
    waterRes: 2,
    iceRes: -1,
    thunderRes: 4,
    dragonRes: -2,
    slots: 2,
    rarity: 3,
    skillPoints: [
      { skillId: 4, points: 2 },
      { skillId: 9, points: -2 },
      { skillId: 10, points: 1 },
      { skillId: 50, points: 3 }
    ],
    price: 5600,
    maxDefense: 10,
    maxLowRankDefense: 15
  }),
  deepFreeze<WaistArmor>({
    id: 39,
    type: 'waist',
    name: 'Rathalos Faulds',
    blade: true,
    gunner: false,
    defense: 20,
    fireRes: 3,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 0,
    rarity: 3,
    skillPoints: [
      { skillId: 25, points: 3 },
      { skillId: 35, points: 5 },
      { skillId: 36, points: -2 },
      { skillId: 66, points: 1 }
    ],
    price: 5600,
    maxDefense: 20,
    maxLowRankDefense: 30
  }),
  deepFreeze<WaistArmor>({
    id: 40,
    type: 'waist',
    name: 'Rathalos Coat',
    blade: false,
    gunner: true,
    defense: 10,
    fireRes: 3,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 0,
    rarity: 3,
    skillPoints: [
      { skillId: 25, points: 3 },
      { skillId: 35, points: 4 },
      { skillId: 36, points: -2 },
      { skillId: 66, points: 2 }
    ],
    price: 5600,
    maxDefense: 10,
    maxLowRankDefense: 15
  }),
  deepFreeze<WaistArmor>({
    id: 41,
    type: 'waist',
    name: 'Barioth Faulds',
    blade: true,
    gunner: false,
    defense: 20,
    fireRes: -4,
    waterRes: 2,
    iceRes: 4,
    thunderRes: -3,
    dragonRes: 0,
    slots: 0,
    rarity: 3,
    skillPoints: [
      { skillId: 13, points: 4 },
      { skillId: 44, points: 2 },
      { skillId: 66, points: -1 },
      { skillId: 67, points: 4 }
    ],
    price: 5600,
    maxDefense: 20,
    maxLowRankDefense: 30
  }),
  deepFreeze<WaistArmor>({
    id: 42,
    type: 'waist',
    name: 'Barioth Coat',
    blade: false,
    gunner: true,
    defense: 10,
    fireRes: -4,
    waterRes: 2,
    iceRes: 4,
    thunderRes: -3,
    dragonRes: 0,
    slots: 0,
    rarity: 3,
    skillPoints: [
      { skillId: 13, points: 3 },
      { skillId: 44, points: 5 },
      { skillId: 66, points: -2 },
      { skillId: 67, points: 1 }
    ],
    price: 5600,
    maxDefense: 10,
    maxLowRankDefense: 15
  }),
  deepFreeze<WaistArmor>({
    id: 43,
    type: 'waist',
    name: 'Uragaan Faulds',
    blade: true,
    gunner: false,
    defense: 22,
    fireRes: 3,
    waterRes: -4,
    iceRes: -1,
    thunderRes: 1,
    dragonRes: -2,
    slots: 1,
    rarity: 3,
    skillPoints: [
      { skillId: 19, points: 2 },
      { skillId: 33, points: 2 },
      { skillId: 36, points: 3 },
      { skillId: 46, points: -2 }
    ],
    price: 6300,
    maxDefense: 22,
    maxLowRankDefense: 30
  }),
  deepFreeze<WaistArmor>({
    id: 44,
    type: 'waist',
    name: 'Uragaan Coat',
    blade: false,
    gunner: true,
    defense: 11,
    fireRes: 3,
    waterRes: -4,
    iceRes: -1,
    thunderRes: 1,
    dragonRes: -2,
    slots: 1,
    rarity: 3,
    skillPoints: [
      { skillId: 3, points: 2 },
      { skillId: 33, points: 2 },
      { skillId: 36, points: 2 },
      { skillId: 46, points: -3 }
    ],
    price: 6300,
    maxDefense: 11,
    maxLowRankDefense: 15
  }),
  deepFreeze<WaistArmor>({
    id: 45,
    type: 'waist',
    name: 'Agnaktor Faulds',
    blade: true,
    gunner: false,
    defense: 22,
    fireRes: 4,
    waterRes: -4,
    iceRes: -2,
    thunderRes: 1,
    dragonRes: 0,
    slots: 2,
    rarity: 3,
    skillPoints: [
      { skillId: 13, points: -2 },
      { skillId: 27, points: 2 },
      { skillId: 28, points: 2 },
      { skillId: 52, points: 1 }
    ],
    price: 7200,
    maxDefense: 22,
    maxLowRankDefense: 30
  }),
  deepFreeze<WaistArmor>({
    id: 46,
    type: 'waist',
    name: 'Agnaktor Coat',
    blade: false,
    gunner: true,
    defense: 11,
    fireRes: 4,
    waterRes: -4,
    iceRes: -2,
    thunderRes: 1,
    dragonRes: 0,
    slots: 2,
    rarity: 3,
    skillPoints: [
      { skillId: 13, points: -2 },
      { skillId: 28, points: 2 },
      { skillId: 29, points: 2 },
      { skillId: 52, points: 1 }
    ],
    price: 7200,
    maxDefense: 11,
    maxLowRankDefense: 15
  }),
  deepFreeze<WaistArmor>({
    id: 47,
    type: 'waist',
    name: 'Helios Coil',
    blade: true,
    gunner: false,
    defense: 24,
    fireRes: 0,
    waterRes: 4,
    iceRes: 3,
    thunderRes: -3,
    dragonRes: -4,
    slots: 0,
    rarity: 3,
    skillPoints: [
      { skillId: 0, points: -2 },
      { skillId: 1, points: 3 },
      { skillId: 11, points: 5 },
      { skillId: 37, points: -1 }
    ],
    price: 11000,
    maxDefense: 24,
    maxLowRankDefense: 32
  }),
  deepFreeze<WaistArmor>({
    id: 48,
    type: 'waist',
    name: 'Helios Coat',
    blade: false,
    gunner: true,
    defense: 12,
    fireRes: 0,
    waterRes: 4,
    iceRes: 3,
    thunderRes: -3,
    dragonRes: -4,
    slots: 0,
    rarity: 3,
    skillPoints: [
      { skillId: 3, points: -2 },
      { skillId: 11, points: 5 },
      { skillId: 14, points: 3 },
      { skillId: 37, points: -1 }
    ],
    price: 11000,
    maxDefense: 12,
    maxLowRankDefense: 16
  }),
  deepFreeze<WaistArmor>({
    id: 49,
    type: 'waist',
    name: 'Yamato Koshiate',
    blade: true,
    gunner: false,
    defense: 24,
    fireRes: 3,
    waterRes: 0,
    iceRes: -3,
    thunderRes: 0,
    dragonRes: -3,
    slots: 1,
    rarity: 3,
    skillPoints: [
      { skillId: 0, points: 4 },
      { skillId: 18, points: 1 },
      { skillId: 24, points: 2 },
      { skillId: 71, points: -2 }
    ],
    price: 12000,
    maxDefense: 24,
    maxLowRankDefense: 32
  }),
  deepFreeze<WaistArmor>({
    id: 50,
    type: 'waist',
    name: 'Mutsu Koshiate',
    blade: false,
    gunner: true,
    defense: 12,
    fireRes: 3,
    waterRes: 0,
    iceRes: -3,
    thunderRes: 0,
    dragonRes: -3,
    slots: 1,
    rarity: 3,
    skillPoints: [
      { skillId: 3, points: 4 },
      { skillId: 24, points: 1 },
      { skillId: 32, points: 1 },
      { skillId: 71, points: -3 }
    ],
    price: 12000,
    maxDefense: 12,
    maxLowRankDefense: 16
  }),
  deepFreeze<WaistArmor>({
    id: 51,
    type: 'waist',
    name: 'Leather Faulds+',
    blade: true,
    gunner: false,
    defense: 26,
    fireRes: -2,
    waterRes: 0,
    iceRes: -2,
    thunderRes: 3,
    dragonRes: 2,
    slots: 2,
    rarity: 4,
    skillPoints: [
      { skillId: 40, points: 3 },
      { skillId: 41, points: 1 },
      { skillId: 69, points: 4 }
    ],
    price: 4600,
    maxDefense: 26
  }),
  deepFreeze<WaistArmor>({
    id: 52,
    type: 'waist',
    name: 'Leather Coat+',
    blade: false,
    gunner: true,
    defense: 15,
    fireRes: -2,
    waterRes: 0,
    iceRes: -2,
    thunderRes: 3,
    dragonRes: 2,
    slots: 2,
    rarity: 4,
    skillPoints: [
      { skillId: 40, points: 2 },
      { skillId: 41, points: 2 },
      { skillId: 69, points: 4 }
    ],
    price: 4600,
    maxDefense: 15
  }),
  deepFreeze<WaistArmor>({
    id: 53,
    type: 'waist',
    name: 'Piscine Belt+',
    blade: true,
    gunner: false,
    defense: 26,
    fireRes: -3,
    waterRes: 5,
    iceRes: 2,
    thunderRes: -4,
    dragonRes: 0,
    slots: 0,
    rarity: 4,
    skillPoints: [{ skillId: 79, points: 13 }],
    price: 4700,
    maxDefense: 26
  }),
  deepFreeze<WaistArmor>({
    id: 54,
    type: 'waist',
    name: 'Piscine Tank+',
    blade: false,
    gunner: true,
    defense: 15,
    fireRes: -3,
    waterRes: 5,
    iceRes: 2,
    thunderRes: -4,
    dragonRes: 0,
    slots: 1,
    rarity: 4,
    skillPoints: [{ skillId: 79, points: 11 }],
    price: 4700,
    maxDefense: 15
  }),
  deepFreeze<WaistArmor>({
    id: 55,
    type: 'waist',
    name: 'Chainmail Faulds+',
    blade: true,
    gunner: false,
    defense: 30,
    fireRes: -1,
    waterRes: -2,
    iceRes: 4,
    thunderRes: -1,
    dragonRes: 1,
    slots: 2,
    rarity: 4,
    skillPoints: [
      { skillId: 23, points: 2 },
      { skillId: 71, points: 2 },
      { skillId: 72, points: 4 }
    ],
    price: 5400,
    maxDefense: 30
  }),
  deepFreeze<WaistArmor>({
    id: 56,
    type: 'waist',
    name: 'Chainmail Coat+',
    blade: false,
    gunner: true,
    defense: 18,
    fireRes: -1,
    waterRes: -2,
    iceRes: 4,
    thunderRes: -1,
    dragonRes: 1,
    slots: 2,
    rarity: 4,
    skillPoints: [
      { skillId: 23, points: 3 },
      { skillId: 71, points: 1 },
      { skillId: 72, points: 4 }
    ],
    price: 5400,
    maxDefense: 18
  }),
  deepFreeze<WaistArmor>({
    id: 57,
    type: 'waist',
    name: 'Loc Lac Kilt+',
    blade: true,
    gunner: false,
    defense: 30,
    fireRes: 5,
    waterRes: -4,
    iceRes: -5,
    thunderRes: 2,
    dragonRes: 0,
    slots: 0,
    rarity: 4,
    skillPoints: [
      { skillId: 24, points: 6 },
      { skillId: 60, points: 2 },
      { skillId: 66, points: 5 }
    ],
    price: 5400,
    maxDefense: 30
  }),
  deepFreeze<WaistArmor>({
    id: 58,
    type: 'waist',
    name: 'Loc Lac Coat+',
    blade: false,
    gunner: true,
    defense: 18,
    fireRes: 5,
    waterRes: -4,
    iceRes: -5,
    thunderRes: 2,
    dragonRes: 0,
    slots: 0,
    rarity: 4,
    skillPoints: [
      { skillId: 24, points: 6 },
      { skillId: 60, points: 2 },
      { skillId: 66, points: 5 }
    ],
    price: 5400,
    maxDefense: 18
  }),
  deepFreeze<WaistArmor>({
    id: 59,
    type: 'waist',
    name: "Hunter's Faulds+",
    blade: true,
    gunner: false,
    defense: 30,
    fireRes: 0,
    waterRes: -2,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 2,
    rarity: 4,
    skillPoints: [
      { skillId: 42, points: 4 },
      { skillId: 44, points: 3 },
      { skillId: 62, points: -1 },
      { skillId: 68, points: 1 }
    ],
    price: 5400,
    maxDefense: 30
  }),
  deepFreeze<WaistArmor>({
    id: 60,
    type: 'waist',
    name: "Hunter's Coat+",
    blade: false,
    gunner: true,
    defense: 18,
    fireRes: 0,
    waterRes: -2,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 2,
    rarity: 4,
    skillPoints: [
      { skillId: 42, points: 4 },
      { skillId: 44, points: 2 },
      { skillId: 62, points: -2 },
      { skillId: 68, points: 1 }
    ],
    price: 5400,
    maxDefense: 18
  }),
  deepFreeze<WaistArmor>({
    id: 61,
    type: 'waist',
    name: 'Bone Faulds+',
    blade: true,
    gunner: false,
    defense: 34,
    fireRes: 3,
    waterRes: -2,
    iceRes: -1,
    thunderRes: 2,
    dragonRes: 3,
    slots: 2,
    rarity: 4,
    skillPoints: [
      { skillId: 13, points: 3 },
      { skillId: 34, points: 4 },
      { skillId: 54, points: -1 },
      { skillId: 77, points: 1 }
    ],
    price: 6400,
    maxDefense: 34
  }),
  deepFreeze<WaistArmor>({
    id: 62,
    type: 'waist',
    name: 'Bone Coat+',
    blade: false,
    gunner: true,
    defense: 20,
    fireRes: 3,
    waterRes: -2,
    iceRes: -1,
    thunderRes: 2,
    dragonRes: 3,
    slots: 2,
    rarity: 4,
    skillPoints: [
      { skillId: 13, points: 1 },
      { skillId: 34, points: 4 },
      { skillId: 54, points: -1 },
      { skillId: 77, points: 3 }
    ],
    price: 6400,
    maxDefense: 20
  }),
  deepFreeze<WaistArmor>({
    id: 63,
    type: 'waist',
    name: 'Alloy Faulds+',
    blade: true,
    gunner: false,
    defense: 34,
    fireRes: 1,
    waterRes: 2,
    iceRes: -1,
    thunderRes: -2,
    dragonRes: -1,
    slots: 2,
    rarity: 4,
    skillPoints: [
      { skillId: 25, points: 2 },
      { skillId: 26, points: 3 },
      { skillId: 76, points: 2 },
      { skillId: 78, points: -2 }
    ],
    price: 7100,
    maxDefense: 34
  }),
  deepFreeze<WaistArmor>({
    id: 64,
    type: 'waist',
    name: 'Alloy Coat+',
    blade: false,
    gunner: true,
    defense: 20,
    fireRes: 1,
    waterRes: 2,
    iceRes: -1,
    thunderRes: -2,
    dragonRes: -1,
    slots: 2,
    rarity: 4,
    skillPoints: [
      { skillId: 7, points: 3 },
      { skillId: 25, points: 2 },
      { skillId: 76, points: 2 },
      { skillId: 78, points: -2 }
    ],
    price: 7100,
    maxDefense: 20
  }),
  deepFreeze<WaistArmor>({
    id: 65,
    type: 'waist',
    name: 'Jaggi Faulds+',
    blade: true,
    gunner: false,
    defense: 38,
    fireRes: -3,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: 2,
    slots: 2,
    rarity: 5,
    skillPoints: [
      { skillId: 35, points: 2 },
      { skillId: 55, points: 3 },
      { skillId: 58, points: 3 },
      { skillId: 67, points: -1 }
    ],
    price: 8000,
    maxDefense: 38
  }),
  deepFreeze<WaistArmor>({
    id: 66,
    type: 'waist',
    name: 'Jaggi Coat+',
    blade: false,
    gunner: true,
    defense: 22,
    fireRes: -3,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: 2,
    slots: 2,
    rarity: 5,
    skillPoints: [
      { skillId: 35, points: 2 },
      { skillId: 55, points: 4 },
      { skillId: 58, points: 1 },
      { skillId: 67, points: -2 }
    ],
    price: 8000,
    maxDefense: 22
  }),
  deepFreeze<WaistArmor>({
    id: 67,
    type: 'waist',
    name: 'Bnahabra Faulds+',
    blade: true,
    gunner: false,
    defense: 38,
    fireRes: -5,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 2,
    dragonRes: 6,
    slots: 1,
    rarity: 5,
    skillPoints: [
      { skillId: 0, points: 3 },
      { skillId: 9, points: 6 },
      { skillId: 22, points: -2 }
    ],
    price: 10500,
    maxDefense: 38
  }),
  deepFreeze<WaistArmor>({
    id: 68,
    type: 'waist',
    name: 'Bnahabra Coat+',
    blade: false,
    gunner: true,
    defense: 22,
    fireRes: -5,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 2,
    dragonRes: 6,
    slots: 1,
    rarity: 5,
    skillPoints: [
      { skillId: 9, points: 5 },
      { skillId: 22, points: -2 },
      { skillId: 29, points: 4 }
    ],
    price: 10500,
    maxDefense: 22
  }),
  deepFreeze<WaistArmor>({
    id: 69,
    type: 'waist',
    name: 'Rhenoplos Coil+',
    blade: true,
    gunner: false,
    defense: 38,
    fireRes: 3,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -2,
    dragonRes: 2,
    slots: 2,
    rarity: 5,
    skillPoints: [
      { skillId: 39, points: 6 },
      { skillId: 46, points: 1 },
      { skillId: 56, points: 1 },
      { skillId: 63, points: -1 }
    ],
    price: 8500,
    maxDefense: 38
  }),
  deepFreeze<WaistArmor>({
    id: 70,
    type: 'waist',
    name: 'Rhenoplos Coat+',
    blade: false,
    gunner: true,
    defense: 22,
    fireRes: 3,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -2,
    dragonRes: 2,
    slots: 2,
    rarity: 5,
    skillPoints: [
      { skillId: 3, points: 5 },
      { skillId: 31, points: 2 },
      { skillId: 46, points: 1 },
      { skillId: 63, points: -1 }
    ],
    price: 8500,
    maxDefense: 22
  }),
  deepFreeze<WaistArmor>({
    id: 71,
    type: 'waist',
    name: 'Qurupeco Coil+',
    blade: true,
    gunner: false,
    defense: 42,
    fireRes: 4,
    waterRes: -3,
    iceRes: -4,
    thunderRes: 0,
    dragonRes: 1,
    slots: 1,
    rarity: 5,
    skillPoints: [
      { skillId: 25, points: 1 },
      { skillId: 36, points: 2 },
      { skillId: 38, points: 5 },
      { skillId: 43, points: 2 },
      { skillId: 64, points: -1 }
    ],
    price: 10000,
    maxDefense: 42
  }),
  deepFreeze<WaistArmor>({
    id: 72,
    type: 'waist',
    name: 'Qurupeco Coat+',
    blade: false,
    gunner: true,
    defense: 25,
    fireRes: 4,
    waterRes: -3,
    iceRes: -4,
    thunderRes: 0,
    dragonRes: 1,
    slots: 1,
    rarity: 5,
    skillPoints: [
      { skillId: 25, points: 1 },
      { skillId: 36, points: 2 },
      { skillId: 38, points: 4 },
      { skillId: 43, points: 3 },
      { skillId: 64, points: -1 }
    ],
    price: 10000,
    maxDefense: 25
  }),
  deepFreeze<WaistArmor>({
    id: 73,
    type: 'waist',
    name: 'Ludroth Faulds+',
    blade: true,
    gunner: false,
    defense: 44,
    fireRes: -4,
    waterRes: 4,
    iceRes: 0,
    thunderRes: -1,
    dragonRes: 1,
    slots: 3,
    rarity: 5,
    skillPoints: [
      { skillId: 34, points: -3 },
      { skillId: 37, points: 1 },
      { skillId: 49, points: 2 },
      { skillId: 79, points: 1 }
    ],
    price: 11800,
    maxDefense: 44
  }),
  deepFreeze<WaistArmor>({
    id: 74,
    type: 'waist',
    name: 'Ludroth Coat+',
    blade: false,
    gunner: true,
    defense: 26,
    fireRes: -4,
    waterRes: 4,
    iceRes: 0,
    thunderRes: -1,
    dragonRes: 1,
    slots: 3,
    rarity: 5,
    skillPoints: [
      { skillId: 30, points: 1 },
      { skillId: 34, points: -3 },
      { skillId: 37, points: 1 },
      { skillId: 49, points: 2 }
    ],
    price: 11800,
    maxDefense: 26
  }),
  deepFreeze<WaistArmor>({
    id: 75,
    type: 'waist',
    name: 'Steel Coil+',
    blade: true,
    gunner: false,
    defense: 42,
    fireRes: -1,
    waterRes: 1,
    iceRes: 1,
    thunderRes: -1,
    dragonRes: 0,
    slots: 1,
    rarity: 5,
    skillPoints: [
      { skillId: 26, points: 4 },
      { skillId: 27, points: 4 },
      { skillId: 50, points: -3 }
    ],
    price: 11000,
    maxDefense: 42
  }),
  deepFreeze<WaistArmor>({
    id: 76,
    type: 'waist',
    name: 'Baggi Coil+',
    blade: true,
    gunner: false,
    defense: 44,
    fireRes: -4,
    waterRes: -1,
    iceRes: 4,
    thunderRes: -1,
    dragonRes: 1,
    slots: 2,
    rarity: 5,
    skillPoints: [
      { skillId: 17, points: 2 },
      { skillId: 18, points: 1 },
      { skillId: 25, points: 1 },
      { skillId: 55, points: -1 },
      { skillId: 64, points: 4 }
    ],
    price: 12300,
    maxDefense: 44
  }),
  deepFreeze<WaistArmor>({
    id: 77,
    type: 'waist',
    name: 'Baggi Coat+',
    blade: false,
    gunner: true,
    defense: 26,
    fireRes: -4,
    waterRes: -1,
    iceRes: 4,
    thunderRes: -1,
    dragonRes: 1,
    slots: 2,
    rarity: 5,
    skillPoints: [
      { skillId: 6, points: 2 },
      { skillId: 17, points: 1 },
      { skillId: 25, points: 1 },
      { skillId: 55, points: -1 },
      { skillId: 64, points: 4 }
    ],
    price: 12300,
    maxDefense: 26
  }),
  deepFreeze<WaistArmor>({
    id: 78,
    type: 'waist',
    name: 'Barroth Faulds+',
    blade: true,
    gunner: false,
    defense: 48,
    fireRes: 5,
    waterRes: -5,
    iceRes: -4,
    thunderRes: 4,
    dragonRes: 0,
    slots: 1,
    rarity: 5,
    skillPoints: [
      { skillId: 13, points: 3 },
      { skillId: 25, points: -1 },
      { skillId: 35, points: 2 },
      { skillId: 45, points: 5 }
    ],
    price: 13800,
    maxDefense: 48
  }),
  deepFreeze<WaistArmor>({
    id: 79,
    type: 'waist',
    name: 'Barroth Coat+',
    blade: false,
    gunner: true,
    defense: 28,
    fireRes: 5,
    waterRes: -5,
    iceRes: -4,
    thunderRes: 4,
    dragonRes: 0,
    slots: 1,
    rarity: 5,
    skillPoints: [
      { skillId: 13, points: 3 },
      { skillId: 25, points: -2 },
      { skillId: 35, points: 2 },
      { skillId: 45, points: 4 }
    ],
    price: 13800,
    maxDefense: 28
  }),
  deepFreeze<WaistArmor>({
    id: 80,
    type: 'waist',
    name: 'Gobul Faulds+',
    blade: true,
    gunner: false,
    defense: 50,
    fireRes: -2,
    waterRes: 4,
    iceRes: 0,
    thunderRes: -4,
    dragonRes: 2,
    slots: 1,
    rarity: 5,
    skillPoints: [
      { skillId: 24, points: -1 },
      { skillId: 25, points: 1 },
      { skillId: 46, points: 5 },
      { skillId: 55, points: 4 }
    ],
    price: 14800,
    maxDefense: 50
  }),
  deepFreeze<WaistArmor>({
    id: 81,
    type: 'waist',
    name: 'Gobul Coat+',
    blade: false,
    gunner: true,
    defense: 30,
    fireRes: -2,
    waterRes: 4,
    iceRes: 0,
    thunderRes: -4,
    dragonRes: 2,
    slots: 1,
    rarity: 5,
    skillPoints: [
      { skillId: 24, points: -1 },
      { skillId: 25, points: 1 },
      { skillId: 46, points: 5 },
      { skillId: 55, points: 4 }
    ],
    price: 14800,
    maxDefense: 30
  }),
  deepFreeze<WaistArmor>({
    id: 82,
    type: 'waist',
    name: 'Guild Bard Coil+',
    blade: true,
    gunner: false,
    defense: 36,
    fireRes: 0,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 1,
    rarity: 6,
    skillPoints: [
      { skillId: 12, points: 2 },
      { skillId: 15, points: 3 },
      { skillId: 17, points: 1 },
      { skillId: 37, points: -5 }
    ],
    price: 25000,
    maxDefense: 36
  }),
  deepFreeze<WaistArmor>({
    id: 83,
    type: 'waist',
    name: 'Guild Bard Coat+',
    blade: false,
    gunner: true,
    defense: 22,
    fireRes: 0,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 1,
    rarity: 6,
    skillPoints: [
      { skillId: 12, points: 2 },
      { skillId: 15, points: 2 },
      { skillId: 17, points: 2 },
      { skillId: 37, points: -5 }
    ],
    price: 25000,
    maxDefense: 22
  }),
  deepFreeze<WaistArmor>({
    id: 84,
    type: 'waist',
    name: 'Rathian Faulds+',
    blade: true,
    gunner: false,
    defense: 50,
    fireRes: 4,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 1,
    rarity: 5,
    skillPoints: [
      { skillId: 11, points: 2 },
      { skillId: 23, points: 4 },
      { skillId: 37, points: -2 },
      { skillId: 61, points: 3 }
    ],
    price: 14800,
    maxDefense: 50
  }),
  deepFreeze<WaistArmor>({
    id: 85,
    type: 'waist',
    name: 'Rathian Coat+',
    blade: false,
    gunner: true,
    defense: 30,
    fireRes: 4,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 1,
    rarity: 5,
    skillPoints: [
      { skillId: 11, points: 1 },
      { skillId: 23, points: 5 },
      { skillId: 37, points: -2 },
      { skillId: 61, points: 3 }
    ],
    price: 14800,
    maxDefense: 30
  }),
  deepFreeze<WaistArmor>({
    id: 86,
    type: 'waist',
    name: 'Gigginox Faulds+',
    blade: true,
    gunner: false,
    defense: 54,
    fireRes: -4,
    waterRes: -1,
    iceRes: 2,
    thunderRes: 3,
    dragonRes: 0,
    slots: 1,
    rarity: 5,
    skillPoints: [
      { skillId: 9, points: 3 },
      { skillId: 22, points: 3 },
      { skillId: 23, points: -1 },
      { skillId: 49, points: 4 }
    ],
    price: 15800,
    maxDefense: 54
  }),
  deepFreeze<WaistArmor>({
    id: 87,
    type: 'waist',
    name: 'Gigginox Coat+',
    blade: false,
    gunner: true,
    defense: 32,
    fireRes: -4,
    waterRes: -1,
    iceRes: 2,
    thunderRes: 3,
    dragonRes: 0,
    slots: 1,
    rarity: 5,
    skillPoints: [
      { skillId: 9, points: 3 },
      { skillId: 22, points: 3 },
      { skillId: 23, points: -1 },
      { skillId: 49, points: 4 }
    ],
    price: 15800,
    maxDefense: 32
  }),
  deepFreeze<WaistArmor>({
    id: 88,
    type: 'waist',
    name: 'Ingot Coil+',
    blade: true,
    gunner: false,
    defense: 54,
    fireRes: -2,
    waterRes: -1,
    iceRes: 1,
    thunderRes: 3,
    dragonRes: 2,
    slots: 3,
    rarity: 5,
    skillPoints: [
      { skillId: 26, points: -3 },
      { skillId: 28, points: 2 },
      { skillId: 39, points: 1 },
      { skillId: 63, points: 1 }
    ],
    price: 17500,
    maxDefense: 54
  }),
  deepFreeze<WaistArmor>({
    id: 89,
    type: 'waist',
    name: 'Ingot Coat+',
    blade: false,
    gunner: true,
    defense: 32,
    fireRes: -2,
    waterRes: -1,
    iceRes: 1,
    thunderRes: 3,
    dragonRes: 2,
    slots: 3,
    rarity: 5,
    skillPoints: [
      { skillId: 3, points: 1 },
      { skillId: 28, points: 2 },
      { skillId: 29, points: -3 },
      { skillId: 63, points: 1 }
    ],
    price: 17500,
    maxDefense: 32
  }),
  deepFreeze<WaistArmor>({
    id: 90,
    type: 'waist',
    name: 'Dober Coil',
    blade: true,
    gunner: false,
    defense: 58,
    fireRes: -2,
    waterRes: -2,
    iceRes: 1,
    thunderRes: 1,
    dragonRes: 5,
    slots: 1,
    rarity: 6,
    skillPoints: [
      { skillId: 13, points: 3 },
      { skillId: 45, points: -1 },
      { skillId: 48, points: 2 },
      { skillId: 65, points: 5 }
    ],
    price: 19000,
    maxDefense: 58
  }),
  deepFreeze<WaistArmor>({
    id: 91,
    type: 'waist',
    name: 'Dober Coat',
    blade: false,
    gunner: true,
    defense: 34,
    fireRes: -2,
    waterRes: -2,
    iceRes: 1,
    thunderRes: 1,
    dragonRes: 5,
    slots: 1,
    rarity: 6,
    skillPoints: [
      { skillId: 6, points: 1 },
      { skillId: 30, points: 4 },
      { skillId: 45, points: -2 },
      { skillId: 65, points: 4 }
    ],
    price: 19000,
    maxDefense: 34
  }),
  deepFreeze<WaistArmor>({
    id: 92,
    type: 'waist',
    name: 'Lagiacrus Faulds+',
    blade: true,
    gunner: false,
    defense: 58,
    fireRes: -4,
    waterRes: 2,
    iceRes: -1,
    thunderRes: 5,
    dragonRes: -2,
    slots: 2,
    rarity: 6,
    skillPoints: [
      { skillId: 9, points: -3 },
      { skillId: 10, points: 2 },
      { skillId: 20, points: 2 },
      { skillId: 50, points: 2 }
    ],
    price: 18000,
    maxDefense: 58
  }),
  deepFreeze<WaistArmor>({
    id: 93,
    type: 'waist',
    name: 'Lagiacrus Coat+',
    blade: false,
    gunner: true,
    defense: 34,
    fireRes: -4,
    waterRes: 2,
    iceRes: -1,
    thunderRes: 5,
    dragonRes: -2,
    slots: 2,
    rarity: 6,
    skillPoints: [
      { skillId: 9, points: -3 },
      { skillId: 10, points: 2 },
      { skillId: 21, points: 2 },
      { skillId: 50, points: 2 }
    ],
    price: 18000,
    maxDefense: 34
  }),
  deepFreeze<WaistArmor>({
    id: 94,
    type: 'waist',
    name: 'Rathalos Faulds+',
    blade: true,
    gunner: false,
    defense: 58,
    fireRes: 4,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 1,
    rarity: 6,
    skillPoints: [
      { skillId: 2, points: 2 },
      { skillId: 25, points: 5 },
      { skillId: 36, points: -1 },
      { skillId: 66, points: 3 }
    ],
    price: 18000,
    maxDefense: 58
  }),
  deepFreeze<WaistArmor>({
    id: 95,
    type: 'waist',
    name: 'Rathalos Coat+',
    blade: false,
    gunner: true,
    defense: 34,
    fireRes: 4,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 1,
    rarity: 6,
    skillPoints: [
      { skillId: 4, points: 1 },
      { skillId: 25, points: 3 },
      { skillId: 36, points: -3 },
      { skillId: 66, points: 4 }
    ],
    price: 18000,
    maxDefense: 34
  }),
  deepFreeze<WaistArmor>({
    id: 96,
    type: 'waist',
    name: 'Barioth Faulds+',
    blade: true,
    gunner: false,
    defense: 58,
    fireRes: -4,
    waterRes: 2,
    iceRes: 5,
    thunderRes: -3,
    dragonRes: 0,
    slots: 3,
    rarity: 6,
    skillPoints: [
      { skillId: 16, points: 1 },
      { skillId: 44, points: 2 },
      { skillId: 66, points: -3 },
      { skillId: 67, points: 1 }
    ],
    price: 18000,
    maxDefense: 58
  }),
  deepFreeze<WaistArmor>({
    id: 97,
    type: 'waist',
    name: 'Barioth Coat+',
    blade: false,
    gunner: true,
    defense: 34,
    fireRes: -4,
    waterRes: 2,
    iceRes: 5,
    thunderRes: -3,
    dragonRes: 0,
    slots: 3,
    rarity: 6,
    skillPoints: [
      { skillId: 16, points: 1 },
      { skillId: 44, points: 2 },
      { skillId: 66, points: -3 },
      { skillId: 67, points: 1 }
    ],
    price: 18000,
    maxDefense: 34
  }),
  deepFreeze<WaistArmor>({
    id: 98,
    type: 'waist',
    name: 'Uragaan Faulds+',
    blade: true,
    gunner: false,
    defense: 62,
    fireRes: 4,
    waterRes: -4,
    iceRes: -1,
    thunderRes: 1,
    dragonRes: -2,
    slots: 1,
    rarity: 6,
    skillPoints: [
      { skillId: 19, points: 2 },
      { skillId: 33, points: 2 },
      { skillId: 36, points: 6 },
      { skillId: 46, points: -1 }
    ],
    price: 18800,
    maxDefense: 62
  }),
  deepFreeze<WaistArmor>({
    id: 99,
    type: 'waist',
    name: 'Uragaan Coat+',
    blade: false,
    gunner: true,
    defense: 37,
    fireRes: 4,
    waterRes: -4,
    iceRes: -1,
    thunderRes: 1,
    dragonRes: -2,
    slots: 1,
    rarity: 6,
    skillPoints: [
      { skillId: 3, points: 6 },
      { skillId: 33, points: 2 },
      { skillId: 36, points: 2 },
      { skillId: 46, points: -1 }
    ],
    price: 18800,
    maxDefense: 37
  }),
  deepFreeze<WaistArmor>({
    id: 100,
    type: 'waist',
    name: 'Agnaktor Faulds+',
    blade: true,
    gunner: false,
    defense: 62,
    fireRes: 5,
    waterRes: -4,
    iceRes: -2,
    thunderRes: 1,
    dragonRes: 0,
    slots: 3,
    rarity: 6,
    skillPoints: [
      { skillId: 0, points: 2 },
      { skillId: 13, points: -3 },
      { skillId: 27, points: 1 },
      { skillId: 52, points: 1 }
    ],
    price: 19800,
    maxDefense: 62
  }),
  deepFreeze<WaistArmor>({
    id: 101,
    type: 'waist',
    name: 'Agnaktor Coat+',
    blade: false,
    gunner: true,
    defense: 37,
    fireRes: 5,
    waterRes: -4,
    iceRes: -2,
    thunderRes: 1,
    dragonRes: 0,
    slots: 3,
    rarity: 6,
    skillPoints: [
      { skillId: 4, points: 1 },
      { skillId: 7, points: 2 },
      { skillId: 13, points: -3 },
      { skillId: 52, points: 1 }
    ],
    price: 19800,
    maxDefense: 37
  }),
  deepFreeze<WaistArmor>({
    id: 102,
    type: 'waist',
    name: 'Vangis Coil',
    blade: true,
    gunner: false,
    defense: 64,
    fireRes: 0,
    waterRes: 0,
    iceRes: 3,
    thunderRes: -4,
    dragonRes: -4,
    slots: 0,
    rarity: 7,
    skillPoints: [],
    torsoUp: true,
    price: 41500,
    maxDefense: 64
  }),
  deepFreeze<WaistArmor>({
    id: 103,
    type: 'waist',
    name: 'Vangis Coat',
    blade: false,
    gunner: true,
    defense: 38,
    fireRes: 0,
    waterRes: 0,
    iceRes: 3,
    thunderRes: -4,
    dragonRes: -4,
    slots: 0,
    rarity: 7,
    skillPoints: [],
    torsoUp: true,
    price: 41500,
    maxDefense: 38
  }),
  deepFreeze<WaistArmor>({
    id: 104,
    type: 'waist',
    name: 'Damascus Coil',
    blade: true,
    gunner: false,
    defense: 62,
    fireRes: -2,
    waterRes: 0,
    iceRes: 2,
    thunderRes: -2,
    dragonRes: 3,
    slots: 1,
    rarity: 6,
    skillPoints: [
      { skillId: 13, points: -1 },
      { skillId: 19, points: 3 },
      { skillId: 23, points: 4 },
      { skillId: 28, points: 3 }
    ],
    price: 32300,
    maxDefense: 62
  }),
  deepFreeze<WaistArmor>({
    id: 105,
    type: 'waist',
    name: 'Damascus Coat',
    blade: false,
    gunner: true,
    defense: 37,
    fireRes: -2,
    waterRes: 0,
    iceRes: 2,
    thunderRes: -2,
    dragonRes: 3,
    slots: 1,
    rarity: 6,
    skillPoints: [
      { skillId: 13, points: -1 },
      { skillId: 23, points: 3 },
      { skillId: 28, points: 4 },
      { skillId: 29, points: 3 }
    ],
    price: 32300,
    maxDefense: 37
  }),
  deepFreeze<WaistArmor>({
    id: 106,
    type: 'waist',
    name: 'Helios Coil+',
    blade: true,
    gunner: false,
    defense: 66,
    fireRes: 0,
    waterRes: 5,
    iceRes: 3,
    thunderRes: -3,
    dragonRes: -4,
    slots: 3,
    rarity: 6,
    skillPoints: [
      { skillId: 0, points: -3 },
      { skillId: 1, points: 2 },
      { skillId: 11, points: 1 },
      { skillId: 37, points: -1 }
    ],
    price: 26200,
    maxDefense: 66
  }),
  deepFreeze<WaistArmor>({
    id: 107,
    type: 'waist',
    name: 'Helios Coat+',
    blade: false,
    gunner: true,
    defense: 39,
    fireRes: 0,
    waterRes: 5,
    iceRes: 3,
    thunderRes: -3,
    dragonRes: -4,
    slots: 3,
    rarity: 6,
    skillPoints: [
      { skillId: 3, points: -3 },
      { skillId: 11, points: 1 },
      { skillId: 14, points: 2 },
      { skillId: 37, points: -1 }
    ],
    price: 26200,
    maxDefense: 39
  }),
  deepFreeze<WaistArmor>({
    id: 108,
    type: 'waist',
    name: 'Yamato Koshiate+',
    blade: true,
    gunner: false,
    defense: 66,
    fireRes: 4,
    waterRes: 0,
    iceRes: -3,
    thunderRes: 0,
    dragonRes: -4,
    slots: 1,
    rarity: 6,
    skillPoints: [
      { skillId: 0, points: 5 },
      { skillId: 18, points: 2 },
      { skillId: 24, points: 3 },
      { skillId: 71, points: -1 }
    ],
    price: 27500,
    maxDefense: 66
  }),
  deepFreeze<WaistArmor>({
    id: 109,
    type: 'waist',
    name: 'Mutsu Koshiate+',
    blade: false,
    gunner: true,
    defense: 39,
    fireRes: 4,
    waterRes: 0,
    iceRes: -3,
    thunderRes: 0,
    dragonRes: -4,
    slots: 1,
    rarity: 6,
    skillPoints: [
      { skillId: 3, points: 2 },
      { skillId: 24, points: 2 },
      { skillId: 32, points: 4 },
      { skillId: 71, points: -3 }
    ],
    price: 27500,
    maxDefense: 39
  }),
  deepFreeze<WaistArmor>({
    id: 110,
    type: 'waist',
    name: 'Escadora Might',
    blade: true,
    gunner: false,
    defense: 70,
    fireRes: -1,
    waterRes: -1,
    iceRes: -1,
    thunderRes: 0,
    dragonRes: -5,
    slots: 2,
    rarity: 7,
    skillPoints: [
      { skillId: 16, points: 3 },
      { skillId: 20, points: 2 },
      { skillId: 43, points: -2 },
      { skillId: 81, points: 2 }
    ],
    price: 66666,
    maxDefense: 70
  }),
  deepFreeze<WaistArmor>({
    id: 111,
    type: 'waist',
    name: 'Escadora Force',
    blade: false,
    gunner: true,
    defense: 42,
    fireRes: -1,
    waterRes: -1,
    iceRes: -1,
    thunderRes: 0,
    dragonRes: -5,
    slots: 2,
    rarity: 7,
    skillPoints: [
      { skillId: 16, points: 3 },
      { skillId: 21, points: 2 },
      { skillId: 43, points: -2 },
      { skillId: 81, points: 2 }
    ],
    price: 66666,
    maxDefense: 42
  }),
  deepFreeze<WaistArmor>({
    id: 112,
    type: 'waist',
    name: 'Chakra Waistlet',
    blade: true,
    gunner: true,
    defense: 18,
    fireRes: 10,
    waterRes: 0,
    iceRes: -10,
    thunderRes: 0,
    dragonRes: 0,
    slots: 3,
    rarity: 7,
    skillPoints: [],
    price: 33333,
    maxDefense: 18
  })
];
