import { deepFreeze } from '../../utils';
import type { WaistArmor } from './types';

export const WaistArmors: WaistArmor[] = [
  deepFreeze<WaistArmor>({
    id: 0,
    type: 'waist',
    name: 'Leather Belt',
    blade: true,
    gunner: true,
    defense: 1,
    fireRes: -1,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 3,
    dragonRes: 2,
    slots: 1,
    rarity: 1,
    price: 150,
    maxDefense: 1,
    maxLowRankDefense: 9,
    skillPoints: { attack: 1, gathering: 4, spd_gather: 2, whim: 1 }
  }),
  deepFreeze<WaistArmor>({
    id: 1,
    type: 'waist',
    name: 'Piscine Belt',
    blade: true,
    gunner: true,
    defense: 3,
    fireRes: -2,
    waterRes: 4,
    iceRes: 2,
    thunderRes: -3,
    dragonRes: 0,
    slots: 0,
    rarity: 1,
    price: 300,
    maxDefense: 3,
    maxLowRankDefense: 11,
    skillPoints: { swimming: 2, currentres: 9 }
  }),
  deepFreeze<WaistArmor>({
    id: 2,
    type: 'waist',
    name: 'Chainmail Belt',
    blade: true,
    gunner: true,
    defense: 2,
    fireRes: -1,
    waterRes: -1,
    iceRes: 3,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 1,
    price: 200,
    maxDefense: 2,
    maxLowRankDefense: 9,
    skillPoints: {
      health: 1,
      fishing: 2,
      combo_rate: 2,
      combo_plus: 4
    }
  }),
  deepFreeze<WaistArmor>({
    id: 3,
    type: 'waist',
    name: 'Loc Lac Kilt',
    blade: true,
    gunner: true,
    defense: 4,
    fireRes: 4,
    waterRes: -3,
    iceRes: -4,
    thunderRes: 2,
    dragonRes: 0,
    slots: 0,
    rarity: 1,
    price: 500,
    maxDefense: 4,
    maxLowRankDefense: 11,
    skillPoints: { rec_speed: 5, transportr: 3, heat_res: 3 }
  }),
  deepFreeze<WaistArmor>({
    id: 4,
    type: 'waist',
    name: "Hunter's Faulds",
    blade: true,
    gunner: false,
    defense: 6,
    fireRes: -1,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: -1,
    slots: 1,
    rarity: 1,
    price: 500,
    maxDefense: 6,
    maxLowRankDefense: 20,
    skillPoints: {
      attack: 1,
      psychic: 1,
      water_res: -1,
      map: 2,
      bbq: 4
    }
  }),
  deepFreeze<WaistArmor>({
    id: 5,
    type: 'waist',
    name: "Hunter's Coat",
    blade: false,
    gunner: true,
    defense: 3,
    fireRes: -1,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: -1,
    slots: 1,
    rarity: 1,
    price: 500,
    maxDefense: 3,
    maxLowRankDefense: 10,
    skillPoints: {
      attack: 1,
      psychic: 1,
      water_res: -1,
      map: 3,
      bbq: 3
    }
  }),
  deepFreeze<WaistArmor>({
    id: 6,
    type: 'waist',
    name: 'Bone Faulds',
    blade: true,
    gunner: false,
    defense: 8,
    fireRes: 2,
    waterRes: -2,
    iceRes: -1,
    thunderRes: 2,
    dragonRes: 3,
    slots: 1,
    rarity: 1,
    price: 750,
    maxDefense: 8,
    maxLowRankDefense: 22,
    skillPoints: {
      hunger: 2,
      sleep: -1,
      lastingpwr: 4,
      perception: 2
    }
  }),
  deepFreeze<WaistArmor>({
    id: 7,
    type: 'waist',
    name: 'Bone Coat',
    blade: false,
    gunner: true,
    defense: 4,
    fireRes: 2,
    waterRes: -2,
    iceRes: -1,
    thunderRes: 2,
    dragonRes: 3,
    slots: 1,
    rarity: 1,
    price: 750,
    maxDefense: 4,
    maxLowRankDefense: 11,
    skillPoints: {
      hunger: 2,
      sleep: -1,
      lastingpwr: 3,
      perception: 3
    }
  }),
  deepFreeze<WaistArmor>({
    id: 8,
    type: 'waist',
    name: 'Alloy Coil',
    blade: true,
    gunner: false,
    defense: 8,
    fireRes: 1,
    waterRes: 1,
    iceRes: -1,
    thunderRes: -2,
    dragonRes: -1,
    slots: 1,
    rarity: 1,
    price: 1000,
    maxDefense: 8,
    maxLowRankDefense: 22,
    skillPoints: {
      expert: 3,
      sharpener: 1,
      speedsetup: 3,
      oxygen: -2
    }
  }),
  deepFreeze<WaistArmor>({
    id: 9,
    type: 'waist',
    name: 'Alloy Coat',
    blade: false,
    gunner: true,
    defense: 4,
    fireRes: 1,
    waterRes: 1,
    iceRes: -1,
    thunderRes: -2,
    dragonRes: -1,
    slots: 1,
    rarity: 1,
    price: 1000,
    maxDefense: 4,
    maxLowRankDefense: 11,
    skillPoints: {
      'normal_s+': 1,
      expert: 3,
      speedsetup: 3,
      oxygen: -2
    }
  }),
  deepFreeze<WaistArmor>({
    id: 10,
    type: 'waist',
    name: 'Jaggi Faulds',
    blade: true,
    gunner: false,
    defense: 10,
    fireRes: -3,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    price: 1200,
    maxDefense: 10,
    maxLowRankDefense: 24,
    skillPoints: { attack: 1, stun: 3, gluttony: 4, cold_res: -1 }
  }),
  deepFreeze<WaistArmor>({
    id: 11,
    type: 'waist',
    name: 'Jaggi Coat',
    blade: false,
    gunner: true,
    defense: 5,
    fireRes: -3,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    price: 1200,
    maxDefense: 5,
    maxLowRankDefense: 12,
    skillPoints: { attack: 1, stun: 3, gluttony: 4, cold_res: -1 }
  }),
  deepFreeze<WaistArmor>({
    id: 12,
    type: 'waist',
    name: 'Bnahabra Coil',
    blade: true,
    gunner: false,
    defense: 10,
    fireRes: -4,
    waterRes: -1,
    iceRes: -1,
    thunderRes: 2,
    dragonRes: 5,
    slots: 0,
    rarity: 2,
    price: 1800,
    maxDefense: 10,
    maxLowRankDefense: 24,
    skillPoints: { sharpness: 3, status: 3, poison: -5 }
  }),
  deepFreeze<WaistArmor>({
    id: 13,
    type: 'waist',
    name: 'Bnahabra Coat',
    blade: false,
    gunner: true,
    defense: 5,
    fireRes: -4,
    waterRes: -1,
    iceRes: -1,
    thunderRes: 2,
    dragonRes: 5,
    slots: 0,
    rarity: 2,
    price: 1800,
    maxDefense: 5,
    maxLowRankDefense: 12,
    skillPoints: { status: 3, poison: -5, reload_spd: 3 }
  }),
  deepFreeze<WaistArmor>({
    id: 14,
    type: 'waist',
    name: 'Rhenoplos Coil',
    blade: true,
    gunner: false,
    defense: 12,
    fireRes: 2,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: 2,
    slots: 1,
    rarity: 2,
    price: 1400,
    maxDefense: 12,
    maxLowRankDefense: 24,
    skillPoints: {
      attack: 1,
      wind_res: 2,
      eating: 4,
      'mud/snow': 1,
      thunderres: -1
    }
  }),
  deepFreeze<WaistArmor>({
    id: 15,
    type: 'waist',
    name: 'Rhenoplos Coat',
    blade: false,
    gunner: true,
    defense: 6,
    fireRes: 2,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: 2,
    slots: 1,
    rarity: 2,
    price: 1400,
    maxDefense: 6,
    maxLowRankDefense: 12,
    skillPoints: {
      recoil: 3,
      'crag_s+': 1,
      attack: 1,
      eating: 3,
      thunderres: -1
    }
  }),
  deepFreeze<WaistArmor>({
    id: 16,
    type: 'waist',
    name: 'Qurupeco Coil',
    blade: true,
    gunner: false,
    defense: 12,
    fireRes: 2,
    waterRes: -2,
    iceRes: -3,
    thunderRes: 0,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    price: 1700,
    maxDefense: 12,
    maxLowRankDefense: 24,
    skillPoints: {
      attack: 2,
      defense: 1,
      rec_level: 2,
      evasion: 2,
      ice_res: -2
    }
  }),
  deepFreeze<WaistArmor>({
    id: 17,
    type: 'waist',
    name: 'Qurupeco Coat',
    blade: false,
    gunner: true,
    defense: 6,
    fireRes: 2,
    waterRes: -2,
    iceRes: -3,
    thunderRes: 0,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    price: 1700,
    maxDefense: 6,
    maxLowRankDefense: 12,
    skillPoints: {
      attack: 2,
      defense: 2,
      rec_level: 1,
      evasion: 1,
      ice_res: -3
    }
  }),
  deepFreeze<WaistArmor>({
    id: 18,
    type: 'waist',
    name: 'Ludroth Faulds',
    blade: true,
    gunner: false,
    defense: 13,
    fireRes: -3,
    waterRes: 2,
    iceRes: 0,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    price: 2200,
    maxDefense: 13,
    maxLowRankDefense: 25,
    skillPoints: {
      protection: 1,
      constitutn: 3,
      fire_res: -1,
      currentres: 4
    }
  }),
  deepFreeze<WaistArmor>({
    id: 19,
    type: 'waist',
    name: 'Ludroth Coat',
    blade: false,
    gunner: true,
    defense: 7,
    fireRes: -3,
    waterRes: 2,
    iceRes: 0,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    price: 2200,
    maxDefense: 7,
    maxLowRankDefense: 13,
    skillPoints: {
      'pellet_s+': 3,
      protection: 3,
      constitutn: 1,
      fire_res: -2
    }
  }),
  deepFreeze<WaistArmor>({
    id: 20,
    type: 'waist',
    name: 'Steel Faulds',
    blade: true,
    gunner: false,
    defense: 12,
    fireRes: -1,
    waterRes: 1,
    iceRes: 1,
    thunderRes: -1,
    dragonRes: 0,
    slots: 1,
    rarity: 2,
    price: 2000,
    maxDefense: 12,
    maxLowRankDefense: 24,
    skillPoints: { sharpener: 3, guard: 3, swimming: -3 }
  }),
  deepFreeze<WaistArmor>({
    id: 21,
    type: 'waist',
    name: 'Baggi Coil',
    blade: true,
    gunner: false,
    defense: 13,
    fireRes: -3,
    waterRes: -1,
    iceRes: 3,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    price: 2400,
    maxDefense: 13,
    maxLowRankDefense: 25,
    skillPoints: {
      tranquilzr: 3,
      fastcharge: 2,
      stun: -1,
      ice_res: 3
    }
  }),
  deepFreeze<WaistArmor>({
    id: 22,
    type: 'waist',
    name: 'Baggi Coat',
    blade: false,
    gunner: true,
    defense: 7,
    fireRes: -3,
    waterRes: -1,
    iceRes: 3,
    thunderRes: -1,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    price: 2400,
    maxDefense: 7,
    maxLowRankDefense: 13,
    skillPoints: {
      pellets_up: 2,
      tranquilzr: 4,
      stun: -1,
      ice_res: 2
    }
  }),
  deepFreeze<WaistArmor>({
    id: 23,
    type: 'waist',
    name: 'Barroth Faulds',
    blade: true,
    gunner: false,
    defense: 15,
    fireRes: 4,
    waterRes: -4,
    iceRes: -3,
    thunderRes: 3,
    dragonRes: 0,
    slots: 1,
    rarity: 2,
    price: 3200,
    maxDefense: 15,
    maxLowRankDefense: 27,
    skillPoints: { stamina: 3, expert: -2, attack: 1, potential: 3 }
  }),
  deepFreeze<WaistArmor>({
    id: 24,
    type: 'waist',
    name: 'Barroth Coat',
    blade: false,
    gunner: true,
    defense: 8,
    fireRes: 4,
    waterRes: -4,
    iceRes: -3,
    thunderRes: 3,
    dragonRes: 0,
    slots: 1,
    rarity: 2,
    price: 3200,
    maxDefense: 8,
    maxLowRankDefense: 14,
    skillPoints: { stamina: 3, expert: -2, attack: 1, potential: 3 }
  }),
  deepFreeze<WaistArmor>({
    id: 25,
    type: 'waist',
    name: 'Gobul Faulds',
    blade: true,
    gunner: false,
    defense: 16,
    fireRes: -2,
    waterRes: 3,
    iceRes: 0,
    thunderRes: -3,
    dragonRes: 2,
    slots: 0,
    rarity: 2,
    price: 3600,
    maxDefense: 16,
    maxLowRankDefense: 28,
    skillPoints: { rec_speed: -1, eating: 4, stun: 4, water_res: 2 }
  }),
  deepFreeze<WaistArmor>({
    id: 26,
    type: 'waist',
    name: 'Gobul Coat',
    blade: false,
    gunner: true,
    defense: 8,
    fireRes: -2,
    waterRes: 3,
    iceRes: 0,
    thunderRes: -3,
    dragonRes: 2,
    slots: 0,
    rarity: 2,
    price: 3600,
    maxDefense: 8,
    maxLowRankDefense: 14,
    skillPoints: { rec_speed: -1, eating: 4, stun: 4, water_res: 2 }
  }),
  deepFreeze<WaistArmor>({
    id: 27,
    type: 'waist',
    name: "Ranger's Faulds",
    blade: true,
    gunner: false,
    defense: 15,
    fireRes: 0,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 0,
    rarity: 3,
    price: 10000,
    maxDefense: 15,
    maxLowRankDefense: 27,
    skillPoints: {
      fate: -2,
      carving: 4,
      'wide-range': 4,
      spd_gather: 2
    }
  }),
  deepFreeze<WaistArmor>({
    id: 28,
    type: 'waist',
    name: "Archer's Bandolier",
    blade: false,
    gunner: true,
    defense: 8,
    fireRes: 0,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 0,
    rarity: 3,
    price: 10000,
    maxDefense: 8,
    maxLowRankDefense: 14,
    skillPoints: {
      fate: -3,
      carving: 3,
      'wide-range': 4,
      spd_gather: 2
    }
  }),
  deepFreeze<WaistArmor>({
    id: 29,
    type: 'waist',
    name: 'Guild Bard Coil',
    blade: true,
    gunner: false,
    defense: 15,
    fireRes: 0,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 0,
    rarity: 3,
    price: 10000,
    maxDefense: 15,
    maxLowRankDefense: 27,
    skillPoints: { fate: 4, psychic: 4, evasion: 2, sense: -1 }
  }),
  deepFreeze<WaistArmor>({
    id: 30,
    type: 'waist',
    name: 'Guild Bard Coat',
    blade: false,
    gunner: true,
    defense: 8,
    fireRes: 0,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 0,
    rarity: 3,
    price: 10000,
    maxDefense: 8,
    maxLowRankDefense: 14,
    skillPoints: { fate: 2, psychic: 4, evasion: 3, sense: -2 }
  }),
  deepFreeze<WaistArmor>({
    id: 31,
    type: 'waist',
    name: 'Rathian Faulds',
    blade: true,
    gunner: false,
    defense: 16,
    fireRes: 3,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 1,
    rarity: 2,
    price: 3600,
    maxDefense: 16,
    maxLowRankDefense: 28,
    skillPoints: {
      hearing: 3,
      health: 2,
      protection: -2,
      fire_res: 2
    }
  }),
  deepFreeze<WaistArmor>({
    id: 32,
    type: 'waist',
    name: 'Rathian Coat',
    blade: false,
    gunner: true,
    defense: 8,
    fireRes: 3,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 1,
    rarity: 2,
    price: 3600,
    maxDefense: 8,
    maxLowRankDefense: 14,
    skillPoints: {
      hearing: 3,
      health: 3,
      protection: -1,
      fire_res: 2
    }
  }),
  deepFreeze<WaistArmor>({
    id: 33,
    type: 'waist',
    name: 'Gigginox Faulds',
    blade: true,
    gunner: false,
    defense: 18,
    fireRes: -4,
    waterRes: 0,
    iceRes: 2,
    thunderRes: 2,
    dragonRes: -1,
    slots: 1,
    rarity: 2,
    price: 4100,
    maxDefense: 18,
    maxLowRankDefense: 30,
    skillPoints: { status: 2, poison: 3, health: -1, constitutn: 3 }
  }),
  deepFreeze<WaistArmor>({
    id: 34,
    type: 'waist',
    name: 'Gigginox Coat',
    blade: false,
    gunner: true,
    defense: 9,
    fireRes: -4,
    waterRes: 0,
    iceRes: 2,
    thunderRes: 2,
    dragonRes: -1,
    slots: 1,
    rarity: 2,
    price: 4100,
    maxDefense: 9,
    maxLowRankDefense: 15,
    skillPoints: { status: 2, poison: 1, health: -2, constitutn: 4 }
  }),
  deepFreeze<WaistArmor>({
    id: 35,
    type: 'waist',
    name: 'Ingot Coil',
    blade: true,
    gunner: false,
    defense: 18,
    fireRes: -2,
    waterRes: -1,
    iceRes: 1,
    thunderRes: 3,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    price: 5000,
    maxDefense: 18,
    maxLowRankDefense: 28,
    skillPoints: {
      sharpener: -2,
      guard_up: 3,
      wind_res: 1,
      thunderres: 3
    }
  }),
  deepFreeze<WaistArmor>({
    id: 36,
    type: 'waist',
    name: 'Ingot Coat',
    blade: false,
    gunner: true,
    defense: 9,
    fireRes: -2,
    waterRes: -1,
    iceRes: 1,
    thunderRes: 3,
    dragonRes: 1,
    slots: 1,
    rarity: 2,
    price: 5000,
    maxDefense: 9,
    maxLowRankDefense: 14,
    skillPoints: {
      recoil: 1,
      guard_up: 3,
      reload_spd: -2,
      thunderres: 3
    }
  }),
  deepFreeze<WaistArmor>({
    id: 37,
    type: 'waist',
    name: 'Lagiacrus Faulds',
    blade: true,
    gunner: false,
    defense: 20,
    fireRes: -3,
    waterRes: 2,
    iceRes: -1,
    thunderRes: 4,
    dragonRes: -2,
    slots: 2,
    rarity: 3,
    price: 5600,
    maxDefense: 20,
    maxLowRankDefense: 30,
    skillPoints: {
      sharpness: 2,
      status: -2,
      elemental: 1,
      swimming: 3
    }
  }),
  deepFreeze<WaistArmor>({
    id: 38,
    type: 'waist',
    name: 'Lagiacrus Coat',
    blade: false,
    gunner: true,
    defense: 10,
    fireRes: -3,
    waterRes: 2,
    iceRes: -1,
    thunderRes: 4,
    dragonRes: -2,
    slots: 2,
    rarity: 3,
    price: 5600,
    maxDefense: 10,
    maxLowRankDefense: 15,
    skillPoints: {
      normals_up: 2,
      status: -2,
      elemental: 1,
      swimming: 3
    }
  }),
  deepFreeze<WaistArmor>({
    id: 39,
    type: 'waist',
    name: 'Rathalos Faulds',
    blade: true,
    gunner: false,
    defense: 20,
    fireRes: 3,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 0,
    rarity: 3,
    price: 5600,
    maxDefense: 20,
    maxLowRankDefense: 30,
    skillPoints: { expert: 3, attack: 5, defense: -2, heat_res: 1 }
  }),
  deepFreeze<WaistArmor>({
    id: 40,
    type: 'waist',
    name: 'Rathalos Coat',
    blade: false,
    gunner: true,
    defense: 10,
    fireRes: 3,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 0,
    rarity: 3,
    price: 5600,
    maxDefense: 10,
    maxLowRankDefense: 15,
    skillPoints: { expert: 3, attack: 4, defense: -2, heat_res: 2 }
  }),
  deepFreeze<WaistArmor>({
    id: 41,
    type: 'waist',
    name: 'Barioth Faulds',
    blade: true,
    gunner: false,
    defense: 20,
    fireRes: -4,
    waterRes: 2,
    iceRes: 4,
    thunderRes: -3,
    dragonRes: 0,
    slots: 0,
    rarity: 3,
    price: 5600,
    maxDefense: 20,
    maxLowRankDefense: 30,
    skillPoints: {
      stamina: 4,
      evasion: 2,
      heat_res: -1,
      cold_res: 4
    }
  }),
  deepFreeze<WaistArmor>({
    id: 42,
    type: 'waist',
    name: 'Barioth Coat',
    blade: false,
    gunner: true,
    defense: 10,
    fireRes: -4,
    waterRes: 2,
    iceRes: 4,
    thunderRes: -3,
    dragonRes: 0,
    slots: 0,
    rarity: 3,
    price: 5600,
    maxDefense: 10,
    maxLowRankDefense: 15,
    skillPoints: {
      stamina: 3,
      evasion: 5,
      heat_res: -2,
      cold_res: 1
    }
  }),
  deepFreeze<WaistArmor>({
    id: 43,
    type: 'waist',
    name: 'Uragaan Faulds',
    blade: true,
    gunner: false,
    defense: 22,
    fireRes: 3,
    waterRes: -4,
    iceRes: -1,
    thunderRes: 1,
    dragonRes: -2,
    slots: 1,
    rarity: 3,
    price: 6300,
    maxDefense: 22,
    maxLowRankDefense: 30,
    skillPoints: {
      punishdraw: 2,
      bomb_boost: 2,
      defense: 3,
      eating: -2
    }
  }),
  deepFreeze<WaistArmor>({
    id: 44,
    type: 'waist',
    name: 'Uragaan Coat',
    blade: false,
    gunner: true,
    defense: 11,
    fireRes: 3,
    waterRes: -4,
    iceRes: -1,
    thunderRes: 1,
    dragonRes: -2,
    slots: 1,
    rarity: 3,
    price: 6300,
    maxDefense: 11,
    maxLowRankDefense: 15,
    skillPoints: {
      recoil: 2,
      bomb_boost: 2,
      defense: 2,
      eating: -3
    }
  }),
  deepFreeze<WaistArmor>({
    id: 45,
    type: 'waist',
    name: 'Agnaktor Faulds',
    blade: true,
    gunner: false,
    defense: 22,
    fireRes: 4,
    waterRes: -4,
    iceRes: -2,
    thunderRes: 1,
    dragonRes: 0,
    slots: 2,
    rarity: 3,
    price: 7200,
    maxDefense: 22,
    maxLowRankDefense: 30,
    skillPoints: {
      stamina: -2,
      guard: 2,
      guard_up: 2,
      flame_aura: 1
    }
  }),
  deepFreeze<WaistArmor>({
    id: 46,
    type: 'waist',
    name: 'Agnaktor Coat',
    blade: false,
    gunner: true,
    defense: 11,
    fireRes: 4,
    waterRes: -4,
    iceRes: -2,
    thunderRes: 1,
    dragonRes: 0,
    slots: 2,
    rarity: 3,
    price: 7200,
    maxDefense: 11,
    maxLowRankDefense: 15,
    skillPoints: {
      stamina: -2,
      guard_up: 2,
      reload_spd: 2,
      flame_aura: 1
    }
  }),
  deepFreeze<WaistArmor>({
    id: 47,
    type: 'waist',
    name: 'Helios Coil',
    blade: true,
    gunner: false,
    defense: 24,
    fireRes: 0,
    waterRes: 4,
    iceRes: 3,
    thunderRes: -3,
    dragonRes: -4,
    slots: 0,
    rarity: 3,
    price: 11000,
    maxDefense: 24,
    maxLowRankDefense: 32,
    skillPoints: {
      sharpness: -2,
      handicraft: 3,
      hearing: 5,
      protection: -1
    }
  }),
  deepFreeze<WaistArmor>({
    id: 48,
    type: 'waist',
    name: 'Helios Coat',
    blade: false,
    gunner: true,
    defense: 12,
    fireRes: 0,
    waterRes: 4,
    iceRes: 3,
    thunderRes: -3,
    dragonRes: -4,
    slots: 0,
    rarity: 3,
    price: 11000,
    maxDefense: 12,
    maxLowRankDefense: 16,
    skillPoints: {
      recoil: -2,
      hearing: 5,
      loading: 3,
      protection: -1
    }
  }),
  deepFreeze<WaistArmor>({
    id: 49,
    type: 'waist',
    name: 'Yamato Koshiate',
    blade: true,
    gunner: false,
    defense: 24,
    fireRes: 3,
    waterRes: 0,
    iceRes: -3,
    thunderRes: 0,
    dragonRes: -3,
    slots: 1,
    rarity: 3,
    price: 12000,
    maxDefense: 24,
    maxLowRankDefense: 32,
    skillPoints: {
      sharpness: 4,
      fastcharge: 1,
      rec_speed: 2,
      combo_rate: -2
    }
  }),
  deepFreeze<WaistArmor>({
    id: 50,
    type: 'waist',
    name: 'Mutsu Koshiate',
    blade: false,
    gunner: true,
    defense: 12,
    fireRes: 3,
    waterRes: 0,
    iceRes: -3,
    thunderRes: 0,
    dragonRes: -3,
    slots: 1,
    rarity: 3,
    price: 12000,
    maxDefense: 12,
    maxLowRankDefense: 16,
    skillPoints: {
      recoil: 4,
      rec_speed: 1,
      'clust_s+': 1,
      combo_rate: -3
    }
  }),
  deepFreeze<WaistArmor>({
    id: 51,
    type: 'waist',
    name: 'Leather Faulds+',
    blade: true,
    gunner: false,
    defense: 26,
    fireRes: -2,
    waterRes: 0,
    iceRes: -2,
    thunderRes: 3,
    dragonRes: 2,
    slots: 2,
    rarity: 4,
    price: 4600,
    maxDefense: 26,
    skillPoints: { gathering: 3, spd_gather: 1, whim: 4 }
  }),
  deepFreeze<WaistArmor>({
    id: 52,
    type: 'waist',
    name: 'Leather Coat+',
    blade: false,
    gunner: true,
    defense: 15,
    fireRes: -2,
    waterRes: 0,
    iceRes: -2,
    thunderRes: 3,
    dragonRes: 2,
    slots: 2,
    rarity: 4,
    price: 4600,
    maxDefense: 15,
    skillPoints: { gathering: 2, spd_gather: 2, whim: 4 }
  }),
  deepFreeze<WaistArmor>({
    id: 53,
    type: 'waist',
    name: 'Piscine Belt+',
    blade: true,
    gunner: false,
    defense: 26,
    fireRes: -3,
    waterRes: 5,
    iceRes: 2,
    thunderRes: -4,
    dragonRes: 0,
    slots: 0,
    rarity: 4,
    price: 4700,
    maxDefense: 26,
    skillPoints: { currentres: 13 }
  }),
  deepFreeze<WaistArmor>({
    id: 54,
    type: 'waist',
    name: 'Piscine Tank+',
    blade: false,
    gunner: true,
    defense: 15,
    fireRes: -3,
    waterRes: 5,
    iceRes: 2,
    thunderRes: -4,
    dragonRes: 0,
    slots: 1,
    rarity: 4,
    price: 4700,
    maxDefense: 15,
    skillPoints: { currentres: 11 }
  }),
  deepFreeze<WaistArmor>({
    id: 55,
    type: 'waist',
    name: 'Chainmail Faulds+',
    blade: true,
    gunner: false,
    defense: 30,
    fireRes: -1,
    waterRes: -2,
    iceRes: 4,
    thunderRes: -1,
    dragonRes: 1,
    slots: 2,
    rarity: 4,
    price: 5400,
    maxDefense: 30,
    skillPoints: { health: 2, combo_rate: 2, combo_plus: 4 }
  }),
  deepFreeze<WaistArmor>({
    id: 56,
    type: 'waist',
    name: 'Chainmail Coat+',
    blade: false,
    gunner: true,
    defense: 18,
    fireRes: -1,
    waterRes: -2,
    iceRes: 4,
    thunderRes: -1,
    dragonRes: 1,
    slots: 2,
    rarity: 4,
    price: 5400,
    maxDefense: 18,
    skillPoints: { health: 3, combo_rate: 1, combo_plus: 4 }
  }),
  deepFreeze<WaistArmor>({
    id: 57,
    type: 'waist',
    name: 'Loc Lac Kilt+',
    blade: true,
    gunner: false,
    defense: 30,
    fireRes: 5,
    waterRes: -4,
    iceRes: -5,
    thunderRes: 2,
    dragonRes: 0,
    slots: 0,
    rarity: 4,
    price: 5400,
    maxDefense: 30,
    skillPoints: { rec_speed: 6, transportr: 2, heat_res: 5 }
  }),
  deepFreeze<WaistArmor>({
    id: 58,
    type: 'waist',
    name: 'Loc Lac Coat+',
    blade: false,
    gunner: true,
    defense: 18,
    fireRes: 5,
    waterRes: -4,
    iceRes: -5,
    thunderRes: 2,
    dragonRes: 0,
    slots: 0,
    rarity: 4,
    price: 5400,
    maxDefense: 18,
    skillPoints: { rec_speed: 6, transportr: 2, heat_res: 5 }
  }),
  deepFreeze<WaistArmor>({
    id: 59,
    type: 'waist',
    name: "Hunter's Faulds+",
    blade: true,
    gunner: false,
    defense: 30,
    fireRes: 0,
    waterRes: -2,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 2,
    rarity: 4,
    price: 5400,
    maxDefense: 30,
    skillPoints: { psychic: 4, evasion: 3, water_res: -1, map: 1 }
  }),
  deepFreeze<WaistArmor>({
    id: 60,
    type: 'waist',
    name: "Hunter's Coat+",
    blade: false,
    gunner: true,
    defense: 18,
    fireRes: 0,
    waterRes: -2,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 2,
    rarity: 4,
    price: 5400,
    maxDefense: 18,
    skillPoints: { psychic: 4, evasion: 2, water_res: -2, map: 1 }
  }),
  deepFreeze<WaistArmor>({
    id: 61,
    type: 'waist',
    name: 'Bone Faulds+',
    blade: true,
    gunner: false,
    defense: 34,
    fireRes: 3,
    waterRes: -2,
    iceRes: -1,
    thunderRes: 2,
    dragonRes: 3,
    slots: 2,
    rarity: 4,
    price: 6400,
    maxDefense: 34,
    skillPoints: { stamina: 3, hunger: 4, sleep: -1, perception: 1 }
  }),
  deepFreeze<WaistArmor>({
    id: 62,
    type: 'waist',
    name: 'Bone Coat+',
    blade: false,
    gunner: true,
    defense: 20,
    fireRes: 3,
    waterRes: -2,
    iceRes: -1,
    thunderRes: 2,
    dragonRes: 3,
    slots: 2,
    rarity: 4,
    price: 6400,
    maxDefense: 20,
    skillPoints: { stamina: 1, hunger: 4, sleep: -1, perception: 3 }
  }),
  deepFreeze<WaistArmor>({
    id: 63,
    type: 'waist',
    name: 'Alloy Faulds+',
    blade: true,
    gunner: false,
    defense: 34,
    fireRes: 1,
    waterRes: 2,
    iceRes: -1,
    thunderRes: -2,
    dragonRes: -1,
    slots: 2,
    rarity: 4,
    price: 7100,
    maxDefense: 34,
    skillPoints: {
      expert: 2,
      sharpener: 3,
      speedsetup: 2,
      oxygen: -2
    }
  }),
  deepFreeze<WaistArmor>({
    id: 64,
    type: 'waist',
    name: 'Alloy Coat+',
    blade: false,
    gunner: true,
    defense: 20,
    fireRes: 1,
    waterRes: 2,
    iceRes: -1,
    thunderRes: -2,
    dragonRes: -1,
    slots: 2,
    rarity: 4,
    price: 7100,
    maxDefense: 20,
    skillPoints: {
      'normal_s+': 3,
      expert: 2,
      speedsetup: 2,
      oxygen: -2
    }
  }),
  deepFreeze<WaistArmor>({
    id: 65,
    type: 'waist',
    name: 'Jaggi Faulds+',
    blade: true,
    gunner: false,
    defense: 38,
    fireRes: -3,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: 2,
    slots: 2,
    rarity: 5,
    price: 8000,
    maxDefense: 38,
    skillPoints: { attack: 2, stun: 3, gluttony: 3, cold_res: -1 }
  }),
  deepFreeze<WaistArmor>({
    id: 66,
    type: 'waist',
    name: 'Jaggi Coat+',
    blade: false,
    gunner: true,
    defense: 22,
    fireRes: -3,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -1,
    dragonRes: 2,
    slots: 2,
    rarity: 5,
    price: 8000,
    maxDefense: 22,
    skillPoints: { attack: 2, stun: 4, gluttony: 1, cold_res: -2 }
  }),
  deepFreeze<WaistArmor>({
    id: 67,
    type: 'waist',
    name: 'Bnahabra Faulds+',
    blade: true,
    gunner: false,
    defense: 38,
    fireRes: -5,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 2,
    dragonRes: 6,
    slots: 1,
    rarity: 5,
    price: 10500,
    maxDefense: 38,
    skillPoints: { sharpness: 3, status: 6, poison: -2 }
  }),
  deepFreeze<WaistArmor>({
    id: 68,
    type: 'waist',
    name: 'Bnahabra Coat+',
    blade: false,
    gunner: true,
    defense: 22,
    fireRes: -5,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 2,
    dragonRes: 6,
    slots: 1,
    rarity: 5,
    price: 10500,
    maxDefense: 22,
    skillPoints: { status: 5, poison: -2, reload_spd: 4 }
  }),
  deepFreeze<WaistArmor>({
    id: 69,
    type: 'waist',
    name: 'Rhenoplos Coil+',
    blade: true,
    gunner: false,
    defense: 38,
    fireRes: 3,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -2,
    dragonRes: 2,
    slots: 2,
    rarity: 5,
    price: 8500,
    maxDefense: 38,
    skillPoints: {
      wind_res: 6,
      eating: 1,
      'mud/snow': 1,
      thunderres: -1
    }
  }),
  deepFreeze<WaistArmor>({
    id: 70,
    type: 'waist',
    name: 'Rhenoplos Coat+',
    blade: false,
    gunner: true,
    defense: 22,
    fireRes: 3,
    waterRes: -1,
    iceRes: -1,
    thunderRes: -2,
    dragonRes: 2,
    slots: 2,
    rarity: 5,
    price: 8500,
    maxDefense: 22,
    skillPoints: {
      recoil: 5,
      'crag_s+': 2,
      eating: 1,
      thunderres: -1
    }
  }),
  deepFreeze<WaistArmor>({
    id: 71,
    type: 'waist',
    name: 'Qurupeco Coil+',
    blade: true,
    gunner: false,
    defense: 42,
    fireRes: 4,
    waterRes: -3,
    iceRes: -4,
    thunderRes: 0,
    dragonRes: 1,
    slots: 1,
    rarity: 5,
    price: 10000,
    maxDefense: 42,
    skillPoints: {
      expert: 1,
      defense: 2,
      'wide-range': 5,
      rec_level: 2,
      ice_res: -1
    }
  }),
  deepFreeze<WaistArmor>({
    id: 72,
    type: 'waist',
    name: 'Qurupeco Coat+',
    blade: false,
    gunner: true,
    defense: 25,
    fireRes: 4,
    waterRes: -3,
    iceRes: -4,
    thunderRes: 0,
    dragonRes: 1,
    slots: 1,
    rarity: 5,
    price: 10000,
    maxDefense: 25,
    skillPoints: {
      expert: 1,
      defense: 2,
      'wide-range': 4,
      rec_level: 3,
      ice_res: -1
    }
  }),
  deepFreeze<WaistArmor>({
    id: 73,
    type: 'waist',
    name: 'Ludroth Faulds+',
    blade: true,
    gunner: false,
    defense: 44,
    fireRes: -4,
    waterRes: 4,
    iceRes: 0,
    thunderRes: -1,
    dragonRes: 1,
    slots: 3,
    rarity: 5,
    price: 11800,
    maxDefense: 44,
    skillPoints: {
      hunger: -3,
      protection: 1,
      constitutn: 2,
      currentres: 1
    }
  }),
  deepFreeze<WaistArmor>({
    id: 74,
    type: 'waist',
    name: 'Ludroth Coat+',
    blade: false,
    gunner: true,
    defense: 26,
    fireRes: -4,
    waterRes: 4,
    iceRes: 0,
    thunderRes: -1,
    dragonRes: 1,
    slots: 3,
    rarity: 5,
    price: 11800,
    maxDefense: 26,
    skillPoints: {
      'pellet_s+': 1,
      hunger: -3,
      protection: 1,
      constitutn: 2
    }
  }),
  deepFreeze<WaistArmor>({
    id: 75,
    type: 'waist',
    name: 'Steel Coil+',
    blade: true,
    gunner: false,
    defense: 42,
    fireRes: -1,
    waterRes: 1,
    iceRes: 1,
    thunderRes: -1,
    dragonRes: 0,
    slots: 1,
    rarity: 5,
    price: 11000,
    maxDefense: 42,
    skillPoints: { sharpener: 4, guard: 4, swimming: -3 }
  }),
  deepFreeze<WaistArmor>({
    id: 76,
    type: 'waist',
    name: 'Baggi Coil+',
    blade: true,
    gunner: false,
    defense: 44,
    fireRes: -4,
    waterRes: -1,
    iceRes: 4,
    thunderRes: -1,
    dragonRes: 1,
    slots: 2,
    rarity: 5,
    price: 12300,
    maxDefense: 44,
    skillPoints: {
      tranquilzr: 2,
      fastcharge: 1,
      expert: 1,
      stun: -1,
      ice_res: 4
    }
  }),
  deepFreeze<WaistArmor>({
    id: 77,
    type: 'waist',
    name: 'Baggi Coat+',
    blade: false,
    gunner: true,
    defense: 26,
    fireRes: -4,
    waterRes: -1,
    iceRes: 4,
    thunderRes: -1,
    dragonRes: 1,
    slots: 2,
    rarity: 5,
    price: 12300,
    maxDefense: 26,
    skillPoints: {
      pellets_up: 2,
      tranquilzr: 1,
      expert: 1,
      stun: -1,
      ice_res: 4
    }
  }),
  deepFreeze<WaistArmor>({
    id: 78,
    type: 'waist',
    name: 'Barroth Faulds+',
    blade: true,
    gunner: false,
    defense: 48,
    fireRes: 5,
    waterRes: -5,
    iceRes: -4,
    thunderRes: 4,
    dragonRes: 0,
    slots: 1,
    rarity: 5,
    price: 13800,
    maxDefense: 48,
    skillPoints: { stamina: 3, expert: -1, attack: 2, potential: 5 }
  }),
  deepFreeze<WaistArmor>({
    id: 79,
    type: 'waist',
    name: 'Barroth Coat+',
    blade: false,
    gunner: true,
    defense: 28,
    fireRes: 5,
    waterRes: -5,
    iceRes: -4,
    thunderRes: 4,
    dragonRes: 0,
    slots: 1,
    rarity: 5,
    price: 13800,
    maxDefense: 28,
    skillPoints: { stamina: 3, expert: -2, attack: 2, potential: 4 }
  }),
  deepFreeze<WaistArmor>({
    id: 80,
    type: 'waist',
    name: 'Gobul Faulds+',
    blade: true,
    gunner: false,
    defense: 50,
    fireRes: -2,
    waterRes: 4,
    iceRes: 0,
    thunderRes: -4,
    dragonRes: 2,
    slots: 1,
    rarity: 5,
    price: 14800,
    maxDefense: 50,
    skillPoints: { rec_speed: -1, expert: 1, eating: 5, stun: 4 }
  }),
  deepFreeze<WaistArmor>({
    id: 81,
    type: 'waist',
    name: 'Gobul Coat+',
    blade: false,
    gunner: true,
    defense: 30,
    fireRes: -2,
    waterRes: 4,
    iceRes: 0,
    thunderRes: -4,
    dragonRes: 2,
    slots: 1,
    rarity: 5,
    price: 14800,
    maxDefense: 30,
    skillPoints: { rec_speed: -1, expert: 1, eating: 5, stun: 4 }
  }),
  deepFreeze<WaistArmor>({
    id: 82,
    type: 'waist',
    name: 'Guild Bard Coil+',
    blade: true,
    gunner: false,
    defense: 36,
    fireRes: 0,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 1,
    rarity: 6,
    price: 25000,
    maxDefense: 36,
    skillPoints: {
      fate: 2,
      carving: 3,
      tranquilzr: 1,
      protection: -5
    }
  }),
  deepFreeze<WaistArmor>({
    id: 83,
    type: 'waist',
    name: 'Guild Bard Coat+',
    blade: false,
    gunner: true,
    defense: 22,
    fireRes: 0,
    waterRes: 0,
    iceRes: 0,
    thunderRes: 0,
    dragonRes: 0,
    slots: 1,
    rarity: 6,
    price: 25000,
    maxDefense: 22,
    skillPoints: {
      fate: 2,
      carving: 2,
      tranquilzr: 2,
      protection: -5
    }
  }),
  deepFreeze<WaistArmor>({
    id: 84,
    type: 'waist',
    name: 'Rathian Faulds+',
    blade: true,
    gunner: false,
    defense: 50,
    fireRes: 4,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 1,
    rarity: 5,
    price: 14800,
    maxDefense: 50,
    skillPoints: {
      hearing: 2,
      health: 4,
      protection: -2,
      fire_res: 3
    }
  }),
  deepFreeze<WaistArmor>({
    id: 85,
    type: 'waist',
    name: 'Rathian Coat+',
    blade: false,
    gunner: true,
    defense: 30,
    fireRes: 4,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 1,
    rarity: 5,
    price: 14800,
    maxDefense: 30,
    skillPoints: {
      hearing: 1,
      health: 5,
      protection: -2,
      fire_res: 3
    }
  }),
  deepFreeze<WaistArmor>({
    id: 86,
    type: 'waist',
    name: 'Gigginox Faulds+',
    blade: true,
    gunner: false,
    defense: 54,
    fireRes: -4,
    waterRes: -1,
    iceRes: 2,
    thunderRes: 3,
    dragonRes: 0,
    slots: 1,
    rarity: 5,
    price: 15800,
    maxDefense: 54,
    skillPoints: { status: 3, poison: 3, health: -1, constitutn: 4 }
  }),
  deepFreeze<WaistArmor>({
    id: 87,
    type: 'waist',
    name: 'Gigginox Coat+',
    blade: false,
    gunner: true,
    defense: 32,
    fireRes: -4,
    waterRes: -1,
    iceRes: 2,
    thunderRes: 3,
    dragonRes: 0,
    slots: 1,
    rarity: 5,
    price: 15800,
    maxDefense: 32,
    skillPoints: { status: 3, poison: 3, health: -1, constitutn: 4 }
  }),
  deepFreeze<WaistArmor>({
    id: 88,
    type: 'waist',
    name: 'Ingot Coil+',
    blade: true,
    gunner: false,
    defense: 54,
    fireRes: -2,
    waterRes: -1,
    iceRes: 1,
    thunderRes: 3,
    dragonRes: 2,
    slots: 3,
    rarity: 5,
    price: 17500,
    maxDefense: 54,
    skillPoints: {
      sharpener: -3,
      guard_up: 2,
      wind_res: 1,
      thunderres: 1
    }
  }),
  deepFreeze<WaistArmor>({
    id: 89,
    type: 'waist',
    name: 'Ingot Coat+',
    blade: false,
    gunner: true,
    defense: 32,
    fireRes: -2,
    waterRes: -1,
    iceRes: 1,
    thunderRes: 3,
    dragonRes: 2,
    slots: 3,
    rarity: 5,
    price: 17500,
    maxDefense: 32,
    skillPoints: {
      recoil: 1,
      guard_up: 2,
      reload_spd: -3,
      thunderres: 1
    }
  }),
  deepFreeze<WaistArmor>({
    id: 90,
    type: 'waist',
    name: 'Dober Coil',
    blade: true,
    gunner: false,
    defense: 58,
    fireRes: -2,
    waterRes: -2,
    iceRes: 1,
    thunderRes: 1,
    dragonRes: 5,
    slots: 1,
    rarity: 6,
    price: 19000,
    maxDefense: 58,
    skillPoints: {
      stamina: 3,
      potential: -1,
      crit_draw: 2,
      dragon_res: 5
    }
  }),
  deepFreeze<WaistArmor>({
    id: 91,
    type: 'waist',
    name: 'Dober Coat',
    blade: false,
    gunner: true,
    defense: 34,
    fireRes: -2,
    waterRes: -2,
    iceRes: 1,
    thunderRes: 1,
    dragonRes: 5,
    slots: 1,
    rarity: 6,
    price: 19000,
    maxDefense: 34,
    skillPoints: {
      pellets_up: 1,
      'pellet_s+': 4,
      potential: -2,
      dragon_res: 4
    }
  }),
  deepFreeze<WaistArmor>({
    id: 92,
    type: 'waist',
    name: 'Lagiacrus Faulds+',
    blade: true,
    gunner: false,
    defense: 58,
    fireRes: -4,
    waterRes: 2,
    iceRes: -1,
    thunderRes: 5,
    dragonRes: -2,
    slots: 2,
    rarity: 6,
    price: 18000,
    maxDefense: 58,
    skillPoints: {
      status: -3,
      elemental: 2,
      freeelemnt: 2,
      swimming: 2
    }
  }),
  deepFreeze<WaistArmor>({
    id: 93,
    type: 'waist',
    name: 'Lagiacrus Coat+',
    blade: false,
    gunner: true,
    defense: 34,
    fireRes: -4,
    waterRes: 2,
    iceRes: -1,
    thunderRes: 5,
    dragonRes: -2,
    slots: 2,
    rarity: 6,
    price: 18000,
    maxDefense: 34,
    skillPoints: {
      status: -3,
      elemental: 2,
      rapid_fire: 2,
      swimming: 2
    }
  }),
  deepFreeze<WaistArmor>({
    id: 94,
    type: 'waist',
    name: 'Rathalos Faulds+',
    blade: true,
    gunner: false,
    defense: 58,
    fireRes: 4,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 1,
    rarity: 6,
    price: 18000,
    maxDefense: 58,
    skillPoints: { fencing: 2, expert: 5, defense: -1, heat_res: 3 }
  }),
  deepFreeze<WaistArmor>({
    id: 95,
    type: 'waist',
    name: 'Rathalos Coat+',
    blade: false,
    gunner: true,
    defense: 34,
    fireRes: 4,
    waterRes: 0,
    iceRes: 0,
    thunderRes: -2,
    dragonRes: -4,
    slots: 1,
    rarity: 6,
    price: 18000,
    maxDefense: 34,
    skillPoints: {
      normals_up: 1,
      expert: 3,
      defense: -3,
      heat_res: 4
    }
  }),
  deepFreeze<WaistArmor>({
    id: 96,
    type: 'waist',
    name: 'Barioth Faulds+',
    blade: true,
    gunner: false,
    defense: 58,
    fireRes: -4,
    waterRes: 2,
    iceRes: 5,
    thunderRes: -3,
    dragonRes: 0,
    slots: 3,
    rarity: 6,
    price: 18000,
    maxDefense: 58,
    skillPoints: {
      evade_dist: 1,
      evasion: 2,
      heat_res: -3,
      cold_res: 1
    }
  }),
  deepFreeze<WaistArmor>({
    id: 97,
    type: 'waist',
    name: 'Barioth Coat+',
    blade: false,
    gunner: true,
    defense: 34,
    fireRes: -4,
    waterRes: 2,
    iceRes: 5,
    thunderRes: -3,
    dragonRes: 0,
    slots: 3,
    rarity: 6,
    price: 18000,
    maxDefense: 34,
    skillPoints: {
      evade_dist: 1,
      evasion: 2,
      heat_res: -3,
      cold_res: 1
    }
  }),
  deepFreeze<WaistArmor>({
    id: 98,
    type: 'waist',
    name: 'Uragaan Faulds+',
    blade: true,
    gunner: false,
    defense: 62,
    fireRes: 4,
    waterRes: -4,
    iceRes: -1,
    thunderRes: 1,
    dragonRes: -2,
    slots: 1,
    rarity: 6,
    price: 18800,
    maxDefense: 62,
    skillPoints: {
      punishdraw: 2,
      bomb_boost: 2,
      defense: 6,
      eating: -1
    }
  }),
  deepFreeze<WaistArmor>({
    id: 99,
    type: 'waist',
    name: 'Uragaan Coat+',
    blade: false,
    gunner: true,
    defense: 37,
    fireRes: 4,
    waterRes: -4,
    iceRes: -1,
    thunderRes: 1,
    dragonRes: -2,
    slots: 1,
    rarity: 6,
    price: 18800,
    maxDefense: 37,
    skillPoints: {
      recoil: 6,
      bomb_boost: 2,
      defense: 2,
      eating: -1
    }
  }),
  deepFreeze<WaistArmor>({
    id: 100,
    type: 'waist',
    name: 'Agnaktor Faulds+',
    blade: true,
    gunner: false,
    defense: 62,
    fireRes: 5,
    waterRes: -4,
    iceRes: -2,
    thunderRes: 1,
    dragonRes: 0,
    slots: 3,
    rarity: 6,
    price: 19800,
    maxDefense: 62,
    skillPoints: {
      sharpness: 2,
      stamina: -3,
      guard: 1,
      flame_aura: 1
    }
  }),
  deepFreeze<WaistArmor>({
    id: 101,
    type: 'waist',
    name: 'Agnaktor Coat+',
    blade: false,
    gunner: true,
    defense: 37,
    fireRes: 5,
    waterRes: -4,
    iceRes: -2,
    thunderRes: 1,
    dragonRes: 0,
    slots: 3,
    rarity: 6,
    price: 19800,
    maxDefense: 37,
    skillPoints: {
      normals_up: 1,
      'normal_s+': 2,
      stamina: -3,
      flame_aura: 1
    }
  }),
  deepFreeze<WaistArmor>({
    id: 102,
    type: 'waist',
    name: 'Vangis Coil',
    blade: true,
    gunner: false,
    defense: 64,
    fireRes: 0,
    waterRes: 0,
    iceRes: 3,
    thunderRes: -4,
    dragonRes: -4,
    slots: 0,
    rarity: 7,
    price: 41500,
    maxDefense: 64,
    skillPoints: {},
    torsoUp: true
  }),
  deepFreeze<WaistArmor>({
    id: 103,
    type: 'waist',
    name: 'Vangis Coat',
    blade: false,
    gunner: true,
    defense: 38,
    fireRes: 0,
    waterRes: 0,
    iceRes: 3,
    thunderRes: -4,
    dragonRes: -4,
    slots: 0,
    rarity: 7,
    price: 41500,
    maxDefense: 38,
    skillPoints: {},
    torsoUp: true
  }),
  deepFreeze<WaistArmor>({
    id: 104,
    type: 'waist',
    name: 'Damascus Coil',
    blade: true,
    gunner: false,
    defense: 62,
    fireRes: -2,
    waterRes: 0,
    iceRes: 2,
    thunderRes: -2,
    dragonRes: 3,
    slots: 1,
    rarity: 6,
    price: 32300,
    maxDefense: 62,
    skillPoints: {
      stamina: -1,
      punishdraw: 3,
      health: 4,
      guard_up: 3
    }
  }),
  deepFreeze<WaistArmor>({
    id: 105,
    type: 'waist',
    name: 'Damascus Coat',
    blade: false,
    gunner: true,
    defense: 37,
    fireRes: -2,
    waterRes: 0,
    iceRes: 2,
    thunderRes: -2,
    dragonRes: 3,
    slots: 1,
    rarity: 6,
    price: 32300,
    maxDefense: 37,
    skillPoints: {
      stamina: -1,
      health: 3,
      guard_up: 4,
      reload_spd: 3
    }
  }),
  deepFreeze<WaistArmor>({
    id: 106,
    type: 'waist',
    name: 'Helios Coil+',
    blade: true,
    gunner: false,
    defense: 66,
    fireRes: 0,
    waterRes: 5,
    iceRes: 3,
    thunderRes: -3,
    dragonRes: -4,
    slots: 3,
    rarity: 6,
    price: 26200,
    maxDefense: 66,
    skillPoints: {
      sharpness: -3,
      handicraft: 2,
      hearing: 1,
      protection: -1
    }
  }),
  deepFreeze<WaistArmor>({
    id: 107,
    type: 'waist',
    name: 'Helios Coat+',
    blade: false,
    gunner: true,
    defense: 39,
    fireRes: 0,
    waterRes: 5,
    iceRes: 3,
    thunderRes: -3,
    dragonRes: -4,
    slots: 3,
    rarity: 6,
    price: 26200,
    maxDefense: 39,
    skillPoints: {
      recoil: -3,
      hearing: 1,
      loading: 2,
      protection: -1
    }
  }),
  deepFreeze<WaistArmor>({
    id: 108,
    type: 'waist',
    name: 'Yamato Koshiate+',
    blade: true,
    gunner: false,
    defense: 66,
    fireRes: 4,
    waterRes: 0,
    iceRes: -3,
    thunderRes: 0,
    dragonRes: -4,
    slots: 1,
    rarity: 6,
    price: 27500,
    maxDefense: 66,
    skillPoints: {
      sharpness: 5,
      fastcharge: 2,
      rec_speed: 3,
      combo_rate: -1
    }
  }),
  deepFreeze<WaistArmor>({
    id: 109,
    type: 'waist',
    name: 'Mutsu Koshiate+',
    blade: false,
    gunner: true,
    defense: 39,
    fireRes: 4,
    waterRes: 0,
    iceRes: -3,
    thunderRes: 0,
    dragonRes: -4,
    slots: 1,
    rarity: 6,
    price: 27500,
    maxDefense: 39,
    skillPoints: {
      recoil: 2,
      rec_speed: 2,
      'clust_s+': 4,
      combo_rate: -3
    }
  }),
  deepFreeze<WaistArmor>({
    id: 110,
    type: 'waist',
    name: 'Escadora Might',
    blade: true,
    gunner: false,
    defense: 70,
    fireRes: -1,
    waterRes: -1,
    iceRes: -1,
    thunderRes: 0,
    dragonRes: -5,
    slots: 2,
    rarity: 7,
    price: 66666,
    maxDefense: 70,
    skillPoints: {
      evade_dist: 3,
      freeelemnt: 2,
      rec_level: -2,
      blight_res: 2
    }
  }),
  deepFreeze<WaistArmor>({
    id: 111,
    type: 'waist',
    name: 'Escadora Force',
    blade: false,
    gunner: true,
    defense: 42,
    fireRes: -1,
    waterRes: -1,
    iceRes: -1,
    thunderRes: 0,
    dragonRes: -5,
    slots: 2,
    rarity: 7,
    price: 66666,
    maxDefense: 42,
    skillPoints: {
      evade_dist: 3,
      rapid_fire: 2,
      rec_level: -2,
      blight_res: 2
    }
  }),
  deepFreeze<WaistArmor>({
    id: 112,
    type: 'waist',
    name: 'Chakra Waistlet',
    blade: true,
    gunner: true,
    defense: 18,
    fireRes: 10,
    waterRes: 0,
    iceRes: -10,
    thunderRes: 0,
    dragonRes: 0,
    slots: 3,
    rarity: 7,
    price: 33333,
    maxDefense: 18,
    skillPoints: {}
  })
];
