/**
 * !RAW
 * This is a "raw" object taken from the archived MH3 stilltruth website.
 * http://web.archive.org/web/20130407144759/http://mhtri.stilltruth.com/
 */
var Guns = {
  Frames: {
    short: "frm",
    weapons: [
      {
        name: "Light Bowgun",
        description:
          "A cheap, lightweight, mass-produced Frame. The best choice for novice Gunners.",
        attack: 60,
        maxattack: 180,
        weight: 10,
        range: 0.9,
        reload: 2,
        recoil: 1,
        deviation: 0,
        folding: false,
        affinity: 0,
        slots: 0,
        rarity: 1,
        shots: {
          normal: [{ clip: 3 }, { clip: 3 }, { clip: 3 }],
          pierce: [{ clip: 2 }, { clip: 0 }, { clip: 0 }],
          pellet: [{ clip: 1, rapid: true }, { clip: 0 }, { clip: 1 }],
          recovery: [{ clip: 2 }, { clip: 0 }],
          poison: [{ clip: 2 }, { clip: 0 }],
          para: [{ clip: 2 }, { clip: 0 }],
          sleep: [{ clip: 2 }, { clip: 0 }],
          flaming: [{ clip: 1 }],
          water: [{ clip: 0 }],
          freeze: [{ clip: 0 }],
          thunder: [{ clip: 0 }],
          crag: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          clust: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          wyvernfire: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          sub: [{ clip: 1 }, { clip: 0 }],
          demon: [{ clip: 1 }, { clip: 0 }],
          armor: [{ clip: 1 }, { clip: 0 }],
          exhaust: [{ clip: 1 }],
          dragon: [{ clip: 0 }],
          slicing: [{ clip: 0 }],
          tranq: [{ clip: 2 }],
          paint: [{ clip: 2 }],
        },
        price: 740,
        create: { "97": 1, "245": 2 },
      },
      {
        name: "Medium Bowgun",
        description:
          "A cheap, mid-weight, mass-produced Frame. Deviates slightly L/R.",
        attack: 72,
        maxattack: 192,
        weight: 25,
        range: 1.0,
        reload: 2,
        recoil: 1,
        deviation: 1,
        devl: true,
        devr: true,
        folding: true,
        affinity: 0,
        slots: 0,
        rarity: 1,
        shots: {
          normal: [{ clip: 3 }, { clip: 3 }, { clip: 0 }],
          pierce: [{ clip: 2 }, { clip: 0 }, { clip: 0 }],
          pellet: [{ clip: 1 }, { clip: 0 }, { clip: 0 }],
          recovery: [{ clip: 2 }, { clip: 0 }],
          poison: [{ clip: 2 }, { clip: 0 }],
          para: [{ clip: 2 }, { clip: 0 }],
          sleep: [{ clip: 2 }, { clip: 0 }],
          flaming: [{ clip: 1 }],
          water: [{ clip: 1 }],
          freeze: [{ clip: 0 }],
          thunder: [{ clip: 0 }],
          crag: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          clust: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          wyvernfire: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          sub: [{ clip: 0 }, { clip: 0 }],
          demon: [{ clip: 1 }, { clip: 0 }],
          armor: [{ clip: 1 }, { clip: 0 }],
          exhaust: [{ clip: 1 }],
          dragon: [{ clip: 0 }],
          slicing: [{ clip: 0 }],
          tranq: [{ clip: 2 }],
          paint: [{ clip: 2 }],
        },
        price: 860,
        create: { "97": 2, "149": 2 },
      },
      {
        name: "Heavy Bowgun",
        description: "A cheap, heavy, mass-produced Frame.",
        attack: 96,
        maxattack: 216,
        weight: 30,
        range: 1.0,
        reload: 1,
        recoil: 1,
        deviation: 1,
        devl: true,
        devr: false,
        folding: true,
        affinity: 0,
        slots: 0,
        rarity: 1,
        shots: {
          normal: [{ clip: 3 }, { clip: 3 }, { clip: 3 }],
          pierce: [{ clip: 2 }, { clip: 0 }, { clip: 0 }],
          pellet: [{ clip: 1 }, { clip: 0 }, { clip: 0 }],
          recovery: [{ clip: 2 }, { clip: 0 }],
          poison: [{ clip: 2 }, { clip: 0 }],
          para: [{ clip: 2 }, { clip: 0 }],
          sleep: [{ clip: 2 }, { clip: 0 }],
          flaming: [{ clip: 1 }],
          water: [{ clip: 0 }],
          freeze: [{ clip: 0 }],
          thunder: [{ clip: 0 }],
          crag: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          clust: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          wyvernfire: [{ clip: 1 }, { clip: 0 }, { clip: 0 }],
          sub: [{ clip: 0 }, { clip: 0 }],
          demon: [{ clip: 0 }, { clip: 0 }],
          armor: [{ clip: 0 }, { clip: 0 }],
          exhaust: [{ clip: 1 }],
          dragon: [{ clip: 0 }],
          slicing: [{ clip: 0 }],
          tranq: [{ clip: 2 }],
          paint: [{ clip: 2 }],
        },
        price: 980,
        create: { "99": 1, "149": 2 },
      },
      {
        name: "Royal Launcher",
        description:
          "The sponge on the body makes this Frame comfy to hold. Take it on underwater hunts!",
        attack: 72,
        maxattack: 192,
        weight: 10,
        range: 0.9,
        reload: 2,
        recoil: 1,
        deviation: 1,
        devl: false,
        devr: true,
        folding: false,
        affinity: 0,
        slots: 0,
        rarity: 2,
        shots: {
          normal: [{ clip: 2 }, { clip: 2 }, { clip: 0 }],
          pierce: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          pellet: [{ clip: 2 }, { clip: 2 }, { clip: 0 }],
          recovery: [{ clip: 2 }, { clip: 0 }],
          poison: [{ clip: 1 }, { clip: 0 }],
          para: [{ clip: 2 }, { clip: 0 }],
          sleep: [{ clip: 0 }, { clip: 0 }],
          flaming: [{ clip: 0 }],
          water: [{ clip: 1 }],
          freeze: [{ clip: 0 }],
          thunder: [{ clip: 0 }],
          crag: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          clust: [{ clip: 1 }, { clip: 0 }, { clip: 0 }],
          wyvernfire: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          sub: [{ clip: 1, rapid: true }, { clip: 0 }],
          demon: [{ clip: 0 }, { clip: 0 }],
          armor: [{ clip: 1 }, { clip: 0 }],
          exhaust: [{ clip: 0 }],
          dragon: [{ clip: 0 }],
          slicing: [{ clip: 0 }],
          tranq: [{ clip: 2 }],
          paint: [{ clip: 2 }],
        },
        price: 3600,
        create: { "289": 3, "97": 2, "291": 2 },
      },
      {
        name: "Jaggid Fire",
        description:
          "The mark of an accomplished Jaggi hunter. Your quest for glory has only just begun...",
        attack: 84,
        maxattack: 204,
        weight: 15,
        range: 1.0,
        reload: 1,
        recoil: 1,
        deviation: 1,
        devl: true,
        devr: true,
        folding: false,
        affinity: 0,
        slots: 0,
        rarity: 2,
        shots: {
          normal: [{ clip: 2 }, { clip: 1 }, { clip: 0 }],
          pierce: [{ clip: 3 }, { clip: 2, rapid: true }, { clip: 0 }],
          pellet: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          recovery: [{ clip: 2 }, { clip: 0 }],
          poison: [{ clip: 0 }, { clip: 0 }],
          para: [{ clip: 0 }, { clip: 0 }],
          sleep: [{ clip: 2 }, { clip: 0 }],
          flaming: [{ clip: 0 }],
          water: [{ clip: 0 }],
          freeze: [{ clip: 0 }],
          thunder: [{ clip: 0 }],
          crag: [{ clip: 0 }, { clip: 1 }, { clip: 0 }],
          clust: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          wyvernfire: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          sub: [{ clip: 0 }, { clip: 0 }],
          demon: [{ clip: 1 }, { clip: 0 }],
          armor: [{ clip: 1 }, { clip: 0 }],
          exhaust: [{ clip: 0 }],
          dragon: [{ clip: 0 }],
          slicing: [{ clip: 1 }],
          tranq: [{ clip: 2 }],
          paint: [{ clip: 2 }],
        },
        price: 3500,
        create: { "281": 2, "277": 3, "182": 4 },
      },
      {
        name: "Tropeco Gun",
        description:
          "An exercise in flamboyance? More reliable than it looks, thankfully.",
        attack: 72,
        maxattack: 192,
        weight: 25,
        range: 1.0,
        reload: 1,
        recoil: 2,
        deviation: 0,
        folding: true,
        affinity: 0,
        slots: 0,
        rarity: 2,
        shots: {
          normal: [{ clip: 3 }, { clip: 3 }, { clip: 3 }],
          pierce: [{ clip: 2 }, { clip: 0 }, { clip: 0 }],
          pellet: [{ clip: 1 }, { clip: 0 }, { clip: 0 }],
          recovery: [{ clip: 2 }, { clip: 0 }],
          poison: [{ clip: 0 }, { clip: 0 }],
          para: [{ clip: 0 }, { clip: 0 }],
          sleep: [{ clip: 2 }, { clip: 0 }],
          flaming: [{ clip: 1 }],
          water: [{ clip: 0 }],
          freeze: [{ clip: 0 }],
          thunder: [{ clip: 0 }],
          crag: [{ clip: 1 }, { clip: 1 }, { clip: 0 }],
          clust: [{ clip: 1 }, { clip: 0 }, { clip: 0 }],
          wyvernfire: [{ clip: 1 }, { clip: 0 }, { clip: 0 }],
          sub: [{ clip: 0 }, { clip: 0 }],
          demon: [{ clip: 0 }, { clip: 1 }],
          armor: [{ clip: 0 }, { clip: 1 }],
          exhaust: [{ clip: 1 }],
          dragon: [{ clip: 0 }],
          slicing: [{ clip: 0 }],
          tranq: [{ clip: 2 }],
          paint: [{ clip: 2 }],
        },
        price: 4200,
        create: { "260": 2, "99": 4, "150": 3 },
      },
      {
        name: "Poison Stinger",
        description:
          "An unsettling Frame built from unsettling things. It's heavier than it looks.",
        attack: 96,
        maxattack: 216,
        weight: 35,
        range: 1.0,
        reload: 1,
        recoil: 1,
        deviation: 0,
        folding: false,
        affinity: 0,
        slots: 0,
        rarity: 3,
        shots: {
          normal: [{ clip: 2 }, { clip: 2 }, { clip: 1 }],
          pierce: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          pellet: [{ clip: 2 }, { clip: 0 }, { clip: 0 }],
          recovery: [{ clip: 2 }, { clip: 0 }],
          poison: [{ clip: 1 }, { clip: 1 }],
          para: [{ clip: 2 }, { clip: 0 }],
          sleep: [{ clip: 0 }, { clip: 0 }],
          flaming: [{ clip: 0 }],
          water: [{ clip: 0 }],
          freeze: [{ clip: 0 }],
          thunder: [{ clip: 0 }],
          crag: [{ clip: 1 }, { clip: 0 }, { clip: 1 }],
          clust: [{ clip: 1 }, { clip: 0 }, { clip: 0 }],
          wyvernfire: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          sub: [{ clip: 0 }, { clip: 0 }],
          demon: [{ clip: 0 }, { clip: 0 }],
          armor: [{ clip: 1 }, { clip: 0 }],
          exhaust: [{ clip: 1 }],
          dragon: [{ clip: 0 }],
          slicing: [{ clip: 0 }],
          tranq: [{ clip: 2 }],
          paint: [{ clip: 2 }],
        },
        price: 4600,
        create: { "264": 2, "265": 2, "314": 1 },
      },
      {
        name: "Agnablaster",
        description:
          "A scarlet Frame whose steamlined body makes it a stylish hit.",
        attack: 120,
        maxattack: 240,
        weight: 35,
        range: 1.1,
        reload: 0,
        recoil: 1,
        deviation: 2,
        devl: true,
        devr: false,
        folding: true,
        affinity: 0,
        slots: 0,
        rarity: 3,
        shots: {
          normal: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          pierce: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          pellet: [{ clip: 2 }, { clip: 0 }, { clip: 2 }],
          recovery: [{ clip: 2 }, { clip: 0 }],
          poison: [{ clip: 0 }, { clip: 0 }],
          para: [{ clip: 0 }, { clip: 0 }],
          sleep: [{ clip: 0 }, { clip: 0 }],
          flaming: [{ clip: 1 }],
          water: [{ clip: 0 }],
          freeze: [{ clip: 0 }],
          thunder: [{ clip: 0 }],
          crag: [{ clip: 0 }, { clip: 1 }, { clip: 0 }],
          clust: [{ clip: 0 }, { clip: 1 }, { clip: 1 }],
          wyvernfire: [{ clip: 0 }, { clip: 1 }, { clip: 0 }],
          sub: [{ clip: 0 }, { clip: 0 }],
          demon: [{ clip: 0 }, { clip: 0 }],
          armor: [{ clip: 0 }, { clip: 1 }],
          exhaust: [{ clip: 1 }],
          dragon: [{ clip: 1 }],
          slicing: [{ clip: 1 }],
          tranq: [{ clip: 2 }],
          paint: [{ clip: 2 }],
        },
        price: 5100,
        create: { "382": 3, "386": 2, "104": 1 },
      },
      {
        name: "Thundacrus Rex",
        description:
          "The Frame you've been waiting for, made from the finest Lagiacrus materials!",
        attack: 156,
        maxattack: 204,
        weight: 20,
        range: 1.0,
        reload: 2,
        recoil: 1,
        deviation: 1,
        devl: true,
        devr: false,
        folding: false,
        affinity: 10,
        slots: 0,
        rarity: 4,
        shots: {
          normal: [{ clip: 2 }, { clip: 1 }, { clip: 0 }],
          pierce: [{ clip: 3 }, { clip: 2 }, { clip: 0 }],
          pellet: [{ clip: 1 }, { clip: 1 }, { clip: 0 }],
          recovery: [{ clip: 0 }, { clip: 2 }],
          poison: [{ clip: 1 }, { clip: 0 }],
          para: [{ clip: 0 }, { clip: 2 }],
          sleep: [{ clip: 0 }, { clip: 0 }],
          flaming: [{ clip: 0 }],
          water: [{ clip: 1 }],
          freeze: [{ clip: 0 }],
          thunder: [{ clip: 1 }],
          crag: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          clust: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          wyvernfire: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          sub: [{ clip: 1 }, { clip: 1 }],
          demon: [{ clip: 0 }, { clip: 1 }],
          armor: [{ clip: 1 }, { clip: 0 }],
          exhaust: [{ clip: 1 }],
          dragon: [{ clip: 0 }],
          slicing: [{ clip: 1 }],
          tranq: [{ clip: 2 }],
          paint: [{ clip: 2 }],
        },
        price: 6800,
        create: { "467": 7, "465": 14, "419": 3, "170": 8 },
      },
      {
        name: "Rathling Gun+",
        description:
          "A Frame made possible by superior Rathalos materials. Less accuracy, more power.",
        attack: 144,
        maxattack: 216,
        weight: 25,
        range: 1.0,
        reload: 1,
        recoil: 2,
        deviation: 1,
        devl: true,
        devr: true,
        folding: false,
        affinity: 0,
        slots: 0,
        rarity: 5,
        shots: {
          normal: [{ clip: 2 }, { clip: 1 }, { clip: 2 }],
          pierce: [{ clip: 3 }, { clip: 2 }, { clip: 0 }],
          pellet: [{ clip: 1 }, { clip: 1 }, { clip: 0 }],
          recovery: [{ clip: 0 }, { clip: 2 }],
          poison: [{ clip: 0 }, { clip: 1 }],
          para: [{ clip: 2 }, { clip: 0 }],
          sleep: [{ clip: 0 }, { clip: 0 }],
          flaming: [{ clip: 1 }],
          water: [{ clip: 0 }],
          freeze: [{ clip: 0 }],
          thunder: [{ clip: 0 }],
          crag: [{ clip: 1 }, { clip: 1 }, { clip: 0 }],
          clust: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          wyvernfire: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          sub: [{ clip: 0 }, { clip: 0 }],
          demon: [{ clip: 0 }, { clip: 1 }],
          armor: [{ clip: 0 }, { clip: 1 }],
          exhaust: [{ clip: 0 }],
          dragon: [{ clip: 1 }],
          slicing: [{ clip: 1 }],
          tranq: [{ clip: 2 }],
          paint: [{ clip: 2 }],
        },
        price: 7400,
        create: { "164": 4, "353": 4, "101": 2, "258": 5 },
      },
      {
        name: "Blizzard Cannon",
        description:
          "A powerful, snow-white Frame made of Barioth materials. Excels at Critical Hits.",
        attack: 132,
        maxattack: 192,
        weight: 30,
        range: 1.0,
        reload: 2,
        recoil: 1,
        deviation: 2,
        devl: false,
        devr: true,
        folding: false,
        affinity: 20,
        slots: 0,
        rarity: 4,
        shots: {
          normal: [{ clip: 0 }, { clip: 1 }, { clip: 2 }],
          pierce: [{ clip: 0 }, { clip: 2 }, { clip: 2 }],
          pellet: [{ clip: 0 }, { clip: 0 }, { clip: 1 }],
          recovery: [{ clip: 0 }, { clip: 2 }],
          poison: [{ clip: 0 }, { clip: 0 }],
          para: [{ clip: 0 }, { clip: 0 }],
          sleep: [{ clip: 2 }, { clip: 2 }],
          flaming: [{ clip: 0 }],
          water: [{ clip: 1 }],
          freeze: [{ clip: 1 }],
          thunder: [{ clip: 0 }],
          crag: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          clust: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          wyvernfire: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          sub: [{ clip: 0 }, { clip: 0 }],
          demon: [{ clip: 1 }, { clip: 0 }],
          armor: [{ clip: 0 }, { clip: 0 }],
          exhaust: [{ clip: 0 }],
          dragon: [{ clip: 1 }],
          slicing: [{ clip: 1 }],
          tranq: [{ clip: 2 }],
          paint: [{ clip: 2 }],
        },
        price: 8800,
        create: { "417": 4, "514": 10, "420": 4, "376": 3 },
      },
      {
        name: "Devil's Grin",
        description:
          "A baleful Frame said to have been crafted in a dark workshop.",
        attack: 156,
        maxattack: 240,
        weight: 45,
        range: 0.9,
        reload: 1,
        recoil: 1,
        deviation: 2,
        devl: true,
        devr: true,
        folding: false,
        affinity: -10,
        slots: 0,
        rarity: 6,
        shots: {
          normal: [{ clip: 0 }, { clip: 2 }, { clip: 1 }],
          pierce: [{ clip: 0 }, { clip: 1 }, { clip: 1 }],
          pellet: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          recovery: [{ clip: 0 }, { clip: 0 }],
          poison: [{ clip: 0 }, { clip: 0 }],
          para: [{ clip: 0 }, { clip: 0 }],
          sleep: [{ clip: 0 }, { clip: 0 }],
          flaming: [{ clip: 0 }],
          water: [{ clip: 0 }],
          freeze: [{ clip: 0 }],
          thunder: [{ clip: 0 }],
          crag: [{ clip: 0 }, { clip: 0 }, { clip: 1 }],
          clust: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          wyvernfire: [{ clip: 1 }, { clip: 0 }, { clip: 2 }],
          sub: [{ clip: 0 }, { clip: 0 }],
          demon: [{ clip: 0 }, { clip: 1 }],
          armor: [{ clip: 0 }, { clip: 1 }],
          exhaust: [{ clip: 1 }],
          dragon: [{ clip: 1 }],
          slicing: [{ clip: 0 }],
          tranq: [{ clip: 2 }],
          paint: [{ clip: 2 }],
        },
        price: 9600,
        create: { "449": 4, "450": 6, "153": 9, "453": 1 },
      },
      {
        name: "Diablazooka",
        description:
          "A majestic Frame with two giant horns, popular among pro Gunners.",
        attack: 168,
        maxattack: 204,
        weight: 20,
        range: 1.0,
        reload: 1,
        recoil: 1,
        deviation: 2,
        devl: true,
        devr: false,
        folding: true,
        affinity: 10,
        slots: 0,
        rarity: 5,
        shots: {
          normal: [{ clip: 2 }, { clip: 0 }, { clip: 2 }],
          pierce: [{ clip: 0 }, { clip: 2 }, { clip: 2 }],
          pellet: [{ clip: 0 }, { clip: 1, rapid: true }, { clip: 0 }],
          recovery: [{ clip: 0 }, { clip: 0 }],
          poison: [{ clip: 0 }, { clip: 0 }],
          para: [{ clip: 0 }, { clip: 0 }],
          sleep: [{ clip: 0 }, { clip: 0 }],
          flaming: [{ clip: 0 }],
          water: [{ clip: 0 }],
          freeze: [{ clip: 0 }],
          thunder: [{ clip: 0 }],
          crag: [{ clip: 0 }, { clip: 1 }, { clip: 0 }],
          clust: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          wyvernfire: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          sub: [{ clip: 0 }, { clip: 0 }],
          demon: [{ clip: 0 }, { clip: 1 }],
          armor: [{ clip: 0 }, { clip: 0 }],
          exhaust: [{ clip: 0 }],
          dragon: [{ clip: 1 }],
          slicing: [{ clip: 1 }],
          tranq: [{ clip: 2 }],
          paint: [{ clip: 2 }],
        },
        price: 4400,
        create: { "424": 1, "422": 5, "269": 6, "102": 4 },
      },
      {
        name: "Chaos Wing",
        description:
          "The ultimate weapon, complete with dreadful Alatreon wings.",
        attack: 168,
        maxattack: 252,
        weight: 45,
        range: 1.2,
        reload: 0,
        recoil: 2,
        deviation: 2,
        devl: false,
        devr: true,
        folding: true,
        affinity: 10,
        slots: 0,
        rarity: 7,
        shots: {
          normal: [{ clip: 0 }, { clip: 3 }, { clip: 3 }],
          pierce: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          pellet: [{ clip: 0 }, { clip: 1 }, { clip: 1 }],
          recovery: [{ clip: 0 }, { clip: 2 }],
          poison: [{ clip: 0 }, { clip: 0 }],
          para: [{ clip: 0 }, { clip: 0 }],
          sleep: [{ clip: 0 }, { clip: 0 }],
          flaming: [{ clip: 1 }],
          water: [{ clip: 1 }],
          freeze: [{ clip: 1 }],
          thunder: [{ clip: 1 }],
          crag: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          clust: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          wyvernfire: [{ clip: 0 }, { clip: 0 }, { clip: 1 }],
          sub: [{ clip: 0 }, { clip: 1 }],
          demon: [{ clip: 0 }, { clip: 1 }],
          armor: [{ clip: 0 }, { clip: 1 }],
          exhaust: [{ clip: 1 }],
          dragon: [{ clip: 0 }],
          slicing: [{ clip: 0 }],
          tranq: [{ clip: 2 }],
          paint: [{ clip: 2 }],
        },
        price: 14200,
        create: { "478": 2, "401": 5, "403": 1, "148": 6 },
      },
      {
        name: "Jhen Cannon",
        description:
          "A stately frame made of Jhen Mohran parts. Heavy and tough to use.",
        attack: 144,
        maxattack: 228,
        weight: 50,
        range: 1.1,
        reload: 1,
        recoil: 1,
        deviation: 0,
        folding: true,
        affinity: 0,
        slots: 0,
        rarity: 6,
        shots: {
          normal: [{ clip: 2 }, { clip: 1 }, { clip: 2 }],
          pierce: [{ clip: 0 }, { clip: 2 }, { clip: 0 }],
          pellet: [{ clip: 0 }, { clip: 1 }, { clip: 0 }],
          recovery: [{ clip: 0 }, { clip: 2 }],
          poison: [{ clip: 0 }, { clip: 0 }],
          para: [{ clip: 0 }, { clip: 2 }],
          sleep: [{ clip: 0 }, { clip: 0 }],
          flaming: [{ clip: 0 }],
          water: [{ clip: 0 }],
          freeze: [{ clip: 0 }],
          thunder: [{ clip: 0 }],
          crag: [{ clip: 0 }, { clip: 1 }, { clip: 1 }],
          clust: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          wyvernfire: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          sub: [{ clip: 0 }, { clip: 0 }],
          demon: [{ clip: 0 }, { clip: 0 }],
          armor: [{ clip: 0 }, { clip: 1 }],
          exhaust: [{ clip: 1 }],
          dragon: [{ clip: 1 }],
          slicing: [{ clip: 0 }],
          tranq: [{ clip: 2 }],
          paint: [{ clip: 2 }],
        },
        price: 8800,
        create: { "438": 2, "433": 8, "103": 4, "432": 1 },
      },
      {
        name: 'Aquamatic "Spark"',
        description:
          "A Light Bowgun kit. Parts can't be changed, but it has special qualities.",
        attack: 108,
        maxattack: 228,
        weight: 25,
        range: 0.8,
        reload: 2,
        recoil: 1,
        deviation: 2,
        devl: true,
        devr: true,
        folding: false,
        affinity: 0,
        slots: 0,
        rarity: 3,
        shots: {
          normal: [{ clip: 3 }, { clip: 4 }, { clip: 0 }],
          pierce: [{ clip: 4 }, { clip: 0 }, { clip: 0 }],
          pellet: [{ clip: 0 }, { clip: 0 }, { clip: 2 }],
          recovery: [{ clip: 0 }, { clip: 2 }],
          poison: [{ clip: 0 }, { clip: 2 }],
          para: [{ clip: 2 }, { clip: 0 }],
          sleep: [{ clip: 2 }, { clip: 0 }],
          flaming: [{ clip: 0 }],
          water: [{ clip: 0 }],
          freeze: [{ clip: 0 }],
          thunder: [{ clip: 0 }],
          crag: [{ clip: 2, rapid: true }, { clip: 0 }, { clip: 0 }],
          clust: [{ clip: 0 }, { clip: 1 }, { clip: 0 }],
          wyvernfire: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          sub: [{ clip: 0 }, { clip: 0 }],
          demon: [{ clip: 0 }, { clip: 0 }],
          armor: [{ clip: 1 }, { clip: 0 }],
          exhaust: [{ clip: 0 }],
          dragon: [{ clip: 0 }],
          slicing: [{ clip: 0 }],
          tranq: [{ clip: 2 }],
          paint: [{ clip: 2 }],
        },
        price: 0,
        create: { "108": 1 },
      },
      {
        name: 'Aquamatic "Longshot"',
        description:
          "A Medium Bowgun Kit. Parts of it can't be changed, but it has special qualities.",
        attack: 108,
        maxattack: 240,
        weight: 46,
        range: 1.1,
        reload: 1,
        recoil: 2,
        deviation: 0,
        folding: true,
        affinity: 0,
        slots: 0,
        rarity: 6,
        shots: {
          normal: [{ clip: 5 }, { clip: 5 }, { clip: 0 }],
          pierce: [{ clip: 2 }, { clip: 0 }, { clip: 2 }],
          pellet: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          recovery: [{ clip: 2 }, { clip: 0 }],
          poison: [{ clip: 0 }, { clip: 0 }],
          para: [{ clip: 0 }, { clip: 2 }],
          sleep: [{ clip: 0 }, { clip: 0 }],
          flaming: [{ clip: 0 }],
          water: [{ clip: 0 }],
          freeze: [{ clip: 0 }],
          thunder: [{ clip: 0 }],
          crag: [{ clip: 0 }, { clip: 2 }, { clip: 1 }],
          clust: [{ clip: 1, rapid: true }, { clip: 0 }, { clip: 0 }],
          wyvernfire: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          sub: [{ clip: 0 }, { clip: 0 }],
          demon: [{ clip: 1 }, { clip: 0 }],
          armor: [{ clip: 0 }, { clip: 1 }],
          exhaust: [{ clip: 0 }],
          dragon: [{ clip: 0 }],
          slicing: [{ clip: 0 }],
          tranq: [{ clip: 2 }],
          paint: [{ clip: 2 }],
        },
        price: 30000,
        create: { "553": 1, "550": 2, "552": 2 },
      },
      {
        name: "Vulcannon",
        description:
          "A Heavy Bowgun Kit. Parts can't be changed, but it has special qualities.",
        attack: 252,
        maxattack: 300,
        weight: 72,
        range: 1.0,
        reload: 0,
        recoil: 3,
        deviation: 1,
        devl: false,
        devr: true,
        folding: true,
        affinity: 0,
        slots: 0,
        rarity: 7,
        shots: {
          normal: [{ clip: 6 }, { clip: 7 }, { clip: 3 }],
          pierce: [{ clip: 0 }, { clip: 4 }, { clip: 0 }],
          pellet: [{ clip: 2 }, { clip: 1 }, { clip: 0 }],
          recovery: [{ clip: 2 }, { clip: 0 }],
          poison: [{ clip: 0 }, { clip: 0 }],
          para: [{ clip: 0 }, { clip: 0 }],
          sleep: [{ clip: 0 }, { clip: 0 }],
          flaming: [{ clip: 4 }],
          water: [{ clip: 0 }],
          freeze: [{ clip: 3 }],
          thunder: [{ clip: 2 }],
          crag: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          clust: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          wyvernfire: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          sub: [{ clip: 0 }, { clip: 0 }],
          demon: [{ clip: 0 }, { clip: 0 }],
          armor: [{ clip: 1 }, { clip: 0 }],
          exhaust: [{ clip: 0 }],
          dragon: [{ clip: 0 }],
          slicing: [{ clip: 0 }],
          tranq: [{ clip: 2 }],
          paint: [{ clip: 2 }],
        },
        price: 30000,
        create: { "555": 4, "553": 2, "578": 2 },
      },
    ],
  },
  Barrels: {
    short: "brl",
    weapons: [
      {
        name: "Light Bowgun",
        description:
          "A cheap, lightweight, mass-produced Barrel. Slightly decreases Deviation.",
        attack: 48,
        weight: 10,
        range: 1.0,
        deviation: -1,
        shield: false,
        affinity: 0,
        slots: 0,
        rarity: 1,
        shots: {
          normal: [{ clip: 2 }, { clip: 1, rapid: true }, { clip: 0 }],
          pierce: [{ clip: 2 }, { clip: 0 }, { clip: 0 }],
          pellet: [{ clip: 0 }, { clip: 1 }, { clip: 0 }],
          recovery: [{ clip: 0 }, { clip: 0 }],
          poison: [{ clip: 1 }, { clip: 0 }],
          para: [{ clip: 0 }, { clip: 2 }],
          sleep: [{ clip: 0 }, { clip: 0 }],
          flaming: [{ clip: 0 }],
          water: [{ clip: 0 }],
          freeze: [{ clip: 0 }],
          thunder: [{ clip: 0 }],
          crag: [{ clip: 1 }, { clip: 0 }, { clip: 0 }],
          clust: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          wyvernfire: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          sub: [{ clip: 0 }, { clip: 0 }],
          demon: [{ clip: 0 }, { clip: 0 }],
          armor: [{ clip: 0 }, { clip: 0 }],
          exhaust: [{ clip: 0 }],
          dragon: [{ clip: 0 }],
          slicing: [{ clip: 0 }],
          tranq: [{ clip: 0 }],
          paint: [{ clip: 0 }],
        },
        price: 430,
        create: { "97": 1, "245": 2, "98": 1 },
      },
      {
        name: "Medium Bowgun",
        description:
          "A cheap, mid-weight, mass-produced Barrel. Slightly decreases Deviation.",
        attack: 72,
        weight: 20,
        range: 1.1,
        deviation: -1,
        shield: false,
        affinity: 0,
        slots: 0,
        rarity: 1,
        shots: {
          normal: [{ clip: 2, rapid: true }, { clip: 1 }, { clip: 2 }],
          pierce: [{ clip: 1 }, { clip: 2 }, { clip: 1 }],
          pellet: [{ clip: 0 }, { clip: 1 }, { clip: 1 }],
          recovery: [{ clip: 0 }, { clip: 0 }],
          poison: [{ clip: 1 }, { clip: 0 }],
          para: [{ clip: 1 }, { clip: 0 }],
          sleep: [{ clip: 0 }, { clip: 0 }],
          flaming: [{ clip: 0 }],
          water: [{ clip: 0 }],
          freeze: [{ clip: 0 }],
          thunder: [{ clip: 0 }],
          crag: [{ clip: 1 }, { clip: 0 }, { clip: 0 }],
          clust: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          wyvernfire: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          sub: [{ clip: 0 }, { clip: 0 }],
          demon: [{ clip: 0 }, { clip: 0 }],
          armor: [{ clip: 0 }, { clip: 0 }],
          exhaust: [{ clip: 0 }],
          dragon: [{ clip: 0 }],
          slicing: [{ clip: 0 }],
          tranq: [{ clip: 0 }],
          paint: [{ clip: 0 }],
        },
        price: 520,
        create: { "97": 1, "245": 1, "98": 2 },
      },
      {
        name: "Heavy Bowgun",
        description:
          "A cheap, heavy, mass-produced Barrel. Allows you to block.",
        attack: 84,
        weight: 25,
        range: 1.2,
        deviation: 0,
        shield: true,
        affinity: 0,
        slots: 0,
        rarity: 1,
        shots: {
          normal: [{ clip: 2 }, { clip: 2 }, { clip: 0 }],
          pierce: [{ clip: 1 }, { clip: 1 }, { clip: 0 }],
          pellet: [{ clip: 2 }, { clip: 1 }, { clip: 1 }],
          recovery: [{ clip: 0 }, { clip: 0 }],
          poison: [{ clip: 1 }, { clip: 0 }],
          para: [{ clip: 3 }, { clip: 0 }],
          sleep: [{ clip: 0 }, { clip: 0 }],
          flaming: [{ clip: 0 }],
          water: [{ clip: 0 }],
          freeze: [{ clip: 0 }],
          thunder: [{ clip: 0 }],
          crag: [{ clip: 1 }, { clip: 0 }, { clip: 0 }],
          clust: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          wyvernfire: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          sub: [{ clip: 0 }, { clip: 0 }],
          demon: [{ clip: 0 }, { clip: 0 }],
          armor: [{ clip: 0 }, { clip: 0 }],
          exhaust: [{ clip: 0 }],
          dragon: [{ clip: 0 }],
          slicing: [{ clip: 0 }],
          tranq: [{ clip: 0 }],
          paint: [{ clip: 0 }],
        },
        price: 660,
        create: { "99": 2, "149": 2 },
      },
      {
        name: 'Aquamatic "Needler"',
        description:
          "An odd Barrel that may have once been a full Bowgun Kit. Works well enough in combat.",
        attack: 96,
        weight: 5,
        range: 1.0,
        deviation: -2,
        shield: false,
        affinity: 0,
        slots: 1,
        rarity: 3,
        shots: {
          normal: [{ clip: 2 }, { clip: 2 }, { clip: 0 }],
          pierce: [{ clip: 0 }, { clip: 2 }, { clip: 0 }],
          pellet: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          recovery: [{ clip: 0 }, { clip: 0 }],
          poison: [{ clip: 0 }, { clip: 0 }],
          para: [{ clip: 0 }, { clip: 0 }],
          sleep: [{ clip: 0 }, { clip: 0 }],
          flaming: [{ clip: 0 }],
          water: [{ clip: 0 }],
          freeze: [{ clip: 0 }],
          thunder: [{ clip: 0 }],
          crag: [{ clip: 0, rapid: true }, { clip: 2 }, { clip: 1 }],
          clust: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          wyvernfire: [{ clip: 2 }, { clip: 0 }, { clip: 0 }],
          sub: [{ clip: 0 }, { clip: 0 }],
          demon: [{ clip: 0 }, { clip: 0 }],
          armor: [{ clip: 0 }, { clip: 0 }],
          exhaust: [{ clip: 0 }],
          dragon: [{ clip: 0 }],
          slicing: [{ clip: 0 }],
          tranq: [{ clip: 0 }],
          paint: [{ clip: 0 }],
        },
        price: 5600,
        create: { "584": 1, "102": 4, "252": 1, "145": 3 },
      },
      {
        name: "Royal Launcher",
        description:
          "A Barrel capable of rapid-fire Water Shots. Favored by many Gunners for its portability.",
        attack: 84,
        weight: 5,
        range: 1.0,
        deviation: -1,
        shield: false,
        affinity: 0,
        slots: 0,
        rarity: 2,
        shots: {
          normal: [{ clip: 2 }, { clip: 2 }, { clip: 0 }],
          pierce: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          pellet: [{ clip: 2 }, { clip: 0 }, { clip: 0 }],
          recovery: [{ clip: 0 }, { clip: 0 }],
          poison: [{ clip: 0 }, { clip: 0 }],
          para: [{ clip: 0 }, { clip: 0 }],
          sleep: [{ clip: 0 }, { clip: 0 }],
          flaming: [{ clip: 0 }],
          water: [{ clip: 2, rapid: true }],
          freeze: [{ clip: 0 }],
          thunder: [{ clip: 0 }],
          crag: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          clust: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          wyvernfire: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          sub: [{ clip: 1 }, { clip: 2 }],
          demon: [{ clip: 0 }, { clip: 0 }],
          armor: [{ clip: 1 }, { clip: 0 }],
          exhaust: [{ clip: 0 }],
          dragon: [{ clip: 0 }],
          slicing: [{ clip: 0 }],
          tranq: [{ clip: 0 }],
          paint: [{ clip: 0 }],
        },
        price: 3600,
        create: { "290": 3, "291": 1, "149": 4, "371": 1 },
      },
      {
        name: "Jaggid Fire",
        description:
          "The mark of an accomplished Jaggi hunter. Your quest for glory has only just begun...",
        attack: 72,
        weight: 10,
        range: 0.8,
        deviation: 0,
        shield: false,
        affinity: 10,
        slots: 1,
        rarity: 2,
        shots: {
          normal: [{ clip: 4 }, { clip: 3 }, { clip: 0 }],
          pierce: [{ clip: 2, rapid: true }, { clip: 2 }, { clip: 2 }],
          pellet: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          recovery: [{ clip: 0 }, { clip: 0 }],
          poison: [{ clip: 0 }, { clip: 0 }],
          para: [{ clip: 0 }, { clip: 0 }],
          sleep: [{ clip: 2 }, { clip: 0 }],
          flaming: [{ clip: 0 }],
          water: [{ clip: 0 }],
          freeze: [{ clip: 0 }],
          thunder: [{ clip: 0 }],
          crag: [{ clip: 0 }, { clip: 1 }, { clip: 0 }],
          clust: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          wyvernfire: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          sub: [{ clip: 0 }, { clip: 0 }],
          demon: [{ clip: 1 }, { clip: 0 }],
          armor: [{ clip: 0 }, { clip: 0 }],
          exhaust: [{ clip: 2 }],
          dragon: [{ clip: 0 }],
          slicing: [{ clip: 2 }],
          tranq: [{ clip: 0 }],
          paint: [{ clip: 0 }],
        },
        price: 3500,
        create: { "388": 1, "280": 3, "279": 4, "97": 2 },
      },
      {
        name: "Tropeco Gun",
        description:
          "An exercise in flamboyance? More reliable than it looks, thankfully.",
        attack: 84,
        weight: 10,
        range: 0.9,
        deviation: -1,
        shield: false,
        affinity: 0,
        slots: 0,
        rarity: 2,
        shots: {
          normal: [{ clip: 2 }, { clip: 0 }, { clip: 2 }],
          pierce: [{ clip: 1 }, { clip: 0 }, { clip: 2 }],
          pellet: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          recovery: [{ clip: 0, rapid: true }, { clip: 0 }],
          poison: [{ clip: 2 }, { clip: 0 }],
          para: [{ clip: 0 }, { clip: 0 }],
          sleep: [{ clip: 2 }, { clip: 0 }],
          flaming: [{ clip: 2 }],
          water: [{ clip: 0 }],
          freeze: [{ clip: 0 }],
          thunder: [{ clip: 0 }],
          crag: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          clust: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          wyvernfire: [{ clip: 1 }, { clip: 0 }, { clip: 0 }],
          sub: [{ clip: 0 }, { clip: 0 }],
          demon: [{ clip: 1 }, { clip: 0 }],
          armor: [{ clip: 0 }, { clip: 0 }],
          exhaust: [{ clip: 0 }],
          dragon: [{ clip: 0 }],
          slicing: [{ clip: 0 }],
          tranq: [{ clip: 0 }],
          paint: [{ clip: 0 }],
        },
        price: 4200,
        create: { "263": 1, "261": 4, "260": 2, "150": 2 },
      },
      {
        name: "Barrozooka",
        description:
          "One for the power-hungry: Pretty? No. Well-rounded? Nope. Destructive? HELL yes!",
        attack: 120,
        weight: 35,
        range: 0.6,
        deviation: 2,
        shield: true,
        affinity: 0,
        slots: 1,
        rarity: 2,
        shots: {
          normal: [{ clip: 3 }, { clip: 4 }, { clip: 2 }],
          pierce: [{ clip: 3 }, { clip: 2 }, { clip: 0 }],
          pellet: [{ clip: 3 }, { clip: 0 }, { clip: 0 }],
          recovery: [{ clip: 0 }, { clip: 0 }],
          poison: [{ clip: 0 }, { clip: 0 }],
          para: [{ clip: 0 }, { clip: 0 }],
          sleep: [{ clip: 0 }, { clip: 0 }],
          flaming: [{ clip: 0 }],
          water: [{ clip: 0 }],
          freeze: [{ clip: 0 }],
          thunder: [{ clip: 0 }],
          crag: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          clust: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          wyvernfire: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          sub: [{ clip: 0 }, { clip: 0 }],
          demon: [{ clip: 0 }, { clip: 0 }],
          armor: [{ clip: 0 }, { clip: 0 }],
          exhaust: [{ clip: 2 }],
          dragon: [{ clip: 0 }],
          slicing: [{ clip: 0 }],
          tranq: [{ clip: 0 }],
          paint: [{ clip: 0 }],
        },
        price: 5300,
        create: { "276": 3, "272": 2, "99": 4 },
      },
      {
        name: "Thundacrus",
        description:
          "A stable Barrel crafted from Lagiacrus materials, which allow for more firepower.",
        attack: 108,
        weight: 15,
        range: 1.0,
        deviation: -1,
        shield: false,
        affinity: 0,
        slots: 1,
        rarity: 3,
        shots: {
          normal: [{ clip: 0 }, { clip: 2 }, { clip: 0 }],
          pierce: [{ clip: 0 }, { clip: 3 }, { clip: 0 }],
          pellet: [{ clip: 2 }, { clip: 0 }, { clip: 0 }],
          recovery: [{ clip: 0 }, { clip: 0 }],
          poison: [{ clip: 0 }, { clip: 0 }],
          para: [{ clip: 0 }, { clip: 0 }],
          sleep: [{ clip: 0 }, { clip: 0 }],
          flaming: [{ clip: 0 }],
          water: [{ clip: 0 }],
          freeze: [{ clip: 0 }],
          thunder: [{ clip: 2, rapid: true }],
          crag: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          clust: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          wyvernfire: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          sub: [{ clip: 0 }, { clip: 2 }],
          demon: [{ clip: 0 }, { clip: 0 }],
          armor: [{ clip: 1 }, { clip: 0 }],
          exhaust: [{ clip: 0 }],
          dragon: [{ clip: 0 }],
          slicing: [{ clip: 1 }],
          tranq: [{ clip: 0 }],
          paint: [{ clip: 0 }],
        },
        price: 4500,
        create: { "283": 3, "102": 5, "391": 2 },
      },
      {
        name: "Thundacrus Rex",
        description:
          "A slightly tweaked Barrel made from only the finest Lagiacrus materials.",
        attack: 108,
        weight: 15,
        range: 1.1,
        deviation: 0,
        shield: false,
        affinity: 0,
        slots: 1,
        rarity: 4,
        shots: {
          normal: [{ clip: 0 }, { clip: 3 }, { clip: 2 }],
          pierce: [{ clip: 0 }, { clip: 3 }, { clip: 0 }],
          pellet: [{ clip: 2 }, { clip: 0 }, { clip: 0 }],
          recovery: [{ clip: 0 }, { clip: 0 }],
          poison: [{ clip: 0 }, { clip: 0 }],
          para: [{ clip: 0 }, { clip: 0 }],
          sleep: [{ clip: 0 }, { clip: 0 }],
          flaming: [{ clip: 0 }],
          water: [{ clip: 0 }],
          freeze: [{ clip: 0, rapid: true }],
          thunder: [{ clip: 1 }],
          crag: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          clust: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          wyvernfire: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          sub: [{ clip: 0 }, { clip: 2 }],
          demon: [{ clip: 0 }, { clip: 0 }],
          armor: [{ clip: 1 }, { clip: 0 }],
          exhaust: [{ clip: 0 }],
          dragon: [{ clip: 0 }],
          slicing: [{ clip: 1 }],
          tranq: [{ clip: 0 }],
          paint: [{ clip: 0 }],
        },
        price: 6800,
        create: { "465": 6, "103": 3, "469": 1, "170": 4 },
      },
      {
        name: "Bloodguilty Maw",
        description:
          "Opinions differ on the bizarre appearance of this poison-equipped Barrel.",
        attack: 84,
        weight: 15,
        range: 0.9,
        deviation: 0,
        shield: false,
        affinity: 0,
        slots: 1,
        rarity: 2,
        shots: {
          normal: [{ clip: 2 }, { clip: 0 }, { clip: 1 }],
          pierce: [{ clip: 1 }, { clip: 1 }, { clip: 0 }],
          pellet: [{ clip: 1 }, { clip: 0 }, { clip: 2 }],
          recovery: [{ clip: 1 }, { clip: 0 }],
          poison: [{ clip: 3, rapid: true }, { clip: 2 }],
          para: [{ clip: 0 }, { clip: 0 }],
          sleep: [{ clip: 0 }, { clip: 0 }],
          flaming: [{ clip: 0 }],
          water: [{ clip: 0 }],
          freeze: [{ clip: 0 }],
          thunder: [{ clip: 0 }],
          crag: [{ clip: 0 }, { clip: 0 }, { clip: 1 }],
          clust: [{ clip: 1 }, { clip: 0 }, { clip: 0 }],
          wyvernfire: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          sub: [{ clip: 0 }, { clip: 0 }],
          demon: [{ clip: 0 }, { clip: 0 }],
          armor: [{ clip: 1 }, { clip: 0 }],
          exhaust: [{ clip: 1 }],
          dragon: [{ clip: 2 }],
          slicing: [{ clip: 0 }],
          tranq: [{ clip: 0 }],
          paint: [{ clip: 0 }],
        },
        price: 4600,
        create: { "168": 1, "267": 3, "529": 10, "530": 5 },
      },
      {
        name: "Rathling Gun",
        description:
          "A Barrel made with Rathalos materials, featuring a dignified design to match.",
        attack: 96,
        weight: 25,
        range: 1.0,
        deviation: -1,
        shield: true,
        affinity: 0,
        slots: 1,
        rarity: 3,
        shots: {
          normal: [{ clip: 2 }, { clip: 0 }, { clip: 3 }],
          pierce: [{ clip: 0 }, { clip: 1 }, { clip: 0 }],
          pellet: [{ clip: 2 }, { clip: 0 }, { clip: 0 }],
          recovery: [{ clip: 0 }, { clip: 0 }],
          poison: [{ clip: 0 }, { clip: 0 }],
          para: [{ clip: 0 }, { clip: 0 }],
          sleep: [{ clip: 0 }, { clip: 0 }],
          flaming: [{ clip: 2 }],
          water: [{ clip: 0 }],
          freeze: [{ clip: 0 }],
          thunder: [{ clip: 0 }],
          crag: [{ clip: 0 }, { clip: 2 }, { clip: 0 }],
          clust: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          wyvernfire: [{ clip: 0 }, { clip: 0 }, { clip: 2 }],
          sub: [{ clip: 0 }, { clip: 0 }],
          demon: [{ clip: 0 }, { clip: 1 }],
          armor: [{ clip: 0 }, { clip: 0 }],
          exhaust: [{ clip: 0 }],
          dragon: [{ clip: 2 }],
          slicing: [{ clip: 0 }],
          tranq: [{ clip: 0 }],
          paint: [{ clip: 0 }],
        },
        price: 5200,
        create: { "255": 3, "330": 20, "102": 4, "258": 1 },
      },
      {
        name: "Rathling Gun+",
        description:
          "A more capable Barrel that uses Rathalos materials of superior quality.",
        attack: 108,
        weight: 20,
        range: 1.0,
        deviation: -1,
        shield: false,
        affinity: 0,
        slots: 1,
        rarity: 5,
        shots: {
          normal: [{ clip: 2 }, { clip: 0 }, { clip: 2 }],
          pierce: [{ clip: 0 }, { clip: 2 }, { clip: 0 }],
          pellet: [{ clip: 1 }, { clip: 0 }, { clip: 0 }],
          recovery: [{ clip: 0 }, { clip: 0 }],
          poison: [{ clip: 0 }, { clip: 0 }],
          para: [{ clip: 0 }, { clip: 0 }],
          sleep: [{ clip: 0 }, { clip: 0 }],
          flaming: [{ clip: 1, rapid: true }],
          water: [{ clip: 0 }],
          freeze: [{ clip: 0 }],
          thunder: [{ clip: 0 }],
          crag: [{ clip: 0 }, { clip: 2 }, { clip: 0 }],
          clust: [{ clip: 0 }, { clip: 1 }, { clip: 0 }],
          wyvernfire: [{ clip: 0 }, { clip: 1 }, { clip: 0 }],
          sub: [{ clip: 0 }, { clip: 0 }],
          demon: [{ clip: 0 }, { clip: 1 }],
          armor: [{ clip: 0 }, { clip: 0 }],
          exhaust: [{ clip: 0 }],
          dragon: [{ clip: 2 }],
          slicing: [{ clip: 0 }],
          tranq: [{ clip: 0 }],
          paint: [{ clip: 0 }],
        },
        price: 7900,
        create: { "164": 18, "162": 8, "103": 8, "161": 1 },
      },
      {
        name: "Devil's Grin",
        description:
          "A baleful Barrel said to have been crafted in a dark workshop.",
        attack: 144,
        weight: 25,
        range: 0.8,
        deviation: -1,
        shield: true,
        affinity: -10,
        slots: 1,
        rarity: 6,
        shots: {
          normal: [{ clip: 0 }, { clip: 3 }, { clip: 4 }],
          pierce: [{ clip: 0 }, { clip: 2 }, { clip: 3 }],
          pellet: [{ clip: 0 }, { clip: 0 }, { clip: 3 }],
          recovery: [{ clip: 0 }, { clip: 0 }],
          poison: [{ clip: 0 }, { clip: 0 }],
          para: [{ clip: 0 }, { clip: 0 }],
          sleep: [{ clip: 0 }, { clip: 0 }],
          flaming: [{ clip: 0 }],
          water: [{ clip: 0 }],
          freeze: [{ clip: 0 }],
          thunder: [{ clip: 0 }],
          crag: [{ clip: 0 }, { clip: 0 }, { clip: 2 }],
          clust: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          wyvernfire: [{ clip: 3 }, { clip: 0 }, { clip: 0 }],
          sub: [{ clip: 0 }, { clip: 0 }],
          demon: [{ clip: 0 }, { clip: 1 }],
          armor: [{ clip: 1 }, { clip: 0 }],
          exhaust: [{ clip: 1 }],
          dragon: [{ clip: 1 }],
          slicing: [{ clip: 0 }],
          tranq: [{ clip: 0 }],
          paint: [{ clip: 0 }],
        },
        price: 9600,
        create: { "454": 1, "452": 4, "451": 8, "148": 12 },
      },
      {
        name: "Diablazooka",
        description:
          "A strong Barrel but, much like its namesake, hard to handle. Allows you to block.",
        attack: 132,
        weight: 40,
        range: 0.7,
        deviation: 2,
        shield: true,
        affinity: -10,
        slots: 0,
        rarity: 5,
        shots: {
          normal: [{ clip: 3 }, { clip: 4 }, { clip: 1 }],
          pierce: [{ clip: 4 }, { clip: 2 }, { clip: 0 }],
          pellet: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          recovery: [{ clip: 0 }, { clip: 0 }],
          poison: [{ clip: 0 }, { clip: 0 }],
          para: [{ clip: 0 }, { clip: 0 }],
          sleep: [{ clip: 0 }, { clip: 0 }],
          flaming: [{ clip: 0 }],
          water: [{ clip: 0 }],
          freeze: [{ clip: 0 }],
          thunder: [{ clip: 0 }],
          crag: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          clust: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          wyvernfire: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          sub: [{ clip: 0 }, { clip: 0 }],
          demon: [{ clip: 0 }, { clip: 0 }],
          armor: [{ clip: 1 }, { clip: 0 }],
          exhaust: [{ clip: 0 }],
          dragon: [{ clip: 0 }],
          slicing: [{ clip: 0 }],
          tranq: [{ clip: 0 }],
          paint: [{ clip: 0 }],
        },
        price: 8100,
        create: { "423": 1, "422": 3, "421": 2, "101": 16 },
      },
      {
        name: "Chaos Wing",
        description: "undefined",
        attack: 120,
        weight: 10,
        range: 0.9,
        deviation: -1,
        shield: false,
        affinity: 0,
        slots: 0,
        rarity: 7,
        shots: {
          normal: [{ clip: 0 }, { clip: 4 }, { clip: 0 }],
          pierce: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          pellet: [{ clip: 0 }, { clip: 0 }, { clip: 2 }],
          recovery: [{ clip: 0 }, { clip: 0 }],
          poison: [{ clip: 0 }, { clip: 0 }],
          para: [{ clip: 0 }, { clip: 0 }],
          sleep: [{ clip: 0 }, { clip: 0 }],
          flaming: [{ clip: 2 }],
          water: [{ clip: 2 }],
          freeze: [{ clip: 2 }],
          thunder: [{ clip: 2 }],
          crag: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          clust: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          wyvernfire: [{ clip: 0 }, { clip: 0 }, { clip: 3 }],
          sub: [{ clip: 0 }, { clip: 0 }],
          demon: [{ clip: 0 }, { clip: 0 }],
          armor: [{ clip: 0 }, { clip: 0 }],
          exhaust: [{ clip: 0 }],
          dragon: [{ clip: 0, rapid: true }],
          slicing: [{ clip: 0 }],
          tranq: [{ clip: 0 }],
          paint: [{ clip: 0 }],
        },
        price: 14200,
        create: { "405": 1, "476": 3, "401": 4, "432": 3 },
      },
      {
        name: "Jhen Cannon",
        description:
          "A stately Barrel made of Jhen Mohran materials. Heavy and tough to use.",
        attack: 132,
        weight: 30,
        range: 1.0,
        deviation: -2,
        shield: true,
        affinity: 0,
        slots: 1,
        rarity: 6,
        shots: {
          normal: [{ clip: 2 }, { clip: 5 }, { clip: 0 }],
          pierce: [{ clip: 0 }, { clip: 0 }, { clip: 3 }],
          pellet: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          recovery: [{ clip: 0 }, { clip: 0 }],
          poison: [{ clip: 0 }, { clip: 0 }],
          para: [{ clip: 0 }, { clip: 0 }],
          sleep: [{ clip: 0 }, { clip: 2 }],
          flaming: [{ clip: 0 }],
          water: [{ clip: 0 }],
          freeze: [{ clip: 0 }],
          thunder: [{ clip: 0 }],
          crag: [{ clip: 0 }, { clip: 0 }, { clip: 2 }],
          clust: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          wyvernfire: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          sub: [{ clip: 0 }, { clip: 2 }],
          demon: [{ clip: 0 }, { clip: 0 }],
          armor: [{ clip: 0 }, { clip: 0 }],
          exhaust: [{ clip: 0 }],
          dragon: [{ clip: 3 }],
          slicing: [{ clip: 0 }],
          tranq: [{ clip: 0 }],
          paint: [{ clip: 0 }],
        },
        price: 8800,
        create: { "439": 14, "440": 1, "103": 8, "430": 1 },
      },
      {
        name: 'Aquamatic "Spark"',
        description:
          "A Light Bowgun kit. Parts can't be changed, but it has special qualities.",
        attack: 120,
        weight: 1,
        range: 1.0,
        deviation: -1,
        shield: false,
        affinity: 0,
        slots: 0,
        rarity: 6,
        shots: {
          normal: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          pierce: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          pellet: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          recovery: [{ clip: 0 }, { clip: 0 }],
          poison: [{ clip: 0 }, { clip: 0 }],
          para: [{ clip: 0 }, { clip: 0 }],
          sleep: [{ clip: 0 }, { clip: 0 }],
          flaming: [{ clip: 0 }],
          water: [{ clip: 0 }],
          freeze: [{ clip: 0 }],
          thunder: [{ clip: 0 }],
          crag: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          clust: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          wyvernfire: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          sub: [{ clip: 0 }, { clip: 0 }],
          demon: [{ clip: 0 }, { clip: 0 }],
          armor: [{ clip: 0 }, { clip: 0 }],
          exhaust: [{ clip: 0 }],
          dragon: [{ clip: 0 }],
          slicing: [{ clip: 0 }],
          tranq: [{ clip: 0 }],
          paint: [{ clip: 0 }],
        },
        price: 0,
        create: {},
      },
      {
        name: 'Aquamatic "Longshot"',
        description:
          "A Medium Bowgun Kit. Parts of it can't be changed, but it has special qualities.",
        attack: 120,
        weight: 1,
        range: 1.1,
        deviation: -1,
        shield: false,
        affinity: 0,
        slots: 0,
        rarity: 6,
        shots: {
          normal: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          pierce: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          pellet: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          recovery: [{ clip: 0 }, { clip: 0 }],
          poison: [{ clip: 0 }, { clip: 0 }],
          para: [{ clip: 0 }, { clip: 0 }],
          sleep: [{ clip: 0 }, { clip: 0 }],
          flaming: [{ clip: 0 }],
          water: [{ clip: 0 }],
          freeze: [{ clip: 0 }],
          thunder: [{ clip: 0 }],
          crag: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          clust: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          wyvernfire: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          sub: [{ clip: 0 }, { clip: 0 }],
          demon: [{ clip: 0 }, { clip: 0 }],
          armor: [{ clip: 0 }, { clip: 0 }],
          exhaust: [{ clip: 0 }],
          dragon: [{ clip: 0 }],
          slicing: [{ clip: 0 }],
          tranq: [{ clip: 0 }],
          paint: [{ clip: 0 }],
        },
        price: 0,
        create: {},
      },
      {
        name: "Vulcannon",
        description:
          "A Heavy Bowgun Kit. Parts can't be changed, but it has special qualities.",
        attack: 120,
        weight: 1,
        range: 1.2,
        deviation: -1,
        shield: true,
        affinity: 0,
        slots: 0,
        rarity: 6,
        shots: {
          normal: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          pierce: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          pellet: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          recovery: [{ clip: 0 }, { clip: 0 }],
          poison: [{ clip: 0 }, { clip: 0 }],
          para: [{ clip: 0 }, { clip: 0 }],
          sleep: [{ clip: 0 }, { clip: 0 }],
          flaming: [{ clip: 0 }],
          water: [{ clip: 0 }],
          freeze: [{ clip: 0 }],
          thunder: [{ clip: 0 }],
          crag: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          clust: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          wyvernfire: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          sub: [{ clip: 0 }, { clip: 0 }],
          demon: [{ clip: 0 }, { clip: 0 }],
          armor: [{ clip: 0 }, { clip: 0 }],
          exhaust: [{ clip: 0 }],
          dragon: [{ clip: 0 }],
          slicing: [{ clip: 0 }],
          tranq: [{ clip: 0 }],
          paint: [{ clip: 0 }],
        },
        price: 0,
        create: {},
      },
    ],
  },
  Stocks: {
    short: "stk",
    weapons: [
      {
        name: "Light Bowgun",
        description:
          "This ultra-light Stock features a quick reload speed. A popular choice.",
        weight: 5,
        reload: 1,
        recoil: 0,
        affinity: 0,
        slots: 2,
        rarity: 1,
        shots: {
          normal: [{ clip: 1 }, { clip: 2 }, { clip: 0 }],
          pierce: [{ clip: 0 }, { clip: 1 }, { clip: 0 }],
          pellet: [{ clip: 2 }, { clip: 1 }, { clip: 0 }],
          recovery: [{ clip: 1 }, { clip: 0 }],
          poison: [{ clip: 2 }, { clip: 0 }],
          para: [{ clip: 1 }, { clip: 0 }],
          sleep: [{ clip: 1 }, { clip: 0 }],
          flaming: [{ clip: 0 }],
          water: [{ clip: 0 }],
          freeze: [{ clip: 0 }],
          thunder: [{ clip: 0 }],
          crag: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          clust: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          wyvernfire: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          sub: [{ clip: 0 }, { clip: 0 }],
          demon: [{ clip: 0 }, { clip: 0 }],
          armor: [{ clip: 0 }, { clip: 0 }],
          exhaust: [{ clip: 0 }],
          dragon: [{ clip: 0 }],
          slicing: [{ clip: 0 }],
          tranq: [{ clip: 0 }],
          paint: [{ clip: 0 }],
        },
        price: 430,
        create: { "97": 1, "245": 2, "98": 2 },
      },
      {
        name: "Medium Bowgun",
        description:
          "A mid-weight Stock with a lightning-fast reload speed. Simple and easy to use.",
        weight: 10,
        reload: 2,
        recoil: 1,
        affinity: 0,
        slots: 0,
        rarity: 1,
        shots: {
          normal: [{ clip: 1 }, { clip: 2 }, { clip: 1 }],
          pierce: [{ clip: 0 }, { clip: 1 }, { clip: 0 }],
          pellet: [{ clip: 1 }, { clip: 2 }, { clip: 0 }],
          recovery: [{ clip: 1 }, { clip: 0 }],
          poison: [{ clip: 0 }, { clip: 0 }],
          para: [{ clip: 0 }, { clip: 0 }],
          sleep: [{ clip: 1 }, { clip: 0 }],
          flaming: [{ clip: 0 }],
          water: [{ clip: 0 }],
          freeze: [{ clip: 0 }],
          thunder: [{ clip: 0 }],
          crag: [{ clip: 0 }, { clip: 1 }, { clip: 0 }],
          clust: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          wyvernfire: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          sub: [{ clip: 0 }, { clip: 0 }],
          demon: [{ clip: 0 }, { clip: 0 }],
          armor: [{ clip: 0 }, { clip: 0 }],
          exhaust: [{ clip: 0 }],
          dragon: [{ clip: 0 }],
          slicing: [{ clip: 0 }],
          tranq: [{ clip: 0 }],
          paint: [{ clip: 0 }],
        },
        price: 520,
        create: { "97": 1, "149": 2, "98": 1 },
      },
      {
        name: "Heavy Bowgun",
        description:
          "Heavy, but supports a wider variety of ammo types. For more experienced Gunners.",
        defense: 10,
        weight: 20,
        reload: 1,
        recoil: 1,
        affinity: 0,
        slots: 0,
        rarity: 1,
        shots: {
          normal: [{ clip: 2 }, { clip: 1 }, { clip: 1 }],
          pierce: [{ clip: 0 }, { clip: 1 }, { clip: 0 }],
          pellet: [{ clip: 1 }, { clip: 1 }, { clip: 1 }],
          recovery: [{ clip: 1 }, { clip: 0 }],
          poison: [{ clip: 0 }, { clip: 0 }],
          para: [{ clip: 0 }, { clip: 0 }],
          sleep: [{ clip: 3 }, { clip: 0 }],
          flaming: [{ clip: 0 }],
          water: [{ clip: 0 }],
          freeze: [{ clip: 0 }],
          thunder: [{ clip: 0 }],
          crag: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          clust: [{ clip: 1 }, { clip: 0 }, { clip: 0 }],
          wyvernfire: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          sub: [{ clip: 0 }, { clip: 0 }],
          demon: [{ clip: 0 }, { clip: 0 }],
          armor: [{ clip: 0 }, { clip: 0 }],
          exhaust: [{ clip: 0 }],
          dragon: [{ clip: 0 }],
          slicing: [{ clip: 0 }],
          tranq: [{ clip: 0 }],
          paint: [{ clip: 0 }],
        },
        price: 660,
        create: { "99": 2, "149": 2 },
      },
      {
        name: 'Aquamatic "Needler"',
        description:
          "An odd Stock that may once have been a full Bowgun Kit. Works well enough in combat.",
        weight: 15,
        reload: 1,
        recoil: 1,
        affinity: 10,
        slots: 1,
        rarity: 3,
        shots: {
          normal: [{ clip: 0 }, { clip: 3 }, { clip: 0 }],
          pierce: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          pellet: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          recovery: [{ clip: 0 }, { clip: 0 }],
          poison: [{ clip: 0 }, { clip: 0 }],
          para: [{ clip: 0 }, { clip: 0 }],
          sleep: [{ clip: 2 }, { clip: 0 }],
          flaming: [{ clip: 0 }],
          water: [{ clip: 0 }],
          freeze: [{ clip: 0 }],
          thunder: [{ clip: 0 }],
          crag: [{ clip: 2 }, { clip: 0 }, { clip: 0 }],
          clust: [{ clip: 2 }, { clip: 0 }, { clip: 2 }],
          wyvernfire: [{ clip: 0 }, { clip: 1 }, { clip: 0 }],
          sub: [{ clip: 0 }, { clip: 0 }],
          demon: [{ clip: 1 }, { clip: 0 }],
          armor: [{ clip: 1 }, { clip: 0 }],
          exhaust: [{ clip: 0 }],
          dragon: [{ clip: 3 }],
          slicing: [{ clip: 0 }],
          tranq: [{ clip: 0 }],
          paint: [{ clip: 0 }],
        },
        price: 5600,
        create: { "583": 1, "102": 3, "225": 1, "151": 4 },
      },
      {
        name: "Royal Launcher",
        description:
          "The sponge on the body makes this Stock comfy to hold. Take it on underwater hunts!",
        weight: 5,
        reload: 1,
        recoil: 1,
        affinity: 0,
        slots: 0,
        rarity: 2,
        shots: {
          normal: [{ clip: 3 }, { clip: 0 }, { clip: 0 }],
          pierce: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          pellet: [{ clip: 0 }, { clip: 2 }, { clip: 0 }],
          recovery: [{ clip: 0 }, { clip: 0 }],
          poison: [{ clip: 0 }, { clip: 0 }],
          para: [{ clip: 0 }, { clip: 0 }],
          sleep: [{ clip: 0 }, { clip: 0 }],
          flaming: [{ clip: 0 }],
          water: [{ clip: 2 }],
          freeze: [{ clip: 0 }],
          thunder: [{ clip: 0 }],
          crag: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          clust: [{ clip: 1 }, { clip: 0 }, { clip: 0 }],
          wyvernfire: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          sub: [{ clip: 2 }, { clip: 0 }],
          demon: [{ clip: 0 }, { clip: 0 }],
          armor: [{ clip: 1 }, { clip: 0 }],
          exhaust: [{ clip: 2 }],
          dragon: [{ clip: 0 }],
          slicing: [{ clip: 0 }],
          tranq: [{ clip: 0 }],
          paint: [{ clip: 0 }],
        },
        price: 3600,
        create: { "295": 3, "294": 2, "99": 2, "182": 5 },
      },
      {
        name: "Tropeco Gun",
        description:
          "An exercise in flamboyance? More reliable than it looks, thankfully.",
        weight: 25,
        reload: 1,
        recoil: 2,
        affinity: 0,
        slots: 0,
        rarity: 2,
        shots: {
          normal: [{ clip: 3 }, { clip: 2 }, { clip: 0 }],
          pierce: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          pellet: [{ clip: 2 }, { clip: 0 }, { clip: 0 }],
          recovery: [{ clip: 0 }, { clip: 0 }],
          poison: [{ clip: 0 }, { clip: 0 }],
          para: [{ clip: 2 }, { clip: 0 }],
          sleep: [{ clip: 1 }, { clip: 0 }],
          flaming: [{ clip: 2 }],
          water: [{ clip: 0 }],
          freeze: [{ clip: 0 }],
          thunder: [{ clip: 0 }],
          crag: [{ clip: 1 }, { clip: 0 }, { clip: 0 }],
          clust: [{ clip: 0 }, { clip: 0 }, { clip: 1 }],
          wyvernfire: [{ clip: 1 }, { clip: 0 }, { clip: 0 }],
          sub: [{ clip: 0 }, { clip: 0 }],
          demon: [{ clip: 0 }, { clip: 0 }],
          armor: [{ clip: 1 }, { clip: 0 }],
          exhaust: [{ clip: 0 }],
          dragon: [{ clip: 0 }],
          slicing: [{ clip: 0 }],
          tranq: [{ clip: 1 }],
          paint: [{ clip: 0 }],
        },
        price: 4200,
        create: { "261": 2, "262": 2, "99": 1, "149": 8 },
      },
      {
        name: "Thundacrus",
        description:
          "A stable Stock crafted from Lagiacrus mmaterials, which allow for more firepower.",
        weight: 10,
        reload: 1,
        recoil: 2,
        affinity: 0,
        slots: 2,
        rarity: 3,
        shots: {
          normal: [{ clip: 3 }, { clip: 0 }, { clip: 3 }],
          pierce: [{ clip: 2 }, { clip: 0 }, { clip: 0 }],
          pellet: [{ clip: 0 }, { clip: 2 }, { clip: 0 }],
          recovery: [{ clip: 0 }, { clip: 0 }],
          poison: [{ clip: 0 }, { clip: 0 }],
          para: [{ clip: 0 }, { clip: 0 }],
          sleep: [{ clip: 0 }, { clip: 0 }],
          flaming: [{ clip: 0 }],
          water: [{ clip: 2 }],
          freeze: [{ clip: 0 }],
          thunder: [{ clip: 2 }],
          crag: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          clust: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          wyvernfire: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          sub: [{ clip: 2 }, { clip: 0 }],
          demon: [{ clip: 0 }, { clip: 1 }],
          armor: [{ clip: 0 }, { clip: 0 }],
          exhaust: [{ clip: 0 }],
          dragon: [{ clip: 0 }],
          slicing: [{ clip: 0 }],
          tranq: [{ clip: 0 }],
          paint: [{ clip: 0 }],
        },
        price: 4500,
        create: { "284": 4, "102": 2, "288": 1, "287": 1 },
      },
      {
        name: "Thundracrus Rex",
        description:
          "A slightly tweaked Stock made from only the finest Lagiacrus materials.",
        weight: 10,
        reload: 1,
        recoil: 1,
        affinity: 0,
        slots: 2,
        rarity: 4,
        shots: {
          normal: [{ clip: 4 }, { clip: 0 }, { clip: 2 }],
          pierce: [{ clip: 0 }, { clip: 2 }, { clip: 0 }],
          pellet: [{ clip: 0 }, { clip: 2 }, { clip: 0 }],
          recovery: [{ clip: 0 }, { clip: 0 }],
          poison: [{ clip: 0 }, { clip: 0 }],
          para: [{ clip: 0 }, { clip: 1 }],
          sleep: [{ clip: 0 }, { clip: 0 }],
          flaming: [{ clip: 0 }],
          water: [{ clip: 0 }],
          freeze: [{ clip: 1 }],
          thunder: [{ clip: 2 }],
          crag: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          clust: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          wyvernfire: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          sub: [{ clip: 2 }, { clip: 0 }],
          demon: [{ clip: 0 }, { clip: 1 }],
          armor: [{ clip: 0 }, { clip: 1 }],
          exhaust: [{ clip: 0 }],
          dragon: [{ clip: 0 }],
          slicing: [{ clip: 0 }],
          tranq: [{ clip: 0 }],
          paint: [{ clip: 0 }],
        },
        price: 6800,
        create: { "466": 8, "100": 12, "288": 3, "287": 6 },
      },
      {
        name: "Poison Stinger",
        description:
          "An unsettling Stock built from unsettling things. It's heavier than it looks.",
        defense: 10,
        weight: 25,
        reload: 1,
        recoil: 1,
        affinity: 0,
        slots: 1,
        rarity: 3,
        shots: {
          normal: [{ clip: 2 }, { clip: 2 }, { clip: 2 }],
          pierce: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          pellet: [{ clip: 2 }, { clip: 2 }, { clip: 0 }],
          recovery: [{ clip: 0 }, { clip: 0 }],
          poison: [{ clip: 1 }, { clip: 3 }],
          para: [{ clip: 0 }, { clip: 0 }],
          sleep: [{ clip: 0 }, { clip: 0 }],
          flaming: [{ clip: 0 }],
          water: [{ clip: 0 }],
          freeze: [{ clip: 1 }],
          thunder: [{ clip: 0 }],
          crag: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          clust: [{ clip: 2 }, { clip: 0 }, { clip: 0 }],
          wyvernfire: [{ clip: 0 }, { clip: 2 }, { clip: 0 }],
          sub: [{ clip: 0 }, { clip: 0 }],
          demon: [{ clip: 0 }, { clip: 0 }],
          armor: [{ clip: 0 }, { clip: 0 }],
          exhaust: [{ clip: 2 }],
          dragon: [{ clip: 2 }],
          slicing: [{ clip: 0 }],
          tranq: [{ clip: 0 }],
          paint: [{ clip: 0 }],
        },
        price: 4600,
        create: { "265": 3, "100": 2, "330": 15, "150": 10 },
      },
      {
        name: "Rathling Gun",
        description:
          "A Stock made with Rathalos materials (and featuring a dignified design to match).",
        weight: 10,
        reload: 1,
        recoil: 2,
        affinity: 0,
        slots: 2,
        rarity: 3,
        shots: {
          normal: [{ clip: 2 }, { clip: 2 }, { clip: 1 }],
          pierce: [{ clip: 0 }, { clip: 1 }, { clip: 0 }],
          pellet: [{ clip: 0 }, { clip: 2 }, { clip: 0 }],
          recovery: [{ clip: 0 }, { clip: 0 }],
          poison: [{ clip: 1 }, { clip: 0 }],
          para: [{ clip: 1 }, { clip: 0 }],
          sleep: [{ clip: 0 }, { clip: 0 }],
          flaming: [{ clip: 2 }],
          water: [{ clip: 0 }],
          freeze: [{ clip: 0 }],
          thunder: [{ clip: 0 }],
          crag: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          clust: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          wyvernfire: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          sub: [{ clip: 0 }, { clip: 0 }],
          demon: [{ clip: 0 }, { clip: 0 }],
          armor: [{ clip: 0 }, { clip: 1 }],
          exhaust: [{ clip: 0 }],
          dragon: [{ clip: 2 }],
          slicing: [{ clip: 2 }],
          tranq: [{ clip: 0 }],
          paint: [{ clip: 0 }],
        },
        price: 5200,
        create: { "254": 5, "151": 1, "257": 2, "259": 2 },
      },
      {
        name: "Rathling Gun+",
        description:
          "A more capable Stock that uses Rathalos materials of superior quality.",
        defense: 10,
        weight: 5,
        reload: 1,
        recoil: 1,
        affinity: 0,
        slots: 2,
        rarity: 5,
        shots: {
          normal: [{ clip: 1 }, { clip: 2 }, { clip: 2 }],
          pierce: [{ clip: 0 }, { clip: 1 }, { clip: 0 }],
          pellet: [{ clip: 0 }, { clip: 3 }, { clip: 0 }],
          recovery: [{ clip: 0 }, { clip: 0 }],
          poison: [{ clip: 1 }, { clip: 0 }],
          para: [{ clip: 1 }, { clip: 0 }],
          sleep: [{ clip: 0 }, { clip: 0 }],
          flaming: [{ clip: 2 }],
          water: [{ clip: 0 }],
          freeze: [{ clip: 0 }],
          thunder: [{ clip: 0 }],
          crag: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          clust: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          wyvernfire: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          sub: [{ clip: 0 }, { clip: 0 }],
          demon: [{ clip: 0 }, { clip: 0 }],
          armor: [{ clip: 0 }, { clip: 1 }],
          exhaust: [{ clip: 0 }],
          dragon: [{ clip: 3 }],
          slicing: [{ clip: 2 }],
          tranq: [{ clip: 0 }],
          paint: [{ clip: 0 }],
        },
        price: 7900,
        create: { "163": 10, "151": 10, "158": 2, "259": 4 },
      },
      {
        name: "Agnablaster",
        description:
          "Resembles an Agnaktor taking a dip in lava. It's still a bit warm to the touch.",
        weight: 30,
        reload: 1,
        recoil: 0,
        affinity: 0,
        slots: 2,
        rarity: 3,
        shots: {
          normal: [{ clip: 4 }, { clip: 0 }, { clip: 0 }],
          pierce: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          pellet: [{ clip: 0 }, { clip: 2 }, { clip: 0 }],
          recovery: [{ clip: 0 }, { clip: 0 }],
          poison: [{ clip: 0 }, { clip: 0 }],
          para: [{ clip: 0 }, { clip: 0 }],
          sleep: [{ clip: 0 }, { clip: 0 }],
          flaming: [{ clip: 4 }],
          water: [{ clip: 0 }],
          freeze: [{ clip: 0 }],
          thunder: [{ clip: 0 }],
          crag: [{ clip: 0 }, { clip: 0 }, { clip: 2 }],
          clust: [{ clip: 0 }, { clip: 2 }, { clip: 0 }],
          wyvernfire: [{ clip: 0 }, { clip: 2 }, { clip: 0 }],
          sub: [{ clip: 0 }, { clip: 0 }],
          demon: [{ clip: 1 }, { clip: 0 }],
          armor: [{ clip: 1 }, { clip: 0 }],
          exhaust: [{ clip: 2 }],
          dragon: [{ clip: 2 }],
          slicing: [{ clip: 0 }],
          tranq: [{ clip: 0 }],
          paint: [{ clip: 0 }],
        },
        price: 5100,
        create: { "382": 3, "384": 2, "104": 5, "151": 2 },
      },
      {
        name: "Blizzard Cannon",
        description:
          "A snow-white Stock made of Barioth materials. Much, much lighter than it looks.",
        weight: 5,
        reload: 2,
        recoil: 0,
        affinity: 0,
        slots: 0,
        rarity: 4,
        shots: {
          normal: [{ clip: 0 }, { clip: 3 }, { clip: 1 }],
          pierce: [{ clip: 0 }, { clip: 3 }, { clip: 3 }],
          pellet: [{ clip: 0 }, { clip: 3 }, { clip: 0 }],
          recovery: [{ clip: 0 }, { clip: 0 }],
          poison: [{ clip: 0 }, { clip: 0 }],
          para: [{ clip: 0 }, { clip: 0 }],
          sleep: [{ clip: 0 }, { clip: 1 }],
          flaming: [{ clip: 0 }],
          water: [{ clip: 2 }],
          freeze: [{ clip: 3 }],
          thunder: [{ clip: 0 }],
          crag: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          clust: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          wyvernfire: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          sub: [{ clip: 0 }, { clip: 0 }],
          demon: [{ clip: 0 }, { clip: 0 }],
          armor: [{ clip: 0 }, { clip: 0 }],
          exhaust: [{ clip: 0 }],
          dragon: [{ clip: 0 }],
          slicing: [{ clip: 1 }],
          tranq: [{ clip: 0 }],
          paint: [{ clip: 0 }],
        },
        price: 8800,
        create: { "417": 12, "103": 15, "148": 2, "169": 2 },
      },
      {
        name: "Diablazooka",
        description:
          "This Stock uses the tail of Diablos, but is just as powerful as the rest of him.",
        weight: 10,
        reload: 2,
        recoil: 0,
        affinity: 0,
        slots: 1,
        rarity: 5,
        shots: {
          normal: [{ clip: 2 }, { clip: 2 }, { clip: 0 }],
          pierce: [{ clip: 2 }, { clip: 2 }, { clip: 0 }],
          pellet: [{ clip: 0 }, { clip: 2 }, { clip: 0 }],
          recovery: [{ clip: 0 }, { clip: 0 }],
          poison: [{ clip: 0 }, { clip: 0 }],
          para: [{ clip: 0 }, { clip: 0 }],
          sleep: [{ clip: 0 }, { clip: 0 }],
          flaming: [{ clip: 0 }],
          water: [{ clip: 0 }],
          freeze: [{ clip: 0 }],
          thunder: [{ clip: 0 }],
          crag: [{ clip: 0 }, { clip: 1 }, { clip: 0 }],
          clust: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          wyvernfire: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          sub: [{ clip: 0 }, { clip: 0 }],
          demon: [{ clip: 0 }, { clip: 1 }],
          armor: [{ clip: 0 }, { clip: 0 }],
          exhaust: [{ clip: 2 }],
          dragon: [{ clip: 2 }],
          slicing: [{ clip: 1 }],
          tranq: [{ clip: 0 }],
          paint: [{ clip: 0 }],
        },
        price: 4400,
        create: { "422": 3, "423": 10, "103": 18, "271": 8 },
      },
      {
        name: "Chaos Wing",
        description:
          "A Stock of ill portent, whose owners are said to disappear without warning...",
        weight: 25,
        reload: 1,
        recoil: 2,
        affinity: 0,
        slots: 0,
        rarity: 7,
        shots: {
          normal: [{ clip: 0 }, { clip: 0 }, { clip: 4 }],
          pierce: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          pellet: [{ clip: 0 }, { clip: 3 }, { clip: 2 }],
          recovery: [{ clip: 0 }, { clip: 0 }],
          poison: [{ clip: 0 }, { clip: 0 }],
          para: [{ clip: 0 }, { clip: 2 }],
          sleep: [{ clip: 0 }, { clip: 1 }],
          flaming: [{ clip: 2 }],
          water: [{ clip: 2 }],
          freeze: [{ clip: 2 }],
          thunder: [{ clip: 2 }],
          crag: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          clust: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          wyvernfire: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          sub: [{ clip: 0 }, { clip: 2 }],
          demon: [{ clip: 0 }, { clip: 0 }],
          armor: [{ clip: 0 }, { clip: 0 }],
          exhaust: [{ clip: 2 }],
          dragon: [{ clip: 1 }],
          slicing: [{ clip: 3 }],
          tranq: [{ clip: 0 }],
          paint: [{ clip: 0 }],
        },
        price: 14200,
        create: { "477": 1, "402": 12, "403": 2, "404": 1 },
      },
      {
        name: "Jhen Cannon",
        description:
          "A stately Stock make of Jhen Mohran materials. It is surprisingly light.",
        weight: 10,
        reload: 0,
        recoil: 1,
        affinity: 0,
        slots: 1,
        rarity: 6,
        shots: {
          normal: [{ clip: 4 }, { clip: 0 }, { clip: 3 }],
          pierce: [{ clip: 0 }, { clip: 2 }, { clip: 0 }],
          pellet: [{ clip: 0 }, { clip: 3 }, { clip: 0 }],
          recovery: [{ clip: 0 }, { clip: 0 }],
          poison: [{ clip: 0 }, { clip: 0 }],
          para: [{ clip: 0 }, { clip: 2 }],
          sleep: [{ clip: 0 }, { clip: 0 }],
          flaming: [{ clip: 0 }],
          water: [{ clip: 0 }],
          freeze: [{ clip: 0 }],
          thunder: [{ clip: 0 }],
          crag: [{ clip: 2 }, { clip: 0 }, { clip: 0 }],
          clust: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          wyvernfire: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          sub: [{ clip: 2 }, { clip: 0 }],
          demon: [{ clip: 0 }, { clip: 0 }],
          armor: [{ clip: 0 }, { clip: 1 }],
          exhaust: [{ clip: 2 }],
          dragon: [{ clip: 3 }],
          slicing: [{ clip: 0 }],
          tranq: [{ clip: 0 }],
          paint: [{ clip: 0 }],
        },
        price: 8800,
        create: { "441": 10, "438": 2, "103": 12, "436": 3 },
      },
      {
        name: 'Aquamatic "Spark"',
        description:
          "A Light Bowgun kit. Parts can't be changed, but it has special qualities.",
        weight: 1,
        reload: 1,
        recoil: 1,
        affinity: 0,
        slots: 0,
        rarity: 6,
        shots: {
          normal: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          pierce: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          pellet: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          recovery: [{ clip: 0 }, { clip: 0 }],
          poison: [{ clip: 0 }, { clip: 0 }],
          para: [{ clip: 0 }, { clip: 0 }],
          sleep: [{ clip: 0 }, { clip: 0 }],
          flaming: [{ clip: 0 }],
          water: [{ clip: 0 }],
          freeze: [{ clip: 0 }],
          thunder: [{ clip: 0 }],
          crag: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          clust: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          wyvernfire: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          sub: [{ clip: 0 }, { clip: 0 }],
          demon: [{ clip: 0 }, { clip: 0 }],
          armor: [{ clip: 0 }, { clip: 0 }],
          exhaust: [{ clip: 0 }],
          dragon: [{ clip: 0 }],
          slicing: [{ clip: 0 }],
          tranq: [{ clip: 0 }],
          paint: [{ clip: 0 }],
        },
        price: 0,
        create: {},
      },
      {
        name: 'Aquamatic "Longshot"',
        description:
          "A Medium Bowgun Kit. Parts of it can't be changed, but it has special qualities.",
        weight: 1,
        reload: 1,
        recoil: 1,
        affinity: 0,
        slots: 0,
        rarity: 6,
        shots: {
          normal: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          pierce: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          pellet: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          recovery: [{ clip: 0 }, { clip: 0 }],
          poison: [{ clip: 0 }, { clip: 0 }],
          para: [{ clip: 0 }, { clip: 0 }],
          sleep: [{ clip: 0 }, { clip: 0 }],
          flaming: [{ clip: 0 }],
          water: [{ clip: 0 }],
          freeze: [{ clip: 0 }],
          thunder: [{ clip: 0 }],
          crag: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          clust: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          wyvernfire: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          sub: [{ clip: 0 }, { clip: 0 }],
          demon: [{ clip: 0 }, { clip: 0 }],
          armor: [{ clip: 0 }, { clip: 0 }],
          exhaust: [{ clip: 0 }],
          dragon: [{ clip: 0 }],
          slicing: [{ clip: 0 }],
          tranq: [{ clip: 0 }],
          paint: [{ clip: 0 }],
        },
        price: 0,
        create: {},
      },
      {
        name: "Vulcannon",
        description:
          "A Heavy Bowgun Kit. Parts can't be changed, but it has special qualities.",
        weight: 1,
        reload: 2,
        recoil: 1,
        affinity: 0,
        slots: 0,
        rarity: 6,
        shots: {
          normal: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          pierce: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          pellet: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          recovery: [{ clip: 0 }, { clip: 0 }],
          poison: [{ clip: 0 }, { clip: 0 }],
          para: [{ clip: 0 }, { clip: 0 }],
          sleep: [{ clip: 0 }, { clip: 0 }],
          flaming: [{ clip: 0 }],
          water: [{ clip: 0 }],
          freeze: [{ clip: 0 }],
          thunder: [{ clip: 0 }],
          crag: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          clust: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          wyvernfire: [{ clip: 0 }, { clip: 0 }, { clip: 0 }],
          sub: [{ clip: 0 }, { clip: 0 }],
          demon: [{ clip: 0 }, { clip: 0 }],
          armor: [{ clip: 0 }, { clip: 0 }],
          exhaust: [{ clip: 0 }],
          dragon: [{ clip: 0 }],
          slicing: [{ clip: 0 }],
          tranq: [{ clip: 0 }],
          paint: [{ clip: 0 }],
        },
        price: 0,
        create: {},
      },
    ],
  },
};
