/**
 * !RAW
 * This is a "raw" object taken from the archived MH3 stilltruth website.
 * http://web.archive.org/web/20130407144759/http://mhtri.stilltruth.com/
 *
 * This list of items seems to be more complete than the current Items structure
 * found elsewhere on the site.
 */

const Items = [
  { id: 1, name: 'Barrel Bomb S', icon: 'bomb', color: 'yellow', rarity: 2 },
  { id: 2, name: 'Barrel Bomb L', icon: 'bomb', color: 'red', rarity: 4 },
  { id: 3, name: 'Pitfall Trap', icon: 'trap', color: 'green', rarity: 4 },
  { id: 4, name: 'Shock Trap', icon: 'trap', color: 'purple', rarity: 4 },
  { id: 5, name: 'Flash Bomb', icon: 'ball', color: 'yellow', rarity: 2 },
  { id: 6, name: 'Oxygen Supply', icon: 'sac', color: 'cyan', rarity: 1 },
  { id: 7, name: 'Sonic Bomb', icon: 'ball', color: 'gray', rarity: 2 },
  { id: 8, name: 'Throwing Knife', icon: 'knife', color: 'white', rarity: 1 },
  { id: 9, name: 'Poison Knife', icon: 'knife', color: 'purple', rarity: 1 },
  { id: 10, name: 'Sleep Knife', icon: 'knife', color: 'cyan', rarity: 1 },
  {
    id: 11,
    name: 'Paralysis Knife',
    icon: 'knife',
    color: 'yellow',
    rarity: 1
  },
  { id: 12, name: 'Tranq Knife', icon: 'knife', color: 'red', rarity: 4 },
  { id: 13, name: 'Potion', icon: 'drink', color: 'green', rarity: 1 },
  { id: 14, name: 'Mega Potion', icon: 'drink', color: 'green', rarity: 2 },
  { id: 15, name: 'Dash Juice', icon: 'drink', color: 'yellow', rarity: 2 },
  {
    id: 16,
    name: 'Mega Dash Juice',
    icon: 'drink',
    color: 'yellow',
    rarity: 4
  },
  { id: 17, name: 'Antidote', icon: 'drink', color: 'blue', rarity: 1 },
  { id: 18, name: 'Demondrug', icon: 'drink', color: 'red', rarity: 4 },
  { id: 19, name: 'Mega Demondrug', icon: 'drink', color: 'red', rarity: 5 },
  { id: 20, name: 'Might Pill', icon: 'sac', color: 'red', rarity: 1 },
  { id: 21, name: 'Armorskin', icon: 'drink', color: 'orange', rarity: 4 },
  { id: 22, name: 'Mega Armorskin', icon: 'drink', color: 'orange', rarity: 5 },
  { id: 23, name: 'Adamant Pill', icon: 'sac', color: 'orange', rarity: 1 },
  { id: 24, name: 'Cool Drink', icon: 'drink', color: 'white', rarity: 1 },
  { id: 25, name: 'Hot Drink', icon: 'drink', color: 'red', rarity: 1 },
  { id: 26, name: 'Well-done Steak', icon: 'meat', color: 'orange', rarity: 2 },
  { id: 27, name: 'Rare Steak', icon: 'meat', color: 'orange', rarity: 1 },
  { id: 28, name: 'Burnt Meat', icon: 'meat', color: 'gray', rarity: 1 },
  { id: 29, name: 'Raw Meat', icon: 'meat', color: 'red', rarity: 1 },
  { id: 30, name: 'Poisoned Meat', icon: 'meat', color: 'purple', rarity: 1 },
  { id: 31, name: 'Tinged Meat', icon: 'meat', color: 'yellow', rarity: 2 },
  { id: 32, name: 'Drugged Meat', icon: 'meat', color: 'cyan', rarity: 1 },
  { id: 33, name: 'Paintball', icon: 'ball', color: 'pink', rarity: 1 },
  { id: 34, name: 'Old Pickaxe', icon: 'pickaxe', color: 'gray', rarity: 1 },
  { id: 35, name: 'Iron Pickaxe', icon: 'pickaxe', color: 'white', rarity: 1 },
  { id: 36, name: 'Mega Pickaxe', icon: 'pickaxe', color: 'yellow', rarity: 4 },
  { id: 37, name: 'Old Bug Net', icon: 'bugnet', color: 'gray', rarity: 1 },
  { id: 38, name: 'Bug Net', icon: 'bugnet', color: 'white', rarity: 1 },
  { id: 39, name: 'Mega Bug Net', icon: 'bugnet', color: 'yellow', rarity: 4 },
  { id: 40, name: 'BBQ Spit', icon: 'bbq', color: 'red', rarity: 4 },
  {
    id: 41,
    name: 'Great Jaggi Head',
    icon: 'shell',
    color: 'purple',
    rarity: 5
  },
  { id: 42, name: 'Map', icon: 'map', color: 'white', rarity: 1 },
  { id: 43, name: 'Torch', icon: 'torch', color: 'red', rarity: 1 },
  { id: 44, name: 'First-aid Med', icon: 'drink', color: 'green', rarity: 1 },
  { id: 45, name: 'Ration', icon: 'meat', color: 'orange', rarity: 1 },
  { id: 46, name: 'Mini Oxy Supply', icon: 'sac', color: 'cyan', rarity: 1 },
  { id: 47, name: 'Portable Spit', icon: 'bbq' },
  {
    id: 48,
    name: 'Mini Whetstone',
    icon: 'whetstone',
    color: 'yellow',
    rarity: 1
  },
  { id: 49, name: 'EZ Shock Trap', icon: 'trap', color: 'blue', rarity: 4 },
  { id: 50, name: 'EZ Flash Bomb', icon: 'ball', color: 'blue', rarity: 2 },
  { id: 51, name: 'Max Potion', icon: 'sac', color: 'yellow', rarity: 4 },
  { id: 52, name: 'Barrel Bomb L+', icon: 'bomb', color: 'red', rarity: 4 },
  { id: 53, name: 'Normal S Lv1', icon: 'shot', color: 'white', rarity: 1 },
  { id: 54, name: 'Normal S Lv2', icon: 'shot', color: 'white', rarity: 1 },
  { id: 55, name: 'Normal S Lv3', icon: 'shot', color: 'white', rarity: 2 },
  { id: 56, name: 'Pierce S Lv1', icon: 'shot', color: 'white', rarity: 2 },
  { id: 57, name: 'Pierce S Lv2', icon: 'shot', color: 'white', rarity: 2 },
  { id: 58, name: 'Pierce S Lv3', icon: 'shot', color: 'white', rarity: 3 },
  { id: 59, name: 'Pellet S Lv1', icon: 'shot', color: 'white', rarity: 2 },
  { id: 60, name: 'Pellet S Lv2', icon: 'shot', color: 'white', rarity: 2 },
  { id: 61, name: 'Pellet S Lv3', icon: 'shot', color: 'white', rarity: 3 },
  { id: 62, name: 'Crag S Lv1', icon: 'shot', color: 'white', rarity: 3 },
  { id: 63, name: 'Crag S Lv2', icon: 'shot', color: 'white', rarity: 3 },
  { id: 64, name: 'Crag S Lv3', icon: 'shot', color: 'white' },
  { id: 65, name: 'Clust S Lv1', icon: 'shot', color: 'white', rarity: 2 },
  { id: 66, name: 'Clust S Lv2', icon: 'shot', color: 'white', rarity: 3 },
  { id: 67, name: 'Clust S Lv3', icon: 'shot', color: 'white', rarity: 3 },
  { id: 68, name: 'Flaming S', icon: 'shot', color: 'red', rarity: 3 },
  { id: 69, name: 'Water S', icon: 'shot', color: 'cyan', rarity: 3 },
  { id: 70, name: 'Thunder S', icon: 'shot', color: 'yellow', rarity: 3 },
  { id: 71, name: 'Freeze S', icon: 'shot', color: 'blue', rarity: 3 },
  { id: 72, name: 'Dragon S', icon: 'shot', color: 'red', rarity: 5 },
  { id: 73, name: 'Recov S Lv1', icon: 'shot', color: 'green', rarity: 1 },
  { id: 74, name: 'Recov S Lv2', icon: 'shot', color: 'green', rarity: 2 },
  { id: 75, name: 'Poison S Lv1', icon: 'shot', color: 'purple', rarity: 2 },
  { id: 76, name: 'Poison S Lv2', icon: 'shot', color: 'purple', rarity: 3 },
  { id: 77, name: 'Para S Lv1', icon: 'shot', color: 'yellow', rarity: 3 },
  { id: 78, name: 'Para S Lv2', icon: 'shot', color: 'yellow', rarity: 4 },
  { id: 79, name: 'Sleep S Lv1', icon: 'shot', color: 'cyan', rarity: 3 },
  { id: 80, name: 'Sleep S Lv2', icon: 'shot', color: 'cyan', rarity: 4 },
  { id: 81, name: 'Tranq S', icon: 'shot', color: 'red', rarity: 4 },
  { id: 82, name: 'Paint S', icon: 'shot', color: 'pink', rarity: 1 },
  { id: 83, name: 'Demon S I', icon: 'shot', color: 'red', rarity: 3 },
  { id: 84, name: 'Demon S II', icon: 'shot', color: 'red' },
  { id: 85, name: 'Armor S I', icon: 'shot', color: 'orange', rarity: 3 },
  { id: 86, name: 'Armor S II', icon: 'shot', color: 'orange' },
  { id: 87, name: 'Sub S Lv1', icon: 'shot', color: 'cyan', rarity: 3 },
  { id: 88, name: 'Sub S Lv2', icon: 'shot', color: 'cyan' },
  { id: 89, name: 'Exhaust S', icon: 'shot', color: 'yellow', rarity: 4 },
  { id: 91, name: 'Slicing S', icon: 'shot', color: 'white', rarity: 3 },
  { id: 92, name: 'WyvernFire Lv1', icon: 'shot', color: 'red', rarity: 3 },
  { id: 93, name: 'WyvernFire Lv2', icon: 'shot', color: 'red' },
  { id: 94, name: 'WyvernFire Lv3', icon: 'shot', color: 'red' },
  { id: 95, name: 'Binoculars', icon: 'binoculars', color: 'white', rarity: 1 },
  { id: 96, name: 'Tranq Bomb', icon: 'ball', color: 'red', rarity: 4 },
  { id: 97, name: 'Stone', icon: 'ore', color: 'gray', rarity: 1 },
  { id: 98, name: 'Whetstone', icon: 'whetstone', color: 'yellow', rarity: 1 },
  { id: 99, name: 'Iron Ore', icon: 'ore', color: 'gray', rarity: 4 },
  { id: 100, name: 'Earth Crystal', icon: 'ore', color: 'white', rarity: 4 },
  { id: 101, name: 'Machalite Ore', icon: 'ore', color: 'blue', rarity: 5 },
  { id: 102, name: 'Dragonite Ore', icon: 'ore', color: 'green', rarity: 5 },
  { id: 103, name: 'Carbalite Ore', icon: 'ore', color: 'purple', rarity: 5 },
  { id: 104, name: 'Pelagicite Ore', icon: 'ore', color: 'orange', rarity: 4 },
  { id: 105, name: 'Bathycite Ore', icon: 'ore', color: 'pink', rarity: 5 },
  { id: 106, name: 'Firestone', icon: 'ore', color: 'red', rarity: 5 },
  { id: 107, name: 'Ice Crystal', icon: 'ore', color: 'cyan', rarity: 2 },
  { id: 108, name: 'Lightcrystal', icon: 'ore', color: 'gray', rarity: 5 },
  { id: 109, name: 'Sharq Ticket', icon: 'ticket', color: 'cyan', rarity: 5 },
  { id: 110, name: 'Rustshard', icon: 'garbage', color: 'white', rarity: 5 },
  {
    id: 111,
    name: 'Ancient Shard',
    icon: 'garbage',
    color: 'white',
    rarity: 6
  },
  { id: 112, name: 'Isisium', icon: 'ore', color: 'white', rarity: 5 },
  { id: 113, name: 'Gracium', icon: 'ore', color: 'cyan', rarity: 5 },
  { id: 115, name: 'Godbug', icon: 'bug', color: 'white', rarity: 4 },
  { id: 116, name: 'Bitterbug', icon: 'bug', color: 'blue', rarity: 1 },
  { id: 117, name: 'Flashbug', icon: 'bug', color: 'yellow', rarity: 2 },
  { id: 118, name: 'Thunderbug', icon: 'bug', color: 'yellow', rarity: 4 },
  { id: 119, name: 'Gluehopper', icon: 'bug', color: 'pink', rarity: 4 },
  { id: 120, name: 'Killer Beetle', icon: 'bug', color: 'red', rarity: 4 },
  { id: 121, name: 'Rare Scarab', icon: 'bug', color: 'yellow', rarity: 5 },
  { id: 122, name: 'Royal Rhino', icon: 'bug', color: 'cyan', rarity: 2 },
  { id: 123, name: 'Herb', icon: 'herb', color: 'green', rarity: 1 },
  { id: 124, name: 'Antidote Herb', icon: 'herb', color: 'blue', rarity: 1 },
  { id: 125, name: 'Sleep Herb', icon: 'herb', color: 'cyan', rarity: 1 },
  { id: 126, name: 'Fire Herb', icon: 'herb', color: 'red', rarity: 2 },
  { id: 127, name: 'Sap Plant', icon: 'herb', color: 'white', rarity: 1 },
  { id: 128, name: 'Paintberry', icon: 'seed', color: 'pink', rarity: 1 },
  { id: 129, name: 'Needleberry', icon: 'seed', color: 'gray', rarity: 1 },
  { id: 130, name: 'Huskberry', icon: 'husk', color: 'gray', rarity: 1 },
  { id: 131, name: 'Scatternut', icon: 'seed', color: 'gray', rarity: 2 },
  { id: 132, name: 'Bomberry', icon: 'seed', color: 'gray', rarity: 2 },
  { id: 133, name: 'Ivy', icon: 'herb', color: 'green', rarity: 1 },
  { id: 134, name: 'Might Seed', icon: 'seed', color: 'red', rarity: 2 },
  { id: 135, name: 'Adamant Seed', icon: 'seed', color: 'orange', rarity: 2 },
  { id: 136, name: 'Hot Pepper', icon: 'herb', color: 'red', rarity: 2 },
  { id: 137, name: 'Cactus Flower', icon: 'herb', color: 'pink', rarity: 2 },
  { id: 138, name: 'Airweed', icon: 'herb', color: 'blue', rarity: 1 },
  { id: 139, name: 'Wyvern Egg', icon: 'egg', color: 'white', rarity: 5 },
  { id: 140, name: 'Unknown Skull', icon: 'bone', color: 'yellow', rarity: 4 },
  { id: 141, name: 'Honey', icon: 'webbing', color: 'orange', rarity: 2 },
  {
    id: 142,
    name: 'Blue Mushroom',
    icon: 'mushroom',
    color: 'blue',
    rarity: 2
  },
  {
    id: 143,
    name: 'Choice Mushroom',
    icon: 'mushroom',
    color: 'white',
    rarity: 5
  },
  {
    id: 144,
    name: 'Unique Mushroom',
    icon: 'mushroom',
    color: 'white',
    rarity: 5
  },
  {
    id: 145,
    name: 'Exciteshroom',
    icon: 'mushroom',
    color: 'purple',
    rarity: 3
  },
  { id: 146, name: 'Parashroom', icon: 'mushroom', color: 'yellow', rarity: 4 },
  { id: 147, name: 'Nitroshroom', icon: 'mushroom', color: 'red', rarity: 2 },
  { id: 149, name: 'Black Pearl', icon: 'scale', color: 'gray', rarity: 4 },
  { id: 150, name: 'Jumbo Pearl', icon: 'scale', color: 'white', rarity: 4 },
  { id: 151, name: 'Broken Shell', icon: 'scale', color: 'gray', rarity: 2 },
  {
    id: 152,
    name: 'Dragonbone Relic',
    icon: 'bone',
    color: 'white',
    rarity: 5
  },
  { id: 153, name: 'Monster Bone S', icon: 'bone', color: 'yellow', rarity: 3 },
  { id: 154, name: 'Monster Bone M', icon: 'bone', color: 'yellow', rarity: 4 },
  { id: 155, name: 'Monster Bone L', icon: 'bone', color: 'yellow', rarity: 5 },
  {
    id: 157,
    name: 'Eldest Saturnian',
    icon: 'commodity_rare',
    color: 'yellow',
    rarity: 5
  },
  { id: 164, name: 'Hercudrome', icon: 'bug', color: 'red', rarity: 5 },
  { id: 166, name: 'Chilled Meat', icon: 'meat', color: 'cyan', rarity: 2 },
  { id: 167, name: 'Hot Meat', icon: 'meat', color: 'red', rarity: 2 },
  { id: 169, name: 'Rathian Scale+', icon: 'scale', color: 'green', rarity: 4 },
  {
    id: 170,
    name: 'Rathian Carapace',
    icon: 'shell',
    color: 'green',
    rarity: 4
  },
  { id: 171, name: 'Rath Medulla', icon: 'shell', color: 'red', rarity: 5 },
  { id: 172, name: 'Rathian Spike+', icon: 'shell', color: 'green', rarity: 5 },
  { id: 173, name: 'Rathian Ruby', icon: 'ball', color: 'green', rarity: 5 },
  { id: 174, name: 'Rathalos Ruby', icon: 'ball', color: 'red', rarity: 5 },
  { id: 175, name: 'Inferno Sac', icon: 'sac', color: 'red', rarity: 4 },
  { id: 176, name: 'Rathalos Scale+', icon: 'scale', color: 'red', rarity: 4 },
  { id: 177, name: 'RathalosCarapace', icon: 'shell', color: 'red', rarity: 4 },
  { id: 178, name: 'Qurupeco Scale+', icon: 'scale', color: 'pink', rarity: 4 },
  { id: 180, name: 'Wonderful Beak', icon: 'bone', color: 'pink', rarity: 4 },
  { id: 181, name: 'Unnerving Talon', icon: 'claw', color: 'red', rarity: 4 },
  { id: 182, name: 'Fearsome Maw', icon: 'shell', color: 'red', rarity: 4 },
  { id: 183, name: 'Wyvern Stone', icon: 'ball', color: 'green', rarity: 5 },
  { id: 184, name: 'Freezer Sac', icon: 'sac', color: 'white', rarity: 4 },
  {
    id: 185,
    name: 'Wyvrnhide Ticket',
    icon: 'ticket',
    color: 'gray',
    rarity: 5
  },
  {
    id: 186,
    name: 'Black Gem Ticket',
    icon: 'ticket',
    color: 'gray',
    rarity: 5
  },
  { id: 187, name: 'Flabby Hide+', icon: 'hide', color: 'white', rarity: 4 },
  { id: 188, name: 'Uncanny Hide+', icon: 'hide', color: 'red', rarity: 4 },
  { id: 189, name: 'Toxin Sac', icon: 'sac', color: 'purple', rarity: 4 },
  { id: 190, name: 'Unnerving Talon+', icon: 'claw', color: 'red', rarity: 4 },
  {
    id: 191,
    name: 'Stunning Quill',
    icon: 'commodity',
    color: 'yellow',
    rarity: 4
  },
  { id: 192, name: 'Pittance Fang', icon: 'claw', color: 'yellow', rarity: 4 },
  {
    id: 193,
    name: 'Vermilion Scale',
    icon: 'commodity_rare',
    color: 'red',
    rarity: 5
  },
  {
    id: 194,
    name: 'Fishing Harpoon',
    icon: 'harpoon',
    color: 'cyan',
    rarity: 1
  },
  { id: 195, name: 'Insect Husk', icon: 'bug', color: 'gray', rarity: 1 },
  { id: 196, name: 'Bone', icon: 'bone', color: 'white', rarity: 1 },
  { id: 197, name: 'Dung', icon: 'dung', color: 'yellow', rarity: 1 },
  { id: 198, name: 'Spider Web', icon: 'web', color: 'white', rarity: 1 },
  { id: 199, name: 'Bomb Casing', icon: 'ball', color: 'white', rarity: 1 },
  { id: 200, name: 'Small Barrel', icon: 'barrel', color: 'yellow', rarity: 1 },
  { id: 201, name: 'Large Barrel', icon: 'barrel', color: 'red', rarity: 2 },
  { id: 202, name: 'Cricket', icon: 'bait', color: 'green', rarity: 1 },
  { id: 203, name: 'Worm', icon: 'bait', color: 'gray', rarity: 1 },
  { id: 204, name: 'Firefly', icon: 'bait', color: 'yellow', rarity: 2 },
  { id: 205, name: 'Mega Fishing Fly', icon: 'bait', color: 'pink', rarity: 3 },
  { id: 206, name: 'Frog', icon: 'bait', color: 'blue', rarity: 2 },
  { id: 207, name: 'Whetfish', icon: 'fish', color: 'yellow', rarity: 1 },
  { id: 208, name: 'Sushifish', icon: 'fish', color: 'orange', rarity: 1 },
  { id: 209, name: 'Pin Tuna', icon: 'fish', color: 'gray', rarity: 1 },
  { id: 210, name: 'Popfish', icon: 'fish', color: 'gray', rarity: 2 },
  { id: 211, name: 'Sleepyfish', icon: 'fish', color: 'cyan', rarity: 2 },
  { id: 212, name: 'Burst Arowana', icon: 'fish', color: 'gray', rarity: 4 },
  { id: 213, name: 'Bomb Arowana', icon: 'fish', color: 'gray', rarity: 4 },
  { id: 214, name: 'Glutton Tuna', icon: 'fish', color: 'orange', rarity: 4 },
  { id: 215, name: 'Scatterfish', icon: 'fish', color: 'gray', rarity: 4 },
  {
    id: 216,
    name: 'Small Goldenfish',
    icon: 'fish',
    color: 'yellow',
    rarity: 4
  },
  { id: 217, name: 'Goldenfish', icon: 'fish', color: 'yellow', rarity: 4 },
  {
    id: 219,
    name: 'Beautiful Scale',
    icon: 'commodity',
    color: 'blue',
    rarity: 4
  },
  {
    id: 220,
    name: 'Giant Skull',
    icon: 'commodity_rare',
    color: 'white',
    rarity: 5
  },
  { id: 221, name: 'Pirate Booty', icon: 'jewel', color: 'yellow', rarity: 5 },
  { id: 222, name: 'Net', icon: 'web', color: 'white', rarity: 2 },
  { id: 224, name: 'Shroom Germ', icon: 'drink', color: 'white', rarity: 4 },
  { id: 225, name: 'BugMaker! Pro', icon: 'drink', color: 'purple', rarity: 4 },
  { id: 226, name: 'Bizzy Bees', icon: 'bug', color: 'yellow', rarity: 4 },
  { id: 227, name: 'Saturnian', icon: 'shell', color: 'white', rarity: 4 },
  { id: 228, name: 'Fortune Fang', icon: 'claw', color: 'yellow', rarity: 4 },
  {
    id: 229,
    name: 'Shining Starfish',
    icon: 'commodity',
    color: 'yellow',
    rarity: 4
  },
  {
    id: 230,
    name: 'Mystic Narwhal',
    icon: 'commodity',
    color: 'blue',
    rarity: 4
  },
  {
    id: 231,
    name: 'Atlantis Crab',
    icon: 'commodity_rare',
    color: 'red',
    rarity: 5
  },
  { id: 232, name: 'Gold Needle', icon: 'claw', color: 'yellow', rarity: 4 },
  {
    id: 233,
    name: 'Armorfish Morsel',
    icon: 'commodity',
    color: 'white',
    rarity: 4
  },
  { id: 234, name: 'Fish Finder', icon: 'fish', color: 'orange', rarity: 4 },
  {
    id: 235,
    name: 'Treasure Tracker',
    icon: 'ticket',
    color: 'white',
    rarity: 4
  },
  {
    id: 236,
    name: 'Spare Spear',
    icon: 'traptool',
    color: 'orange',
    rarity: 4
  },
  {
    id: 237,
    name: 'Perfect Paddle',
    icon: 'commodity',
    color: 'green',
    rarity: 4
  },
  { id: 238, name: 'Shroom Germ+', icon: 'drink', color: 'yellow', rarity: 4 },
  { id: 239, name: 'Pink Liver', icon: 'meat', color: 'pink', rarity: 4 },
  {
    id: 240,
    name: 'Ethnic Wyvrnmeat',
    icon: 'meat',
    color: 'white',
    rarity: 5
  },
  {
    id: 241,
    name: 'Ancient Skin Oil',
    icon: 'commodity_rare',
    color: 'white',
    rarity: 5
  },
  {
    id: 242,
    name: "Queen's Spirit",
    icon: 'commodity_rare',
    color: 'yellow',
    rarity: 5
  },
  { id: 244, name: 'Funky Pheromones', icon: 'bug', color: 'pink', rarity: 4 },
  {
    id: 245,
    name: 'Saturnian Trap',
    icon: 'traptool',
    color: 'yellow',
    rarity: 4
  },
  {
    id: 247,
    name: 'Super-sized Dung',
    icon: 'dung',
    color: 'orange',
    rarity: 4
  },
  { id: 248, name: 'Fine Pelt', icon: 'commodity', color: 'orange', rarity: 4 },
  {
    id: 249,
    name: 'Moonlight Fang',
    icon: 'commodity',
    color: 'yellow',
    rarity: 5
  },
  {
    id: 250,
    name: 'Queen Needle',
    icon: 'commodity',
    color: 'white',
    rarity: 5
  },
  {
    id: 251,
    name: 'Power Paddle',
    icon: 'commodity',
    color: 'white',
    rarity: 4
  },
  {
    id: 252,
    name: 'Curved Fang',
    icon: 'commodity',
    color: 'white',
    rarity: 4
  },
  {
    id: 253,
    name: 'Flamboyant Quill',
    icon: 'commodity_rare',
    color: 'pink',
    rarity: 5
  },
  {
    id: 254,
    name: 'Glittering Scale',
    icon: 'commodity',
    color: 'yellow',
    rarity: 4
  },
  {
    id: 255,
    name: "Sea-King's Scale",
    icon: 'commodity_rare',
    color: 'blue',
    rarity: 5
  },
  { id: 256, name: 'Wyverngold', icon: 'ore', color: 'yellow', rarity: 5 },
  { id: 264, name: 'Felvine Bomb', icon: 'bomb', color: 'pink', rarity: 4 },
  { id: 265, name: 'Double BBQ Spit', icon: 'bbq', color: 'yellow', rarity: 5 },
  {
    id: 266,
    name: 'Dragonbone Piece',
    icon: 'bone',
    color: 'white',
    rarity: 4
  },
  { id: 267, name: 'Abalone Piece', icon: 'shell', color: 'gray', rarity: 4 },
  { id: 268, name: 'Fossil Piece', icon: 'ore', color: 'gray', rarity: 4 },
  { id: 269, name: 'Odd Egg', icon: 'egg', color: 'green', rarity: 4 },
  { id: 270, name: 'Mystery Bone', icon: 'bone', color: 'yellow', rarity: 1 },
  { id: 273, name: 'Herbal Medicine', icon: 'sac', color: 'white', rarity: 2 },
  { id: 274, name: 'Rathian Scale', icon: 'scale', color: 'green', rarity: 4 },
  { id: 275, name: 'Rathian Shell', icon: 'shell', color: 'green', rarity: 4 },
  {
    id: 276,
    name: 'Rathian Webbing',
    icon: 'webbing',
    color: 'green',
    rarity: 4
  },
  { id: 277, name: 'Rathian Spike', icon: 'shell', color: 'green', rarity: 5 },
  { id: 278, name: 'Rathian Plate', icon: 'scale', color: 'green', rarity: 5 },
  { id: 279, name: 'Flame Sac', icon: 'sac', color: 'red', rarity: 4 },
  { id: 280, name: 'Wyvern Tear', icon: 'shell', color: 'cyan', rarity: 5 },
  { id: 281, name: 'Rathalos Scale', icon: 'scale', color: 'red', rarity: 4 },
  { id: 282, name: 'Rathalos Shell', icon: 'shell', color: 'red', rarity: 4 },
  {
    id: 283,
    name: 'Rathalos Webbing',
    icon: 'webbing',
    color: 'red',
    rarity: 4
  },
  { id: 284, name: 'Rath Marrow', icon: 'shell', color: 'red', rarity: 5 },
  { id: 285, name: 'Rathalos Plate', icon: 'scale', color: 'red', rarity: 5 },
  { id: 286, name: 'Rathalos Tail', icon: 'shell', color: 'red', rarity: 5 },
  { id: 287, name: 'Qurupeco Scale', icon: 'scale', color: 'pink', rarity: 4 },
  {
    id: 288,
    name: 'Qurupeco Feather',
    icon: 'shell',
    color: 'pink',
    rarity: 4
  },
  { id: 289, name: 'Vivid Feather', icon: 'shell', color: 'pink', rarity: 4 },
  { id: 290, name: 'Strange Beak', icon: 'bone', color: 'pink', rarity: 4 },
  { id: 291, name: 'Flabby Hide', icon: 'hide', color: 'white', rarity: 4 },
  { id: 292, name: 'Uncanny Hide', icon: 'hide', color: 'red', rarity: 4 },
  { id: 293, name: 'Poison Sac', icon: 'sac', color: 'purple', rarity: 4 },
  { id: 294, name: 'Pale Extract', icon: 'drink', color: 'blue', rarity: 4 },
  { id: 295, name: 'Diablos Fang', icon: 'claw', color: 'yellow', rarity: 4 },
  { id: 296, name: 'Diablos Shell', icon: 'shell', color: 'yellow', rarity: 4 },
  { id: 297, name: 'Diablos Ridge', icon: 'shell', color: 'yellow', rarity: 5 },
  {
    id: 298,
    name: 'Diablos Tailcase',
    icon: 'shell',
    color: 'yellow',
    rarity: 5
  },
  { id: 299, name: 'Barroth Shell', icon: 'shell', color: 'orange', rarity: 4 },
  { id: 300, name: 'Barroth Ridge', icon: 'shell', color: 'orange', rarity: 4 },
  { id: 301, name: 'Barroth Claw', icon: 'claw', color: 'orange', rarity: 4 },
  { id: 302, name: 'Barroth Tail', icon: 'shell', color: 'orange', rarity: 4 },
  { id: 303, name: 'Barroth Scalp', icon: 'shell', color: 'orange', rarity: 4 },
  {
    id: 304,
    name: 'Bird Wyvern Fang',
    icon: 'claw',
    color: 'purple',
    rarity: 4
  },
  { id: 305, name: 'Jaggi Hide', icon: 'hide', color: 'purple', rarity: 4 },
  { id: 306, name: 'Jaggi Scale', icon: 'scale', color: 'purple', rarity: 4 },
  {
    id: 307,
    name: 'Great Jaggi Claw',
    icon: 'claw',
    color: 'purple',
    rarity: 4
  },
  {
    id: 308,
    name: 'Great Jaggi Hide',
    icon: 'hide',
    color: 'purple',
    rarity: 4
  },
  { id: 309, name: 'Screamer', icon: 'sac', color: 'gray', rarity: 4 },
  { id: 310, name: 'Lagiacrus Hide', icon: 'hide', color: 'cyan', rarity: 4 },
  { id: 311, name: 'Lagiacrus Scale', icon: 'scale', color: 'cyan', rarity: 4 },
  { id: 312, name: 'Lagiacrus Claw', icon: 'claw', color: 'cyan', rarity: 4 },
  { id: 313, name: 'Shell Shocker+', icon: 'shell', color: 'cyan', rarity: 5 },
  { id: 314, name: 'Lagiacrus Tail', icon: 'shell', color: 'cyan', rarity: 4 },
  { id: 315, name: 'Lagiacrus Plate', icon: 'scale', color: 'cyan', rarity: 4 },
  { id: 316, name: 'Spongy Hide', icon: 'hide', color: 'yellow', rarity: 4 },
  {
    id: 317,
    name: 'R.Ludroth Scale',
    icon: 'scale',
    color: 'yellow',
    rarity: 4
  },
  { id: 318, name: 'R.Ludroth Claw', icon: 'claw', color: 'yellow', rarity: 4 },
  {
    id: 319,
    name: 'R.Ludroth Tail',
    icon: 'shell',
    color: 'yellow',
    rarity: 4
  },
  { id: 320, name: 'Dash Extract', icon: 'drink', color: 'blue', rarity: 4 },
  { id: 321, name: 'Hydro Hide', icon: 'hide', color: 'yellow', rarity: 4 },
  {
    id: 322,
    name: 'Immature Sponge',
    icon: 'shell',
    color: 'yellow',
    rarity: 4
  },
  { id: 323, name: 'Gobul Spike', icon: 'shell', color: 'purple', rarity: 4 },
  { id: 324, name: 'Gobul Hide', icon: 'hide', color: 'purple', rarity: 4 },
  { id: 325, name: 'Paralysis Sac', icon: 'sac', color: 'yellow', rarity: 4 },
  { id: 326, name: 'Gobul Fin', icon: 'shell', color: 'purple', rarity: 4 },
  { id: 327, name: 'Armor Sphere', icon: 'sphere', color: 'blue', rarity: 4 },
  { id: 328, name: 'Armor Sphere+', icon: 'sphere', color: 'green', rarity: 4 },
  { id: 329, name: 'Gobul Lantern', icon: 'shell', color: 'white', rarity: 4 },
  { id: 330, name: 'Warm Pelt', icon: 'hide', color: 'green', rarity: 4 },
  { id: 331, name: 'Nutrients', icon: 'drink', color: 'cyan', rarity: 2 },
  { id: 332, name: 'Mega Nutrients', icon: 'drink', color: 'cyan', rarity: 4 },
  {
    id: 333,
    name: 'Dragon Toadstool',
    icon: 'mushroom',
    color: 'red',
    rarity: 4
  },
  { id: 334, name: 'Immunizer', icon: 'drink', color: 'yellow', rarity: 4 },
  { id: 335, name: 'Catalyst', icon: 'sac', color: 'gray', rarity: 2 },
  { id: 336, name: 'Bomb Sac', icon: 'shell', color: 'gray', rarity: 4 },
  { id: 337, name: 'Kelbi Horn', icon: 'claw', color: 'blue', rarity: 4 },
  { id: 338, name: 'Blue Kelbi Horn', icon: 'claw', color: 'green', rarity: 5 },
  { id: 339, name: 'Bnahabra Shell', icon: 'bug', color: 'yellow', rarity: 4 },
  {
    id: 340,
    name: 'Bnahabra Wing',
    icon: 'webbing',
    color: 'yellow',
    rarity: 4
  },
  { id: 341, name: 'Monster Fluid', icon: 'drink', color: 'cyan', rarity: 4 },
  { id: 342, name: 'Bone Husk S', icon: 'husk', color: 'white', rarity: 2 },
  { id: 343, name: 'Bone Husk L', icon: 'husk', color: 'white', rarity: 3 },
  { id: 344, name: 'Toadstool', icon: 'mushroom', color: 'purple', rarity: 2 },
  { id: 345, name: 'Smoke Bomb', icon: 'smoke', color: 'white', rarity: 2 },
  {
    id: 346,
    name: 'Poison Smoke Bmb',
    icon: 'smoke',
    color: 'purple',
    rarity: 2
  },
  { id: 347, name: 'Dung Bomb', icon: 'dung', color: 'yellow', rarity: 2 },
  { id: 348, name: 'Gunpowder', icon: 'sac', color: 'red', rarity: 2 },
  { id: 349, name: 'Trap Tool', icon: 'traptool', color: 'green', rarity: 3 },
  { id: 350, name: 'Yambug', icon: 'bug', color: 'blue', rarity: 1 },
  { id: 351, name: 'Tuna Bait', icon: 'bug', color: 'cyan', rarity: 2 },
  { id: 352, name: 'Bughopper', icon: 'bug', color: 'white', rarity: 1 },
  { id: 353, name: 'Arowana Bait', icon: 'bait', color: 'white', rarity: 2 },
  { id: 354, name: 'Snakebee Larva', icon: 'bug', color: 'orange', rarity: 1 },
  {
    id: 355,
    name: 'Goldenfish Bait',
    icon: 'bait',
    color: 'yellow',
    rarity: 4
  },
  {
    id: 356,
    name: 'Antiseptic Stone',
    icon: 'ore',
    color: 'yellow',
    rarity: 3
  },
  { id: 357, name: 'Wyvern Fang', icon: 'claw', color: 'white', rarity: 3 },
  { id: 358, name: 'Lifecrystals', icon: 'sac', color: 'white', rarity: 3 },
  { id: 359, name: 'Wyvern Claw', icon: 'claw', color: 'white', rarity: 3 },
  { id: 360, name: 'Lifepowder', icon: 'sac', color: 'white', rarity: 4 },
  { id: 361, name: 'Hunting Horn', icon: 'horn', color: 'yellow', rarity: 2 },
  { id: 362, name: 'Health Horn', icon: 'horn', color: 'green', rarity: 4 },
  { id: 363, name: 'Antidote Horn', icon: 'horn', color: 'blue', rarity: 4 },
  { id: 364, name: 'Demon Horn', icon: 'horn', color: 'red', rarity: 5 },
  { id: 365, name: 'Armor Horn', icon: 'horn', color: 'orange', rarity: 5 },
  { id: 366, name: 'Farcaster', icon: 'smoke', color: 'green', rarity: 3 },
  { id: 367, name: 'Tranquilizer', icon: 'drink', color: 'red', rarity: 4 },
  { id: 368, name: 'Dragonfell Berry', icon: 'seed', color: 'red', rarity: 2 },
  { id: 374, name: 'Energy Drink', icon: 'drink', color: 'yellow', rarity: 2 },
  { id: 375, name: 'Cleanser', icon: 'drink', color: 'cyan', rarity: 2 },
  { id: 376, name: 'Garbage', icon: 'garbage', color: 'white', rarity: 1 },
  { id: 377, name: 'Ancient Potion', icon: 'sac', color: 'red', rarity: 5 },
  { id: 378, name: 'Psychoserum', icon: 'drink', color: 'orange', rarity: 3 },
  { id: 379, name: 'Agnaktor Coin', icon: 'coin', color: 'red', rarity: 5 },
  { id: 380, name: 'Ballista Ammo', icon: 'shot', color: 'gray', rarity: 6 },
  { id: 381, name: 'Cannon Ammo', icon: 'shot', color: 'white', rarity: 6 },
  { id: 382, name: 'Powderstone', icon: 'ore', color: 'red', rarity: 6 },
  {
    id: 383,
    name: 'Anti-dragon Bomb',
    icon: 'bomb',
    color: 'yellow',
    rarity: 6
  },
  {
    id: 384,
    name: 'Ballista Binder',
    icon: 'shot',
    color: 'yellow',
    rarity: 6
  },
  { id: 385, name: 'Rath Talon', icon: 'claw', color: 'red', rarity: 5 },
  { id: 386, name: 'Twisted Horn', icon: 'claw', color: 'yellow', rarity: 5 },
  { id: 387, name: 'Majestic Horn', icon: 'claw', color: 'yellow', rarity: 6 },
  { id: 388, name: 'Mega Harpoon', icon: 'harpoon', color: 'cyan', rarity: 4 },
  { id: 389, name: 'Whetfish Bait', icon: 'bait', color: 'yellow', rarity: 4 },
  { id: 390, name: 'Sushifish Bait', icon: 'bait', color: 'yellow', rarity: 4 },
  { id: 391, name: 'Firedouse Berry', icon: 'seed', color: 'red', rarity: 2 },
  { id: 392, name: 'Waterblock Seed', icon: 'seed', color: 'cyan', rarity: 2 },
  { id: 393, name: 'Icethaw Pellet', icon: 'seed', color: 'white', rarity: 2 },
  {
    id: 394,
    name: 'Stormsender Seed',
    icon: 'seed',
    color: 'yellow',
    rarity: 2
  },
  { id: 395, name: 'Herbivore Egg', icon: 'egg', color: 'orange', rarity: 5 },
  { id: 396, name: 'Crystal Bone', icon: 'bone', color: 'purple', rarity: 2 },
  { id: 397, name: 'Golden Bone', icon: 'bone', color: 'yellow', rarity: 2 },
  { id: 398, name: 'Air Philter', icon: 'drink', color: 'cyan', rarity: 1 },
  {
    id: 399,
    name: 'Mega Air Philter',
    icon: 'drink',
    color: 'cyan',
    rarity: 4
  },
  {
    id: 400,
    name: 'Altaroth Stomach',
    icon: 'sac',
    color: 'purple',
    rarity: 4
  },
  { id: 401, name: 'Altaroth Jaw', icon: 'claw', color: 'purple', rarity: 4 },
  {
    id: 402,
    name: 'Ripened Mushroom',
    icon: 'mushroom',
    color: 'green',
    rarity: 5
  },
  {
    id: 403,
    name: 'R.Ludroth Crest',
    icon: 'shell',
    color: 'yellow',
    rarity: 4
  },
  { id: 404, name: 'Barioth Shell', icon: 'shell', color: 'white', rarity: 4 },
  { id: 405, name: 'Barioth Pelt', icon: 'hide', color: 'white', rarity: 4 },
  { id: 406, name: 'Amber Tusks', icon: 'claw', color: 'orange', rarity: 4 },
  { id: 407, name: 'Barioth Claw', icon: 'claw', color: 'white', rarity: 4 },
  { id: 408, name: 'Barioth Spike', icon: 'shell', color: 'white', rarity: 4 },
  { id: 409, name: 'Frost Sac', icon: 'sac', color: 'white', rarity: 4 },
  { id: 410, name: 'Uragaan Shell', icon: 'shell', color: 'red', rarity: 4 },
  { id: 411, name: 'Uragaan Scute', icon: 'shell', color: 'red', rarity: 4 },
  { id: 412, name: 'Uragaan Marrow', icon: 'shell', color: 'red', rarity: 4 },
  { id: 413, name: 'Uragaan Jaw', icon: 'shell', color: 'red', rarity: 4 },
  { id: 414, name: 'Agnaktor Shell', icon: 'shell', color: 'red', rarity: 4 },
  { id: 415, name: 'Agnaktor Hide', icon: 'hide', color: 'red', rarity: 4 },
  { id: 416, name: 'Agnaktor Fin', icon: 'shell', color: 'red', rarity: 4 },
  { id: 417, name: 'Agnaktor Claw', icon: 'claw', color: 'red', rarity: 4 },
  { id: 418, name: 'Agnaktor Scale', icon: 'scale', color: 'red', rarity: 4 },
  { id: 419, name: 'Agnaktor Beak', icon: 'bone', color: 'red', rarity: 4 },
  {
    id: 420,
    name: "King's Frill",
    icon: 'webbing',
    color: 'purple',
    rarity: 4
  },
  { id: 421, name: 'Fertile Mud', icon: 'dung', color: 'yellow', rarity: 4 },
  { id: 422, name: 'Gobul Whisker', icon: 'bone', color: 'purple', rarity: 4 },
  { id: 423, name: 'Shell Shocker', icon: 'shell', color: 'cyan', rarity: 5 },
  { id: 424, name: 'Lagiacrus Horn', icon: 'claw', color: 'cyan', rarity: 5 },
  { id: 425, name: 'Flintstone', icon: 'shell', color: 'red', rarity: 4 },
  { id: 426, name: 'Barioth Tail', icon: 'shell', color: 'white', rarity: 5 },
  { id: 427, name: 'Bloodstone', icon: 'ore', color: 'red', rarity: 3 },
  {
    id: 428,
    name: 'Paw Pass Ticket',
    icon: 'ticket',
    color: 'white',
    rarity: 4
  },
  { id: 429, name: 'Monster Guts', icon: 'shell', color: 'yellow', rarity: 3 },
  { id: 430, name: 'Red Coral Stone', icon: 'ore', color: 'red', rarity: 3 },
  { id: 431, name: 'Voucher', icon: 'voucher', color: 'white', rarity: 4 },
  {
    id: 432,
    name: 'Gourmet Voucher',
    icon: 'voucher',
    color: 'yellow',
    rarity: 5
  },
  {
    id: 433,
    name: 'Alatreon Scute',
    icon: 'shell',
    color: 'purple',
    rarity: 6
  },
  {
    id: 434,
    name: 'Alatreon Plate',
    icon: 'scale',
    color: 'purple',
    rarity: 6
  },
  { id: 435, name: 'Alatreon Talon', icon: 'claw', color: 'purple', rarity: 6 },
  {
    id: 436,
    name: 'Azure Dragongem',
    icon: 'hvnly',
    color: 'purple',
    rarity: 6
  },
  { id: 437, name: 'Skypiercer', icon: 'claw', color: 'purple', rarity: 6 },
  { id: 440, name: 'Mystery Charm', icon: 'charm', color: 'white', rarity: 3 },
  { id: 441, name: 'Shining Charm', icon: 'charm', color: 'yellow', rarity: 4 },
  { id: 442, name: 'Timeworn Charm', icon: 'charm', color: 'red', rarity: 5 },
  { id: 443, name: 'Armor Stone', icon: 'ore', color: 'white', rarity: 4 },
  {
    id: 444,
    name: 'Adv Armor Sphere',
    icon: 'sphere',
    color: 'orange',
    rarity: 5
  },
  {
    id: 445,
    name: 'Hrd Armor Sphere',
    icon: 'sphere',
    color: 'purple',
    rarity: 5
  },
  {
    id: 446,
    name: 'Hvy Armor Sphere',
    icon: 'sphere',
    color: 'red',
    rarity: 5
  },
  { id: 447, name: 'Aquaglow Jewel', icon: 'jewel', color: 'cyan', rarity: 3 },
  { id: 448, name: 'Sunspire Jewel', icon: 'jewel', color: 'white', rarity: 4 },
  {
    id: 449,
    name: 'Bloodrun Jewel',
    icon: 'jewel',
    color: 'purple',
    rarity: 5
  },
  {
    id: 450,
    name: 'Lazurite Jewel',
    icon: 'jewel',
    color: 'yellow',
    rarity: 5
  },
  {
    id: 451,
    name: 'Barioth Carapace',
    icon: 'shell',
    color: 'white',
    rarity: 4
  },
  { id: 452, name: 'Barioth Pelt+', icon: 'hide', color: 'white', rarity: 4 },
  { id: 453, name: 'Amber Tusks+', icon: 'claw', color: 'orange', rarity: 4 },
  { id: 454, name: 'Barioth Claw+', icon: 'claw', color: 'white', rarity: 4 },
  {
    id: 455,
    name: 'Diablos Marrow',
    icon: 'shell',
    color: 'yellow',
    rarity: 5
  },
  {
    id: 456,
    name: 'Diablos Carapace',
    icon: 'shell',
    color: 'yellow',
    rarity: 4
  },
  {
    id: 457,
    name: 'Diablos Ridge+',
    icon: 'shell',
    color: 'yellow',
    rarity: 5
  },
  { id: 458, name: 'Stout Horn', icon: 'claw', color: 'yellow', rarity: 6 },
  { id: 459, name: 'Ceadeus Hide', icon: 'hide', color: 'white', rarity: 4 },
  { id: 460, name: 'Ceadeus Scale', icon: 'scale', color: 'white', rarity: 4 },
  { id: 461, name: 'Ceadeus Fur', icon: 'shell', color: 'white', rarity: 4 },
  { id: 462, name: 'Ceadeus Tail', icon: 'shell', color: 'white', rarity: 4 },
  { id: 463, name: 'Luminous Organ', icon: 'ball', color: 'cyan', rarity: 5 },
  { id: 464, name: 'Deep Dragongem', icon: 'hvnly', color: 'white', rarity: 5 },
  { id: 465, name: 'Crooked Horn', icon: 'claw', color: 'white', rarity: 6 },
  { id: 466, name: 'ElderDragonBlood', icon: 'shell', color: 'red', rarity: 5 },
  { id: 467, name: 'Mohran Shell', icon: 'shell', color: 'yellow', rarity: 5 },
  { id: 468, name: 'Mohran Brace', icon: 'shell', color: 'yellow', rarity: 5 },
  { id: 469, name: 'Mohran Scale', icon: 'scale', color: 'yellow', rarity: 5 },
  { id: 470, name: 'Sturdy Fang', icon: 'claw', color: 'yellow', rarity: 5 },
  {
    id: 471,
    name: 'Earth Dragongem',
    icon: 'hvnly',
    color: 'yellow',
    rarity: 5
  },
  {
    id: 472,
    name: 'Mohran Carapace',
    icon: 'shell',
    color: 'yellow',
    rarity: 5
  },
  { id: 473, name: 'Mohran Scale+', icon: 'scale', color: 'yellow', rarity: 5 },
  { id: 474, name: 'Sturdy Fang+', icon: 'claw', color: 'yellow', rarity: 5 },
  { id: 475, name: 'Mohran Brace+', icon: 'shell', color: 'yellow', rarity: 5 },
  {
    id: 476,
    name: 'Barroth Carapace',
    icon: 'shell',
    color: 'orange',
    rarity: 4
  },
  {
    id: 477,
    name: 'Barroth Ridge+',
    icon: 'shell',
    color: 'orange',
    rarity: 4
  },
  { id: 478, name: 'Barroth Claw+', icon: 'claw', color: 'orange', rarity: 4 },
  { id: 479, name: 'Uragaan Scale', icon: 'scale', color: 'red', rarity: 4 },
  { id: 480, name: 'Uragaan Scale+', icon: 'scale', color: 'red', rarity: 4 },
  { id: 481, name: 'Uragaan Ruby', icon: 'ball', color: 'red', rarity: 5 },
  { id: 482, name: 'Uragaan Carapace', icon: 'shell', color: 'red', rarity: 4 },
  { id: 483, name: 'Deviljho Hide', icon: 'hide', color: 'gray', rarity: 5 },
  { id: 484, name: 'Deviljho Scale', icon: 'scale', color: 'gray', rarity: 5 },
  { id: 485, name: 'Deviljho Talon', icon: 'claw', color: 'gray', rarity: 5 },
  { id: 486, name: 'Deviljho Fang', icon: 'claw', color: 'gray', rarity: 5 },
  { id: 487, name: 'Deviljho Gem', icon: 'hvnly', color: 'gray', rarity: 5 },
  { id: 488, name: 'Deviljho Scalp', icon: 'shell', color: 'gray', rarity: 5 },
  { id: 489, name: 'Deviljho Tail', icon: 'shell', color: 'gray', rarity: 5 },
  {
    id: 490,
    name: 'Quality Sponge',
    icon: 'shell',
    color: 'yellow',
    rarity: 4
  },
  { id: 491, name: 'Spongy Hide+', icon: 'hide', color: 'yellow', rarity: 4 },
  {
    id: 492,
    name: 'R.Ludroth Scale+',
    icon: 'scale',
    color: 'yellow',
    rarity: 4
  },
  {
    id: 493,
    name: 'R.Ludroth Claw+',
    icon: 'claw',
    color: 'yellow',
    rarity: 4
  },
  {
    id: 494,
    name: 'R.Ludroth Crest+',
    icon: 'shell',
    color: 'yellow',
    rarity: 4
  },
  { id: 495, name: 'Gobul Spike+', icon: 'shell', color: 'purple', rarity: 4 },
  { id: 496, name: 'Gobul Hide+', icon: 'hide', color: 'purple', rarity: 4 },
  { id: 497, name: 'Gobul Lantern+', icon: 'shell', color: 'white', rarity: 4 },
  { id: 498, name: 'Gobul Fin+', icon: 'shell', color: 'purple', rarity: 4 },
  { id: 499, name: 'Lagiacrus Hide+', icon: 'hide', color: 'cyan', rarity: 4 },
  {
    id: 500,
    name: 'Lagiacrus Scale+',
    icon: 'scale',
    color: 'cyan',
    rarity: 4
  },
  { id: 501, name: 'Lagiacrus Claw+', icon: 'claw', color: 'cyan', rarity: 4 },
  { id: 502, name: 'Lagiacrus Horn+', icon: 'claw', color: 'cyan', rarity: 4 },
  { id: 503, name: 'Lagia Sapphire', icon: 'ball', color: 'blue', rarity: 5 },
  { id: 504, name: 'Agnaktor Tail', icon: 'shell', color: 'red', rarity: 5 },
  { id: 505, name: 'AgnaktorCarapace', icon: 'shell', color: 'red', rarity: 4 },
  { id: 506, name: 'Agnaktor Hide+', icon: 'hide', color: 'red', rarity: 4 },
  { id: 507, name: 'Agnaktor Fin+', icon: 'shell', color: 'red', rarity: 4 },
  { id: 508, name: 'Agnaktor Claw+', icon: 'claw', color: 'red', rarity: 4 },
  { id: 509, name: 'Firecell Stone', icon: 'ore', color: 'red', rarity: 5 },
  {
    id: 510,
    name: 'Brkn Skypiercer',
    icon: 'claw',
    color: 'purple',
    rarity: 6
  },
  { id: 511, name: 'Alatreon Tail', icon: 'shell', color: 'purple', rarity: 5 },
  {
    id: 512,
    name: 'Alatreon Webbing',
    icon: 'webbing',
    color: 'purple',
    rarity: 5
  },
  {
    id: 513,
    name: 'Kelbi Horn Objet',
    icon: 'furnishing',
    color: 'white',
    rarity: 2
  },
  {
    id: 514,
    name: 'Twstd Horn Objet',
    icon: 'furnishing',
    color: 'yellow',
    rarity: 3
  },
  {
    id: 515,
    name: 'MohranFang Objet',
    icon: 'furnishing',
    color: 'red',
    rarity: 5
  },
  { id: 516, name: 'Piggie', icon: 'furnishing', color: 'white', rarity: 2 },
  {
    id: 517,
    name: 'Eggie Piggie',
    icon: 'furnishing',
    color: 'yellow',
    rarity: 3
  },
  { id: 518, name: 'Rath Piggie', icon: 'furnishing', color: 'red', rarity: 5 },
  {
    id: 519,
    name: 'Sandstone Plant',
    icon: 'furnishing',
    color: 'white',
    rarity: 2
  },
  {
    id: 520,
    name: 'Marshland Plant',
    icon: 'furnishing',
    color: 'yellow',
    rarity: 3
  },
  {
    id: 521,
    name: 'Snowflake Plant',
    icon: 'furnishing',
    color: 'red',
    rarity: 5
  },
  {
    id: 522,
    name: 'Prismshroom Lamp',
    icon: 'furnishing',
    color: 'white',
    rarity: 2
  },
  {
    id: 523,
    name: 'Qurupeco Lamp',
    icon: 'furnishing',
    color: 'yellow',
    rarity: 3
  },
  {
    id: 524,
    name: 'Sirensea Lamp',
    icon: 'furnishing',
    color: 'red',
    rarity: 5
  },
  {
    id: 525,
    name: 'Oceanic Fountain',
    icon: 'furnishing',
    color: 'white',
    rarity: 2
  },
  {
    id: 526,
    name: 'Bubbly Fountain',
    icon: 'furnishing',
    color: 'yellow',
    rarity: 3
  },
  {
    id: 527,
    name: 'Magma Fountain',
    icon: 'furnishing',
    color: 'red',
    rarity: 5
  },
  {
    id: 528,
    name: 'Iron Figure',
    icon: 'furnishing',
    color: 'white',
    rarity: 5
  },
  {
    id: 529,
    name: 'Machalite Figure',
    icon: 'furnishing',
    color: 'yellow',
    rarity: 3
  },
  {
    id: 530,
    name: 'Dragonite Figure',
    icon: 'furnishing',
    color: 'red',
    rarity: 5
  },
  {
    id: 531,
    name: 'Model Sandskiff',
    icon: 'furnishing',
    color: 'white',
    rarity: 2
  },
  {
    id: 532,
    name: 'Model Airship',
    icon: 'furnishing',
    color: 'yellow',
    rarity: 3
  },
  {
    id: 533,
    name: 'Model Piggieship',
    icon: 'furnishing',
    color: 'red',
    rarity: 5
  },
  {
    id: 534,
    name: 'Guildie (Red)',
    icon: 'furnishing',
    color: 'white',
    rarity: 2
  },
  {
    id: 535,
    name: 'Guildie (Green)',
    icon: 'furnishing',
    color: 'yellow',
    rarity: 3
  },
  {
    id: 536,
    name: 'Guildie (Blue)',
    icon: 'furnishing',
    color: 'red',
    rarity: 5
  },
  {
    id: 537,
    name: 'Great Piggie',
    icon: 'furnishing',
    color: 'red',
    rarity: 5
  },
  { id: 538, name: 'Qurupeco Wing', icon: 'shell', color: 'pink', rarity: 4 },
  { id: 539, name: 'Jaggi Hide+', icon: 'hide', color: 'purple', rarity: 4 },
  {
    id: 540,
    name: 'Lightning Ticket',
    icon: 'ticket',
    color: 'yellow',
    rarity: 5
  },
  { id: 541, name: 'Great Baggi Claw', icon: 'claw', color: 'cyan', rarity: 4 },
  {
    id: 542,
    name: 'High-qualty Pelt',
    icon: 'hide',
    color: 'green',
    rarity: 4
  },
  { id: 543, name: 'Popo Tongue', icon: 'meat', color: 'red', rarity: 2 },
  { id: 544, name: 'Rhenoplos Shell', icon: 'shell', color: 'gray', rarity: 4 },
  { id: 545, name: 'Rhenoplos Scalp', icon: 'shell', color: 'gray', rarity: 4 },
  { id: 546, name: 'Rheno Carapace', icon: 'shell', color: 'gray', rarity: 4 },
  {
    id: 547,
    name: 'BnahabraCarapace',
    icon: 'bug',
    color: 'yellow',
    rarity: 4
  },
  { id: 548, name: 'Monster Broth', icon: 'drink', color: 'cyan', rarity: 4 },
  { id: 549, name: 'Quality Sac', icon: 'sac', color: 'purple', rarity: 4 },
  { id: 550, name: 'Sleep Sac', icon: 'sac', color: 'cyan', rarity: 4 },
  { id: 551, name: 'Coma Sac', icon: 'sac', color: 'cyan', rarity: 5 },
  { id: 552, name: 'Baggi Hide', icon: 'hide', color: 'cyan', rarity: 4 },
  { id: 553, name: 'Baggi Scale', icon: 'scale', color: 'cyan', rarity: 4 },
  { id: 554, name: 'Great Baggi Hide', icon: 'hide', color: 'cyan', rarity: 4 },
  { id: 555, name: "Leader's Crest", icon: 'hide', color: 'cyan', rarity: 4 },
  { id: 556, name: 'Bird Wyvern Gem', icon: 'ball', color: 'cyan', rarity: 5 },
  { id: 557, name: 'Uroktor Scale', icon: 'scale', color: 'red', rarity: 4 },
  {
    id: 558,
    name: "Smith's Notebook",
    icon: 'ticket',
    color: 'red',
    rarity: 5
  },
  { id: 559, name: 'Bird Wyvern Bone', icon: 'bone', color: 'blue', rarity: 4 },
  { id: 560, name: 'Big Fin', icon: 'shell', color: 'orange', rarity: 4 },
  { id: 561, name: 'Quality Fin', icon: 'shell', color: 'orange', rarity: 4 },
  { id: 562, name: 'Sharpened Fang', icon: 'claw', color: 'orange', rarity: 4 },
  { id: 563, name: 'Velvety Hide', icon: 'hide', color: 'white', rarity: 4 },
  { id: 564, name: 'Giggi Stinger', icon: 'claw', color: 'white', rarity: 4 },
  { id: 565, name: 'Commendation', icon: 'ticket', color: 'white', rarity: 4 },
  {
    id: 566,
    name: 'Bird Wyvern Claw',
    icon: 'claw',
    color: 'orange',
    rarity: 4
  },
  { id: 567, name: 'Barrel Bomb S+', icon: 'bomb', color: 'yellow' },
  { id: 568, name: 'Felvine', icon: 'herb', color: 'yellow', rarity: 1 },
  { id: 569, name: 'Steel Egg', icon: 'egg', color: 'gray', rarity: 4 },
  { id: 570, name: 'Silver Egg', icon: 'egg', color: 'white', rarity: 4 },
  { id: 571, name: 'Golden Egg', icon: 'egg', color: 'yellow', rarity: 4 },
  {
    id: 572,
    name: 'Incomplete Crown',
    icon: 'garbage',
    color: 'yellow',
    rarity: 4
  },
  {
    id: 573,
    name: "Crown's Gemstone",
    icon: 'garbage',
    color: 'red',
    rarity: 4
  },
  {
    id: 574,
    name: 'Dazzling Crown',
    icon: 'garbage',
    color: 'orange',
    rarity: 4
  },
  { id: 575, name: 'Book of Combos 1', icon: 'book', color: 'gray', rarity: 4 },
  { id: 576, name: 'Book of Combos 2', icon: 'book', color: 'gray', rarity: 4 },
  {
    id: 577,
    name: 'Book of Combos 3',
    icon: 'book',
    color: 'white',
    rarity: 4
  },
  {
    id: 578,
    name: 'Book of Combos 4',
    icon: 'book',
    color: 'white',
    rarity: 5
  },
  {
    id: 579,
    name: 'Book of Combos 5',
    icon: 'book',
    color: 'yellow',
    rarity: 5
  },
  { id: 580, name: 'Organizer Guide', icon: 'book', color: 'white', rarity: 4 },
  { id: 581, name: 'Pack Rat Guide', icon: 'book', color: 'white', rarity: 4 },
  { id: 582, name: 'EZ Barrel Bomb L', icon: 'bomb', color: 'blue', rarity: 3 },
  { id: 583, name: 'UW Ballista Ammo', icon: 'ammo', color: 'blue', rarity: 6 },
  { id: 584, name: 'Rathalos Coin', icon: 'coin', color: 'red', rarity: 5 },
  { id: 585, name: 'Gobul Coin', icon: 'coin', color: 'purple', rarity: 4 },
  { id: 586, name: 'Barioth Coin', icon: 'coin', color: 'white', rarity: 4 },
  {
    id: 587,
    name: 'Hunter King Coin',
    icon: 'coin',
    color: 'white',
    rarity: 4
  },
  { id: 588, name: 'Diablos Coin', icon: 'coin', color: 'yellow', rarity: 5 },
  { id: 589, name: 'Deviljho Coin', icon: 'coin', color: 'purple', rarity: 5 },
  {
    id: 590,
    name: 'HellHunter Tag',
    icon: 'ticket',
    color: 'green',
    rarity: 5
  },
  { id: 591, name: 'Dark Metal', icon: 'ticket', color: 'cyan', rarity: 5 },
  {
    id: 592,
    name: 'Incomplete Plans',
    icon: 'ticket',
    color: 'blue',
    rarity: 5
  },
  {
    id: 593,
    name: "Lion King's Seal",
    icon: 'ticket',
    color: 'orange',
    rarity: 5
  },
  {
    id: 594,
    name: 'SoulHunter Tag',
    icon: 'ticket',
    color: 'green',
    rarity: 5
  },
  { id: 595, name: 'Monster Bone+', icon: 'bone', color: 'orange', rarity: 5 },
  { id: 596, name: 'Powercharm', icon: 'jewel', color: 'red', rarity: 5 },
  { id: 597, name: 'Powertalon', icon: 'claw', color: 'red', rarity: 5 },
  { id: 598, name: 'Armorcharm', icon: 'jewel', color: 'orange', rarity: 5 },
  { id: 599, name: 'Armortalon', icon: 'claw', color: 'orange', rarity: 5 },
  { id: 600, name: 'Bounce Bomb', icon: 'bomb', color: 'blue', rarity: 5 },
  { id: 601, name: 'Bounce Bomb+', icon: 'bomb', color: 'blue', rarity: 5 },
  { id: 602, name: 'Sharqskin', icon: 'hide', color: 'blue', rarity: 4 },
  {
    id: 603,
    name: "Conqueror's Seal",
    icon: 'ticket',
    color: 'red',
    rarity: 5
  },
  { id: 604, name: 'Golden Medallion' },
  {
    id: 605,
    name: 'Prize Gold Sword',
    icon: 'furnishing',
    color: 'yellow',
    rarity: 5
  },
  {
    id: 606,
    name: 'Great Jaggi Coin',
    icon: 'coin',
    color: 'yellow',
    rarity: 4
  },
  { id: 607, name: 'Qurupeco Coin', icon: 'coin', color: 'orange', rarity: 4 },
  { id: 608, name: 'Barroth Coin', icon: 'coin', color: 'orange', rarity: 4 },
  { id: 609, name: 'R.Ludroth Coin', icon: 'coin', color: 'blue', rarity: 4 },
  { id: 610, name: 'Rathian Coin', icon: 'coin', color: 'green', rarity: 5 },
  { id: 611, name: 'Lagiacrus Coin', icon: 'coin', color: 'cyan', rarity: 5 },
  { id: 612, name: 'Uragaan Coin', icon: 'coin', color: 'red', rarity: 4 },
  { id: 613, name: 'Wyvern Lord Coin' },
  { id: 614, name: 'Sea Lord Coin' },
  { id: 615, name: 'Pinnacle Coin', icon: 'coin', color: 'red', rarity: 4 },
  { name: 'Weapon Codex', icon: 'garbage', color: 'white' },
  { name: 'Stock Codex', icon: 'garbage', color: 'white' },
  { name: 'Barrel Codex', icon: 'garbage', color: 'white' }
];
