import { deepFreeze } from '../../utils';
import type { Item } from './types';

export const ItemData = deepFreeze<Item[]>([
  { id: 0, name: 'Barrel Bomb S' },
  { id: 1, name: 'Barrel Bomb L' },
  { id: 2, name: 'Pitfall Trap' },
  { id: 3, name: 'Shock Trap' },
  { id: 4, name: 'Flash Bomb' },
  { id: 5, name: 'Oxygen Supply' },
  { id: 6, name: 'Sonic Bomb' },
  { id: 7, name: 'Throwing Knife' },
  { id: 8, name: 'Poison Knife' },
  { id: 9, name: 'Sleep Knife' },
  { id: 10, name: 'Paralysis Knife' },
  { id: 11, name: 'Tranq Knife' },
  { id: 12, name: 'Potion' },
  { id: 13, name: 'Mega Potion' },
  { id: 14, name: 'Dash Juice' },
  { id: 15, name: 'Mega Dash Juice' },
  { id: 16, name: 'Antidote' },
  { id: 17, name: 'Demondrug' },
  { id: 18, name: 'Mega Demondrug' },
  { id: 19, name: 'Might Pill' },
  { id: 20, name: 'Armorskin' },
  { id: 21, name: 'Mega Armorskin' },
  { id: 22, name: 'Adamant Pill' },
  { id: 23, name: 'Cool Drink' },
  { id: 24, name: 'Hot Drink' },
  { id: 25, name: 'Well-done Steak' },
  { id: 26, name: 'Rare Steak' },
  { id: 27, name: 'Burnt Meat' },
  { id: 28, name: 'Raw Meat' },
  { id: 29, name: 'Poisoned Meat' },
  { id: 30, name: 'Tinged Meat' },
  { id: 31, name: 'Drugged Meat' },
  { id: 32, name: 'Paintball' },
  { id: 33, name: 'Old Pickaxe' },
  { id: 34, name: 'Iron Pickaxe' },
  { id: 35, name: 'Mega Pickaxe' },
  { id: 36, name: 'Old Bug Net' },
  { id: 37, name: 'Bug Net' },
  { id: 38, name: 'Mega Bug Net' },
  { id: 39, name: 'BBQ Spit' },
  { id: 40, name: 'Great Jaggi Head' },
  { id: 41, name: 'Map' },
  { id: 42, name: 'Torch' },
  { id: 43, name: 'First-aid Med' },
  { id: 44, name: 'Ration' },
  { id: 45, name: 'Mini Oxy Supply' },
  { id: 46, name: 'Portable Spit' },
  { id: 47, name: 'Mini Whetstone' },
  { id: 48, name: 'EZ Shock Trap' },
  { id: 49, name: 'EZ Flash Bomb' },
  { id: 50, name: 'Max Potion' },
  { id: 51, name: 'Barrel Bomb L+' },
  { id: 52, name: 'Normal S Lv1' },
  { id: 53, name: 'Normal S Lv2' },
  { id: 54, name: 'Normal S Lv3' },
  { id: 55, name: 'Pierce S Lv1' },
  { id: 56, name: 'Pierce S Lv2' },
  { id: 57, name: 'Pierce S Lv3' },
  { id: 58, name: 'Pellet S Lv1' },
  { id: 59, name: 'Pellet S Lv2' },
  { id: 60, name: 'Pellet S Lv3' },
  { id: 61, name: 'Crag S Lv1' },
  { id: 62, name: 'Crag S Lv2' },
  { id: 63, name: 'Crag S Lv3' },
  { id: 64, name: 'Clust S Lv1' },
  { id: 65, name: 'Clust S Lv2' },
  { id: 66, name: 'Clust S Lv3' },
  { id: 67, name: 'Flaming S' },
  { id: 68, name: 'Water S' },
  { id: 69, name: 'Thunder S' },
  { id: 70, name: 'Freeze S' },
  { id: 71, name: 'Dragon S' },
  { id: 72, name: 'Recov S Lv1' },
  { id: 73, name: 'Recov S Lv2' },
  { id: 74, name: 'Poison S Lv1' },
  { id: 75, name: 'Poison S Lv2' },
  { id: 76, name: 'Para S Lv1' },
  { id: 77, name: 'Para S Lv2' },
  { id: 78, name: 'Sleep S Lv1' },
  { id: 79, name: 'Sleep S Lv2' },
  { id: 80, name: 'Tranq S' },
  { id: 81, name: 'Paint S' },
  { id: 82, name: 'Demon S I' },
  { id: 83, name: 'Demon S II' },
  { id: 84, name: 'Armor S I' },
  { id: 85, name: 'Armor S II' },
  { id: 86, name: 'Sub S Lv1' },
  { id: 87, name: 'Sub S Lv2' },
  { id: 88, name: 'Exhaust S' },
  { id: 89, name: 'Slicing S' },
  { id: 90, name: 'WyvernFire Lv1' },
  { id: 91, name: 'WyvernFire Lv2' },
  { id: 92, name: 'WyvernFire Lv3' },
  { id: 93, name: 'Binoculars' },
  { id: 94, name: 'Tranq Bomb' },
  { id: 95, name: 'Stone' },
  { id: 96, name: 'Whetstone' },
  { id: 97, name: 'Iron Ore' },
  { id: 98, name: 'Earth Crystal' },
  { id: 99, name: 'Machalite Ore' },
  { id: 100, name: 'Dragonite Ore' },
  { id: 101, name: 'Carbalite Ore' },
  { id: 102, name: 'Pelagicite Ore' },
  { id: 103, name: 'Bathycite Ore' },
  { id: 104, name: 'Firestone' },
  { id: 105, name: 'Ice Crystal' },
  { id: 106, name: 'Lightcrystal' },
  { id: 107, name: 'Sharq Ticket' },
  { id: 108, name: 'Rustshard' },
  { id: 109, name: 'Ancient Shard' },
  { id: 110, name: 'Isisium' },
  { id: 111, name: 'Gracium' },
  { id: 112, name: 'Godbug' },
  { id: 113, name: 'Bitterbug' },
  { id: 114, name: 'Flashbug' },
  { id: 115, name: 'Thunderbug' },
  { id: 116, name: 'Gluehopper' },
  { id: 117, name: 'Killer Beetle' },
  { id: 118, name: 'Rare Scarab' },
  { id: 119, name: 'Royal Rhino' },
  { id: 120, name: 'Herb' },
  { id: 121, name: 'Antidote Herb' },
  { id: 122, name: 'Sleep Herb' },
  { id: 123, name: 'Fire Herb' },
  { id: 124, name: 'Sap Plant' },
  { id: 125, name: 'Paintberry' },
  { id: 126, name: 'Needleberry' },
  { id: 127, name: 'Huskberry' },
  { id: 128, name: 'Scatternut' },
  { id: 129, name: 'Bomberry' },
  { id: 130, name: 'Ivy' },
  { id: 131, name: 'Might Seed' },
  { id: 132, name: 'Adamant Seed' },
  { id: 133, name: 'Hot Pepper' },
  { id: 134, name: 'Cactus Flower' },
  { id: 135, name: 'Airweed' },
  { id: 136, name: 'Wyvern Egg' },
  { id: 137, name: 'Unknown Skull' },
  { id: 138, name: 'Honey' },
  { id: 139, name: 'Blue Mushroom' },
  { id: 140, name: 'Choice Mushroom' },
  { id: 141, name: 'Unique Mushroom' },
  { id: 142, name: 'Exciteshroom' },
  { id: 143, name: 'Parashroom' },
  { id: 144, name: 'Nitroshroom' },
  { id: 145, name: 'Black Pearl' },
  { id: 146, name: 'Jumbo Pearl' },
  { id: 147, name: 'Broken Shell' },
  { id: 148, name: 'Dragonbone Relic' },
  { id: 149, name: 'Monster Bone S' },
  { id: 150, name: 'Monster Bone M' },
  { id: 151, name: 'Monster Bone L' },
  { id: 152, name: 'Eldest Saturnian' },
  { id: 153, name: 'Hercudrome' },
  { id: 154, name: 'Chilled Meat' },
  { id: 155, name: 'Hot Meat' },
  { id: 156, name: 'Rathian Scale+' },
  { id: 157, name: 'Rathian Carapace' },
  { id: 158, name: 'Rath Medulla' },
  { id: 159, name: 'Rathian Spike+' },
  { id: 160, name: 'Rathian Ruby' },
  { id: 161, name: 'Rathalos Ruby' },
  { id: 162, name: 'Inferno Sac' },
  { id: 163, name: 'Rathalos Scale+' },
  { id: 164, name: 'RathalosCarapace' },
  { id: 165, name: 'Qurupeco Scale+' },
  { id: 166, name: 'Wonderful Beak' },
  { id: 167, name: 'Unnerving Talon' },
  { id: 168, name: 'Fearsome Maw' },
  { id: 169, name: 'Wyvern Stone' },
  { id: 170, name: 'Freezer Sac' },
  { id: 171, name: 'Wyvrnhide Ticket' },
  { id: 172, name: 'Black Gem Ticket' },
  { id: 173, name: 'Flabby Hide+' },
  { id: 174, name: 'Uncanny Hide+' },
  { id: 175, name: 'Toxin Sac' },
  { id: 176, name: 'Unnerving Talon+' },
  { id: 177, name: 'Stunning Quill' },
  { id: 178, name: 'Pittance Fang' },
  { id: 179, name: 'Vermilion Scale' },
  { id: 180, name: 'Fishing Harpoon' },
  { id: 181, name: 'Insect Husk' },
  { id: 182, name: 'Bone' },
  { id: 183, name: 'Dung' },
  { id: 184, name: 'Spider Web' },
  { id: 185, name: 'Bomb Casing' },
  { id: 186, name: 'Small Barrel' },
  { id: 187, name: 'Large Barrel' },
  { id: 188, name: 'Cricket' },
  { id: 189, name: 'Worm' },
  { id: 190, name: 'Firefly' },
  { id: 191, name: 'Mega Fishing Fly' },
  { id: 192, name: 'Frog' },
  { id: 193, name: 'Whetfish' },
  { id: 194, name: 'Sushifish' },
  { id: 195, name: 'Pin Tuna' },
  { id: 196, name: 'Popfish' },
  { id: 197, name: 'Sleepyfish' },
  { id: 198, name: 'Burst Arowana' },
  { id: 199, name: 'Bomb Arowana' },
  { id: 200, name: 'Glutton Tuna' },
  { id: 201, name: 'Scatterfish' },
  { id: 202, name: 'Small Goldenfish' },
  { id: 203, name: 'Goldenfish' },
  { id: 204, name: 'Beautiful Scale' },
  { id: 205, name: 'Giant Skull' },
  { id: 206, name: 'Pirate Booty' },
  { id: 207, name: 'Net' },
  { id: 208, name: 'Shroom Germ' },
  { id: 209, name: 'BugMaker! Pro' },
  { id: 210, name: 'Bizzy Bees' },
  { id: 211, name: 'Saturnian' },
  { id: 212, name: 'Fortune Fang' },
  { id: 213, name: 'Shining Starfish' },
  { id: 214, name: 'Mystic Narwhal' },
  { id: 215, name: 'Atlantis Crab' },
  { id: 216, name: 'Gold Needle' },
  { id: 217, name: 'Armorfish Morsel' },
  { id: 218, name: 'Fish Finder' },
  { id: 219, name: 'Treasure Tracker' },
  { id: 220, name: 'Spare Spear' },
  { id: 221, name: 'Perfect Paddle' },
  { id: 222, name: 'Shroom Germ+' },
  { id: 223, name: 'Pink Liver' },
  { id: 224, name: 'Ethnic Wyvrnmeat' },
  { id: 225, name: 'Ancient Skin Oil' },
  { id: 226, name: "Queen's Spirit" },
  { id: 227, name: 'Funky Pheromones' },
  { id: 228, name: 'Saturnian Trap' },
  { id: 229, name: 'Super-sized Dung' },
  { id: 230, name: 'Fine Pelt' },
  { id: 231, name: 'Moonlight Fang' },
  { id: 232, name: 'Queen Needle' },
  { id: 233, name: 'Power Paddle' },
  { id: 234, name: 'Curved Fang' },
  { id: 235, name: 'Flamboyant Quill' },
  { id: 236, name: 'Glittering Scale' },
  { id: 237, name: "Sea-King's Scale" },
  { id: 238, name: 'Wyverngold' },
  { id: 239, name: 'Felvine Bomb' },
  { id: 240, name: 'Double BBQ Spit' },
  { id: 241, name: 'Dragonbone Piece' },
  { id: 242, name: 'Abalone Piece' },
  { id: 243, name: 'Fossil Piece' },
  { id: 244, name: 'Odd Egg' },
  { id: 245, name: 'Mystery Bone' },
  { id: 246, name: 'Herbal Medicine' },
  { id: 247, name: 'Rathian Scale' },
  { id: 248, name: 'Rathian Shell' },
  { id: 249, name: 'Rathian Webbing' },
  { id: 250, name: 'Rathian Spike' },
  { id: 251, name: 'Rathian Plate' },
  { id: 252, name: 'Flame Sac' },
  { id: 253, name: 'Wyvern Tear' },
  { id: 254, name: 'Rathalos Scale' },
  { id: 255, name: 'Rathalos Shell' },
  { id: 256, name: 'Rathalos Webbing' },
  { id: 257, name: 'Rath Marrow' },
  { id: 258, name: 'Rathalos Plate' },
  { id: 259, name: 'Rathalos Tail' },
  { id: 260, name: 'Qurupeco Scale' },
  { id: 261, name: 'Qurupeco Feather' },
  { id: 262, name: 'Vivid Feather' },
  { id: 263, name: 'Strange Beak' },
  { id: 264, name: 'Flabby Hide' },
  { id: 265, name: 'Uncanny Hide' },
  { id: 266, name: 'Poison Sac' },
  { id: 267, name: 'Pale Extract' },
  { id: 268, name: 'Diablos Fang' },
  { id: 269, name: 'Diablos Shell' },
  { id: 270, name: 'Diablos Ridge' },
  { id: 271, name: 'Diablos Tailcase' },
  { id: 272, name: 'Barroth Shell' },
  { id: 273, name: 'Barroth Ridge' },
  { id: 274, name: 'Barroth Claw' },
  { id: 275, name: 'Barroth Tail' },
  { id: 276, name: 'Barroth Scalp' },
  { id: 277, name: 'Bird Wyvern Fang' },
  { id: 278, name: 'Jaggi Hide' },
  { id: 279, name: 'Jaggi Scale' },
  { id: 280, name: 'Great Jaggi Claw' },
  { id: 281, name: 'Great Jaggi Hide' },
  { id: 282, name: 'Screamer' },
  { id: 283, name: 'Lagiacrus Hide' },
  { id: 284, name: 'Lagiacrus Scale' },
  { id: 285, name: 'Lagiacrus Claw' },
  { id: 286, name: 'Shell Shocker+' },
  { id: 287, name: 'Lagiacrus Tail' },
  { id: 288, name: 'Lagiacrus Plate' },
  { id: 289, name: 'Spongy Hide' },
  { id: 290, name: 'R.Ludroth Scale' },
  { id: 291, name: 'R.Ludroth Claw' },
  { id: 292, name: 'R.Ludroth Tail' },
  { id: 293, name: 'Dash Extract' },
  { id: 294, name: 'Hydro Hide' },
  { id: 295, name: 'Immature Sponge' },
  { id: 296, name: 'Gobul Spike' },
  { id: 297, name: 'Gobul Hide' },
  { id: 298, name: 'Paralysis Sac' },
  { id: 299, name: 'Gobul Fin' },
  { id: 300, name: 'Armor Sphere' },
  { id: 301, name: 'Armor Sphere+' },
  { id: 302, name: 'Gobul Lantern' },
  { id: 303, name: 'Warm Pelt' },
  { id: 304, name: 'Nutrients' },
  { id: 305, name: 'Mega Nutrients' },
  { id: 306, name: 'Dragon Toadstool' },
  { id: 307, name: 'Immunizer' },
  { id: 308, name: 'Catalyst' },
  { id: 309, name: 'Bomb Sac' },
  { id: 310, name: 'Kelbi Horn' },
  { id: 311, name: 'Blue Kelbi Horn' },
  { id: 312, name: 'Bnahabra Shell' },
  { id: 313, name: 'Bnahabra Wing' },
  { id: 314, name: 'Monster Fluid' },
  { id: 315, name: 'Bone Husk S' },
  { id: 316, name: 'Bone Husk L' },
  { id: 317, name: 'Toadstool' },
  { id: 318, name: 'Smoke Bomb' },
  { id: 319, name: 'Poison Smoke Bmb' },
  { id: 320, name: 'Dung Bomb' },
  { id: 321, name: 'Gunpowder' },
  { id: 322, name: 'Trap Tool' },
  { id: 323, name: 'Yambug' },
  { id: 324, name: 'Tuna Bait' },
  { id: 325, name: 'Bughopper' },
  { id: 326, name: 'Arowana Bait' },
  { id: 327, name: 'Snakebee Larva' },
  { id: 328, name: 'Goldenfish Bait' },
  { id: 329, name: 'Antiseptic Stone' },
  { id: 330, name: 'Wyvern Fang' },
  { id: 331, name: 'Lifecrystals' },
  { id: 332, name: 'Wyvern Claw' },
  { id: 333, name: 'Lifepowder' },
  { id: 334, name: 'Hunting Horn' },
  { id: 335, name: 'Health Horn' },
  { id: 336, name: 'Antidote Horn' },
  { id: 337, name: 'Demon Horn' },
  { id: 338, name: 'Armor Horn' },
  { id: 339, name: 'Farcaster' },
  { id: 340, name: 'Tranquilizer' },
  { id: 341, name: 'Dragonfell Berry' },
  { id: 342, name: 'Energy Drink' },
  { id: 343, name: 'Cleanser' },
  { id: 344, name: 'Garbage' },
  { id: 345, name: 'Ancient Potion' },
  { id: 346, name: 'Psychoserum' },
  { id: 347, name: 'Agnaktor Coin' },
  { id: 348, name: 'Ballista Ammo' },
  { id: 349, name: 'Cannon Ammo' },
  { id: 350, name: 'Powderstone' },
  { id: 351, name: 'Anti-dragon Bomb' },
  { id: 352, name: 'Ballista Binder' },
  { id: 353, name: 'Rath Talon' },
  { id: 354, name: 'Twisted Horn' },
  { id: 355, name: 'Majestic Horn' },
  { id: 356, name: 'Mega Harpoon' },
  { id: 357, name: 'Whetfish Bait' },
  { id: 358, name: 'Sushifish Bait' },
  { id: 359, name: 'Firedouse Berry' },
  { id: 360, name: 'Waterblock Seed' },
  { id: 361, name: 'Icethaw Pellet' },
  { id: 362, name: 'Stormsender Seed' },
  { id: 363, name: 'Herbivore Egg' },
  { id: 364, name: 'Crystal Bone' },
  { id: 365, name: 'Golden Bone' },
  { id: 366, name: 'Air Philter' },
  { id: 367, name: 'Mega Air Philter' },
  { id: 368, name: 'Altaroth Stomach' },
  { id: 369, name: 'Altaroth Jaw' },
  { id: 370, name: 'Ripened Mushroom' },
  { id: 371, name: 'R.Ludroth Crest' },
  { id: 372, name: 'Barioth Shell' },
  { id: 373, name: 'Barioth Pelt' },
  { id: 374, name: 'Amber Tusks' },
  { id: 375, name: 'Barioth Claw' },
  { id: 376, name: 'Barioth Spike' },
  { id: 377, name: 'Frost Sac' },
  { id: 378, name: 'Uragaan Shell' },
  { id: 379, name: 'Uragaan Scute' },
  { id: 380, name: 'Uragaan Marrow' },
  { id: 381, name: 'Uragaan Jaw' },
  { id: 382, name: 'Agnaktor Shell' },
  { id: 383, name: 'Agnaktor Hide' },
  { id: 384, name: 'Agnaktor Fin' },
  { id: 385, name: 'Agnaktor Claw' },
  { id: 386, name: 'Agnaktor Scale' },
  { id: 387, name: 'Agnaktor Beak' },
  { id: 388, name: "King's Frill" },
  { id: 389, name: 'Fertile Mud' },
  { id: 390, name: 'Gobul Whisker' },
  { id: 391, name: 'Shell Shocker' },
  { id: 392, name: 'Lagiacrus Horn' },
  { id: 393, name: 'Flintstone' },
  { id: 394, name: 'Barioth Tail' },
  { id: 395, name: 'Bloodstone' },
  { id: 396, name: 'Paw Pass Ticket' },
  { id: 397, name: 'Monster Guts' },
  { id: 398, name: 'Red Coral Stone' },
  { id: 399, name: 'Voucher' },
  { id: 400, name: 'Gourmet Voucher' },
  { id: 401, name: 'Alatreon Scute' },
  { id: 402, name: 'Alatreon Plate' },
  { id: 403, name: 'Alatreon Talon' },
  { id: 404, name: 'Azure Dragongem' },
  { id: 405, name: 'Skypiercer' },
  { id: 406, name: 'Mystery Charm' },
  { id: 407, name: 'Shining Charm' },
  { id: 408, name: 'Timeworn Charm' },
  { id: 409, name: 'Armor Stone' },
  { id: 410, name: 'Adv Armor Sphere' },
  { id: 411, name: 'Hrd Armor Sphere' },
  { id: 412, name: 'Hvy Armor Sphere' },
  { id: 413, name: 'Aquaglow Jewel' },
  { id: 414, name: 'Sunspire Jewel' },
  { id: 415, name: 'Bloodrun Jewel' },
  { id: 416, name: 'Lazurite Jewel' },
  { id: 417, name: 'Barioth Carapace' },
  { id: 418, name: 'Barioth Pelt+' },
  { id: 419, name: 'Amber Tusks+' },
  { id: 420, name: 'Barioth Claw+' },
  { id: 421, name: 'Diablos Marrow' },
  { id: 422, name: 'Diablos Carapace' },
  { id: 423, name: 'Diablos Ridge+' },
  { id: 424, name: 'Stout Horn' },
  { id: 425, name: 'Ceadeus Hide' },
  { id: 426, name: 'Ceadeus Scale' },
  { id: 427, name: 'Ceadeus Fur' },
  { id: 428, name: 'Ceadeus Tail' },
  { id: 429, name: 'Luminous Organ' },
  { id: 430, name: 'Deep Dragongem' },
  { id: 431, name: 'Crooked Horn' },
  { id: 432, name: 'ElderDragonBlood' },
  { id: 433, name: 'Mohran Shell' },
  { id: 434, name: 'Mohran Brace' },
  { id: 435, name: 'Mohran Scale' },
  { id: 436, name: 'Sturdy Fang' },
  { id: 437, name: 'Earth Dragongem' },
  { id: 438, name: 'Mohran Carapace' },
  { id: 439, name: 'Mohran Scale+' },
  { id: 440, name: 'Sturdy Fang+' },
  { id: 441, name: 'Mohran Brace+' },
  { id: 442, name: 'Barroth Carapace' },
  { id: 443, name: 'Barroth Ridge+' },
  { id: 444, name: 'Barroth Claw+' },
  { id: 445, name: 'Uragaan Scale' },
  { id: 446, name: 'Uragaan Scale+' },
  { id: 447, name: 'Uragaan Ruby' },
  { id: 448, name: 'Uragaan Carapace' },
  { id: 449, name: 'Deviljho Hide' },
  { id: 450, name: 'Deviljho Scale' },
  { id: 451, name: 'Deviljho Talon' },
  { id: 452, name: 'Deviljho Fang' },
  { id: 453, name: 'Deviljho Gem' },
  { id: 454, name: 'Deviljho Scalp' },
  { id: 455, name: 'Deviljho Tail' },
  { id: 456, name: 'Quality Sponge' },
  { id: 457, name: 'Spongy Hide+' },
  { id: 458, name: 'R.Ludroth Scale+' },
  { id: 459, name: 'R.Ludroth Claw+' },
  { id: 460, name: 'R.Ludroth Crest+' },
  { id: 461, name: 'Gobul Spike+' },
  { id: 462, name: 'Gobul Hide+' },
  { id: 463, name: 'Gobul Lantern+' },
  { id: 464, name: 'Gobul Fin+' },
  { id: 465, name: 'Lagiacrus Hide+' },
  { id: 466, name: 'Lagiacrus Scale+' },
  { id: 467, name: 'Lagiacrus Claw+' },
  { id: 468, name: 'Lagiacrus Horn+' },
  { id: 469, name: 'Lagia Sapphire' },
  { id: 470, name: 'Agnaktor Tail' },
  { id: 471, name: 'AgnaktorCarapace' },
  { id: 472, name: 'Agnaktor Hide+' },
  { id: 473, name: 'Agnaktor Fin+' },
  { id: 474, name: 'Agnaktor Claw+' },
  { id: 475, name: 'Firecell Stone' },
  { id: 476, name: 'Brkn Skypiercer' },
  { id: 477, name: 'Alatreon Tail' },
  { id: 478, name: 'Alatreon Webbing' },
  { id: 479, name: 'Kelbi Horn Objet' },
  { id: 480, name: 'Twstd Horn Objet' },
  { id: 481, name: 'MohranFang Objet' },
  { id: 482, name: 'Piggie' },
  { id: 483, name: 'Eggie Piggie' },
  { id: 484, name: 'Rath Piggie' },
  { id: 485, name: 'Sandstone Plant' },
  { id: 486, name: 'Marshland Plant' },
  { id: 487, name: 'Snowflake Plant' },
  { id: 488, name: 'Prismshroom Lamp' },
  { id: 489, name: 'Qurupeco Lamp' },
  { id: 490, name: 'Sirensea Lamp' },
  { id: 491, name: 'Oceanic Fountain' },
  { id: 492, name: 'Bubbly Fountain' },
  { id: 493, name: 'Magma Fountain' },
  { id: 494, name: 'Iron Figure' },
  { id: 495, name: 'Machalite Figure' },
  { id: 496, name: 'Dragonite Figure' },
  { id: 497, name: 'Model Sandskiff' },
  { id: 498, name: 'Model Airship' },
  { id: 499, name: 'Model Piggieship' },
  { id: 500, name: 'Guildie (Red)' },
  { id: 501, name: 'Guildie (Green)' },
  { id: 502, name: 'Guildie (Blue)' },
  { id: 503, name: 'Great Piggie' },
  { id: 504, name: 'Qurupeco Wing' },
  { id: 505, name: 'Jaggi Hide+' },
  { id: 506, name: 'Lightning Ticket' },
  { id: 507, name: 'Great Baggi Claw' },
  { id: 508, name: 'High-qualty Pelt' },
  { id: 509, name: 'Popo Tongue' },
  { id: 510, name: 'Rhenoplos Shell' },
  { id: 511, name: 'Rhenoplos Scalp' },
  { id: 512, name: 'Rheno Carapace' },
  { id: 513, name: 'BnahabraCarapace' },
  { id: 514, name: 'Monster Broth' },
  { id: 515, name: 'Quality Sac' },
  { id: 516, name: 'Sleep Sac' },
  { id: 517, name: 'Coma Sac' },
  { id: 518, name: 'Baggi Hide' },
  { id: 519, name: 'Baggi Scale' },
  { id: 520, name: 'Great Baggi Hide' },
  { id: 521, name: "Leader's Crest" },
  { id: 522, name: 'Bird Wyvern Gem' },
  { id: 523, name: 'Uroktor Scale' },
  { id: 524, name: "Smith's Notebook" },
  { id: 525, name: 'Bird Wyvern Bone' },
  { id: 526, name: 'Big Fin' },
  { id: 527, name: 'Quality Fin' },
  { id: 528, name: 'Sharpened Fang' },
  { id: 529, name: 'Velvety Hide' },
  { id: 530, name: 'Giggi Stinger' },
  { id: 531, name: 'Commendation' },
  { id: 532, name: 'Bird Wyvern Claw' },
  { id: 533, name: 'Barrel Bomb S+' },
  { id: 534, name: 'Felvine' },
  { id: 535, name: 'Steel Egg' },
  { id: 536, name: 'Silver Egg' },
  { id: 537, name: 'Golden Egg' },
  { id: 538, name: 'Incomplete Crown' },
  { id: 539, name: "Crown's Gemstone" },
  { id: 540, name: 'Dazzling Crown' },
  { id: 541, name: 'Book of Combos 1' },
  { id: 542, name: 'Book of Combos 2' },
  { id: 543, name: 'Book of Combos 3' },
  { id: 544, name: 'Book of Combos 4' },
  { id: 545, name: 'Book of Combos 5' },
  { id: 546, name: 'Organizer Guide' },
  { id: 547, name: 'Pack Rat Guide' },
  { id: 548, name: 'EZ Barrel Bomb L' },
  { id: 549, name: 'UW Ballista Ammo' },
  { id: 550, name: 'Rathalos Coin' },
  { id: 551, name: 'Gobul Coin' },
  { id: 552, name: 'Barioth Coin' },
  { id: 553, name: 'Hunter King Coin' },
  { id: 554, name: 'Diablos Coin' },
  { id: 555, name: 'Deviljho Coin' },
  { id: 556, name: 'HellHunter Tag' },
  { id: 557, name: 'Dark Metal' },
  { id: 558, name: 'Incomplete Plans' },
  { id: 559, name: "Lion King's Seal" },
  { id: 560, name: 'SoulHunter Tag' },
  { id: 561, name: 'Monster Bone+' },
  { id: 562, name: 'Powercharm' },
  { id: 563, name: 'Powertalon' },
  { id: 564, name: 'Armorcharm' },
  { id: 565, name: 'Armortalon' },
  { id: 566, name: 'Bounce Bomb' },
  { id: 567, name: 'Bounce Bomb+' },
  { id: 568, name: 'Sharqskin' },
  { id: 569, name: "Conqueror's Seal" },
  { id: 570, name: 'Golden Medallion' },
  { id: 571, name: 'Prize Gold Sword' },
  { id: 572, name: 'Great Jaggi Coin' },
  { id: 573, name: 'Qurupeco Coin' },
  { id: 574, name: 'Barroth Coin' },
  { id: 575, name: 'R.Ludroth Coin' },
  { id: 576, name: 'Rathian Coin' },
  { id: 577, name: 'Lagiacrus Coin' },
  { id: 578, name: 'Uragaan Coin' },
  { id: 579, name: 'Wyvern Lord Coin' },
  { id: 580, name: 'Sea Lord Coin' },
  { id: 581, name: 'Pinnacle Coin' },
  { id: 582, name: 'Weapon Codex' },
  { id: 583, name: 'Stock Codex' },
  { id: 584, name: 'Barrel Codex' }
]);
